export default {
	accessKey: "P",
	ipaEnabled: true,
	ipaTimeout: 3000,
	useWordColors: false,
	audioVolume: 1.0,
	fetchFileAudioTimeout: 1100,
	fetchScrapAudioTimeout: 1300,
	audioEnabled: true,
	googleSpeechSpeed: 0.48,
	setAudioShortcut: "A",
	setIpaShortcut: "Z",
	defaultIpaShortcut: "X",
	popupFontFamily: "Segoe UI",
	popupFontSizepx: 22,
};
