export default function populateIpaw(table) {
return table.set({
"w":"/ˈdəbəlju/",
"w's":"/ˈdəbəljuz/",
"w.":"/ˈdəbəlju/",
"w.'s":"/ˈdəbəljuz/",
"w.s":"/ˈdəbəljuz/",
"wa":"/ˈwɑ/",
"waack":"/ˈwɑk/",
"waag":"/ˈwɑɡ/",
"waage":"/ˈwɑɪdʒ/",
"waah":"/ˈwɑ/",
"waal":"/ˈwɑl/",
"waara":"/ˈwɑɹə/",
"waas":"/ˈwɑz/",
"wabash":"/ˈwɔbæʃ/",
"wabash's":"/ˈwɔbæʃəz/",
"wace":"/ˈweɪs/",
"wach":"/ˈwɔtʃ/",
"wacha":"/ˈwɑtʃə/",
"wachholz":"/ˈwɔkhoʊlz/",
"wachner":"/ˈwæknɝ/",
"wacho":"/ˈwɑtʃoʊ/",
"wachob":"/ˈwɔkəb/",
"wachovia":"/wɑˈtʃoʊviə/",
"wachowiak":"/vəˈhaʊiæk/",
"wachowski":"/vəˈhɔfski/",
"wachs":"/ˈwɔks/",
"wachsman":"/ˈwɔksmən/",
"wachsmuth":"/ˈwɔksmʊθ/",
"wachtel":"/ˈwɔtʃəl/",
"wachtell":"/wɑkˈtɛl/",
"wachter":"/ˈwɔktɝ/",
"wachtler":"/ˈwæktlɝ/",
"wack":"/ˈwæk/",
"wackenhut":"/ˈwɑkənˌhət/",
"wacker":"/ˈwækɝ/",
"wackerle":"/ˈwækɝəl/, /ˈwækɝli/",
"wacko":"/ˈwækoʊ/",
"wackos":"/ˈwækoʊz/",
"wacks":"/ˈwæks/",
"wacksman":"/ˈwæksmən/",
"wacksman's":"/ˈwæksmənz/",
"wacky":"/ˈwæki/",
"waco":"/ˈweɪkoʊ/",
"wactlar":"/ˈwɑktlɝ/",
"wad":"/ˈwɑd/",
"wada":"/ˈwɑdə/",
"wadas":"/ˈwɑdəz/",
"wadded":"/ˈwɑdɪd/",
"waddell":"/wɑˈdɛl/",
"waddie":"/ˈwɑdi/",
"waddill":"/ˈwɔˈdɪl/",
"waddington":"/ˈwɑdɪŋtən/",
"waddle":"/ˈwɑdəl/",
"waddy":"/ˈwɑdi/",
"wade":"/ˈweɪd/",
"wade's":"/ˈweɪdz/",
"waded":"/ˈweɪdɪd/",
"wadel":"/ˈweɪdəl/",
"wader":"/ˈweɪdɝ/",
"waders":"/ˈweɪdɝz/",
"wades":"/ˈweɪdz/",
"wadford":"/ˈwɔdfɝd/",
"wadhams":"/ˈwɔdəmz/",
"wadi":"/ˈwɑˌdi/",
"wading":"/ˈweɪdɪŋ/",
"wadkins":"/ˈwɔdkɪnz/",
"wadle":"/ˈwɔdəl/",
"wadleigh":"/ˈwɔdli/",
"wadley":"/ˈwɑdli/",
"wadlington":"/ˈwɑdlɪŋtən/",
"wadlow":"/ˈwɑdˌloʊ/",
"wadman":"/ˈwɔdmən/",
"wads":"/ˈwɑdz/",
"wadsworth":"/ˈwɑdzwɝθ/",
"wadsworth's":"/ˈwɑdzwɝθs/",
"waechter":"/ˈwɛktɝ/",
"waeltermann":"/ˈvæltɝmən/, /ˈwɑltɝmən/",
"waertsilae":"/ˈwɛɹtsəˌleɪ/",
"wafer":"/ˈweɪfɝ/",
"wafers":"/ˈweɪfɝz/",
"waffenschmidt":"/ˈwɑfənʃˌmɪt/",
"waffle":"/ˈwɑfəl/",
"waffled":"/ˈwɑfəld/",
"waffles":"/ˈwɑfəlz/",
"waffling":"/ˈwɑflɪŋ/",
"wafford":"/ˈwɑfɝd/",
"waft":"/ˈwɑft/",
"wafted":"/ˈwɑftɪd/",
"wafting":"/ˈwɑftɪŋ/",
"wag":"/ˈwæɡ/",
"wag's":"/ˈwæɡz/",
"waga":"/ˈdəbəˌjuˈeɪˈdʒiˈeɪ/, /ˈdəbəlˌjuˈeɪˈdʒiˈeɪ/, /ˈwɑɡə/",
"wagaman":"/ˈwæˈɡəmən/",
"wagar":"/ˈwæɡɝ/",
"wage":"/ˈweɪdʒ/",
"waged":"/ˈweɪdʒd/",
"wageman":"/ˈweɪdʒmən/",
"wagenaar":"/ˈwæɡənɑɹ/",
"wagener":"/ˈwæɡənɝ/",
"wagenknecht":"/ˈwæɡənɪkt/",
"wager":"/ˈweɪdʒɝ/",
"wagered":"/ˈweɪdʒɝd/",
"wagering":"/ˈweɪdʒɝɪŋ/",
"wagers":"/ˈweɪdʒɝz/",
"wages":"/ˈweɪdʒəz/, /ˈweɪdʒɪz/",
"wagg":"/ˈwæɡ/",
"wagged":"/ˈwæɡd/",
"waggener":"/ˈwæɡənɝ/",
"wagging":"/ˈwæɡɪŋ/",
"waggling":"/ˈwæɡəlɪŋ/, /ˈwæɡlɪŋ/",
"waggoner":"/ˈwæɡənɝ/",
"waggy":"/ˈwæɡi/",
"waging":"/ˈweɪdʒɪŋ/",
"wagle":"/ˈwæɡəl/",
"wagler":"/ˈwæɡlɝ/",
"wagley":"/ˈwæɡli/",
"wagman":"/ˈwæɡmən/",
"wagner":"/ˈvɑɡnɝ/, /ˈwæɡnɝ/",
"wagner's":"/ˈvæɡnɝz/, /ˈwæɡnɝz/",
"wagnerian":"/ˌvɑɡˈnɛɹiən/, /ˌwæɡˈnɛɹiən/",
"wagnon":"/ˈwæɡnən/",
"wagon":"/ˈwæɡən/",
"wagoneer":"/ˌwæɡəˈnɪɹ/",
"wagoneers":"/ˌwæɡəˈnɪɹz/",
"wagoner":"/ˈwæɡənɝ/",
"wagons":"/ˈwæɡənz/",
"wags":"/ˈwæɡz/",
"wagstaff":"/ˈwæɡˌstæf/",
"wagster":"/ˈwæɡstɝ/",
"waguespack":"/ˈwæɡɪˌspæk/",
"wagy":"/ˈwæɡi/",
"wah":"/ˈwɑ/",
"wah's":"/ˈwɑz/",
"wah-pei":"/ˈwɑˈpeɪ/",
"wahid":"/ˌwɑˈhid/",
"wahine":"/wəˈhini/",
"wahines":"/wəˈhiniz/",
"wahl":"/ˈwɑl/",
"wahlberg":"/ˈwɑlbɝɡ/",
"wahle":"/ˈwɔl/",
"wahlen":"/ˈwɑlən/",
"wahler":"/ˈwɑlɝ/",
"wahlers":"/ˈwɑlɝz/",
"wahlert":"/ˈwɑlɝt/",
"wahlgren":"/ˈwɑlɡɹən/",
"wahlquist":"/ˈwɑlˌkwɪst/",
"wahlstrom":"/ˈwɑlstɹəm/",
"wahoo":"/ˈwɑˈhu/, /wəˈhu/",
"wai":"/ˈwaɪ/",
"waibel":"/ˈwaɪbəl/, /ˈweɪbəl/",
"waid":"/ˈweɪd/",
"waide":"/ˈweɪd/",
"waidelich":"/ˈwaɪdlɪk/",
"waif":"/ˈweɪf/",
"waifer":"/ˈweɪfɝ/",
"waigel":"/ˈwaɪɡəl/",
"waikiki":"/ˌwaɪkiˈki/",
"wail":"/ˈweɪl/",
"wailed":"/ˈweɪld/",
"wailes":"/ˈweɪlz/",
"wailing":"/ˈweɪlɪŋ/",
"wails":"/ˈweɪlz/",
"wain":"/ˈweɪn/",
"wainer":"/ˈweɪnɝ/",
"wainio":"/ˈweɪnioʊ/",
"wainman":"/ˈweɪnmən/",
"wainoco":"/ˌweɪˈnoʊkoʊ/",
"wainoco's":"/ˌweɪˈnoʊkoʊz/",
"wainright":"/ˈweɪnˌɹaɪt/",
"wainscot":"/ˈweɪnskət/",
"wainscott":"/ˈweɪnskət/",
"wainscotting":"/ˈweɪnskɔtɪŋ/",
"wainwright":"/ˈweɪnˌɹaɪt/",
"wais":"/ˈweɪz/",
"waisanen":"/ˈwaɪsənən/",
"waisner":"/ˈweɪznɝ/",
"waist":"/ˈweɪst/",
"waistline":"/ˈweɪstˌlaɪn/",
"waists":"/ˈweɪsts/",
"wait":"/ˈweɪt/",
"waite":"/ˈweɪt/",
"waite's":"/ˈweɪts/",
"waited":"/ˈweɪtɪd/",
"waiter":"/ˈweɪtɝ/",
"waiter's":"/ˈweɪtɝz/",
"waiters":"/ˈweɪtɝz/",
"waites":"/ˈweɪts/",
"waitin'":"/ˈweɪtɪn/",
"waiting":"/ˈweɪtɪŋ/",
"waitkus":"/ˈweɪtkəs/",
"waitman":"/ˈwaɪtmən/",
"waitress":"/ˈweɪtɹəs/",
"waitresses":"/ˈweɪtɹəsɪz/",
"waits":"/ˈweɪts/",
"waitt":"/ˈweɪt/",
"waitzkin":"/ˈweɪtˌskɪn/",
"waive":"/ˈweɪv/",
"waived":"/ˈweɪvd/",
"waiver":"/ˈweɪvɝ/",
"waivers":"/ˈweɪvɝz/",
"waives":"/ˈweɪvz/",
"waiving":"/ˈweɪvɪŋ/",
"wajda":"/ˈvaɪdə/",
"wakabayashi":"/wɑˌkɑbɑˈjɑʃi/",
"wake":"/ˈweɪk/",
"wake-up":"/ˈweɪˌkəp/",
"wakefield":"/ˈweɪkˌfild/",
"wakeham":"/ˈwækəm/",
"wakeland":"/ˈweɪklənd/",
"wakeley":"/ˈwækli/",
"wakely":"/ˈweɪkli/",
"wakeman":"/ˈweɪkmən/",
"waken":"/ˈweɪkən/",
"wakes":"/ˈweɪks/",
"wakeup":"/ˈweɪˌkəp/",
"wakid":"/ˈweɪkəd/",
"waking":"/ˈweɪkɪŋ/",
"wakley":"/ˈwækli/",
"wako":"/ˈwækoʊ/",
"wal":"/ˈwɔl/",
"wal-mart":"/ˈwɔlˌmɑɹt/",
"wala":"/ˈwɔlə/",
"wala's":"/ˈwɔləz/",
"walas":"/ˈwɔləz/",
"walberg":"/ˈwɔlbɝɡ/",
"walbert":"/ˈwɔlbɝt/",
"walborn":"/ˈwɔlbɝn/",
"walbridge":"/ˈwɔlbɹɪdʒ/",
"walbro":"/ˈwɔlbɹoʊ/",
"walburn":"/ˈwɔlbɝn/",
"walby":"/ˈwɔlbi/",
"walch":"/ˈwɔltʃ/",
"walcher":"/ˈwɔltʃɝ/",
"walck":"/ˈwɔlk/",
"walcot":"/ˈwɔlkɑt/",
"walcott":"/ˈwɔlkɑt/",
"walczak":"/ˈvɑltʃæk/",
"walczyk":"/ˈvɑltʃɪk/",
"wald":"/ˈwɔld/",
"walda":"/ˈvɑldə/",
"waldbaum":"/ˈwɔldˌbaʊm/",
"walde":"/ˈwɔld/",
"waldeck":"/ˈwɔldɛk/",
"waldecker":"/ˈwɔlˌdɛkɝ/",
"waldegard":"/ˈwɔldəˌɡɑɹd/",
"waldemar":"/ˈvɑldəmɑɹ/",
"walden":"/ˈwɔldən/",
"waldenbooks":"/ˈwɔldənˌbʊks/",
"waldenbooks'":"/ˈwɔldənˌbʊks/",
"walder":"/ˈwɔldɝ/",
"waldheim":"/ˈvɔldˌhaɪm/, /ˈwɔldˌhaɪm/",
"waldheim's":"/ˈvɔldˌhaɪmz/, /ˈwɔldˌhaɪmz/",
"waldholtz":"/ˈwɔldˌhoʊlts/",
"waldholtz's":"/ˈwɔldˌhoʊltsɪz/",
"waldholz":"/ˈwɔldˌhoʊlts/",
"waldhorn":"/ˈwɔldˌhɔɹn/",
"waldie":"/ˈwɔldi/",
"walding":"/ˈwɔldɪŋ/",
"waldinger":"/ˈwɔldɪŋɝ/",
"waldman":"/ˈwɑldmən/",
"waldmann":"/ˈwɔldmən/",
"waldner":"/ˈwɔldnɝ/",
"waldo":"/ˈwɑldoʊ/, /ˈwɔldoʊ/",
"waldoch":"/ˈwɔldɑk/",
"waldock":"/ˈwɔldɑk/",
"waldon":"/ˈwɔldən/",
"waldorf":"/ˈwɔldɔɹf/",
"waldow":"/ˈwɔldoʊ/",
"waldren":"/ˈwɔldɹən/",
"waldrep":"/ˈwɔldɹəp/",
"waldridge":"/ˈwɔldɹɪdʒ/",
"waldrip":"/ˈwɔldɹəp/",
"waldron":"/ˈwɔldɹən/",
"waldroop":"/ˈwɔlˌdɹup/",
"waldrop":"/ˈwɔldɹɑp/",
"waldroup":"/ˈwɔlˌdɹup/",
"waldrum":"/ˈwɔldɹəm/",
"waldrup":"/ˈwɔldɹəp/",
"waldschmidt":"/ˈwɔldʃˌmɪt/",
"waldvogel":"/ˈwɔldˌvoʊɡəl/",
"wale":"/ˈweɪl/",
"waleed":"/ˌwɑˈlid/",
"walek":"/ˈvɑlɛk/",
"walen":"/ˈweɪlən/",
"walenta":"/vəˈlɛntə/, /wəˈlɛntə/",
"wales":"/ˈweɪlz/",
"wales'":"/ˈweɪlz/",
"walesa":"/vəˈlɛsə/, /wəˈlɛsə/",
"walesa's":"/vəˈlɛsəz/, /wəˈlɛsəz/",
"waleson":"/ˈweɪlsən/",
"walford":"/ˈwɔlfɝd/",
"walfred":"/ˈwɔlfɹɛd/",
"walgreen":"/ˈwɔlˌɡɹin/",
"walgren":"/ˈwɔlɡɹən/",
"walicki":"/wəˈlɪki/",
"walid":"/wɑˈlid/",
"waligora":"/wɔlɪˈɡɔɹə/",
"walinsky":"/wəˈlɪnski/",
"walizer":"/ˈwɔlaɪzɝ/",
"walk":"/ˈwɑk/, /ˈwɔk/",
"walk-in":"/ˈwɔˌkɪn/",
"walk-on":"/ˈwɔˌkɑn/",
"walk-ons":"/ˈwɔˌkɑnz/",
"walke":"/ˈwɔk/",
"walked":"/ˈwɔkt/",
"walken":"/ˈwɔkən/",
"walkenhorst":"/ˈwɔkənˌhɔɹst/",
"walker":"/ˈwɔkɝ/",
"walker's":"/ˈwɔkɝz/",
"walkers":"/ˈwɔkɝz/",
"walkie":"/ˈwɔki/",
"walkin'":"/ˈwɔkɪn/",
"walking":"/ˈwɔkɪŋ/",
"walkington":"/ˈwɔkɪŋtən/",
"walkinshaw":"/ˈwɔkənʃɔ/",
"walkley":"/ˈwɔkli/",
"walkman":"/ˈwɔkˌmæn/, /ˈwɔkmən/",
"walkner":"/ˈwɔknɝ/",
"walko":"/ˈwɔkoʊ/",
"walkout":"/ˈwɔˌkaʊt/",
"walkouts":"/ˈwɔˌkaʊts/",
"walkowiak":"/wɔˈkaʊiæk/",
"walkowski":"/wɔˈkɔfski/",
"walks":"/ˈwɔks/",
"walkthrough":"/ˈwɔkθɹaʊ/",
"walkup":"/ˈwɔˌkəp/",
"walkure":"/ˈwɔkjɝ/",
"walkway":"/ˈwɔˌkweɪ/",
"walkways":"/ˈwɔˌkweɪz/",
"wall":"/ˈwɔl/",
"wall's":"/ˈwɔlz/",
"wall-e":"/ˈwɔˌli/",
"wall-tex":"/ˈwɔlˌtɛks/",
"walla":"/ˈwɔlɑ/",
"wallabies":"/ˈwɑləˌbiz/",
"wallaby":"/ˈwɑləˌbi/",
"wallace":"/ˈwɔləs/, /ˈwɔlɪs/",
"wallace's":"/ˈwɔləsəz/",
"wallach":"/ˈwɔlək/",
"wallack":"/ˈwɔlək/",
"wallander":"/ˈwɔləndɝ/",
"wallar":"/ˈwɔlɝ/",
"wallboard":"/ˈwɔlˌbɔɹd/",
"walle":"/ˈwɔl/",
"walled":"/ˈwɔld/",
"wallen":"/ˈwɔlən/",
"wallenberg":"/ˈwɔlənbɝɡ/",
"wallenberg's":"/ˈwɔlənbɝɡz/",
"wallenstein":"/ˈwɔlənˌstaɪn/, /ˈwɔlənˌstin/",
"waller":"/ˈwɔlɝ/",
"wallerstein":"/ˈwɔlɝˌstaɪn/, /ˈwɔlɝˌstin/",
"walles":"/ˈwɔlz/",
"wallet":"/ˈwɔlət/",
"wallets":"/ˈwɔləts/",
"walley":"/ˈwɔli/",
"walleye":"/ˈwɔˌlaɪ/",
"wallflower":"/ˈwɔlˌflaʊɝ/",
"wallgren":"/ˈwɔlɡɹən/",
"wallich":"/ˈwɔlɪk/",
"wallich's":"/ˈwɔlɪks/",
"wallick":"/ˈwɔlɪk/",
"wallie":"/ˈwɔli/",
"wallin":"/ˈwɔlɪn/",
"walling":"/ˈwɔlɪŋ/",
"wallingford":"/ˈwɔlɪŋfɝd/",
"wallington":"/ˈwɔlɪŋtən/",
"wallis":"/ˈwɔlɪs/",
"wallison":"/ˈwɔlɪsən/",
"wallman":"/ˈwɔlmən/",
"wallner":"/ˈwɔlnɝ/",
"wallo":"/ˈwɑloʊ/",
"walloch":"/ˈwɔlək/",
"wallop":"/ˈwɑləp/",
"walloping":"/ˈwɔləpɪŋ/",
"wallops":"/ˈwɑləps/",
"wallow":"/ˈwɑloʊ/",
"wallowed":"/ˈwɑloʊd/",
"wallowing":"/ˈwɑloʊɪŋ/",
"wallpaper":"/ˈwɔlˌpeɪpɝ/",
"wallpapered":"/ˈwɔlˌpeɪpɝd/",
"wallpapering":"/ˈwɔlˌpeɪpɝɪŋ/",
"wallpapers":"/ˈwɔlˌpeɪpɝz/",
"walls":"/ˈwɔlz/",
"wallsend":"/ˈwɔlˌsɛnd/",
"wallstreet":"/ˈwɔlˌstɹit/",
"wallwork":"/ˈwɔlˌwɝk/",
"wally":"/ˈweɪli/, /ˈwɔli/",
"wally's":"/ˈwɔliz/",
"walmart":"/ˈwɔlˌmɑɹt/",
"walmart's":"/ˈwɔlˌmɑɹts/",
"walmarts":"/ˈwɔlˌmɑɹts/",
"walmer":"/ˈwɔlmɝ/",
"walmond":"/ˈwɔlmənd/",
"walmsley":"/ˈwɔlmsli/",
"waln":"/ˈwɔln/",
"walnut":"/ˈwɔlˌnət/",
"walnuts":"/ˈwɔlˌnəts/",
"walp":"/ˈwælp/, /ˈwɔlp/",
"walpole":"/ˈwɔlˌpoʊl/",
"walrath":"/ˈwɔlɹəθ/",
"walraven":"/ˈwɔlˌɹeɪvən/",
"walrod":"/ˈwɔlɹɑd/",
"walrus":"/ˈwɔlɹəs/",
"walruses":"/ˈwɑlɹəsɪz/",
"walser":"/ˈwɔlzɝ/",
"walsh":"/ˈwɔlʃ/",
"walsh's":"/ˈwɔlʃɪz/",
"walski":"/ˈvɑlski/",
"walstad":"/ˈwɔlstæd/",
"walston":"/ˈwɔlstən/",
"walstrom":"/ˈwɔlstɹəm/",
"walsworth":"/ˈwɔlswɝθ/",
"walt":"/ˈwɔlt/",
"walter":"/ˈwɔltɝ/",
"walter's":"/ˈwɔltɝz/",
"waltermire":"/ˈwɔltɝmaɪɹ/",
"walters":"/ˈwɔltɝz/",
"walters'":"/ˈwɔltɝz/",
"walth":"/ˈwɔlθ/",
"walthall":"/ˈwɔlθəl/",
"waltham":"/ˈwɔlθəm/",
"walther":"/ˈwɔlθɝ/",
"walthers":"/ˈwɔlθɝz/",
"walthose":"/ˈwɔltˌhoʊz/",
"walthour":"/ˈwɔltaʊɹ/",
"waltman":"/ˈwɔltmən/",
"waltner":"/ˈwɔltnɝ/",
"walton":"/ˈwɔltən/",
"walton's":"/ˈwɔltənz/",
"waltons":"/ˈwɔltənz/",
"waltrip":"/ˈwɔltɹɪp/",
"walts":"/ˈwɔlts/",
"waltz":"/ˈwɔls/, /ˈwɔlts/",
"waltzer":"/ˈwɔlsɝ/, /ˈwɔltsɝ/",
"waltzes":"/ˈwɔlsəz/, /ˈwɔltsəz/",
"waltzing":"/ˈwɔlsɪŋ/, /ˈwɔltsɪŋ/",
"walworth":"/ˈwɔlwɝθ/",
"walwyn":"/ˈwɔlwɪn/",
"walz":"/ˈwɔlz/",
"walzer":"/ˈwɔlzɝ/",
"wambach":"/ˈwɔmbɑk/",
"wambaugh":"/ˈwɔmbɑ/",
"wamble":"/ˈwɑmbəl/",
"wambold":"/ˈwɑmˌboʊld/",
"wamboldt":"/ˈwɑmboʊlt/",
"wambolt":"/ˈwɑmˌboʊlt/",
"wampler":"/ˈwɑmplɝ/",
"wampole":"/ˈwɑmˌpoʊl/",
"wampum":"/ˈwɑmpəm/",
"wamser":"/ˈwɑmzɝ/",
"wamsley":"/ˈwɑmzli/",
"wan":"/ˈwɑn/",
"wanamaker":"/ˈwɑnəˌmeɪkɝ/",
"wanat":"/ˈweɪnət/",
"wand":"/ˈwɑnd/",
"wanda":"/ˈwɑndə/",
"wandel":"/ˈwɑndəl/",
"wandell":"/ˈwɑndəl/",
"wander":"/ˈwɑndɝ/",
"wandered":"/ˈwɑndɝd/",
"wanderer":"/ˈwɑndɝɝ/",
"wanderers":"/ˈwɑndɝɝz/",
"wandering":"/ˈwɑndɝɪŋ/",
"wanderings":"/ˈwɑndɝɪŋz/",
"wanderlust":"/ˈwɑndɝˌləst/",
"wanders":"/ˈwɑndɝz/",
"wandersee":"/ˈwɑndɝˌsi/",
"wandie":"/ˈwɑndi/",
"wandis":"/ˈwɑndɪs/",
"wandler":"/ˈwɑndlɝ/",
"wandling":"/ˈwɑndlɪŋ/",
"wandrey":"/ˈwɑndɹi/",
"wands":"/ˈwɑndz/",
"wane":"/ˈweɪn/",
"waned":"/ˈweɪnd/",
"wanek":"/ˈweɪnɪk/",
"waner":"/ˈweɪnɝ/",
"wanes":"/ˈweɪnz/",
"wang":"/ˈwæŋ/",
"wang's":"/ˈwæŋz/",
"wangen":"/ˈwæŋən/",
"wanger":"/ˈwæŋɝ/",
"wangerin":"/ˈwɔŋɡɝɪn/",
"wangle":"/ˈwæŋɡəl/",
"wangled":"/ˈwæŋɡəld/",
"wangler":"/ˈwæŋɡlɝ/",
"waning":"/ˈweɪnɪŋ/",
"wank":"/ˈwɑŋk/",
"wanke":"/ˈwɑŋk/",
"wanker":"/ˈwɑŋkɝ/",
"wankers":"/ˈwɑŋkɝz/",
"wanko":"/ˈwɑŋkoʊ/",
"wanless":"/ˈwɑnləs/",
"wann":"/ˈwɑn/",
"wanna":"/ˈwɑnə/",
"wannabe":"/ˈwɑnəˌbi/",
"wannabee":"/ˈwɑnəˌbi/",
"wannabees":"/ˈwɑnəˌbiz/",
"wannabes":"/ˈwɑnəˌbiz/",
"wannamaker":"/ˈwɑnəˌmeɪkɝ/",
"wannemacher":"/ˈwɑnəmɑkɝ/",
"wanner":"/ˈwɑnɝ/",
"wanninger":"/ˈwɑnɪŋɝ/",
"wanniski":"/wəˈnɪski/",
"wanser":"/ˈwɔnzɝ/",
"wansley":"/ˈwɔnzli/",
"want":"/ˈwɑnt/, /ˈwɔnt/",
"wanta":"/ˈwɑnə/, /ˈwɑntə/",
"wantage":"/ˈwɑntɪdʒ/",
"wantages":"/ˈwɑntɪdʒɪz/",
"wante":"/ˈwɑntə/",
"wanted":"/ˈwɔntɪd/",
"wanting":"/ˈwɑnɪŋ/, /ˈwɑntɪŋ/",
"wantland":"/ˈwɑntlənd/",
"wanton":"/ˈwɑntən/, /ˈwɔntən/",
"wantonly":"/ˈwɑntənli/, /ˈwɔntənli/",
"wants":"/ˈwɑnts/, /ˈwɔnts/",
"wantz":"/ˈwɑnts/",
"wanzer":"/ˈwɑnzɝ/",
"wapiti":"/wəˈpiti/",
"waples":"/ˈwɔpəlz/",
"wapner":"/ˈwɑpnɝ/",
"wapping":"/ˈwɑpɪŋ/",
"war":"/ˈwɔɹ/",
"war's":"/ˈwɔɹz/",
"warbington":"/ˈwɔɹbɪŋtən/",
"warble":"/ˈwɔɹbəl/",
"warbled":"/ˈwɔɹbəld/",
"warbler":"/ˈwɔɹblɝ/",
"warblers":"/ˈwɔɹblɝz/",
"warbles":"/ˈwɔɹbəlz/",
"warbling":"/ˈwɔɹbəlɪŋ/, /ˈwɔɹblɪŋ/",
"warbucks":"/ˈwɔɹˌbʊks/",
"warburg":"/ˈwɔɹbɝɡ/",
"warburg's":"/ˈwɔɹbɝɡz/",
"warburton":"/ˈwɔɹbɝtən/",
"warchol":"/ˈwɔɹkɔl/",
"warcraft":"/ˈwɔɹˌkɹæft/",
"ward":"/ˈwɔɹd/",
"ward's":"/ˈwɔɹdz/",
"warda":"/ˈwɔɹˌdɑ/",
"wardair":"/ˈwɔɹˌdɛɹ/",
"warde":"/ˈwɔɹd/",
"warded":"/ˈwɔɹdɪd/",
"wardell":"/ˈwɔɹdɛl/",
"warden":"/ˈwɔɹdən/",
"warden's":"/ˈwɔɹdənz/",
"wardens":"/ˈwɔɹdənz/",
"wardens'":"/ˈwɔɹdənz/",
"warder":"/ˈwɔɹdɝ/",
"warders":"/ˈwɔɹdɝz/",
"warding":"/ˈwɔɹdɪŋ/",
"wardlaw":"/ˈwɔɹdˌlɔ/",
"wardle":"/ˈwɔɹdəl/",
"wardley":"/ˈwɔɹdli/",
"wardlow":"/ˈwɔɹdˌloʊ/",
"wardrip":"/ˈwɔɹdɹɪp/",
"wardrobe":"/ˈwɔɹˌdɹoʊb/",
"wardrobes":"/ˈwɔɹˌdɹoʊbz/",
"wardrop":"/ˈwɔɹˌdɹɑp/",
"wards":"/ˈwɔɹdz/",
"wardwell":"/ˈwɔɹdˌwɛl/",
"ware":"/ˈwɛɹ/",
"warehime":"/ˈwɛɹˌhaɪm/",
"warehouse":"/ˈwɛɹˌhaʊs/",
"warehoused":"/ˈwɛɹˌhaʊzd/",
"warehouses":"/ˈwɛɹˌhaʊsɪz/, /ˈwɛɹˌhaʊzɪz/",
"warehousing":"/ˈwɛɹˌhaʊzɪŋ/",
"wareing":"/ˈwɛɹɪŋ/",
"waren":"/ˈwɛɹən/",
"wares":"/ˈwɛɹz/",
"warez":"/ˈwɛɹz/",
"warf":"/ˈwɔɹf/",
"warfare":"/ˈwɔɹˌfɛɹ/",
"warfel":"/ˈwɔɹfəl/",
"warfield":"/ˈwɔɹfild/",
"warford":"/ˈwɔɹfɝd/",
"warga":"/ˈwɔɹɡə/",
"wargo":"/ˈwɔɹˌɡoʊ/",
"warhead":"/ˈwɔɹˌhɛd/",
"warheads":"/ˈwɔɹˌhɛdz/",
"warhol":"/ˈwɔɹhɔl/",
"warhol's":"/ˈwɔhˌɹɔlz/",
"warhurst":"/ˈwɔɹhɝst/",
"warily":"/ˈwɛɹəli/",
"wariness":"/ˈwɛɹinɪs/",
"waring":"/ˈwɛɹɪŋ/",
"wark":"/ˈwɔɹk/",
"warkentin":"/ˈwɔɹkəntɪn/, /wɔɹˈkɛntɪn/",
"warley":"/ˈwɔɹli/",
"warlick":"/ˈwɔɹlɪk/",
"warlike":"/ˈwɔɹˌlaɪk/",
"warling":"/ˈwɔɹlɪŋ/",
"warlock":"/ˈwɔɹˌlɔk/",
"warlock's":"/ˈwɔɹˌlɔks/",
"warlocks":"/ˈwɔɹˌlɔks/",
"warloeck":"/ˈwɔɹˌlɑk/",
"warlord":"/ˈwɔɹˌlɔɹd/",
"warlords":"/ˈwɔɹˌlɔɹdz/",
"warm":"/ˈwɔɹm/",
"warmack":"/ˈwɔɹmæk/",
"warman":"/ˈwɔɹmən/",
"warmed":"/ˈwɔɹmd/",
"warmer":"/ˈwɔɹmɝ/",
"warmest":"/ˈwɔɹməst/",
"warming":"/ˈwɔɹmɪŋ/",
"warmington":"/ˈwɔɹmɪŋtən/",
"warminster":"/ˈwɔɹˌmɪnstɝ/",
"warmish":"/ˈwɔɹmɪʃ/",
"warmly":"/ˈwɔɹmli/",
"warmond":"/ˈwɔɹmənd/",
"warmonger":"/ˈwɔɹˌmɑŋɡɝ/",
"warmongering":"/ˈwɔɹˌmɑŋɡɝɪŋ/",
"warmoth":"/ˈwɔɹməθ/",
"warms":"/ˈwɔɹmz/",
"warmth":"/ˈwɔɹmθ/",
"warmup":"/ˈwɔɹˌməp/",
"warmus":"/ˈwɔɹməs/",
"warmuth":"/ˈwɔɹˌmʊθ/",
"warn":"/ˈwɔɹn/",
"warnaco":"/ˈwɔɹnəˌkoʊ/",
"warncke":"/ˈwɔɹŋki/",
"warne":"/ˈwɔɹn/",
"warnecke":"/ˈwɔɹnɪk/",
"warned":"/ˈwɔɹnd/",
"warneke":"/ˈwɔɹnɪk/",
"warnell":"/ˈwɔɹnəl/",
"warner":"/ˈwɔɹnɝ/",
"warner's":"/ˈwɔɹnɝz/",
"warners":"/ˈwɔɹnɝz/",
"warnes":"/ˈwɔɹnz/",
"warnick":"/ˈwɔɹnɪk/",
"warnico":"/ˈwɔɹnɪkoʊ/",
"warning":"/ˈwɔɹnɪŋ/",
"warningly":"/ˈwɔɹnɪŋli/",
"warnings":"/ˈwɔɹnɪŋz/",
"warnke":"/ˈwɔɹŋki/",
"warnken":"/ˈwɔɹŋkən/",
"warno":"/ˈwɑɹnoʊ/",
"warnock":"/ˈwɔɹnɑk/",
"warns":"/ˈwɔɹnz/",
"waronker":"/wɔˈɹɑŋkɝ/",
"warp":"/ˈwɔɹp/",
"warpath":"/ˈwɔɹˌpæθ/",
"warped":"/ˈwɔɹpt/",
"warping":"/ˈwɔɹpɪŋ/",
"warplane":"/ˈwɔɹˌpleɪn/",
"warplanes":"/ˈwɔɹˌpleɪnz/",
"warps":"/ˈwɔɹps/",
"warr":"/ˈwɔɹ/",
"warrant":"/ˈwɔɹənt/",
"warranted":"/ˈwɔɹəntɪd/",
"warranties":"/ˈwɔɹəntiz/",
"warrantless":"/ˈwɔɹəntləs/",
"warrants":"/ˈwɔɹənts/",
"warranty":"/ˈwɔɹənti/",
"warrell":"/ˌwɔˈɹɛl/",
"warren":"/ˈwɔɹən/",
"warren's":"/ˈwɔɹənz/",
"warrens":"/ˈwɔɹənz/",
"warrenton":"/ˈwɑɹəntən/",
"warrick":"/ˈwɔɹɪk/",
"warriner":"/ˈwɔɹənɝ/",
"warring":"/ˈwɔɹɪŋ/",
"warrington":"/ˈwɔɹɪŋtən/",
"warrior":"/ˈwɔɹiɝ/, /ˈwɔɹjɝ/",
"warriors":"/ˈwɔɹiɝz/, /ˈwɔɹjɝz/",
"wars":"/ˈwɔɹz/",
"wars'":"/ˈwɔɹz/",
"warsaw":"/ˈwɔɹˌsɔ/",
"warsaw's":"/ˈwɔɹˌsɔz/",
"warsaws":"/ˈwɔɹˌsɔz/",
"warshauer":"/ˈwɔɹʃaʊɝ/",
"warshaw":"/ˈwɔɹˌʃɔ/",
"warshawsky":"/ˈwɔɹʃəwski/",
"warship":"/ˈwɔɹˌʃɪp/",
"warships":"/ˈwɔɹˌʃɪps/",
"warstler":"/ˈwɔɹstlɝ/",
"warszawa":"/ˌwɑɹˈʃɑˌwɑ/",
"wart":"/ˈwɔɹt/",
"wartenberg":"/ˈwɔɹtənbɝɡ/",
"warth":"/ˈwɔɹθ/",
"warthen":"/ˈwɔɹθən/",
"wartime":"/ˈwɔɹˌtaɪm/",
"wartimes":"/ˈwɔɹˌtaɪmz/",
"wartman":"/ˈwɔɹtmən/",
"warton":"/ˈwɔɹtən/",
"warts":"/ˈwɔɹts/",
"wartzman":"/ˈwɔɹtsmən/",
"warwick":"/ˈwɔɹwɪk/",
"warwick's":"/ˈwɔɹˌwɪks/",
"wary":"/ˈwɛɹi/",
"warzecha":"/wɔɹˈzɛhə/",
"was":"/ˈwɑz/, /wəz/",
"wasatch":"/ˈwɑsætʃ/",
"wasch":"/ˈwɔʃ/",
"wascher":"/ˈwɔʃɝ/",
"wasco":"/ˈwɔskoʊ/",
"wascom":"/ˈwɔskɑm/",
"wasden":"/ˈwɔsdən/",
"waseda":"/wəˈsidə/",
"wasem":"/ˈwɔsɪm/",
"wash":"/ˈwɑʃ/",
"washabaugh":"/ˈwɔʃəbɔ/",
"washable":"/ˈwɑʃəbəl/",
"washam":"/ˈwɑʃəm/",
"washbasin":"/ˈwɑʃˌbeɪsən/",
"washboard":"/ˈwɑʃˌbɔɹd/",
"washburn":"/ˈwɑʃˌbɝn/",
"washburne":"/ˈwɔʃˌbɝn/",
"washcloth":"/ˈwɑʃˌklɔθ/",
"washed":"/ˈwɑʃt/",
"washer":"/ˈwɑʃɝ/",
"washers":"/ˈwɑʃɝz/",
"washes":"/ˈwɑʃɪz/",
"washi's":"/ˈwɑʃiz/",
"washing":"/ˈwɑʃɪŋ/",
"washington":"/ˈwɑʃɪŋtən/, /ˈwɔʃɪŋtən/",
"washington's":"/ˈwɑʃɪŋtənz/, /ˈwɔʃɪŋtənz/",
"washingtonian":"/ˌwɑʃɪŋˈtoʊniən/, /ˌwɔʃɪŋˈtoʊniən/",
"washingtonians":"/ˌwɑʃɪŋˈtoʊniənz/, /ˌwɔʃɪŋˈtoʊniənz/",
"washko":"/ˈvɑʃkoʊ/",
"washoe":"/ˈwɑˌʃoʊ/",
"washout":"/ˈwɑˌʃaʊt/",
"washouts":"/ˈwɑˌʃaʊts/",
"washroom":"/ˈwɑʃˌɹum/",
"washtub":"/ˈwɑʃˌtəb/",
"washy":"/ˈwɑʃi/",
"wasielewski":"/vəsiˈlɛfski/",
"wasik":"/ˈvɑsɪk/",
"wasil":"/ˈwɔsəl/",
"wasilewski":"/vəsɪˈlɛfski/",
"wasinger":"/ˈwɔsɪndʒɝ/",
"wasiyu":"/wəˈsiu/",
"waskiewicz":"/ˈvɑskəvɪtʃ/",
"wasko":"/ˈvɑskoʊ/",
"waskow":"/ˈvɑskoʊ/",
"wasley":"/ˈwɔsli/",
"wasmer":"/ˈwɔsəmɝ/",
"wasmund":"/ˈwɔzmənd/",
"wasmuth":"/ˈwɔzmuθ/",
"wasn't":"/ˈwɑzənt/, /ˈwəzənt/",
"wason":"/ˈwɑsən/",
"wasp":"/ˈwɑsp/",
"wasp's":"/ˈwɑsps/",
"wasps":"/ˈwɑsps/",
"wass":"/ˈwɑs/, /ˈwəs/",
"wassel":"/ˈwɔsəl/",
"wassell":"/ˈwɔsəl/",
"wassenaar":"/ˈwɔsɪnɑɹ/",
"wasser":"/ˈwɔsɝ/",
"wasserman":"/ˈwɑsɝmən/",
"wasserman's":"/ˈwɑsɝmənz/",
"wasserstein":"/ˈwɑsɝˌstaɪn/, /ˈwɑsɝˌstin/",
"wassilievitch":"/wɑˈsɪljəˌvɪtʃ/",
"wassily":"/vəˈsɪˌli/",
"wassink":"/ˈwɔsɪŋk/",
"wassman":"/ˈwɔsmən/",
"wassmer":"/ˈwɑsmɝ/",
"wassom":"/ˈwɑsəm/",
"wasson":"/ˈwɔsən/",
"wassum":"/ˈwɑsəm/",
"waste":"/ˈweɪst/",
"waste's":"/ˈweɪsts/",
"wastebasket":"/ˈweɪstˌbæskət/",
"wastebaskets":"/ˈweɪstˌbæskəts/",
"wasted":"/ˈweɪstɪd/",
"wasteful":"/ˈweɪstfəl/",
"wastefulness":"/ˈweɪstfəlnəs/",
"wasteland":"/ˈweɪstˌlænd/",
"wastepaper":"/ˈweɪstˌpeɪpɝ/",
"waster":"/ˈweɪstɝ/",
"wasters":"/ˈweɪstɝz/",
"wastes":"/ˈweɪsts/",
"wastewater":"/ˈweɪstˌwɔtɝ/",
"wasting":"/ˈweɪstɪŋ/",
"waszak":"/ˈvɑʃək/",
"waszkiewicz":"/ˌvɑʃˈkɛvɪtʃ/",
"wat":"/ˈwɔt/",
"watanabe":"/ˌwɑtɑˈnɑbeɪ/",
"watch":"/ˈwɑtʃ/, /ˈwɔtʃ/",
"watchdog":"/ˈwɑtʃˌdɔɡ/",
"watchdogs":"/ˈwɑtʃˌdɔɡz/",
"watched":"/ˈwɑtʃt/, /ˈwɔtʃt/",
"watcher":"/ˈwɑtʃɝ/",
"watchers":"/ˈwɑtʃɝz/",
"watches":"/ˈwɑtʃəz/, /ˈwɑtʃɪz/",
"watchful":"/ˈwɑtʃfəl/",
"watchin'":"/ˈwɑtʃɪn/",
"watching":"/ˈwɑtʃɪŋ/",
"watchman":"/ˈwɑtʃmən/",
"watchmen":"/ˈwɑtʃmɛn/",
"watchorn":"/ˈwɔtʃɝn/",
"watchword":"/ˈwɑtʃˌwɝd/",
"watchwords":"/ˈwɑtʃˌwɝdz/",
"water":"/ˈwɔtɝ/",
"water's":"/ˈwɔtɝz/",
"water-repellent":"/ˈwɔtɝɹɪˈpɛlənt/",
"waterbed":"/ˈwɔtɝˌbɛd/",
"waterbeds":"/ˈwɔtɝˌbɛdz/",
"waterborne":"/ˈwɔtɝˌbɔɹn/",
"waterbottle":"/ˈwɔtɝˌbɔtəl/",
"waterbottles":"/ˈwɔtɝˌbɔtəlz/",
"waterbury":"/ˈwɔtɝˌbɛɹi/",
"watercolor":"/ˈwɔtɝˌkəlɝ/",
"watercolors":"/ˈwɔtɝˌkəlɝz/",
"watercress":"/ˈwɔtɝˌkɹɛs/",
"watered":"/ˈwɔtɝd/",
"waterer":"/ˈwɔtɝɝ/",
"waterfall":"/ˈwɔtɝˌfɔl/",
"waterfalls":"/ˈwɔtɝˌfɔlz/",
"waterfield":"/ˈwɔtɝfild/",
"waterford":"/ˈwɔtɝfɝd/",
"waterfowl":"/ˈwɔtɝˌfaʊl/",
"waterfront":"/ˈwɔtɝˌfɹənt/",
"waterfronts":"/ˈwɔtɝˌfɹənts/",
"watergate":"/ˈwɑtɝˌɡeɪt/, /ˈwɔtɝˌɡeɪt/",
"waterhouse":"/ˈwɔtɝˌhaʊs/",
"waterhouse's":"/ˈwɔtɝˌhaʊsɪz/",
"watering":"/ˈwɔtɝɪŋ/",
"waterishness":"/ˈwɔtɝɪʃnəs/",
"waterlog":"/ˈwɔtɝˌlɑɡ/",
"waterlogged":"/ˈwɔtɝˌlɑɡd/",
"waterloo":"/ˈwɔtɝˌlu/",
"waterman":"/ˈwɔtɝmən/",
"waterman's":"/ˈwɔtɝmənz/",
"watermark":"/ˈwɔtɝˌmɑɹk/",
"watermarks":"/ˈwɔtɝˌmɑɹks/",
"watermelon":"/ˈwɔtɝˌmɛlən/",
"watermelons":"/ˈwɔtɝˌmɛlənz/",
"watermen":"/ˈwɔtɝmən/",
"waterproof":"/ˈwɔtɝˌpɹuf/",
"waterproofing":"/ˈwɔtɝˌpɹufɪŋ/",
"waters":"/ˈwɔtɝz/",
"watershed":"/ˈwɑtɝˌʃɛd/, /ˈwɔtɝˌʃɛd/",
"watersheds":"/ˈwɑtɝˌʃɛdz/, /ˈwɔtɝˌʃɛdz/",
"waterson":"/ˈwɔtɝsən/",
"waterstein":"/ˈwɔtɝstaɪn/, /ˈwɔtɝstin/",
"waterston":"/ˈwɔtɝstən/",
"waterstone":"/ˈwɔtɝˌstoʊn/",
"waterstone's":"/ˈwɔtɝˌstoʊnz/",
"watertight":"/ˈwɔtɝˌtaɪt/",
"watertown":"/ˈwɔtɝˌtaʊn/",
"waterville":"/ˈwɔtɝvɪl/",
"waterway":"/ˈwɔtɝˌweɪ/",
"waterways":"/ˈwɔtɝˌweɪz/",
"waterwork":"/ˈwɔtɝˌwɝk/",
"waterworks":"/ˈwɔtɝˌwɝks/",
"waterworld":"/ˈwɔtɝˌwɝld/",
"waterworth":"/ˈwɔtɝwɝθ/",
"watery":"/ˈwɔtɝi/",
"watford":"/ˈwɔtfɝd/",
"wathen":"/ˈwɔθən/",
"watkin":"/ˈwɔtkɪn/",
"watkins":"/ˈwɑtkɪnz/",
"watkins'":"/ˈwɑtkɪnz/",
"watkinson":"/ˈwɔtkɪnsən/",
"watland":"/ˈwɑtlənd/",
"watley":"/ˈwɑtli/",
"watling":"/ˈwɔtəlɪŋ/, /ˈwɔtlɪŋ/",
"watlington":"/ˈwɔtəlɪŋtən/, /ˈwɔtlɪŋtən/",
"watne":"/ˈwɔtn/",
"watrous":"/ˈwɑtɹəs/",
"watry":"/ˈwɑtɹi/",
"watsco":"/ˈwɑtˌskoʊ/",
"watson":"/ˈwɑtsən/",
"watson's":"/ˈwɑtsənz/",
"watsonville":"/ˈwɑtsənˌvɪl/",
"watt":"/ˈwɑt/",
"watt's":"/ˈwɑts/",
"wattage":"/ˈwɑtədʒ/",
"wattenbarger":"/ˈwɔtɪnbɑɹɡɝ/",
"wattenberg":"/ˈwɑtənbɝɡ/",
"wattenburg":"/ˈwɑtənbɝɡ/",
"watters":"/ˈwɑtɝz/",
"wattie":"/ˈwɑti/",
"wattle":"/ˈwɑtəl/",
"wattled":"/ˈwɑtəld/",
"wattles":"/ˈwɑtəlz/",
"wattleton":"/ˈwɑtəltən/",
"watton":"/ˈwɔtən/",
"watts":"/ˈwɑts/",
"wattwil":"/ˈwɑtwɪl/",
"watwood":"/ˈwɔtwʊd/",
"watz":"/ˈwɑts/",
"watzman":"/ˈwɑtsmən/",
"waugaman":"/ˈwɔɡəmən/",
"waugh":"/ˈwɔ/",
"waugh's":"/ˈwɔz/",
"waukegan":"/wɔˈkiɡən/",
"waukesha":"/wɔˈkiʃə/",
"wausau":"/ˈwɔsɔ/",
"wauters":"/ˈwaʊtɝz/",
"wave":"/ˈweɪv/",
"waved":"/ˈweɪvd/",
"waveform":"/ˈweɪvˌfɔɹm/",
"waveforms":"/ˈweɪvˌfɔɹmz/",
"wavelength":"/ˈweɪvˌlɛŋθ/",
"wavelengths":"/ˈweɪvˌlɛŋθs/",
"waver":"/ˈweɪvɝ/",
"wavered":"/ˈweɪvɝd/",
"wavering":"/ˈweɪvɝɪŋ/",
"waverley":"/ˈweɪvɝli/",
"waverly":"/ˈweɪvɝli/",
"waves":"/ˈweɪvz/",
"wavetek":"/ˈweɪvˌtɛk/",
"waving":"/ˈweɪvɪŋ/",
"wavra":"/ˈwɑvɹə/",
"wavy":"/ˈweɪvi/",
"wawrzyniak":"/wɑɹˈzɪniæk/",
"wax":"/ˈwæks/",
"waxed":"/ˈwækst/",
"waxes":"/ˈwæksɪz/",
"waxing":"/ˈwæksɪŋ/",
"waxler":"/ˈwækslɝ/",
"waxman":"/ˈwæksmən/",
"waxman's":"/ˈwæksmənz/",
"waxy":"/ˈwæksi/",
"way":"/ˈweɪ/",
"way's":"/ˈweɪz/",
"wayans":"/ˈhweɪənz/, /ˈweɪənz/",
"waybright":"/ˈweɪˌbɹaɪt/",
"waycaster":"/ˈweɪˌkæstɝ/",
"waye":"/ˈweɪ/",
"waylaid":"/ˈweɪˌleɪd/",
"wayland":"/ˈweɪlənd/",
"waylay":"/ˈweɪˌleɪ/",
"waylon":"/ˈweɪˌlɑn/",
"wayman":"/ˈweɪmən/",
"waymire":"/ˈweɪˌmaɪɹ/",
"wayne":"/ˈweɪn/",
"wayne's":"/ˈweɪnz/",
"waynesboro":"/ˈweɪnzbɝoʊ/",
"waynesville":"/ˈweɪnzˌvɪl/",
"waynick":"/ˈweɪnɪk/",
"ways":"/ˈweɪz/",
"wayside":"/ˈweɪˌsaɪd/",
"wayson":"/ˈweɪzən/",
"wayt":"/ˈweɪt/",
"wayward":"/ˈweɪwɝd/",
"wazir":"/wɑˈzɪɹ/",
"wazir's":"/wɑˈzɪɹz/",
"we":"/ˈwi/",
"we'd":"/ˈwid/",
"we'll":"/ˈwil/, /ˈwɪl/",
"we're":"/ˈwɝ/, /ˈwiɹ/, /ˈwɪɹ/",
"we've":"/ˈwiv/",
"weak":"/ˈwik/",
"weaken":"/ˈwikən/",
"weakened":"/ˈwikənd/",
"weakening":"/ˈwikənɪŋ/",
"weakens":"/ˈwikənz/",
"weaker":"/ˈwikɝ/",
"weakest":"/ˈwikəst/",
"weakland":"/ˈwiklənd/",
"weakley":"/ˈwikli/",
"weakling":"/ˈwiklɪŋ/",
"weakly":"/ˈwikli/",
"weakness":"/ˈwiknəs/",
"weaknesses":"/ˈwiknəsəz/, /ˈwiknəsɪz/",
"weaks":"/ˈwiks/",
"wealth":"/ˈwɛlθ/",
"wealthier":"/ˈwɛlθiɝ/",
"wealthiest":"/ˈwɛlθiəst/",
"wealths":"/ˈwɛlθs/",
"wealthy":"/ˈwɛlθi/",
"wean":"/ˈwin/",
"weaned":"/ˈwind/",
"weaning":"/ˈwinɪŋ/",
"weant":"/ˈwint/",
"weapon":"/ˈwɛpən/",
"weapon's":"/ˈwɛpənz/",
"weaponry":"/ˈwɛpənɹi/",
"weapons":"/ˈwɛpənz/",
"weapons'":"/ˈwɛpənz/",
"wear":"/ˈwɛɹ/",
"wearable":"/ˈwɛɹəbəl/",
"wearer":"/ˈwɛɹɝ/",
"wearers":"/ˈwɛɹɝz/",
"wearever":"/ˈwɛˌɹɛvɝ/",
"wearhouse":"/ˈwɛɹˌhaʊs/",
"wearied":"/ˈwɪɹid/",
"wearily":"/ˈwɛɹəli/",
"weariness":"/ˈwɪɹinəs/",
"wearing":"/ˈwɛɹɪŋ/",
"wearisome":"/ˈwɪɹisəm/",
"wears":"/ˈwɛɹz/",
"weary":"/ˈwɪɹi/",
"wearying":"/ˈwiɹiɪŋ/",
"wease":"/ˈwiz/",
"weasel":"/ˈwizəl/",
"weasellike":"/ˈwizəlˌlaɪk/",
"weasels":"/ˈwizəlz/",
"weast":"/ˈwist/",
"weather":"/ˈwɛðɝ/",
"weather's":"/ˈwɛðɝz/",
"weatherall":"/ˈwɛðɝˌɔl/",
"weatherbee":"/ˈwɛðɝˌbi/",
"weatherby":"/ˈwɛðɝbi/",
"weathered":"/ˈwɛðɝd/",
"weatherford":"/ˈwɛðɝfɝd/",
"weatherhead":"/ˈwɛðɝˌhɛd/",
"weatherholt":"/ˈwɛðɝˌhoʊlt/",
"weatherholtz":"/ˈwɛðɝˌhoʊlts/",
"weathering":"/ˈwɛðɝɪŋ/",
"weatherington":"/ˈwɛðɝɪŋtən/",
"weatherly":"/ˈwɛðɝli/",
"weatherman":"/ˈwɛðɝˌmæn/",
"weathermen":"/ˈwɛðɝˌmɛn/",
"weatherperson":"/ˈwɛθɝˌpɝsən/",
"weatherproof":"/ˈwɛðɝˌpɹuf/",
"weathers":"/ˈwɛðɝz/",
"weathersbee":"/ˈwɛðɝzˌbi/",
"weathersby":"/ˈwɛðɝsbi/",
"weatherspoon":"/ˈwɛðɝˌspun/",
"weatherstone":"/ˈwɛðɝˌstoʊn/",
"weatherwax":"/ˈwɛðɝˌwæks/",
"weathington":"/ˈwɛθɪŋtən/",
"weave":"/ˈwiv/",
"weaved":"/ˈwivd/",
"weaver":"/ˈwivɝ/",
"weaver's":"/ˈwivɝz/",
"weaverling":"/ˈwivɝlɪŋ/",
"weavers":"/ˈwivɝz/",
"weaves":"/ˈwivz/",
"weavil":"/ˈwivəl/",
"weaving":"/ˈwivɪŋ/",
"weavings":"/ˈwivɪŋz/",
"web":"/ˈwɛb/",
"webb":"/ˈwɛb/",
"webb's":"/ˈwɛbz/",
"webbed":"/ˈwɛbd/",
"webber":"/ˈwɛbɝ/",
"webber's":"/ˈwɛbɝz/",
"webbing":"/ˈwɛbɪŋ/",
"webbs":"/ˈwɛbz/",
"weber":"/ˈwɛbɝ/",
"weber's":"/ˈveɪbɝz/, /ˈwɛbɝz/",
"weberg":"/ˈwɛbɝɡ/",
"webers":"/ˈwɛbɝz/",
"webinar":"/ˈwɛbɪnɝ/",
"webley":"/ˈwɛbli/",
"webmaster":"/ˈwɛbˌmæstɝ/",
"webmasters":"/ˈwɛbˌmæstɝz/",
"webpage":"/ˈwɛbpɪdʒ/",
"webre":"/ˈwɛbɝ/",
"webs":"/ˈwɛbz/",
"website":"/ˈwɛbˌsaɪt/",
"website's":"/ˈwɛbˌsaɪts/",
"websites":"/ˈwɛbˌsaɪts/",
"webster":"/ˈwɛbstɝ/",
"webster's":"/ˈwɛbstɝz/",
"websters":"/ˈwɛbstɝz/",
"wechsel":"/ˈwɛksəl/",
"wechsler":"/ˈwɛkslɝ/, /ˈwɛʃlɝ/",
"wecht":"/ˈwɛkt/",
"wecht's":"/ˈwɛkts/",
"wechter":"/ˈwɛktɝ/",
"weck":"/ˈwɛk/",
"wecker":"/ˈwɛkɝ/",
"weckerly":"/ˈwɛkɝli/",
"weckesser":"/ˈwɛkɪsɝ/",
"weckwerth":"/ˈwɛkwɝθ/",
"wed":"/ˈwɛd/",
"wedbush":"/ˈwɛdˌbʊʃ/",
"wedd":"/ˈwɛd/",
"wedded":"/ˈwɛdɪd/",
"weddell":"/ˈwɛdəl/",
"wedding":"/ˈwɛdɪŋ/",
"wedding's":"/ˈwɛdɪŋz/",
"weddings":"/ˈwɛdɪŋz/",
"weddington":"/ˈwɛdɪŋtən/",
"weddle":"/ˈwɛdəl/",
"wedekind":"/ˈwɛdɪkɪnd/",
"wedeking":"/ˈwɛdɪkɪŋ/",
"wedel":"/ˈwɛdəl/",
"wedell":"/ˈwɛdəl/",
"wedemeyer":"/ˈwɛdɪˌmaɪɝ/",
"wedge":"/ˈwɛdʒ/",
"wedged":"/ˈwɛdʒd/",
"wedges":"/ˈwɛdʒəz/, /ˈwɛdʒɪz/",
"wedgestone":"/ˈwɛdʒˌstoʊn/",
"wedgewood":"/ˈwɛdʒˌwʊd/",
"wedgewood's":"/ˈwɛdʒˌwʊdz/",
"wedgeworth":"/ˈwɛdʒˌwɝθ/",
"wedgwood":"/ˈwɛdʒˌwʊd/",
"wedig":"/ˈwɛdɪɡ/",
"wedin":"/ˈwɛdɪn/",
"wedlock":"/ˈwɛdˌlɑk/",
"wednesday":"/ˈwɛnzˌdeɪ/, /ˈwɛnzdi/",
"wednesday's":"/ˈwɛnzˌdeɪz/, /ˈwɛnzdiz/",
"wednesdays":"/ˈwɛnzˌdeɪz/, /ˈwɛnzdiz/",
"wedowee":"/wɛˈdaʊˌwi/",
"wedowee's":"/wɛˈdaʊˌwiz/",
"wedtech":"/ˈwɛdˌtɛk/",
"wedtech's":"/ˈwɛdˌtɛks/",
"wee":"/ˈwi/",
"weeber":"/ˈwibɝ/",
"weech":"/ˈwitʃ/",
"weed":"/ˈwid/",
"weeded":"/ˈwidɪd/",
"weeden":"/ˈwidən/",
"weeding":"/ˈwidɪŋ/",
"weedman":"/ˈwidmən/",
"weedon":"/ˈwidən/",
"weeds":"/ˈwidz/",
"weedy":"/ˈwidi/",
"weehawken":"/ˌwiˈhɔkən/",
"week":"/ˈwik/",
"week's":"/ˈwiks/",
"weekday":"/ˈwikˌdeɪ/",
"weekdays":"/ˈwikˌdeɪz/",
"weekend":"/ˈwiˌkɛnd/, /ˈwiˌkɪnd/",
"weekend's":"/ˈwiˌkɛndz/",
"weekender":"/ˈwiˌkɛndɝ/",
"weekends":"/ˈwiˌkɛndz/",
"weekes":"/ˈwiks/",
"weekley":"/ˈwikli/",
"weeklies":"/ˈwikliz/",
"weeklong":"/ˈwiˌklɔŋ/",
"weekly":"/ˈwikli/",
"weekly's":"/ˈwikliz/",
"weeks":"/ˈwiks/",
"weeks'":"/ˈwiks/",
"weems":"/ˈwimz/",
"weeny":"/ˈwini/",
"weep":"/ˈwip/",
"weeping":"/ˈwipɪŋ/",
"weeps":"/ˈwips/",
"weepy":"/ˈwipi/",
"weers":"/ˈwiɝz/",
"weerts":"/ˈwɪɹts/",
"weese":"/ˈwiz/",
"weesner":"/ˈwiznɝ/",
"weevil":"/ˈwivəl/",
"weevils":"/ˈwivəlz/",
"wegbreit":"/ˈwɛɡˌbɹaɪt/",
"wege":"/ˈwidʒ/",
"wegener":"/ˈwɛɡinɝ/",
"weger":"/ˈwiɡɝ/",
"weglarz":"/ˈwɛɡlɑɹz/",
"wegman":"/ˈwɛɡmən/",
"wegmann":"/ˈwɛɡmən/",
"wegner":"/ˈwɛɡnɝ/",
"wegrzyn":"/ˈwɛɡɝzɪn/",
"wehde":"/ˈwɛd/",
"wehe":"/ˈwih/",
"wehlan":"/ˈwɛlən/",
"wehle":"/ˈwɛli/",
"wehler":"/ˈwɛlɝ/",
"wehling":"/ˈwɛlɪŋ/",
"wehman":"/ˈwɛmən/",
"wehmeier":"/ˈwɛmaɪɝ/",
"wehmeyer":"/ˈwɛmaɪɝ/",
"wehner":"/ˈwɛnɝ/",
"wehr":"/ˈwɛɹ/",
"wehrenberg":"/ˈwɛɹənbɝɡ/",
"wehrheim":"/ˈwɛɹhaɪm/",
"wehrle":"/ˈwɛɹəl/",
"wehrli":"/ˈwɛɹli/",
"wehrly":"/ˈwɛɹli/",
"wehrman":"/ˈwɛɹmən/",
"wehrmann":"/ˈwɛɹmən/",
"wehunt":"/ˈwɛhənt/",
"wei":"/ˈweɪ/",
"weiand":"/ˈwaɪənd/",
"weibel":"/ˈwaɪbəl/",
"weible":"/ˈwibəl/",
"weich":"/ˈwaɪk/",
"weichel":"/ˈwaɪkəl/",
"weichert":"/ˈwaɪkɝt/",
"weichman":"/ˈwaɪkmən/",
"weicht":"/ˈwaɪkt/",
"weick":"/ˈwik/",
"weicker":"/ˈwaɪkɝ/",
"weicker's":"/ˈwaɪkɝz/",
"weida":"/ˈvaɪdə/",
"weide":"/ˈwaɪdi/",
"weidel":"/ˈwaɪdəl/",
"weideman":"/ˈwaɪdmən/",
"weidemann":"/ˈwaɪdmən/",
"weidenbach":"/ˈwaɪdɪnbɑk/",
"weidenbaum":"/ˈwaɪdənˌbaʊm/",
"weidenfeld":"/ˈwaɪdənˌfɛld/",
"weider":"/ˈwaɪdɝ/",
"weiderman":"/ˈwaɪdɝmən/",
"weidig":"/ˈwaɪdɪɡ/",
"weidinger":"/ˈwaɪdɪŋɝ/",
"weidler":"/ˈwaɪdəlɝ/, /ˈwaɪdlɝ/",
"weidlich":"/ˈwaɪdlɪk/",
"weidman":"/ˈwaɪdmən/",
"weidmann":"/ˈwaɪdmən/",
"weidner":"/ˈwaɪdnɝ/",
"weier":"/ˈweɪɝ/",
"weigand":"/ˈwaɪɡənd/",
"weigandt":"/ˈwaɪɡənt/",
"weigel":"/ˈwaɪɡəl/",
"weigelt":"/ˈwaɪɡɪlt/",
"weigert":"/ˈwaɪɡɝt/",
"weigh":"/ˈweɪ/",
"weighed":"/ˈweɪd/",
"weighing":"/ˈweɪɪŋ/",
"weighs":"/ˈweɪz/",
"weight":"/ˈweɪt/",
"weighted":"/ˈweɪtɪd/",
"weighting":"/ˈweɪtɪŋ/",
"weightings":"/ˈweɪtɪŋz/",
"weightless":"/ˈweɪtləs/",
"weightlessness":"/ˈweɪtləsnəs/",
"weightlifter":"/ˈweɪtˌlɪftɝ/",
"weightlifters":"/ˈweɪtˌlɪftɝz/",
"weightlifting":"/ˈweɪtˌlɪftɪŋ/",
"weightman":"/ˈwaɪtmən/",
"weights":"/ˈweɪts/",
"weighty":"/ˈweɪˌti/, /ˈweɪti/",
"weigl":"/ˈwiɡəl/",
"weigle":"/ˈwiɡəl/",
"weigold":"/ˈwaɪˌɡoʊld/",
"weihe":"/ˈwih/",
"weiher":"/ˈwaɪhɝ/",
"weik":"/ˈwik/",
"weikel":"/ˈwaɪkəl/",
"weiker":"/ˈwaɪkɝ/",
"weikert":"/ˈwaɪkɝt/",
"weikle":"/ˈwikəl/",
"weil":"/ˈwaɪl/, /ˈwil/",
"weil's":"/ˈwaɪlz/",
"weiland":"/ˈwaɪlənd/",
"weilbacher":"/ˈwaɪlˌbɑkɝ/",
"weild":"/ˈwaɪld/, /ˈwild/",
"weiler":"/ˈwaɪlɝ/",
"weill":"/ˈwaɪl/",
"weill's":"/ˈwaɪlz/",
"weiman":"/ˈwaɪmən/",
"weimann":"/ˈwaɪmən/",
"weimar":"/ˈvaɪmɑɹ/",
"weimer":"/ˈwaɪmɝ/",
"weimeyer":"/ˈwaɪmaɪɝ/",
"wein":"/ˈwin/",
"weinand":"/ˈwaɪnənd/",
"weinbach":"/ˈwaɪnˌbɑk/",
"weinbaum":"/ˈwaɪnˌbaʊm/",
"weinberg":"/ˈwaɪnbɝɡ/",
"weinberger":"/ˈwaɪnbɝɡɝ/",
"weinberger's":"/ˈwaɪnbɝɡɝz/",
"weindel":"/ˈwaɪndəl/",
"weinel":"/ˈwaɪnəl/",
"weiner":"/ˈwaɪnɝ/",
"weinert":"/ˈwaɪnɝt/",
"weinfeld":"/ˈwaɪnˌfɛld/",
"weingart":"/ˈwaɪŋɡɑɹt/",
"weingarten":"/ˈwaɪnˌɡɑɹtən/",
"weingartner":"/ˈwaɪŋɡɑɹtnɝ/",
"weinger":"/ˈwaɪnɡɝ/",
"weinhardt":"/ˈwaɪnˌhɑɹt/",
"weinheimer":"/ˈwaɪnˌhaɪmɝ/",
"weinhold":"/ˈwaɪnˌhoʊld/",
"weininger":"/ˈwaɪnɪŋɝ/",
"weinkauf":"/ˈwaɪŋkaʊf/",
"weinman":"/ˈwaɪnmən/",
"weinmann":"/ˈwaɪnmən/",
"weinreb":"/ˈwaɪnɹɪb/",
"weinreich":"/ˈwaɪnˌɹaɪk/",
"weinrich":"/ˈwaɪnɹɪk/",
"weinroth":"/ˈwaɪnˌɹɔθ/",
"weins":"/ˈwinz/",
"weinstein":"/ˈwaɪnˌstaɪn/, /ˈwaɪnˌstin/",
"weinstein's":"/ˈwaɪnˌstaɪnz/, /ˈwaɪnˌstinz/",
"weinstock":"/ˈwaɪnˌstɑk/",
"weintraub":"/ˈwaɪnˌtɹaʊb/",
"weintz":"/ˈwaɪnts/",
"weintz'":"/ˈwaɪnts/",
"weintz's":"/ˈwaɪntsɪz/",
"weinzierl":"/ˈwaɪnzɪɹl/",
"weipert":"/ˈwaɪpɝt/",
"weir":"/ˈwiɹ/",
"weir's":"/ˈwiɹz/",
"weirauch":"/ˈwaɪɹaʊk/",
"weird":"/ˈwɪɹd/",
"weirder":"/ˈwɪɹdɝ/",
"weirdest":"/ˈwɪɹdəst/",
"weirdly":"/ˈwɪɹdli/",
"weirdness":"/ˈwɪɹdnəs/",
"weirdo":"/ˈwɪɹdoʊ/",
"weirdos":"/ˈwɪɹdoʊz/",
"weirich":"/ˈwaɪɹɪk/",
"weirick":"/ˈwaɪɹɪk/",
"weirton":"/ˈwɪɹtən/",
"weirton's":"/ˈwɪɹtənz/",
"weis":"/ˈwaɪs/",
"weisbach":"/ˈwaɪsˌbɑk/",
"weisbecker":"/ˈwaɪsˌbɛkɝ/",
"weisberg":"/ˈwaɪsbɝɡ/",
"weisberger":"/ˈwaɪsbɝɡɝ/",
"weisbrod":"/ˈwaɪsˌbɹɑd/",
"weisbrot":"/ˈwaɪsbɹət/",
"weischedel":"/ˈwaɪʃədəl/",
"weise":"/ˈwis/",
"weisel":"/ˈwaɪsəl/, /ˈwaɪzəl/, /ˌwiˈzɛl/",
"weiseman":"/ˈwaɪsəmən/",
"weisenbach":"/ˈwaɪsɪnbɑk/, /ˈwaɪzɪnbɑk/",
"weisenberg":"/ˈwaɪsənbɝɡ/, /ˈwaɪzənbɝɡ/",
"weisenberger":"/ˈwaɪsənbɝɡɝ/, /ˈwaɪzənbɝɡɝ/",
"weisenborn":"/ˈwaɪsɪnbɝn/, /ˈwaɪzɪnbɝn/",
"weisenburger":"/ˈwaɪsənbɝɡɝ/, /ˈwaɪsɪnbɝɡɝ/",
"weisensel":"/ˈwaɪsɪnsəl/, /ˈwaɪzɪnsəl/",
"weisenthal":"/ˈwaɪsɪnˌθɑl/, /ˈwaɪzɪnˌθɑl/",
"weiser":"/ˈwaɪsɝ/",
"weisfeld":"/ˈwaɪsˌfɛld/",
"weisfield's":"/ˈwaɪsfildz/",
"weisgerber":"/ˈwaɪsɡɝbɝ/",
"weishaar":"/ˈwaɪʃɑɹ/",
"weishaupt":"/ˈwaɪʃaʊpt/",
"weisheit":"/ˈwaɪʃaɪt/",
"weisinger":"/ˈwaɪsɪndʒɝ/",
"weiskopf":"/ˈwaɪskɔf/",
"weisman":"/ˈwaɪsmən/",
"weismann":"/ˈwaɪsmən/",
"weisner":"/ˈwaɪsnɝ/",
"weiss":"/ˈwaɪs/",
"weiss's":"/ˈwaɪsɪz/",
"weissberg":"/ˈwaɪsbɝɡ/",
"weisse":"/ˈwaɪs/",
"weissenborn":"/ˈwaɪsɪnbɝn/",
"weisser":"/ˈwaɪsɝ/",
"weissert":"/ˈwaɪsɝt/",
"weissinger":"/ˈwaɪsɪndʒɝ/",
"weissman":"/ˈwaɪsmən/",
"weissmann":"/ˈwaɪsmən/",
"weist":"/ˈwaɪst/, /ˈwiɪst/",
"weisz":"/ˈvaɪʃ/",
"weitek":"/ˈweɪˌtɛk/",
"weith":"/ˈwiθ/",
"weitkamp":"/ˈwaɪtˌkæmp/",
"weitler":"/ˈwaɪtlɝ/",
"weitman":"/ˈwaɪtmən/",
"weitz":"/ˈwits/",
"weitzel":"/ˈwaɪtzəl/",
"weitzen":"/ˈwaɪtsən/",
"weitzman":"/ˈwaɪtsmən/",
"weitzman's":"/ˈwaɪtsmənz/",
"weitzner":"/ˈwaɪtsnɝ/",
"weizman":"/ˈwaɪzmən/",
"weizsaecker":"/ˈwaɪˌsækɝ/",
"weksel":"/ˈwɛksəl/",
"welbilt":"/ˈwɛlˈbɪlt/",
"welbilt's":"/ˈwɛlˈbɪlts/",
"welborn":"/ˈwɛlbɝn/",
"welborne":"/ˈwɛlbɝn/",
"welby":"/ˈwɛlbi/",
"welch":"/ˈwɛltʃ/",
"welch's":"/ˈwɛltʃɪz/",
"welchel":"/ˈwɛltʃəl/",
"welcher":"/ˈwɛltʃɝ/",
"welcome":"/ˈwɛlkəm/",
"welcomed":"/ˈwɛlkəmd/",
"welcomes":"/ˈwɛlkəmz/",
"welcoming":"/ˈwɛlkəmɪŋ/",
"weld":"/ˈwɛld/",
"weld's":"/ˈwɛldz/",
"welded":"/ˈwɛldɪd/",
"welden":"/ˈwɛldən/",
"welder":"/ˈwɛldɝ/",
"welders":"/ˈwɛldɝz/",
"weldin":"/ˈwɛldɪn/",
"welding":"/ˈwɛldɪŋ/",
"weldon":"/ˈwɛldən/",
"weldon's":"/ˈwɛldənz/",
"welds":"/ˈwɛldz/",
"weldwood":"/ˈwɛldˌwʊd/",
"weldy":"/ˈwɛldi/",
"welfare":"/ˈwɛlˌfɛɹ/",
"welford":"/ˈwɛlfɝd/",
"welge":"/ˈwɛldʒ/",
"welinder":"/ˈwɛˌlɪndɝ/",
"welinsk":"/wɛˈlɪnsk/",
"welk":"/ˈwɛlk/",
"welke":"/ˈwɛlk/",
"welker":"/ˈwɛlkɝ/",
"well":"/ˈwɛl/",
"well-being":"/ˌwɛlˈbiɪŋ/",
"well-doer":"/ˈwɛlˈduɹ/",
"well-educated":"/ˈwɛˈlɛdʒəˌkeɪtɪd/",
"well-known":"/ˈwɛlˈnoʊn/",
"welland":"/ˈwɛlənd/",
"wellbeing":"/ˌwɛlˈbiɪŋ/",
"wellborn":"/ˈwɛlˈbɔɹn/",
"wellbrock":"/ˈwɛlbɹək/",
"wellco":"/ˈwɛlkoʊ/",
"wellcome":"/ˈwɛlˌkəm/",
"wellcome's":"/ˈwɛlˌkəmz/",
"welle":"/ˈwɛl/",
"wellek":"/ˈwɛlɛk/",
"wellen":"/ˈwɛlən/",
"wellendorf":"/ˈwɛlɪndɔɹf/",
"wellens":"/ˈwɛlənz/",
"weller":"/ˈwɛlɝ/",
"welles":"/ˈwɛlz/",
"welles'":"/ˈwɛlz/",
"wellesley":"/ˈwɛlzli/",
"wellfleet":"/ˈwɛlˌflit/",
"wellhead":"/ˈwɛlˌhɛd/",
"wellies":"/ˈwɛliz/",
"welling":"/ˈwɛlɪŋ/",
"wellington":"/ˈwɛlɪŋtən/",
"wellington's":"/ˈwɛlɪŋtənz/",
"welliver":"/ˈwɛlɪvɝ/",
"wellman":"/ˈwɛlmən/",
"wellner":"/ˈwɛlnɝ/",
"wellness":"/ˈwɛlnəs/",
"wellnitz":"/ˈwɛlnɪts/",
"wellons":"/ˈwɛlənz/",
"wellpoint":"/ˈwɛlˌpɔɪnt/",
"wells":"/ˈwɛlz/",
"wells's":"/ˈwɛlzɪz/",
"wellspring":"/ˈwɛlsˌpɹɪŋ/",
"wellstone":"/ˈwɛlˌsoʊn/",
"wellstone's":"/ˈwɛlˌsoʊnz/",
"welltech":"/ˈwɛlˌtɛk/",
"welna":"/ˈwɛlnə/",
"welp":"/ˈwɛlp/",
"welsch":"/ˈwɛlʃ/",
"welser":"/ˈwɛlsɝ/",
"welsh":"/ˈwɛlʃ/, /ˈwɛltʃ/",
"welshans":"/ˈwɛlʃənz/",
"welt":"/ˈwɛlt/",
"welte":"/ˈwɛlt/",
"welter":"/ˈwɛltɝ/",
"welterweight":"/ˈwɛltɝˌweɪt/",
"weltman":"/ˈwɛltmən/",
"welton":"/ˈwɛltən/",
"welty":"/ˈwɛlti/",
"weltz":"/ˈwɛlts/",
"welz":"/ˈwɛlz/",
"wembley":"/ˈwɛmbli/",
"wemhoff":"/ˈwɛmˌhɔf/",
"wemmer":"/ˈwɛmɝ/",
"wempe":"/ˈwɛmp/",
"wemple":"/ˈwɛmpəl/",
"wen":"/ˈwɛn/",
"wenatchee":"/wəˈnætʃi/",
"wenberg":"/ˈwɛnbɝɡ/",
"wenceslaus":"/ˈwɛnsəˌslɔs/",
"wench":"/ˈwɛntʃ/",
"wenches":"/ˈwɛntʃɪz/",
"wenchester":"/ˈwɛnˌtʃɛstɝ/",
"wenchester's":"/ˈwɛnˌtʃɛstɝz/",
"wenck":"/ˈwɛŋk/",
"wend":"/ˈwɛnd/",
"wenda":"/ˈwɛndə/",
"wende":"/ˈwɛnd/",
"wendel":"/ˈwɛndəl/",
"wendeline":"/ˈwɛndɪˌlaɪn/",
"wendelken":"/ˈwɛndɪlkən/",
"wendell":"/ˈwɛndəl/",
"wender":"/ˈwɛndɝ/",
"wenders":"/ˈwɛndɝz/",
"wending":"/ˈwɛndɪŋ/",
"wendland":"/ˈwɛndlənd/",
"wendlandt":"/ˈwɛndlənt/",
"wendler":"/ˈwɛndlɝ/",
"wendling":"/ˈwɛndlɪŋ/",
"wendorf":"/ˈwɛndɔɹf/",
"wendorff":"/ˈwɛndɔɹf/",
"wends":"/ˈwɛndz/",
"wendt":"/ˈwɛnt/",
"wendy":"/ˈwɛndi/",
"wendy's":"/ˈwɛndiz/",
"wenfan":"/ˈwɛnˈfæn/",
"weng":"/ˈwɛŋ/",
"wenge":"/ˈwɛndʒ/, /ˈwɛŋ/",
"wenger":"/ˈwɛŋɝ/",
"wengerd":"/ˈwɛŋɡɝd/",
"wengert":"/ˈwɛŋɡɝt/",
"wengler":"/ˈwɪŋəlɝ/, /ˈwɪŋɡlɝ/",
"wenig":"/ˈwɛnɪɡ/",
"weniger":"/ˈwɛnɪɡɝ/",
"weninger":"/ˈwɛnɪŋɝ/",
"wenk":"/ˈwɛŋk/",
"wenke":"/ˈwɛŋk/",
"wenker":"/ˈwɛŋkɝ/",
"wennberg":"/ˈwɛnbɝɡ/",
"wenner":"/ˈwɛnɝ/",
"wennerstrom":"/ˈwɛnɝstɹəm/",
"wenning":"/ˈwɛnɪŋ/",
"wenninger":"/ˈwɛnɪŋɝ/",
"wenona":"/ˈwɛnənə/",
"wenrich":"/ˈwɛnɹɪk/",
"wenrick":"/ˈwɛnɹɪk/",
"wensberg":"/ˈwɛnzbɝɡ/",
"wensel":"/ˈwɛnsəl/",
"wenstrom":"/ˈwɛnstɹəm/",
"went":"/ˈwɛnt/",
"wente":"/ˈwɛnt/",
"wentland":"/ˈwɛntlənd/",
"wentling":"/ˈwɛntlɪŋ/",
"wentworth":"/ˈwɛntˈwɝθ/",
"wentz":"/ˈwɛnts/",
"wentzel":"/ˈwɛntzəl/",
"wentzell":"/ˈwɛntzəl/",
"wentzville":"/ˈwɛntsˌvɪl/",
"wenz":"/ˈwɛnz/",
"wenzel":"/ˈwɛnzəl/",
"wenzhou":"/wɛnˈzu/",
"wenzl":"/ˈwɛnzəl/",
"wenzler":"/ˈwɛnzlɝ/",
"wenzlick":"/ˈwɛnzlɪk/",
"weppler":"/ˈwɛplɝ/",
"wept":"/ˈwɛpt/",
"werber":"/ˈwɝbɝ/",
"werden":"/ˈwɝdən/",
"werder":"/ˈwɝdɝ/",
"werdesheim":"/ˈwɝdzˌhaɪm/",
"were":"/ˈwɝ/",
"wereldhave":"/ˈwɛɹəldˌhɑveɪ/",
"weren't":"/ˈwɝənt/, /ˈwɝnt/",
"werewolf":"/ˈwɛɹˌwʊlf/",
"werewolves":"/ˈwɛɹˌwʊlvz/",
"wergin":"/ˈwɝɡɪn/",
"werk":"/ˈwɝk/",
"werke":"/ˈwɝk/",
"werkheiser":"/ˈwɝkhaɪsɝ/",
"werking":"/ˈwɝkɪŋ/",
"werkmeister":"/ˈwɝkmaɪstɝ/",
"werle":"/ˈwɝl/",
"werley":"/ˈwɝli/",
"werling":"/ˈwɝlɪŋ/",
"werman":"/ˈwɝmən/",
"wermer":"/ˈwɝmɝ/",
"wermiel":"/ˈwɝmiəl/",
"wermuth":"/wɝˈmuθ/",
"werne":"/ˈwɝnə/",
"wernecke":"/ˈwɝnɪk/",
"werner":"/ˈwɝnɝ/",
"werner's":"/ˈwɝnɝz/",
"wernert":"/ˈwɝnɝt/",
"wernet":"/ˈwɝnɪt/",
"wernette":"/wɝˈnɛt/",
"wernick":"/ˈwɝnɪk/",
"wernicke":"/ˈwɝnɪk/",
"wernimont":"/ˈwɝnɪmənt/",
"werning":"/ˈwɝnɪŋ/",
"wernli":"/ˈwɝnli/",
"werntz":"/ˈwɝnts/",
"werre":"/ˈwɛɹ/",
"werry":"/ˈwɛɹi/",
"werst":"/ˈwɝst/",
"wert":"/ˈwɝt/",
"wertenberger":"/ˈwɝtənbɝɡɝ/",
"werth":"/ˈwɝθ/",
"wertheim":"/ˈwɝthaɪm/",
"wertheimer":"/ˈwɝthaɪmɝ/",
"werther":"/ˈwɝðɝ/",
"wertman":"/ˈwɝtmən/",
"werts":"/ˈwɝts/",
"wertz":"/ˈwɝts/",
"wery":"/ˈwɛɹi/",
"wes":"/ˈwɛs/",
"wesat":"/ˈwɛˌsæt/, /ˈwiˌsæt/",
"wesch":"/ˈwɛʃ/",
"wesche":"/ˈwɛʃ/",
"wesco":"/ˈwɛskoʊ/",
"wescoat":"/ˈwɛsˌkoʊt/",
"wescott":"/ˈwɛskɑt/",
"weseloh":"/weɪˈseɪloʊ/",
"wesely":"/ˈwizli/",
"weseman":"/ˈwizmən/",
"wesemann":"/ˈwizmən/",
"wesenberg":"/ˈwizənbɝɡ/",
"wesker":"/ˈwɛskɝ/",
"wesker's":"/ˈwɛskɝz/",
"wesler":"/ˈwɛsəlɝ/, /ˈwɛslɝ/",
"wesley":"/ˈwɛsli/",
"wesleyan":"/ˈwɛzliən/",
"weslia":"/ˈhwɛsliə/, /ˈwɛsliə/",
"wesner":"/ˈwɛsnɝ/",
"wesolek":"/ˈwɛsəlɪk/",
"wesolowski":"/vɪsəˈlɔfski/",
"wesp":"/ˈwɛsp/",
"wespac":"/ˈwɛsˌpæk/",
"wespercorp":"/ˈwɛspɝˌkɔɹp/",
"wesray":"/ˈwɛsɹeɪ/",
"wess":"/ˈwɛs/",
"wessel":"/ˈwɛsəl/",
"wessell":"/ˈwɛsəl/",
"wessells":"/ˈwɛsəlz/",
"wesselman":"/ˈwɛsəlmən/",
"wessels":"/ˈwɛsəlz/",
"wessex":"/ˈwɛsəks/",
"wessinger":"/ˈwɛsɪndʒɝ/",
"wessler":"/ˈwɛslɝ/",
"wessling":"/ˈwɛsəlɪŋ/, /ˈwɛslɪŋ/",
"wessman":"/ˈwɛsmən/",
"wessner":"/ˈwɛsnɝ/",
"wesson":"/ˈwɛsən/",
"west":"/ˈwɛst/",
"west's":"/ˈwɛsts/",
"westair":"/ˈwɛsˈtɛɹ/",
"westall":"/ˈwɛstəl/",
"westall's":"/ˈwɛstəlz/",
"westamerica":"/ˌwɛstəˈmɛɹɪkə/",
"westamerica's":"/ˌwɛstəˈmɛɹɪkəz/",
"westar":"/ˈwɛstɝ/",
"westbay":"/ˈwɛstˌbeɪ/",
"westberg":"/ˈwɛstbɝɡ/",
"westberry":"/ˈwɛstˌbɛɹi/",
"westboro":"/ˈwɛstbɝoʊ/",
"westborough":"/ˈwɛstbɝoʊ/",
"westbound":"/ˈwɛstˌbaʊnd/",
"westbridge":"/ˈwɛstˌbɹɪdʒ/",
"westbrook":"/ˈwɛstˌbɹʊk/",
"westbrooks":"/ˈwɛstˌbɹʊks/",
"westburne":"/ˈwɛstbɝn/",
"westbury":"/ˈwɛstˌbɛɹi/",
"westby":"/ˈwɛstbi/",
"westcap":"/ˈwɛstˌkæp/",
"westchester":"/ˈwɛstˌtʃɛstɝ/",
"westchester's":"/ˈwɛstˌtʃɛstɝz/",
"westcoast":"/ˈwɛstˌkoʊst/",
"westcoast's":"/ˈwɛstˌkoʊsts/",
"westcorp":"/ˈwɛstˌkɔɹp/",
"westcott":"/ˈwɛstˌkɑt/",
"westdeutsche":"/ˈwɛstˈdɔɪtʃ/",
"westech":"/ˈwɛstɛk/",
"westen":"/ˈwɛstən/",
"westenberger":"/ˈwɛstənbɝɡɝ/",
"westendorf":"/ˈwɛstɪndɔɹf/",
"wester":"/ˈwɛstɝ/",
"westerbeck":"/ˈwɛstɝˌbɛk/",
"westerberg":"/ˈwɛstɝbɝɡ/",
"westerdam":"/ˈwɛstɝˌdæm/",
"westerdam's":"/ˈwɛstɝˌdæmz/",
"westerfeld":"/ˈwɛstɝˌfɛld/",
"westerfield":"/ˈwɛstɝˌfild/",
"westergaard":"/ˈwɛstɝˌɡɑɹd/",
"westergard":"/ˈwɛstɝɡɝd/",
"westergren":"/ˈwɛstɝɡɹɛn/",
"westerhoff":"/ˈwɛstɝˌhɔf/",
"westerhold":"/ˈwɛstɝˌhoʊld/",
"westerlies":"/ˈwɛstɝliz/",
"westerlund":"/ˈwɛstɝlənd/",
"westerly":"/ˈwɛstɝli/",
"westerman":"/ˈwɛstɝmən/",
"westermann":"/ˈwɛstɝmən/",
"westermeyer":"/ˈwɛstɝmaɪɝ/",
"western":"/ˈhwɛstɝn/, /ˈwɛstɝn/",
"western's":"/ˈwɛstɝnz/",
"westerner":"/ˈwɛstɝnɝ/",
"westerners":"/ˈwɛstɝnɝz/",
"westernization":"/ˌwɛstɝnɪˈzeɪʃən/",
"westernize":"/ˈwɛstɝˌnaɪz/",
"westernized":"/ˈwɛstɝˌnaɪzd/",
"westernmost":"/ˈwɛstɝnˌmoʊst/",
"westerns":"/ˈwɛstɝnz/",
"westervelt":"/ˈwɛstɝvɪlt/",
"westfaelisches":"/ˈwɛstˌfeɪlɪʃɪz/",
"westfahl":"/ˈwɛstˌfɑl/",
"westfall":"/ˈwɛstˌfɔl/",
"westfed":"/ˈwɛstˌfɛd/",
"westfield":"/ˈwɛstfild/",
"westford":"/ˈwɛstfɝd/",
"westgate":"/ˈwɛstˌɡeɪt/",
"westhampton":"/ˌwɛstˈhæmptən/",
"westheimer":"/ˈwɛstˌhaɪmɝ/",
"westhoff":"/ˈwɛstˌhɔf/",
"westin":"/ˈwɛstɪn/",
"westinghouse":"/ˈwɛstɪŋˌhaʊs/",
"westinghouse's":"/ˈwɛstɪŋˌhaʊsɪz/",
"westlake":"/ˈwɛstˌleɪk/",
"westland":"/ˈwɛstlənd/",
"westleigh":"/ˈwɛstlaɪ/",
"westley":"/ˈwɛstli/",
"westling":"/ˈwɛstlɪŋ/",
"westlund":"/ˈwɛstlənd/",
"westman":"/ˈwɛstmən/",
"westmarc":"/ˈwɛstˌmɑɹk/",
"westmark":"/ˈwɛstˌmɑɹk/",
"westmark's":"/ˈwɛstˌmɑɹks/",
"westmin":"/ˈwɛstmɪn/",
"westminster":"/ˌwɛstˈmɪnstɝ/",
"westmoreland":"/wɛstˈmɔɹlənd/",
"weston":"/ˈwɛstən/",
"westover":"/ˈwɛsˌtoʊvɝ/",
"westpac":"/ˈwɛstˌpæk/",
"westpac's":"/ˈwɛstˌpæks/",
"westphal":"/ˈwɛstfəl/",
"westphalen":"/ˈwɛstfələn/",
"westphalia":"/ˈwɛstˌfeɪliə/, /ˈwɛstˌfeɪljə/",
"westport":"/ˈwɛstˌpɔɹt/",
"westpride":"/ˈwɛstˌpɹaɪd/",
"westra":"/ˈwɛstɹə/",
"westrich":"/ˈwɛstɹɪk/",
"westrick":"/ˈwɛstɹɪk/",
"westridge":"/ˈwɛsˌtɹɪdʒ/",
"westrom":"/ˈwɛstɹəm/",
"westrum":"/ˈwɛstɹəm/",
"westrup":"/ˈwɛstɹəp/",
"westside":"/ˈwɛstˈsaɪd/",
"westtech":"/ˈwɛsˌtɛk/",
"westtech's":"/ˈwɛsˌtɛks/",
"westvaco":"/ˌwɛstˈvækoʊ/",
"westward":"/ˈwɛstwɝd/",
"westward-faring":"/ˌwɛstwɝdˈfɛɹiŋ/",
"westwards":"/ˈwɛstwɝdz/",
"westwood":"/ˈwɛstˌwʊd/",
"westwood's":"/ˈwɛstˌwʊdz/",
"westworld":"/ˈwɛstˌwɝld/",
"wesun":"/ˈwiˌsən/",
"wet":"/ˈwɛt/",
"wetherbee":"/ˈwɛðɝˌbi/",
"wetherby":"/ˈwɛθɝbi/",
"wetherell":"/ˈwɛθɝəl/",
"wetherill":"/ˈwɛθɝəl/",
"wetherington":"/ˈwɛðɝɪŋtən/",
"wetherly":"/ˈwɛðɝli/",
"wethington":"/ˈwɛθɪŋtən/",
"wetland":"/ˈwɛtˌlænd/",
"wetlands":"/ˈwɛtˌlændz/",
"wetlands'":"/ˈwɛtˌlændz/",
"wetmore":"/ˈwɛtmɔɹ/",
"wetness":"/ˈwɛtnəs/",
"wetsel":"/ˈwɛtsəl/",
"wetstein":"/ˈwɛtˌstaɪn/, /ˈwɛtˌstin/",
"wetsuit":"/ˈwɛtˌsut/",
"wettengel":"/ˈwɛtɪŋɡəl/",
"wetter":"/ˈwɛtɝ/",
"wetterau":"/ˈwɛtɝaʊ/",
"wettergreen":"/ˈwɛtɝˌɡɹin/",
"wettest":"/ˈwɛtəst/",
"wetting":"/ˈhwɛtɪŋ/, /ˈwɛtɪŋ/",
"wettlaufer":"/ˈwɛtlaʊfɝ/",
"wettstein":"/ˈwɛtstaɪn/, /ˈwɛtstin/",
"wetz":"/ˈwɛts/",
"wetzel":"/ˈwɛtzəl/",
"wetzler":"/ˈwɛtslɝ/",
"wetzstein":"/ˈwɛtstaɪn/, /ˈwɛtstin/",
"wever":"/ˈwivɝ/",
"wexler":"/ˈwɛkslɝ/",
"wexner":"/ˈwɛksnɝ/",
"wey":"/ˈweɪ/",
"weyand":"/ˈweɪənd/",
"weyandt":"/ˈweɪənt/",
"weyant":"/ˈweɪənt/",
"weyenberg":"/ˈwaɪnbɝɡ/",
"weyer":"/ˈweɪɝ/",
"weyerhaeuser":"/ˈwɛɹˌhaʊzɝ/",
"weyerhaeuser's":"/ˌwɛɹˌhaʊzɝz/",
"weyers":"/ˈweɪɝz/",
"weyforth":"/ˈweɪˌfɔɹθ/",
"weygandt":"/ˈweɪɡənt/",
"weyhrauch":"/ˈweɪˌɹaʊk/",
"weyl":"/ˈweɪl/",
"weyland":"/ˈweɪlənd/",
"weylin":"/ˈweɪlɪn/",
"weyman":"/ˈweɪmən/",
"weymer":"/ˈweɪmɝ/",
"weymouth":"/ˈweɪməθ/",
"weyrauch":"/ˈwɛɹaʊk/",
"weyrich":"/ˈwɛɹɪk/",
"weyrick":"/ˈweɪɹɪk/",
"whack":"/ˈhwæk/, /ˈwæk/",
"whacked":"/ˈhwækt/, /ˈwækt/",
"whacker":"/ˈhwækɝ/, /ˈwækɝ/",
"whacking":"/ˈhwækɪŋ/, /ˈwækɪŋ/",
"whacko":"/ˈwækoʊ/",
"whackos":"/ˈwækoʊz/",
"whacks":"/ˈhwæks/, /ˈwæks/",
"whale":"/ˈhweɪl/, /ˈweɪl/",
"whale's":"/ˈhweɪlz/, /ˈweɪlz/",
"whalen":"/ˈhweɪlən/, /ˈweɪlən/",
"whaler":"/ˈhweɪlɝ/, /ˈweɪlɝ/",
"whalers":"/ˈhweɪlɝz/, /ˈweɪlɝz/",
"whales":"/ˈhweɪlz/, /ˈweɪlz/",
"whaley":"/ˈhweɪli/, /ˈweɪli/",
"whalin":"/ˈwælɪn/",
"whaling":"/ˈhweɪlɪŋ/, /ˈweɪlɪŋ/",
"whalley":"/ˈwæli/",
"wham":"/ˈhwæm/, /ˈwæm/",
"whammy":"/ˈhwæmi/, /ˈwæmi/",
"whampoa":"/wæmˈpoʊə/",
"whan":"/ˈhwæn/, /ˈwæn/",
"whang":"/ˈhwæŋ/, /ˈwæŋ/",
"wharf":"/ˈhwɔɹf/, /ˈwɔɹf/",
"wharf's":"/ˈhwɔɹfs/, /ˈwɔɹfs/",
"wharff":"/ˈhwɑɹf/, /ˈwɑɹf/",
"wharfs":"/ˈhwɔɹfs/, /ˈwɔɹfs/",
"wharry":"/ˈhwæɹi/, /ˈwæɹi/",
"wharton":"/ˈwɔɹtən/",
"wharton's":"/ˈwɔɹtənz/",
"what":"/ˈhwət/, /ˈwət/",
"what'd":"/ˈhwətɪd/, /ˈwətɪd/",
"what'll":"/ˈhwətəl/, /ˈwətəl/",
"what're":"/ˈhwətɝ/, /ˈwətɝ/",
"what's":"/ˈhwəts/, /ˈwəts/",
"what've":"/ˈwətəv/",
"what-what":"/ˈwətˈwət/",
"whate":"/ˈweɪt/",
"whatever":"/ˌhwəˈtɛvɝ/, /ˌwəˈtɛvɝ/",
"whatever's":"/ˌhwəˈtɛvɝz/, /ˌwəˈtɛvɝz/",
"whatley":"/ˈhwətli/, /ˈwətli/",
"whatnot":"/ˈhwətˌnɑt/, /ˈwətˌnɑt/",
"whats":"/hwəts/, /wəts/",
"whatsapp":"/ˌwətˈsɑp/",
"whatsoever":"/ˌhwətsoʊˈɛvɝ/, /ˌwətsoʊˈɛvɝ/",
"whay-yu":"/ˈhweɪˈju/, /ˈweɪˈju/",
"wheat":"/ˈhwit/, /ˈwit/",
"wheaten":"/ˈhwitən/, /ˈwitən/",
"wheatie":"/ˈhwiti/, /ˈwiti/",
"wheaties":"/ˈhwitiz/, /ˈwitiz/",
"wheatley":"/ˈhwitli/, /ˈwitli/",
"wheatly":"/ˈhwitli/, /ˈwitli/",
"wheaton":"/ˈhwitən/, /ˈwitən/",
"whedbee":"/ˈhwɛdˌbi/, /ˈwɛdˌbi/",
"whedon":"/ˈhwɛdən/, /ˈwɛdən/",
"wheel":"/ˈhwil/, /ˈwil/",
"wheelabrator":"/ˌhwiləˈbɹeɪtɝ/, /ˌwiləˈbɹeɪtɝ/",
"wheelan":"/ˈhwilən/, /ˈwilən/",
"wheeland":"/ˈhwilənd/, /ˈwilənd/",
"wheelbarrow":"/ˈhwilˌbɛɹoʊ/, /ˈwilˌbɛɹoʊ/",
"wheelbarrows":"/ˈhwilˌbɛɹoʊz/, /ˈwilˌbɛɹoʊz/",
"wheelbase":"/ˈhwilˌbeɪs/, /ˈwilˌbeɪs/",
"wheelchair":"/ˈhwilˌtʃɛɹ/, /ˈwilˌtʃɛɹ/",
"wheelchairs":"/ˈhwilˌtʃɛɹz/, /ˈwilˌtʃɛɹz/",
"wheeldon":"/ˈhwildən/, /ˈwildən/",
"wheeled":"/ˈhwild/, /ˈwild/",
"wheeler":"/ˈhwilɝ/, /ˈwilɝ/",
"wheeler's":"/ˈhwilɝz/, /ˈwilɝz/",
"wheelers":"/ˈhwilɝz/, /ˈwilɝz/",
"wheeless":"/ˈhwiləs/, /ˈwiləs/",
"wheeling":"/ˈhwilɪŋ/, /ˈwilɪŋ/",
"wheeling's":"/ˈhwilɪŋz/, /ˈwilɪŋz/",
"wheelis":"/ˈhwilɪs/, /ˈwilɪs/",
"wheelock":"/ˈhwiˌlɑk/, /ˈwiˌlɑk/",
"wheelon":"/ˈhwilən/, /ˈwilən/",
"wheels":"/ˈhwilz/, /ˈwilz/",
"wheelus":"/ˈhwiləs/, /ˈwiləs/",
"wheelwright":"/ˈhwilˌɹaɪt/, /ˈwilˌɹaɪt/",
"wheelwriter":"/ˈhwilˌɹaɪtɝ/, /ˈwilˌɹaɪtɝ/",
"wheeze":"/ˈhwiz/, /ˈwiz/",
"wheezes":"/ˈhwizəz/, /ˈwizəz/, /ˈwizɪz/",
"wheezing":"/ˈhwizɪŋ/, /ˈwizɪŋ/",
"whelan":"/ˈhwɛlən/, /ˈhwilən/, /ˈwɛlən/, /ˈwilən/",
"whelchel":"/ˈhwɛltʃəl/, /ˈwɛltʃəl/",
"wheless":"/ˈhwilɪs/, /ˈwilɪs/",
"whelpley":"/ˈhwɛlpli/, /ˈwɛlpli/",
"whelton":"/ˈhwɛltən/, /ˈwɛltən/",
"when":"/ˈhwɛn/, /ˈhwɪn/, /ˈwɛn/, /ˈwɪn/",
"when'll":"/ˈhwɛnəl/, /ˈwɛnəl/",
"when's":"/ˈhwɛnz/, /ˈwɛnz/",
"whence":"/ˈhwɛns/, /ˈwɛns/",
"whenever":"/hwɛˈnɛvɝ/, /wɛˈnɛvɝ/",
"where":"/ˈhwɛɹ/, /ˈwɛɹ/",
"where'd":"/ˈhwɛɹd/, /ˈwɛɹd/",
"where're":"/ˈwɛɹɝ/",
"where's":"/ˈhwɛɹz/, /ˈwɛɹz/",
"where've":"/ˈwɛɹəv/",
"whereabouts":"/ˈhwɛɹəˌbaʊts/, /ˈwɛɹəˌbaʊts/",
"whereas":"/werˈæz/",
"whereby":"/hwɛɹˈbaɪ/, /wɛɹˈbaɪ/",
"wherefore":"/wɛɹˈfɔɹ/",
"wherein":"/hwɛˈɹɪn/, /wɛˈɹɪn/",
"whereupon":"/ˈhwɛɹəˈpɑn/, /ˈwɛɹəˈpɑn/",
"wherever":"/werˈev.ɚ/",
"wherewithal":"/ˈhwɛɹwɪˌðɔl/, /ˈwɛɹwɪˌðɔl/",
"wherley":"/ˈhwɝli/, /ˈwɝli/",
"wherry":"/ˈhwɛɹi/, /ˈwɛɹi/",
"whet":"/ˈhwɛt/, /ˈwɛt/",
"whether":"/ˈhwɛðɝ/, /ˈwɛðɝ/",
"whetsel":"/ˈhwɛtsəl/, /ˈwɛtsəl/",
"whetsell":"/ˈhwɛtsəl/, /ˈwɛtsəl/",
"whetstine":"/ˈhwɛtstin/, /ˈwɛtstin/",
"whetstone":"/ˈhwɛtˌstoʊn/, /ˈwɛtˌstoʊn/",
"whetted":"/ˈhwɛtɪd/, /ˈwɛtɪd/",
"whetzel":"/ˈhwɛtzəl/, /ˈwɛtzəl/",
"whew":"/ˈhju/, /ˈhwu/, /ˈwu/",
"whey":"/ˈhweɪ/, /ˈweɪ/",
"which":"/ˈhwɪtʃ/, /ˈwɪtʃ/",
"which're":"/ˈhwɪtʃɝ/, /ˈwɪtʃɝ/",
"which's":"/ˈhwɪtʃɪz/, /ˈwɪtʃɪz/",
"whichard":"/ˈhwɪtʃɝd/, /ˈwɪtʃɝd/",
"whichever":"/hwɪˈtʃɛvɝ/, /wɪˈtʃɛvɝ/",
"whicker":"/ˈhwɪkɝ/, /ˈwɪkɝ/",
"whidby":"/ˈhwɪdbi/, /ˈwɪdbi/",
"whidden":"/ˈhwɪdən/, /ˈwɪdən/",
"whiddon":"/ˈhwɪdən/, /ˈwɪdən/",
"whiff":"/ˈhwɪf/, /ˈwɪf/",
"whig":"/ˈhwɪɡ/, /ˈwɪɡ/",
"whigham":"/ˈhwɪɡəm/, /ˈwɪɡəm/",
"whigs":"/ˈhwɪɡz/, /ˈwɪɡz/",
"whilden":"/ˈhwaɪldən/, /ˈwaɪldən/",
"while":"/ˈhwaɪl/, /ˈwaɪl/",
"whiles":"/ˈhwaɪlz/, /ˈwaɪlz/",
"whilst":"/ˈwaɪlst/",
"whim":"/ˈhwɪm/, /ˈwɪm/",
"whimper":"/ˈhwɪmpɝ/, /ˈwɪmpɝ/",
"whimpering":"/ˈhwɪmpɝɪŋ/, /ˈwɪmpɝɪŋ/",
"whims":"/ˈhwɪmz/, /ˈwɪmz/",
"whimsical":"/ˈhwɪmzɪkəl/, /ˈwɪmzɪkəl/",
"whimsically":"/ˈhwɪmzɪkli/, /ˈwɪmzɪkli/",
"whimsy":"/ˈhwɪmsi/, /ˈwɪmsi/",
"whine":"/ˈhwaɪn/, /ˈwaɪn/",
"whiner":"/ˈhwaɪnɝ/, /ˈwaɪnɝ/",
"whiners":"/ˈhwaɪnɝz/, /ˈwaɪnɝz/",
"whinery":"/ˈhwaɪnɝi/, /ˈwaɪnɝi/",
"whines":"/ˈhwaɪnz/, /ˈwaɪnz/",
"whining":"/ˈhwaɪnɪŋ/, /ˈwaɪnɪŋ/",
"whinnery":"/ˈhwɪnɝi/, /ˈwɪnɝi/",
"whinney":"/ˈhwɪni/, /ˈwɪni/",
"whiny":"/ˈhwaɪni/, /ˈwaɪni/",
"whip":"/ˈhwɪp/, /ˈwɪp/",
"whipkey":"/ˈhwɪpˌki/, /ˈwɪpˌki/",
"whiplash":"/ˈhwɪˌplæʃ/, /ˈwɪˌplæʃ/",
"whiplashes":"/ˈhwɪˌplæʃəz/, /ˈwɪˌplæʃəz/",
"whipp":"/ˈhwɪp/, /ˈwɪp/",
"whippany":"/ˈhwɪpəni/, /ˈwɪpəni/",
"whipped":"/ˈhwɪpt/, /ˈwɪpt/",
"whipping":"/ˈhwɪpɪŋ/, /ˈwɪpɪŋ/",
"whipple":"/ˈhwɪpəl/, /ˈwɪpəl/",
"whipple's":"/ˈhwɪpəlz/, /ˈwɪpəlz/",
"whippoorwills":"/ˈhwɪpɝˌwɪlz/, /ˈwɪpɝˌwɪlz/",
"whipps":"/ˈhwɪps/, /ˈwɪps/",
"whips":"/ˈhwɪps/, /ˈwɪps/",
"whipsaw":"/ˈhwɪpˌsɔ/, /ˈwɪpˌsɔ/",
"whipsawed":"/ˈhwɪpˌsɔd/, /ˈwɪpˌsɔd/",
"whipsawing":"/ˈhwɪpˌsɔɪŋ/, /ˈwɪpˌsɔɪŋ/",
"whirl":"/ˈhwɝl/, /ˈwɝl/",
"whirled":"/ˈhwɝld/, /ˈwɝld/",
"whirley":"/ˈhwɝli/, /ˈwɝli/",
"whirling":"/ˈhwɝlɪŋ/, /ˈwɝlɪŋ/",
"whirlpool":"/ˈhwɝlˌpul/, /ˈwɝlˌpul/",
"whirlpool's":"/ˈhwɝlˌpulz/, /ˈwɝlˌpulz/",
"whirlpools":"/ˈhwɝlˌpulz/, /ˈwɝlˌpulz/",
"whirlwind":"/ˈhwɝlˌwɪnd/, /ˈwɝlˌwɪnd/",
"whirring":"/ˈhwɝɪŋ/, /ˈwɝɪŋ/",
"whisenand":"/ˈhwɪsɪnænd/, /ˈwɪsɪnænd/",
"whisenant":"/ˈhwɪsɪnənt/, /ˈwɪsɪnənt/",
"whisenhunt":"/ˈhwaɪzənˌhənt/, /ˈwaɪzənˌhənt/",
"whisk":"/ˈhwɪsk/, /ˈwɪsk/",
"whisked":"/ˈhwɪskt/, /ˈwɪskt/",
"whisker":"/ˈhwɪskɝ/, /ˈwɪskɝ/",
"whiskered":"/ˈwɪskɝd/",
"whiskers":"/ˈhwɪskɝz/, /ˈwɪskɝz/",
"whiskey":"/ˈhwɪski/, /ˈwɪski/",
"whiskeys":"/ˈhwɪskiz/, /ˈwɪskiz/",
"whisks":"/ˈhwɪsks/, /ˈwɪsks/",
"whisky":"/ˈhwɪski/, /ˈwɪski/",
"whisler":"/ˈhwɪslɝ/, /ˈwɪslɝ/",
"whisman":"/ˈhwɪsmən/, /ˈwɪsmən/",
"whisnant":"/ˈhwɪsnənt/, /ˈwɪsnənt/",
"whisner":"/ˈhwɪsnɝ/, /ˈwɪsnɝ/",
"whisonant":"/ˈwɪsənənt/",
"whisper":"/ˈhwɪspɝ/, /ˈwɪspɝ/",
"whispered":"/ˈhwɪspɝd/, /ˈwɪspɝd/",
"whisperer":"/ˈwɪspəˌɹɝ/",
"whisperer's":"/ˈwɪspəˌɹɝz/",
"whisperers":"/ˈwɪspəˌɹɝz/",
"whispering":"/ˈhwɪspɝɪŋ/, /ˈwɪspɝɪŋ/",
"whispers":"/ˈhwɪspɝz/, /ˈwɪspɝz/",
"whistle":"/ˈhwɪsəl/, /ˈwɪsəl/",
"whistleblower":"/ˈhwɪsəlˌbloʊɝ/, /ˈwɪsəlˌbloʊɝ/",
"whistleblowers":"/ˈhwɪsəlˌbloʊɝz/, /ˈwɪsəlˌbloʊɝz/",
"whistled":"/ˈhwɪsəld/, /ˈwɪsəld/",
"whistler":"/ˈhwɪslɝ/, /ˈwɪslɝ/",
"whistlers":"/ˈhwɪslɝz/, /ˈwɪslɝz/",
"whistles":"/ˈhwɪsəlz/, /ˈwɪsəlz/",
"whistling":"/ˈhwɪslɪŋ/, /ˈwɪslɪŋ/",
"whiston":"/ˈhwɪstən/, /ˈwɪstən/",
"whit":"/ˈhwɪt/, /ˈwɪt/",
"whitacre":"/ˈhwɪtəkɝ/, /ˈwɪtəkɝ/",
"whitaker":"/ˈhwɪtəkɝ/, /ˈwɪtəkɝ/",
"whitbeck":"/ˈhwɪtˌbɛk/, /ˈwɪtˌbɛk/",
"whitbread":"/ˈhwɪtˌbɹɛd/, /ˈwɪtˌbɹɛd/",
"whitby":"/ˈhwɪtbi/, /ˈwɪtbi/",
"whitcher":"/ˈhwɪtʃɝ/, /ˈwɪtʃɝ/",
"whitchurch":"/ˈhwɪtˌtʃɝtʃ/, /ˈwɪtˌtʃɝtʃ/",
"whitcomb":"/ˈhwɪtkəm/, /ˈwɪtkəm/",
"whitcraft":"/ˈhwɪtˌkɹæft/, /ˈwɪtˌkɹæft/",
"white":"/ˈhwaɪt/, /ˈwaɪt/",
"white's":"/ˈhwaɪts/, /ˈwaɪts/",
"whiteaker":"/ˈhwɪtəkɝ/, /ˈwɪtəkɝ/",
"whitebread":"/ˈhwaɪtˌbɹɛd/, /ˈwaɪtˌbɹɛd/",
"whitecotton":"/ˈhwaɪtˌkɑtən/, /ˈwaɪtˌkɑtən/",
"whited":"/ˈhwaɪtɪd/, /ˈwaɪtɪd/",
"whitefield":"/ˈhwaɪtˌfild/, /ˈwaɪtˌfild/",
"whitefish":"/ˈhwaɪtˌfɪʃ/, /ˈwaɪtˌfɪʃ/",
"whiteford":"/ˈhwaɪtfɔɹd/, /ˈwaɪtfɔɹd/",
"whitehair":"/ˈhwaɪtˈhɛɹ/, /ˈwaɪtˈhɛɹ/",
"whitehall":"/ˈhwaɪtˌhɔl/, /ˈwaɪtˌhɔl/",
"whitehall's":"/ˈhwaɪtˌhɔlz/, /ˈwaɪtˌhɔlz/",
"whitehead":"/ˈhwaɪtˌhɛd/, /ˈwaɪtˌhɛd/",
"whitehead's":"/ˈhwaɪtˌhɛdz/, /ˈwaɪtˌhɛdz/",
"whitehill":"/ˈhwaɪtˌhɪl/, /ˈwaɪtˌhɪl/",
"whitehorn":"/ˈhwaɪtˌhɔɹn/, /ˈwaɪtˌhɔɹn/",
"whitehorse":"/ˈhwaɪtˌhɔɹs/, /ˈwaɪtˌhɔɹs/",
"whitehouse":"/ˈhwaɪtˌhaʊs/, /ˈwaɪtˌhaʊs/",
"whitehurst":"/ˈhwaɪtˌhɝst/, /ˈwaɪtˌhɝst/",
"whitehurst's":"/ˈwaɪtˌhɝsts/",
"whitelaw":"/ˈhwaɪtˌlɔ/, /ˈwaɪtˌlɔ/",
"whiteley":"/ˈhwaɪtli/, /ˈwaɪtli/",
"whitelock":"/ˈhwaɪtˌlɑk/, /ˈwaɪtˌlɑk/",
"whitely":"/ˈhwaɪtli/, /ˈwaɪtli/",
"whiteman":"/ˈhwaɪtmən/, /ˈwaɪtmən/",
"whitemont":"/ˈhwaɪtˌmɑnt/, /ˈwaɪtˌmɑnt/",
"whiten":"/ˈhwaɪtən/, /ˈwaɪtən/",
"whitenack":"/ˈhwaɪtˌnæk/, /ˈwaɪtˌnæk/",
"whiteneir":"/ˈhwaɪtˌnɪɹ/, /ˈwaɪtˌnɪɹ/",
"whitener":"/ˈhwaɪtnɝ/, /ˈwaɪtnɝ/",
"whiteness":"/ˈhwaɪtnəs/, /ˈwaɪtnəs/",
"whitenight":"/ˈhwaɪtˌnaɪt/, /ˈwaɪtˌnaɪt/",
"whitening":"/ˈhwaɪtɪnɪŋ/, /ˈhwaɪtnɪŋ/, /ˈwaɪtɪnɪŋ/, /ˈwaɪtnɪŋ/",
"whiter":"/ˈhwaɪtɝ/, /ˈwaɪtɝ/",
"whites":"/ˈhwaɪts/, /ˈwaɪts/",
"whitescarver":"/ˈhwaɪtˌskɑɹvɝ/, /ˈwaɪtˌskɑɹvɝ/",
"whitesel":"/ˈhwaɪtˌsɛl/, /ˈwaɪtˌsɛl/",
"whitesell":"/ˈhwaɪtˌsɛl/, /ˈwaɪtˌsɛl/",
"whiteside":"/ˈhwaɪtˌsaɪd/, /ˈwaɪtˌsaɪd/",
"whitesides":"/ˈhwaɪtˌsaɪdz/, /ˈwaɪtˌsaɪdz/",
"whitest":"/ˈhwaɪtɪst/, /ˈwaɪtɪst/",
"whitestone":"/ˈhwaɪtˌstoʊn/, /ˈwaɪtˌstoʊn/",
"whitetail":"/ˈhwaɪˌteɪl/, /ˈhwaɪtˌteɪl/, /ˈwaɪtˌteɪl/",
"whitewash":"/ˈhwaɪtˌwɑʃ/, /ˈwaɪtˌwɑʃ/",
"whitewashed":"/ˈhwaɪtˌwɑʃt/, /ˈwaɪtˌwɑʃt/",
"whitewater":"/ˈhwaɪtˌwɔtɝ/, /ˈwaɪtˌwɔtɝ/",
"whitewater's":"/ˈhwaɪtˌwɔtɝz/, /ˈwaɪtˌwɔtɝz/",
"whitey":"/ˈhwaɪˌti/, /ˈhwaɪti/, /ˈwaɪˌti/",
"whitfield":"/ˈhwɪtfild/, /ˈwɪtfild/",
"whitfill":"/ˈhwɪtˌfɪl/, /ˈwɪtˌfɪl/",
"whitford":"/ˈhwɪtfɝd/, /ˈwɪtfɝd/",
"whitham":"/ˈhwɪtəm/, /ˈhwɪθəm/, /ˈwɪθəm/",
"whither":"/ˈhwɪðɝ/, /ˈwɪðɝ/",
"whiting":"/ˈhwaɪtɪŋ/, /ˈwaɪtɪŋ/",
"whitings":"/ˈhwaɪtɪŋz/, /ˈwaɪtɪŋz/",
"whitis":"/ˈhwaɪtɪs/, /ˈwaɪtɪs/",
"whitish":"/ˈhwaɪtɪʃ/, /ˈwaɪtɪʃ/",
"whitlatch":"/ˈhwɪtˌlætʃ/, /ˈwɪtˌlætʃ/",
"whitledge":"/ˈhwɪtˌlɛdʒ/, /ˈwɪtˌlɛdʒ/",
"whitley":"/ˈhwɪtli/, /ˈwɪtli/",
"whitling":"/ˈhwɪtlɪŋ/, /ˈwɪtlɪŋ/",
"whitlock":"/ˈhwɪtˌlɑk/, /ˈwɪtˌlɑk/",
"whitlow":"/ˈhwɪtˌloʊ/, /ˈwɪtˌloʊ/",
"whitly":"/ˈhwɪtli/, /ˈwɪtli/",
"whitman":"/ˈhwɪtmən/, /ˈwɪtmən/",
"whitman's":"/ˈhwɪtmənz/, /ˈwɪtmənz/",
"whitmarsh":"/ˈhwɪtˌmɑɹʃ/, /ˈwɪtˌmɑɹʃ/",
"whitmer":"/ˈhwɪtmɝ/, /ˈwɪtmɝ/",
"whitmill":"/ˈhwɪtˌmɪl/, /ˈwɪtˌmɪl/",
"whitmire":"/ˈhwɪtˌmaɪɹ/, /ˈwɪtˌmaɪɹ/",
"whitmore":"/ˈhwɪtmɔɹ/, /ˈwɪtmɔɹ/",
"whitmoyer":"/ˈhwɪtˌmɔɪɝ/, /ˈwɪtˌmɔɪɝ/",
"whitmyer":"/ˈhwɪtˌmaɪɝ/, /ˈwɪtˌmaɪɝ/",
"whitner":"/ˈhwɪtnɝ/, /ˈwɪtnɝ/",
"whitney":"/ˈhwɪtni/, /ˈwɪtni/",
"whitney's":"/ˈhwɪtniz/, /ˈwɪtniz/",
"whiton":"/ˈhwɪtən/, /ˈwɪtən/",
"whitrow":"/ˈhwɪˌtɹoʊ/, /ˈwɪˌtɹoʊ/",
"whitsel":"/ˈhwɪtsəl/, /ˈwɪtsəl/",
"whitsell":"/ˈhwɪtsəl/, /ˈwɪtsəl/",
"whitsett":"/ˈhwɪtsɪt/, /ˈwɪtsɪt/",
"whitsitt":"/ˈhwɪtsɪt/, /ˈwɪtsɪt/",
"whitson":"/ˈhwɪtsən/, /ˈwɪtsən/",
"whitt":"/ˈhwɪt/, /ˈwɪt/",
"whittaker":"/ˈhwɪtəkɝ/, /ˈwɪtəkɝ/",
"whitted":"/ˈhwɪtɪd/, /ˈwɪtɪd/",
"whittemore":"/ˈhwɪtmɔɹ/, /ˈwɪtmɔɹ/",
"whitten":"/ˈhwɪtən/, /ˈwɪtən/",
"whittenberg":"/ˈhwɪtənbɝɡ/, /ˈwɪtənbɝɡ/",
"whittenburg":"/ˈhwɪtənbɝɡ/, /ˈwɪtənbɝɡ/",
"whittet":"/ˈhwɪtɪt/, /ˈwɪtɪt/",
"whittier":"/ˈhwɪtiɝ/, /ˈwɪtiɝ/",
"whitting":"/ˈhwɪtɪŋ/, /ˈwɪtɪŋ/",
"whittingham":"/ˈhwɪtɪŋˌhæm/, /ˈwɪtɪŋˌhæm/",
"whittinghill":"/ˈhwɪtɪŋˌhɪl/, /ˈwɪtɪŋˌhɪl/",
"whittington":"/ˈhwɪtɪŋtən/, /ˈwɪtɪŋtən/",
"whittle":"/ˈhwɪtəl/, /ˈwɪtəl/",
"whittle's":"/ˈhwɪtəlz/, /ˈwɪtəlz/",
"whittled":"/ˈhwɪtəld/, /ˈwɪtəld/",
"whittlesey":"/ˈhwɪtəlsi/, /ˈwɪtəlsi/",
"whittling":"/ˈhwɪtlɪŋ/, /ˈwɪtlɪŋ/",
"whitton":"/ˈhwɪtən/, /ˈwɪtən/",
"whitty":"/ˈhwɪti/, /ˈwɪti/",
"whitwam":"/ˈhwɪtwɑm/, /ˈwɪtwɑm/",
"whitwell":"/ˈhwɪtˌwɛl/, /ˈwɪtˌwɛl/",
"whitworth":"/ˈhwɪtˌwɝθ/, /ˈwɪtˌwɝθ/",
"whiz":"/ˈhwɪz/, /ˈwɪz/",
"whiz-zip-bang":"/ˈwɪzˈzɪpˈbæŋ/",
"whizzed":"/ˈhwɪzd/, /ˈwɪzd/",
"whizzer":"/ˈhwɪzɝ/, /ˈwɪzɝ/",
"whizzes":"/ˈhwɪzɪz/, /ˈwɪzɪz/",
"whizzing":"/ˈhwɪzɪŋ/, /ˈwɪzɪŋ/",
"who":"/ˈhu/",
"who'd":"/ˈhud/",
"who'll":"/ˈhul/",
"who're":"/ˈhuɝ/",
"who's":"/ˈhuz/",
"who've":"/huv/",
"whoa":"/ˈhoʊ/, /ˈhwoʊ/, /ˈwoʊ/",
"whobrey":"/ˈwɑbɹi/",
"whodunit":"/huˈdənɪt/",
"whodunits":"/huˈdənɪts/",
"whoever":"/huˈɛvɝ/",
"whoever's":"/huˈɛvɝz/",
"whole":"/ˈhoʊl/",
"wholehearted":"/ˈhoʊlˌhɑɹtɪd/",
"wholeheartedly":"/ˈhoʊlhɑɹtɪdli/",
"wholeness":"/ˈhoʊlnɪs/",
"wholes":"/ˈhoʊlz/",
"wholesale":"/ˈhoʊlˌseɪl/",
"wholesaler":"/ˈhoʊlˌseɪlɝ/",
"wholesaler's":"/ˈhoʊlˌseɪlɝz/",
"wholesalers":"/ˈhoʊlˌseɪlɝz/",
"wholesalers'":"/ˈhoʊlˌseɪlɝz/",
"wholesales":"/ˈhoʊlˌseɪlz/",
"wholesaling":"/ˈhoʊlˌseɪlɪŋ/",
"wholesome":"/ˈhoʊlsəm/",
"wholesomeness":"/ˈhoʊlsəmnəs/",
"wholey":"/ˈhɑli/",
"wholly":"/ˈhoʊli/",
"whom":"/ˈhum/",
"whomever":"/huˈmɛvɝ/",
"whomsoever":"/ˌhumsoʊˈɛvɝ/",
"whoo":"/ˈwu/",
"whoop":"/ˈhwup/, /ˈwup/",
"whoopdedoo":"/ˈhwʊpdidu/, /ˈwʊpdidu/",
"whooped":"/ˈhwupt/, /ˈwupt/",
"whoopee":"/ˈhwuˈpi/, /ˈwuˈpi/",
"whoopi":"/ˈhwupi/, /ˈwupi/",
"whoopie":"/ˈhwupi/, /ˈwupi/",
"whooping":"/ˈhwupɪŋ/, /ˈwupɪŋ/",
"whoops":"/ˈhwups/, /ˈwups/",
"whoosh":"/ˈhwuʃ/, /ˈwuʃ/",
"whopper":"/ˈhwɑpɝ/, /ˈwɑpɝ/",
"whoppers":"/ˈhwɑpɝz/, /ˈwɑpɝz/",
"whopping":"/ˈhwɑpɪŋ/, /ˈwɑpɪŋ/",
"whore":"/ˈhɔɹ/",
"whorehouse":"/ˈhɔɹˌhaʊs/",
"whores":"/ˈhɔɹz/",
"whorl":"/ˈhwɔɹl/, /ˈwɝl/, /ˈwɔɹl/",
"whorley":"/ˈhɔɹli/, /ˈhwɔɹli/, /ˈwɔɹli/",
"whorls":"/ˈhwɔɹlz/, /ˈwɝlz/, /ˈwɔɹlz/",
"whorton":"/ˈhɔɹtən/",
"whose":"/ˈhuz/",
"whosoever":"/ˌhusoʊˈɛvɝ/",
"why":"/ˈhwaɪ/, /ˈwaɪ/",
"why'd":"/ˈhwaɪd/, /ˈwaɪd/",
"why're":"/ˈwaɪɝ/",
"why's":"/ˈhwaɪz/, /ˈwaɪz/",
"whys":"/ˈhwaɪz/, /ˈwaɪz/",
"whyte":"/ˈhwaɪt/, /ˈwaɪt/",
"wi-fi":"/ˈwaɪˌfaɪ/",
"wiacek":"/ˈvaɪəˌtʃɛk/",
"wian":"/ˈwaɪən/",
"wiant":"/ˈwaɪənt/",
"wiard":"/ˈwaɪɑɹd/",
"wiater":"/ˈwaɪətɝ/",
"wiatrowski":"/viəˈtɹɔfˌski/",
"wiatt":"/ˈwaɪət/",
"wibbelsman":"/ˈwɪbəlzmən/",
"wibbenmeyer":"/ˈwɪbɪnˌmaɪɝ/",
"wiberg":"/ˈwaɪbɝɡ/",
"wible":"/ˈwaɪbəl/",
"wicat":"/ˈwɪkæt/",
"wicca":"/ˈwɪkə/",
"wiccan":"/ˈwɪkən/",
"wice":"/ˈwaɪs/",
"wich":"/ˈwɪtʃ/",
"wichern":"/ˈwɪkɝn/",
"wichert":"/ˈwɪtʃɝt/",
"wichita":"/ˈwɪtʃəˌtɔ/",
"wichita's":"/ˈwɪtʃəˌtɔz/",
"wichman":"/ˈwɪtʃmən/",
"wichmann":"/ˈwɪtʃmən/",
"wick":"/ˈwɪk/",
"wickard":"/ˈwɪkɝd/",
"wicke":"/ˈwɪk/",
"wicked":"/ˈwɪkəd/",
"wickedly":"/ˈwɪkɪdli/",
"wickedness":"/ˈwɪkədnəs/",
"wickens":"/ˈwɪkənz/",
"wicker":"/ˈwɪkɝ/",
"wicker's":"/ˈwɪkɝz/",
"wickerham":"/ˈwɪkɝˌhæm/",
"wickers":"/ˈwɪkɝz/",
"wickersham":"/ˈwɪkɝˌʃæm/",
"wickert":"/ˈwɪkɝt/",
"wickes":"/ˈwɪks/",
"wickes's":"/ˈwɪksɪz/",
"wicket":"/ˈhwɪkət/, /ˈwɪkət/",
"wickets":"/ˈhwɪkəts/, /ˈwɪkəts/",
"wickett":"/ˈwɪkɪt/",
"wickey":"/ˈwɪki/",
"wickham":"/ˈwɪkəm/",
"wickizer":"/ˈwɪˌkaɪzɝ/",
"wickland":"/ˈwɪklənd/",
"wicklander":"/ˈwɪˌklændɝ/",
"wickley":"/ˈwɪkli/",
"wickliff":"/ˈwɪklɪf/",
"wickliffe":"/ˈwɪklɪf/",
"wickline":"/ˈwɪˌklaɪn/",
"wicklund":"/ˈwɪklənd/",
"wickman":"/ˈwɪkmən/",
"wicks":"/ˈwɪks/",
"wickstrom":"/ˈwɪkstɹəm/",
"wickware":"/ˈwɪˌkwɛɹ/",
"wickwire":"/ˈvɪskvaɪɹ/",
"wicomico":"/ˌwaɪˈkɑmɪˌkoʊ/",
"wicor":"/ˈwaɪˌkɔɹ/",
"widder":"/ˈwɪdɝ/",
"widdle":"/ˈwɪdəl/",
"widdled":"/ˈwɪdəld/",
"widdly":"/ˈwɪdli/",
"widdows":"/ˈwɪˌdoʊz/",
"widdowson":"/ˈwɪdaʊsən/",
"wide":"/ˈwaɪd/",
"wide's":"/ˈwaɪdz/",
"widebody":"/ˈwaɪdˌbɑdi/",
"widell":"/ˈwɪdəl/",
"widely":"/ˈwaɪdli/",
"wideman":"/ˈwaɪdmən/",
"widen":"/ˈwaɪdən/",
"widened":"/ˈwaɪdənd/",
"widener":"/ˈwɪdinɝ/",
"widening":"/ˈwaɪdənɪŋ/",
"widens":"/ˈwaɪdənz/",
"wider":"/ˈwaɪdɝ/",
"widespread":"/ˈwaɪdsˈpɹɛd/",
"widest":"/ˈwaɪdəst/",
"widger":"/ˈwɪdʒɝ/",
"widget":"/ˈwɪdʒɪt/",
"widgets":"/ˈwɪdʒɪts/",
"widhalm":"/ˈwɪdhɑm/",
"widick":"/ˈwɪdɪk/",
"widing":"/ˈwaɪdɪŋ/",
"widmaier":"/ˈwɪdmaɪɝ/",
"widman":"/ˈwɪdmən/",
"widmann":"/ˈwɪdmən/",
"widmar":"/ˈwɪdmɝ/",
"widmayer":"/ˈwɪdˌmeɪɝ/",
"widmer":"/ˈwɪdmɝ/",
"widnall":"/ˈwɪdnəl/",
"widner":"/ˈwɪdnɝ/",
"widow":"/ˈwɪdoʊ/",
"widow's":"/ˈwɪdoʊz/",
"widowed":"/ˈwɪdoʊd/",
"widower":"/ˈwɪdoʊɝ/",
"widowers":"/ˈwɪdoʊɝz/",
"widows":"/ˈwɪdoʊz/",
"widrick":"/ˈwɪdɹɪk/",
"widrig":"/ˈwɪdɹɪɡ/",
"width":"/ˈwɪdθ/",
"widths":"/ˈwɪdθs/",
"widuri":"/wɪˈdʊɹi/",
"wieand":"/ˈwiənd/",
"wiebe":"/ˈwib/",
"wieber":"/ˈwibɝ/",
"wieberg":"/ˈwibɝɡ/",
"wiebke":"/ˈwibki/",
"wiebold":"/ˈwiˌboʊld/",
"wiebusch":"/ˈwibəʃ/",
"wiech":"/ˈwitʃ/",
"wiechert":"/ˈwikɝt/",
"wiechman":"/ˈwikmən/",
"wiechmann":"/ˈwikmən/",
"wieck":"/ˈwik/",
"wieczorek":"/viˈtʃɔɹɛk/",
"wied":"/ˈwid/",
"wiedel":"/ˈwidəl/",
"wiedeman":"/ˈwidmən/",
"wiedemann":"/ˈwidmən/",
"wieden":"/ˈwidən/",
"wieder":"/ˈwidɝ/",
"wiederaufbau":"/ˌwidɝˈɔfbaʊ/",
"wiederhold":"/ˈwidɝhoʊld/",
"wiederholt":"/ˈwidɝhoʊlt/",
"wiederkehr":"/ˈwidɝkɪɹ/",
"wiedman":"/ˈwidmən/",
"wiedmann":"/ˈwidmən/",
"wiedmeyer":"/ˈwidmaɪɝ/",
"wiedner":"/ˈwidnɝ/",
"wiedrich":"/ˈwidɹɪk/",
"wiegand":"/ˈwiɡənd/",
"wiegel":"/ˈwiɡəl/",
"wiegers":"/ˈwiɡɝz/",
"wiegert":"/ˈwiɡɝt/",
"wiegman":"/ˈwiɡmən/",
"wiegmann":"/ˈwiɡmən/",
"wiehe":"/ˈwi/",
"wieland":"/ˈwilənd/",
"wield":"/ˈwild/",
"wielded":"/ˈwildɪd/",
"wielding":"/ˈwildɪŋ/",
"wields":"/ˈwildz/",
"wielgus":"/ˈwilɡəs/",
"wieman":"/ˈwimən/",
"wiemann":"/ˈwimən/",
"wiemer":"/ˈwimɝ/",
"wiemers":"/ˈwimɝz/",
"wien":"/ˈwin/",
"wiencek":"/ˈvintʃɛk/",
"wienecke":"/ˈwinɪk/",
"wieneke":"/ˈwinɪk/",
"wiener":"/ˈwaɪnɝ/, /ˈwinɝ/",
"wieners":"/ˈwinɝz/",
"wienerschnitzel":"/ˈvinɝʃˌnɪtsəl/, /ˈwinɝʃˌnɪtsəl/",
"wienerschnitzel's":"/ˈvinɝʃˌnɪtsəlz/, /ˈwinɝʃˌnɪtsəlz/",
"wienke":"/ˈwiŋk/",
"wiens":"/ˈwinz/",
"wier":"/ˈwɪɹ/",
"wierdin":"/ˈwɪɹdɪn/",
"wierenga":"/vɪˈɹɛŋɡə/",
"wierman":"/ˈwɪɹmən/",
"wiers":"/ˈwiɹz/",
"wiersema":"/vɪɹˈsimə/",
"wiersma":"/ˈvɪɹsmə/",
"wierzba":"/ˈvɪɹzbə/",
"wierzbicki":"/vɪɹzˈbɪtski/",
"wies":"/ˈwaɪz/",
"wiesbaden":"/ˈwaɪsˌbɑdən/, /ˈwisˌbɑdən/",
"wiese":"/ˈwiz/",
"wiesel":"/ˈwisəl/",
"wieseler":"/ˈwisəlɝ/",
"wiesemann":"/ˈwismən/",
"wiesen":"/ˈwisən/",
"wiesenthal":"/ˈwisənˈθɑl/, /ˈwizənˈθɑl/",
"wieser":"/ˈwisɝ/",
"wiesman":"/ˈwizmən/",
"wiesner":"/ˈwiznɝ/",
"wiess":"/ˈwis/",
"wiessner":"/ˈwisnɝ/",
"wiest":"/ˈwaɪɪst/",
"wieting":"/ˈwitɪŋ/",
"wife":"/ˈwaɪf/",
"wife's":"/ˈwaɪfs/",
"wifi":"/ˈwaɪˌfaɪ/, /ˈwiˌfi/",
"wifi's":"/ˈwaɪˌfaɪz/",
"wifis":"/ˈwaɪˌfaɪz/",
"wig":"/ˈwɪɡ/",
"wigal":"/ˈwɪɡəl/",
"wigand":"/ˈwɪɡənd/",
"wigand's":"/ˈwɪɡəndz/",
"wigen":"/ˈwɪɡən/",
"wigfall":"/ˈwɪɡˌfɔl/",
"wigfield":"/ˈwɪɡˌfild/",
"wigg":"/ˈwɪɡ/",
"wiggans":"/ˈwɪɡənz/",
"wigger":"/ˈwɪɡɝ/",
"wiggers":"/ˈwɪɡɝz/",
"wiggin":"/ˈwɪɡɪn/",
"wiggington":"/ˈwɪɡɪŋtən/",
"wiggins":"/ˈwɪɡɪnz/",
"wigginton":"/ˈwɪɡɪntən/",
"wiggle":"/ˈwɪɡəl/",
"wiggled":"/ˈwɪɡəld/",
"wiggles":"/ˈwɪɡəlz/",
"wigglesworth":"/ˈwɪɡəlzˌwɝθ/",
"wiggling":"/ˈwɪɡəlɪŋ/, /ˈwɪɡlɪŋ/",
"wiggly":"/ˈwɪɡəli/",
"wiggs":"/ˈwɪɡz/",
"wight":"/ˈwaɪt/",
"wightman":"/ˈwaɪtmən/",
"wigington":"/ˈwɪɡɪŋtən/",
"wiginton":"/ˈwɪdʒɪntən/",
"wigle":"/ˈwaɪɡəl/",
"wigley":"/ˈwɪɡli/",
"wigmore":"/ˈwɪɡmɔɹ/",
"wignall":"/ˈwɪɡnəl/",
"wigs":"/ˈwɪɡz/",
"wigton":"/ˈwɪɡtən/",
"wigton's":"/ˈwɪɡtənz/",
"wigwam":"/ˈwɪɡwɑm/",
"wii":"/ˈwi/",
"wiitala":"/viˈtɑlə/",
"wik":"/ˈwɪk/",
"wike":"/ˈwaɪk/",
"wikel":"/ˈwɪkəl/",
"wiker":"/ˈwaɪkɝ/",
"wiki":"/ˈwɪˌki/",
"wiki's":"/ˈwɪˌkiz/",
"wikipedia":"/ˈwɪkiˌpiˌdiə/",
"wikipedia's":"/ˈwɪkiˌpiˌdiəz/",
"wikis":"/ˈwɪˌkiz/",
"wikle":"/ˈwaɪkəl/",
"wiklund":"/ˈwɪklənd/",
"wikoff":"/ˈwɪkɔf/",
"wikowsky":"/wɪˈkaʊski/",
"wikstrom":"/ˈwɪkstɹəm/",
"wil":"/ˈwɪl/",
"wil's":"/ˈwɪlz/",
"wiland":"/ˈwaɪlənd/",
"wilander":"/ˈwaɪləndɝ/",
"wilbanks":"/ˈwɪlbəŋks/",
"wilber":"/ˈwɪlbɝ/",
"wilberforce":"/ˈwɪlbɝˌfɔɹs/",
"wilberg":"/ˈwɪlbɝɡ/",
"wilbert":"/ˈwɪlbɝt/",
"wilbon":"/ˈwɪlbən/",
"wilborn":"/ˈwɪlbɝn/",
"wilbourn":"/ˈwɪlbɝn/",
"wilbourne":"/ˈwɪlbɝn/",
"wilbur":"/ˈwɪlbɝ/",
"wilburn":"/ˈwɪlbɝn/",
"wilcher":"/ˈwɪltʃɝ/",
"wilcock":"/ˈwɪlkɑk/",
"wilcox":"/ˈwɪlkɑks/",
"wilcoxen":"/wɪlˈkɑksən/",
"wilcoxon":"/wɪlˈkɑksən/",
"wilcoxson":"/ˈwɪlkɑksən/",
"wilczak":"/ˈvɪltʃæk/",
"wilczek":"/ˈvɪltʃɛk/",
"wilczewski":"/vɪlˈtʃɛfski/",
"wilczynski":"/vɪlˈtʃɪnski/",
"wild":"/ˈwaɪld/",
"wildasin":"/ˈwaɪldəˌsɪn/",
"wildavsky":"/wɪlˈdævski/",
"wildcard":"/ˈwaɪldˌkɑɹd/",
"wildcat":"/ˈwaɪldˌkæt/",
"wildcats":"/ˈwaɪldˌkæts/",
"wildcatter":"/ˈwaɪldˌkætɝ/",
"wildcatters":"/ˈwaɪldˌkætɝz/",
"wildcatting":"/ˈwaɪldˌkætɪŋ/",
"wilde":"/ˈwaɪld/",
"wilde's":"/ˈwaɪldz/",
"wildeman":"/ˈwaɪldmən/",
"wilden":"/ˈwaɪldən/",
"wilder":"/ˈwaɪldɝ/",
"wilder's":"/ˈwaɪldɝz/",
"wilderman":"/ˈwaɪldɝmən/",
"wildermuth":"/ˈwaɪldɝmuθ/",
"wilderness":"/ˈwɪldɝnəs/",
"wildes":"/ˈwaɪldz/",
"wildest":"/ˈwaɪldɪst/",
"wildey":"/ˈwɪldi/",
"wildfire":"/ˈwaɪldˌfaɪɝ/",
"wildfires":"/ˈwaɪldˌfaɪɝz/",
"wildflower":"/ˈwaɪldˌflaʊɝ/",
"wildflowers":"/ˈwaɪldˌflaʊɹz/",
"wilding":"/ˈwaɪldɪŋ/",
"wildlife":"/ˈwaɪldˌlaɪf/",
"wildly":"/ˈwaɪldli/",
"wildman":"/ˈwaɪldmən/",
"wildmon":"/ˈwaɪldmən/",
"wildness":"/ˈwaɪldnəs/",
"wildon":"/ˈwaɪldən/",
"wildrick":"/ˈwaɪldɹɪk/",
"wilds":"/ˈwaɪldz/",
"wildt":"/ˈwɪlt/",
"wildwood":"/ˈwaɪldˌwʊd/",
"wildwoods":"/ˈwaɪldˌwʊdz/",
"wile":"/ˈwaɪl/",
"wileen":"/wɪˈlin/",
"wileman":"/ˈwaɪlmən/",
"wilemon":"/ˈwɪlɪmɑn/",
"wilen":"/ˈwaɪlən/",
"wilensky":"/wəˈlɪnski/",
"wilentz":"/wəˈlɛnts/",
"wiler":"/ˈwaɪlɝ/",
"wiles":"/ˈwaɪlz/",
"wiles's":"/ˈwaɪlzɪz/",
"wiley":"/ˈwaɪli/",
"wilfert":"/ˈwɪlfɝt/",
"wilfong":"/ˈwɪlfɔŋ/",
"wilford":"/ˈwɪlfɝd/",
"wilfred":"/ˈwɪlfɹɪd/",
"wilfreda":"/ˈwɪlfɹɪˌdɑ/",
"wilfredo":"/ˌwɪlˈfeɪˌdoʊ/",
"wilfrid":"/ˈwɪlfɹɪd/",
"wilfried":"/ˈwɪlfɹid/",
"wilfully":"/ˈwɪlfəli/",
"wilgus":"/ˈwɪlɡəs/",
"wilham":"/ˈwɪlhəm/",
"wilhelm":"/ˈwɪlˌhɛlm/",
"wilhelma":"/wɪlˈhɛlmə/",
"wilhelmi":"/wɪlˈhɛlmi/",
"wilhelmina":"/ˌwɪlhɛlˈmiˌnɑ/",
"wilhelmine":"/ˈwɪlhɪlmɪn/",
"wilhelms":"/ˈwɪlˌhɛlmz/",
"wilhelmsen":"/ˈwɪlhɪlmsən/",
"wilhelmy":"/ˈwɪlhɪlmi/",
"wilhemina":"/ˈwɪlhɛˈmiˌnɑ/",
"wilhide":"/ˈwɪlˌhaɪd/",
"wilhite":"/ˈwɪlˌhaɪt/",
"wilhoit":"/ˈwɪlˌhɔɪt/",
"wilhoite":"/ˈwɪlˌhɔɪt/",
"wiliams":"/ˈwɪliəmz/",
"wiling":"/ˈwaɪlɪŋ/",
"wilinski":"/vɪˈlɪnski/",
"wilk":"/ˈwɪlk/",
"wilke":"/ˈwɪlk/",
"wilken":"/ˈwɪlkən/",
"wilkening":"/ˈwɪlkənɪŋ/",
"wilkens":"/ˈwɪlkənz/",
"wilkenson":"/ˈwɪlkɪnsən/",
"wilker":"/ˈwɪlkɝ/",
"wilkerson":"/ˈwɪlkɝsən/",
"wilkes":"/ˈwɪlks/",
"wilkesboro":"/ˈwɪlksbɝoʊ/",
"wilkey":"/ˈwɪlki/",
"wilkie":"/ˈwɪlki/",
"wilkin":"/ˈwɪlkɪn/",
"wilking":"/ˈwɪlkɪŋ/",
"wilkins":"/ˈwɪlkɪnz/",
"wilkinson":"/ˈwɪlkənsən/, /ˈwɪlkɪnsən/",
"wilkinson's":"/ˈwɪlkɪnsənz/",
"wilkis":"/ˈwɪlkɪs/",
"wilkison":"/ˈwɪlkɪsən/",
"wilkowski":"/vɪlˈkɔfski/",
"wilks":"/ˈwɪlks/",
"will":"/ˈwɪl/, /wəl/",
"will's":"/ˈwɪlz/",
"willa":"/ˈwɪlə/",
"willabelle":"/ˈwɪləˌbɛl/",
"willadsen":"/wɪˈlædsən/",
"willaims":"/ˈwɪləmz/",
"willam":"/ˈwɪləm/",
"willamette":"/ˌwɪləˈmɛt/, /wəˈlæmət/",
"willamette's":"/ˌwɪləˈmɛts/, /wəˈlæməts/",
"willamina":"/wɪləˈmaɪnə/",
"willapa":"/wɪˈlɑpə/",
"willapa's":"/wɪˈlɑpəz/",
"willard":"/ˈwɪlɝd/",
"willbanks":"/ˈwɪlˌbæŋks/",
"willcox":"/ˈwɪlˌkɑks/",
"willcutt":"/ˈwɪlkət/",
"willden":"/ˈwɪldən/",
"wille":"/ˈwɪl/",
"willed":"/ˈwɪld/",
"willeford":"/ˈwɪlfɝd/, /ˈwɪlɪfɝd/",
"willem":"/ˈwɪləm/",
"willems":"/ˈwɪləmz/",
"willemsen":"/ˈwɪləmsən/, /wɪˈlɛmsən/",
"willen":"/ˈwɪlən/",
"willenborg":"/ˈwɪlɪnbɔɹɡ/",
"willenbring":"/ˈwɪlənˌbɹɪŋ/",
"willens":"/ˈwɪlənz/",
"willer":"/ˈwɪlɝ/",
"willers":"/ˈwɪlɝz/",
"willert":"/ˈwɪlɝt/",
"willes":"/ˈwaɪlz/",
"willet":"/ˈwɪlɪt/",
"willets":"/ˈwɪlɪts/",
"willett":"/ˈwɪlɪt/",
"willette":"/wɪˈlɛt/",
"willetts":"/ˈwɪlɪts/",
"willey":"/ˈwɪli/",
"willford":"/ˈwɪlfɝd/",
"willful":"/ˈwɪlfəl/",
"willfully":"/ˈwɪlfəli/",
"willhelm":"/ˈwɪlˌhɛlm/",
"willhite":"/ˈwɪlˌhaɪt/",
"willhoit":"/ˈwɪlˌhɔɪt/",
"willhoite":"/ˈwɪlˌhɔɪt/",
"willi":"/ˈwɪli/",
"william":"/ˈwɪljəm/",
"william's":"/ˈwɪljəmz/",
"williams":"/ˈwɪljəmz/",
"williams'":"/ˈwɪljəmz/",
"williams's":"/ˈwɪljəmzɪz/",
"williamsburg":"/ˈwɪljəmzbɝɡ/",
"williamsburgh":"/ˈwɪljəmzbɝɡ/",
"williamsen":"/ˈwɪljəmsən/",
"williamson":"/ˈwɪljəmsən/",
"williamson's":"/ˈwɪljəmsənz/",
"williamsport":"/ˈwɪljəmˌspɔɹt/",
"williamstown":"/ˈwɪljəmˌstaʊn/",
"williard":"/ˈwɪljɑɹd/",
"willie":"/ˈwɪli/",
"willie's":"/ˈwɪliz/",
"williford":"/ˈwɪlɪfɝd/",
"willig":"/ˈwɪlɪɡ/",
"willing":"/ˈwɪlɪŋ/",
"willinger":"/ˈwɪlɪŋɝ/",
"willingham":"/ˈwɪlɪŋˌhæm/",
"willingly":"/ˈwɪlɪŋli/",
"willingness":"/ˈwɪlɪŋnəs/",
"willis":"/ˈwɪlɪs/",
"willis's":"/ˈwɪlɪsɪz/",
"willison":"/ˈwɪlɪsən/",
"williston":"/ˈwɪlɪstɑn/",
"willits":"/ˈwɪlɪts/",
"willke":"/ˈwɪlki/",
"willkie":"/ˈwɪlki/",
"willman":"/ˈwɪlmən/",
"willmann":"/ˈwɪlmən/",
"willmon":"/ˈwɪlmən/",
"willmore":"/ˈwɪlmɔɹ/",
"willmott":"/ˈwɪlmət/",
"willms":"/ˈwɪlmz/",
"willner":"/ˈwɪlnɝ/",
"willock":"/ˈwɪlək/",
"willoughby":"/ˈwɪləbi/",
"willow":"/ˈwɪˌloʊ/",
"willowbrook":"/ˈwɪloʊˌbɹʊk/",
"willowes":"/ˈwɪˌloʊz/",
"willows":"/ˈwɪˌloʊz/",
"willowy":"/ˈwɪləwi/",
"willpower":"/ˈwɪlˌpaʊɝ/",
"wills":"/ˈwɪlz/",
"willse":"/ˈwɪlsi/",
"willsey":"/ˈwɪlsi/",
"willson":"/ˈwɪlsən/",
"willwerth":"/ˈwɪlwɝθ/",
"willy":"/ˈwɪli/",
"willyard":"/ˈwɪlˌjɑɹd/",
"wilma":"/ˈwɪlmə/",
"wilmar":"/ˈwɪlmɝ/",
"wilmarth":"/ˈwɪlmɑɹθ/",
"wilmer":"/ˈwɪlmɝ/",
"wilmes":"/ˈwɪlmz/",
"wilmet":"/ˈwɪlmɪt/",
"wilmeth":"/ˈwɪlmɪθ/",
"wilmette":"/wɪlˈmɛt/",
"wilmington":"/ˈwɪlmɪŋtən/",
"wilmore":"/ˈwɪlmɔɹ/",
"wilmot":"/ˈwɪlmət/",
"wilmoth":"/ˈwɪlməθ/",
"wilmott":"/ˈwɪlmət/",
"wilmouth":"/ˈwɪlmaʊθ/",
"wilms":"/ˈwɪlmz/",
"wilmut":"/ˈwɪlmət/",
"wilner":"/ˈwɪlnɝ/",
"wilpon":"/ˈwɪlpɑn/",
"wilsey":"/ˈwɪlsi/",
"wilshire":"/ˈwɪlˌʃaɪɹ/",
"wilshusen":"/ˈwɪlʃusən/",
"wilson":"/ˈwɪlsən/",
"wilson's":"/ˈwɪlsənz/",
"wilt":"/ˈwɪlt/",
"wilted":"/ˈwɪltɪd/",
"wiltel":"/ˈwɪlˌtɛl/",
"wiltfong":"/ˈwɪltfɔŋ/",
"wiltgen":"/ˈwɪltɡən/",
"wilthew":"/ˈwɪlθju/",
"wilting":"/ˈwɪltɪŋ/",
"wilton":"/ˈwɪltən/",
"wiltron":"/ˈwɪltɹən/",
"wiltrout":"/ˈwɪlˌtɹaʊt/",
"wilts":"/ˈwɪlts/",
"wiltse":"/ˈwɪlts/",
"wiltsey":"/ˈwɪltsi/",
"wiltshire":"/ˈwɪlˌtʃaɪɹ/",
"wiltsie":"/ˈwɪltsi/",
"wiltz":"/ˈwɪlts/",
"wily":"/ˈwaɪli/",
"wiman":"/ˈwaɪmən/",
"wimberley":"/ˈwɪmbɝli/",
"wimberly":"/ˈwɪmbɝli/",
"wimbish":"/ˈwɪmbɪʃ/",
"wimbledon":"/ˈwɪmbəldən/",
"wimbley":"/ˈwɪmbli/",
"wimbush":"/ˈwɪmbəʃ/, /ˈwɪmbʊʃ/",
"wimer":"/ˈwaɪmɝ/",
"wimmer":"/ˈwɪmɝ/",
"wimp":"/ˈwɪmp/",
"wimpee":"/ˈwɪmpi/",
"wimpiness":"/ˈwɪmpinəs/",
"wimps":"/ˈwɪmps/",
"wimpy":"/ˈwɪmpi/",
"wims":"/ˈwɪmz/",
"wimsatt":"/ˈwɪmsət/",
"win":"/ˈwɪn/",
"win's":"/ˈwɪnz/",
"win-win":"/ˌwɪnˈwɪn/",
"winamac":"/ˈwɪnəmæk/",
"winamac's":"/ˈwɪnəmæks/",
"winans":"/ˈwɪnənz/",
"winans's":"/ˈwɪnənzɪz/",
"winant":"/ˈwaɪnənt/",
"winberg":"/ˈwɪnbɝɡ/",
"winberry":"/ˈwɪnˌbɛɹi/",
"winborn":"/ˈwɪnbɝn/",
"winborne":"/ˈwɪnbɝn/",
"winburn":"/ˈwɪnˌbɝn/",
"winbush":"/ˈwɪnˌbʊʃ/",
"wince":"/ˈwɪns/",
"winced":"/ˈwɪnst/",
"wincek":"/ˈwɪnsɪk/",
"winch":"/ˈwɪntʃ/",
"winchel":"/ˈwɪnkəl/",
"winchell":"/ˈwɪntʃəl/",
"winchell's":"/ˈwɪntʃəlz/",
"winchester":"/ˈwɪnˌtʃɛstɝ/",
"wincing":"/ˈwɪnsɪŋ/",
"winckler":"/ˈwɪŋklɝ/",
"wind":"/ˈwaɪnd/, /ˈwɪnd/",
"wind's":"/ˈwɪndz/",
"windchill":"/ˈwɪndˌtʃɪl/",
"windchime":"/ˈwɪndˌtʃaɪm/",
"windchimes":"/ˈwɪndˌtʃaɪmz/",
"windecker":"/ˈwɪnˌdɛkɝ/",
"winded":"/ˈwaɪndɪd/, /ˈwɪndɪd/",
"windell":"/ˈwɪndəl/",
"windels":"/ˈwɪndəlz/",
"winder":"/ˈwaɪndɝ/, /ˈwɪndɝ/",
"winders":"/ˈwaɪndɝz/, /ˈwɪndɝz/",
"windes":"/ˈwaɪndz/, /ˈwɪndz/",
"windfall":"/ˈwɪndˌfɔl/",
"windfalls":"/ˈwɪndˌfɔlz/",
"windham":"/ˈwɪndəm/",
"windheim":"/ˈwɪndˌhaɪm/",
"windhoek":"/ˈwɪndˌhoʊk/",
"windholz":"/ˈwɪndˌhoʊlz/",
"windhorst":"/ˈwɪndhɔɹst/",
"winding":"/ˈwaɪndɪŋ/",
"windisch":"/ˈwɪndɪʃ/",
"windish":"/ˈwɪndɪʃ/",
"windlass":"/ˈwɪndləs/",
"windle":"/ˈwɪndəl/",
"windler":"/ˈwɪndlɝ/",
"windley":"/ˈwɪndli/",
"windmere":"/ˈwɪndˌmɪɹ/",
"windmere's":"/ˈwɪndˌmɪɹz/",
"windmill":"/ˈwɪndˌmɪl/",
"windmiller":"/ˈwɪndˌmɪlɝ/",
"windmills":"/ˈwɪndˌmɪlz/",
"windom":"/ˈwɪndəm/",
"windon":"/ˈwɪndən/",
"window":"/ˈwɪndoʊ/",
"windowed":"/ˈwɪndoʊd/",
"windowless":"/ˈwɪndoʊləs/",
"windowpane":"/ˈwɪndoʊˌpeɪn/",
"windowpanes":"/ˈwɪndoʊˌpeɪnz/",
"windows":"/ˈwɪndoʊz/",
"winds":"/ˈwaɪndz/, /ˈwɪndz/",
"windshield":"/ˈwɪndˌʃild/",
"windshields":"/ˈwɪndˌʃildz/",
"windsor":"/ˈwɪnzɝ/",
"windsor's":"/ˈwɪnzɝz/",
"windsors":"/ˈwɪnzɝz/",
"windspeed":"/ˈwɪndˌspid/",
"windstar":"/ˈwɪndˌstɑɹ/",
"windstar's":"/ˈwɪndˌstɑɹz/",
"windstorm":"/ˈwɪndˌstɔɹm/",
"windswept":"/ˈwɪnˌswɛpt/",
"windt":"/ˈwɪnt/",
"windup":"/ˈwaɪnˌdəp/",
"windward":"/ˈwɪndwɝd/",
"windy":"/ˈwaɪndi/, /ˈwɪndi/",
"wine":"/ˈwaɪn/",
"wine's":"/ˈwaɪnz/",
"winebarger":"/ˈwɪnɪbɑɹɡɝ/",
"wineberg":"/ˈwaɪnbɝɡ/",
"winebrenner":"/ˈwɪnɪbɹɪnɝ/",
"winecoff":"/ˈwɪnɪkɔf/",
"wined":"/ˈwaɪnd/",
"winegar":"/ˈwɪnɪɡɝ/",
"winegarden":"/ˈwaɪnˌɡɑɹdən/",
"winegardner":"/ˈwɪnɪɡɑɹdnɝ/",
"wineheim":"/ˈwaɪnˌhaɪm/",
"wineinger":"/ˈwaɪnɪŋɝ/",
"wineland":"/ˈwaɪnlənd/, /ˈwɪnɪlənd/",
"winema":"/ˈwɪnɪmə/",
"wineman":"/ˈwaɪnmən/",
"winemiller":"/ˈwaɪnˌmɪlɝ/",
"winer":"/ˈwaɪnɝ/",
"wineries":"/ˈwaɪnɝiz/",
"winery":"/ˈwaɪnɝi/",
"winery's":"/ˈwaɪnɝiz/",
"wines":"/ˈwaɪnz/",
"winey":"/ˈwaɪni/",
"winfield":"/ˈwɪnˌfild/",
"winford":"/ˈwɪnfɝd/",
"winfred":"/ˈwɪnfɹɪd/",
"winfree":"/ˈwɪnˌfɹi/",
"winfrey":"/ˈwɪnfɹi/",
"winfrid":"/ˈwɪnfɹɪd/",
"wing":"/ˈwɪŋ/",
"wing's":"/ˈwɪŋz/",
"wingard":"/ˈwɪŋɡɝd/",
"wingate":"/ˈwɪnˌɡeɪt/",
"wingback":"/ˈwɪŋˌbæk/",
"winge":"/ˈwɪndʒ/",
"winged":"/ˈwɪŋd/",
"winger":"/ˈwɪŋɝ/",
"wingers":"/ˈwɪŋɝz/",
"wingert":"/ˈwɪŋɡɝt/",
"wingerter":"/ˈwɪŋɡɝtɝ/",
"winget":"/ˈwɪŋɡɪt/",
"wingett":"/ˈwɪŋɡɪt/",
"wingfield":"/ˈwɪŋˌfild/",
"winging":"/ˈwɪŋɪŋ/",
"wingler":"/ˈwɪŋɡəlɝ/, /ˈwɪŋɡlɝ/",
"winglike":"/ˈwɪŋˌlaɪk/",
"wingman":"/ˈwɪŋmən/",
"wingo":"/ˈwiŋɡoʊ/",
"wingrove":"/ˈwɪnˌɡɹoʊv/",
"wings":"/ˈwɪŋz/",
"wings'":"/ˈwɪŋz/",
"wingspan":"/ˈwɪŋˌspæn/",
"winiarski":"/vɪniˈɑɹski/",
"winick":"/ˈwɪnɪk/",
"winiecki":"/vɪˈnitski/",
"winifred":"/ˈwɪnɪfɹɪd/",
"winik":"/ˈwɪnɪk/",
"wining":"/ˈwaɪnɪŋ/",
"wininger":"/ˈwaɪnɪŋɝ/",
"winings":"/ˈwaɪnɪŋz/",
"wink":"/ˈwɪŋk/",
"winked":"/ˈwɪŋkt/",
"winkel":"/ˈwɪŋkəl/",
"winkelman":"/ˈwɪŋkəlmən/",
"winkelmann":"/ˈwɪŋkəlmən/",
"winkels":"/ˈwɪŋkəlz/",
"winker":"/ˈwɪŋkɝ/",
"winkfield":"/ˈwɪŋkˌfild/",
"winking":"/ˈwɪŋkɪŋ/",
"winkle":"/ˈwɪŋkəl/",
"winkleman":"/ˈwɪŋkəlmən/",
"winkler":"/ˈwɪŋklɝ/",
"winkles":"/ˈwɪŋkəlz/",
"winkley":"/ˈwɪŋkli/",
"winkowski":"/vɪŋˈkɔfski/",
"winks":"/ˈwɪŋks/",
"winland":"/ˈwɪnlənd/",
"winn":"/ˈwɪn/",
"winnable":"/ˈwɪnəbəl/",
"winne":"/ˈwɪn/",
"winnebago":"/ˌwɪnəˈbeɪɡoʊ/",
"winnebago's":"/ˌwɪnəˈbeɪɡoʊz/",
"winner":"/ˈwɪnɝ/",
"winner's":"/ˈwɪnɝz/",
"winners":"/ˈwɪnɝz/",
"winners'":"/ˈwɪnɝz/",
"winnetka":"/wɪˈnɛtkə/",
"winnett":"/ˈwɪnɪt/",
"winney":"/ˈwɪni/",
"winnick":"/ˈwɪnɪk/",
"winnicki":"/vɪˈnɪtski/",
"winnie":"/ˈwɪni/",
"winning":"/ˈwɪnɪŋ/",
"winningest":"/ˈwɪnɪŋəst/",
"winningham":"/ˈwɪnɪŋˌhæm/",
"winnings":"/ˈwɪnɪŋz/",
"winnipeg":"/ˈwɪnɪpəɡ/",
"winnow":"/ˈwɪˌnoʊ/",
"winnowed":"/ˈwɪˌnoʊd/",
"winnowing":"/ˈwɪˌnoʊɪŋ/",
"winny":"/ˈwɪni/",
"wino":"/ˈwinoʊ/",
"winograd":"/ˈwɪnəɡɹæd/",
"winokur":"/ˈwɪnəkɝ/",
"winola":"/vɪˈnoʊlə/",
"winona":"/ˈwɪnənə/",
"winonah":"/ˈwɪnənə/",
"winooski":"/wɪˈnuski/",
"winos":"/ˈwinoʊs/",
"winquist":"/ˈwɪnˌkwɪst/",
"wins":"/ˈwɪnz/",
"winsett":"/ˈwɪnsɪt/",
"winship":"/ˈwɪnˌʃɪp/",
"winski":"/ˈwɪnˌski/",
"winslet":"/ˈwɪnslɪt/",
"winslet's":"/ˈwɪnslɪts/",
"winslett":"/ˈwɪnslɪt/",
"winslow":"/ˈwɪnzloʊ/",
"winsome":"/ˈwɪnsəm/",
"winson":"/ˈwɪnsən/",
"winsor":"/ˈwɪnzɝ/",
"winstanley":"/ˈwɪnstənli/",
"winstead":"/ˈwɪnˌstɛd/",
"winston":"/ˈwɪnstən/",
"wint":"/ˈwɪnt/",
"winter":"/ˈwɪntɝ/",
"winter's":"/ˈwɪntɝz/",
"winterberg":"/ˈwɪntɝbɝɡ/",
"winterbourne":"/ˈwɪntɝˌbɔɹn/",
"wintered":"/ˈwɪntɝd/",
"wintergreen":"/ˈwɪntɝˌɡɹin/",
"winterhalter":"/ˈwɪntɝˌhɔltɝ/",
"winterize":"/ˈwɪntɝˌaɪz/",
"winterized":"/ˈwɪntɝˌaɪzd/",
"wintermute":"/ˈwɪntɝmˌjut/",
"winterrowd":"/ˈwɪntɝaʊd/",
"winters":"/ˈwɪntɝz/",
"wintershall":"/ˈwɪntɝˌʃæl/",
"wintersteen":"/ˈwɪntɝˌstin/",
"winterstein":"/ˈwɪntɝˌstaɪn/, /ˈwɪntɝˌstin/",
"winterthur":"/ˈwɪntɝθɝ/",
"wintertime":"/ˈwɪntɝˌtaɪm/",
"winterton":"/ˈwɪntɝtən/",
"winther":"/ˈwɪnθɝ/",
"winthrop":"/ˈwɪnθɹəp/",
"winthrop's":"/ˈwɪnθɹəps/",
"wintle":"/ˈwɪntəl/",
"wintom":"/ˈwɪntəm/",
"winton":"/ˈwɪntən/",
"wintour":"/ˈwɪnˌtʊɹ/",
"wintry":"/ˈwɪntɹi/",
"wintz":"/ˈwɪnts/",
"wintzer":"/ˈwɪntsɝ/",
"winward":"/ˈwɪnwɝd/",
"winwood":"/ˈwɪnˌwʊd/",
"winwood's":"/ˈwɪnˌwʊdz/",
"winword":"/ˈwɪnwɝd/",
"winzeler":"/ˈwɪnzəlɝ/",
"winzer":"/ˈwɪnzɝ/",
"wion":"/ˈwaɪən/",
"wipe":"/ˈwaɪp/",
"wiped":"/ˈwaɪpt/",
"wipeout":"/ˈwaɪˌpaʊt/",
"wiper":"/ˈwaɪpɝ/",
"wipers":"/ˈwaɪpɝz/",
"wipes":"/ˈwaɪps/",
"wipf":"/ˈwɪpf/",
"wiping":"/ˈwaɪpɪŋ/",
"wipperfurth":"/ˈwɪpɝfɝθ/",
"wire":"/ˈwaɪɝ/, /ˈwaɪɹ/",
"wired":"/ˈwaɪɝd/, /ˈwaɪɹd/",
"wireless":"/ˈwaɪɹlɪs/",
"wireless's":"/ˈwaɪɝləsɪz/",
"wireline":"/ˈwaɪɹˌlaɪn/",
"wireman":"/ˈwaɪɹmən/",
"wires":"/ˈwaɪɝz/, /ˈwaɪɹz/",
"wiretap":"/ˈwaɪɝˌtæp/",
"wiretapped":"/ˈwaɪɝˌtæpt/",
"wiretapping":"/ˈwaɪɝˌtæpɪŋ/",
"wiretaps":"/ˈwaɪɹˌtæps/",
"wirick":"/ˈwɪɹɪk/",
"wiring":"/ˈwaɪɹɪŋ/",
"wirkkala":"/vɝˈkɑlə/",
"wirkus":"/ˈwɝkɪs/",
"wirsing":"/ˈwɝsɪŋ/",
"wirt":"/ˈwɝt/",
"wirtanen":"/ˈwɝtənən/",
"wirth":"/ˈwɝθ/",
"wirthlin":"/ˈwɝθlɪn/",
"wirtz":"/ˈwɝts/",
"wiry":"/ˈwɪɹi/",
"wirz":"/ˈwɝz/",
"wis":"/ˈwɪs/",
"wisby":"/ˈwɪsbi/",
"wisch":"/ˈwɪʃ/",
"wischmeyer":"/ˈwɪʃmaɪɝ/",
"wisconsin":"/wɪˈskɑnsən/",
"wisconsin's":"/wɪˈskɑnsənz/",
"wisdom":"/ˈwɪzdəm/",
"wise":"/ˈwaɪz/",
"wisecarver":"/ˈwaɪzˌkɑɹvɝ/",
"wisecrack":"/ˈwaɪzˌkɹæk/",
"wisecracking":"/ˈwaɪzˌkɹækɪŋ/",
"wisecracks":"/ˈwaɪzˌkɹæks/",
"wisecup":"/ˈwaɪzˌkəp/",
"wised":"/ˈwaɪzd/",
"wiseguy":"/ˈwaɪzˌɡaɪ/",
"wisehart":"/ˈwaɪzˌhɑɹt/",
"wisel":"/ˈwaɪzəl/",
"wiseley":"/ˈwaɪzli/, /ˈwɪsɪli/",
"wisely":"/ˈwaɪzli/",
"wiseman":"/ˈwaɪzmən/",
"wisenbaker":"/ˈwaɪzənˌbeɪkɝ/",
"wisener":"/ˈwɪsinɝ/",
"wiser":"/ˈwaɪzɝ/",
"wisest":"/ˈwaɪzəst/",
"wish":"/ˈwɪʃ/",
"wisham":"/ˈwɪʃəm/",
"wishard":"/ˈwɪʃɝd/",
"wishart":"/ˈwɪˌʃɑɹt/",
"wishbone":"/ˈwɪʃˌboʊn/",
"wished":"/ˈwɪʃt/",
"wisher":"/ˈwɪʃɝ/",
"wishers":"/ˈwɪʃɝz/",
"wishes":"/ˈwɪʃɪz/",
"wishful":"/ˈwɪʃfəl/",
"wishfully":"/ˈwɪʃfəli/",
"wishing":"/ˈwɪʃɪŋ/",
"wishlist":"/ˈwɪʃlɪst/",
"wishner":"/ˈwɪʃnɝ/",
"wishnick":"/ˈwɪʃnɪk/",
"wishon":"/ˈwɪʃən/",
"wishy":"/ˈwɪʃi/",
"wisinski":"/vɪˈsɪnski/",
"wisler":"/ˈwɪsəlɝ/, /ˈwɪslɝ/",
"wisley":"/ˈwɪzli/",
"wisman":"/ˈwɪzmən/",
"wismer":"/ˈwɪzəmɝ/",
"wisner":"/ˈwɪsnɝ/",
"wisneski":"/vɪsˈnɛski/",
"wisnewski":"/vɪsˈnɛfski/",
"wisnieski":"/vɪsˈniski/",
"wisniewski":"/wɪzniˈɛfski/",
"wisor":"/ˈwaɪzɝ/",
"wisp":"/ˈwɪsp/",
"wispy":"/ˈwɪspi/",
"wiss":"/ˈwɪs/",
"wissa":"/ˈwɪsə/",
"wissel":"/ˈwɪsəl/",
"wisser":"/ˈwɪsɝ/",
"wissing":"/ˈwɪsɪŋ/",
"wissinger":"/ˈwɪsɪŋɝ/",
"wissink":"/ˈwɪsɪŋk/",
"wissler":"/ˈwɪslɝ/",
"wissman":"/ˈwɪsmən/",
"wissmann":"/ˈwɪsmən/",
"wissner":"/ˈwɪsnɝ/",
"wist":"/ˈwɪst/",
"wistful":"/ˈwɪstfəl/",
"wistfully":"/ˈwɪstfəli/",
"wistfulness":"/ˈwɪstfəlnəs/",
"wiswell":"/ˈwɪswɛl/",
"wisz":"/ˈvɪʃ/",
"wit":"/ˈwɪt/",
"wit's":"/ˈwɪts/",
"witbeck":"/ˈwɪtˌbɛk/",
"witbrock":"/ˈwɪtˌbɹɔk/",
"witch":"/ˈwɪtʃ/",
"witch's":"/ˈwɪtʃɪz/",
"witchcraft":"/ˈwɪtʃˌkɹæft/",
"witcher":"/ˈwɪtʃɝ/",
"witches":"/ˈwɪtʃəz/, /ˈwɪtʃɪz/",
"witchey":"/ˈwɪtʃi/",
"witchhunt":"/ˈwɪtʃˌhənt/",
"witching":"/ˈwɪtʃɪŋ/",
"witchy":"/ˈwɪtʃi/",
"witco":"/ˈwɪtkoʊ/",
"witczak":"/ˈvɪttʃæk/",
"witek":"/ˈvɪtɛk/",
"with":"/ˈwɪð/, /ˈwɪθ/, /wɪð/, /wɪθ/",
"witham":"/ˈwɪθəm/",
"withdraw":"/wɪðˈdɹɔ/, /wɪθˈdɹɔ/",
"withdrawal":"/wɪðˈdɹɔəl/, /wɪθˈdɹɔəl/",
"withdrawals":"/wɪðˈdɹɔəlz/, /wɪθˈdɹɔəlz/",
"withdrawing":"/wɪðˈdɹɔɪŋ/, /wɪθˈdɹɔɪŋ/",
"withdrawn":"/wɪðˈdɹɔn/, /wɪθˈdɹɔn/",
"withdraws":"/wɪðˈdɹɔz/, /wɪθˈdɹɔz/",
"withdrew":"/wɪðˈdɹu/, /wɪθˈdɹu/",
"withe":"/ˈwɪθ/",
"withee":"/ˈwɪˈθi/",
"withem":"/ˈwɪθɪm/",
"wither":"/ˈwɪðɝ/",
"withered":"/ˈwɪðɝd/",
"witherell":"/ˈwɪθɝəl/",
"withering":"/ˈwɪðɝɪŋ/",
"witherington":"/ˈwɪθɝɪŋtən/",
"witherow":"/ˈwɪθɝoʊ/",
"withers":"/ˈwɪðɝz/",
"witherspoon":"/ˈwɪðɝˌspun/",
"withey":"/ˈwɪθi/",
"withheld":"/wɪθˈhɛld/",
"withhold":"/wɪθˈhoʊld/",
"withholding":"/wɪθˈhoʊldɪŋ/",
"withholds":"/ˈwɪθˌhoʊldz/",
"within":"/wɪˈðɪn/, /wɪˈθɪn/",
"withington":"/ˈwɪθɪŋtən/",
"withnail":"/wɪθˈneɪl/",
"without":"/wɪˈðaʊt/, /wɪˈθaʊt/",
"withrow":"/ˈwɪˌθɹoʊ/",
"withstand":"/wɪθˈstænd/",
"withstanding":"/wɪθˈstændɪŋ/",
"withstands":"/wɪθˈstændz/",
"withstood":"/wɪθˈstʊd/",
"witkin":"/ˈwɪtˌkɪn/",
"witkop":"/ˈwɪtkəp/",
"witkowski":"/vɪtˈkɔfski/",
"witless":"/ˈwɪtləs/",
"witman":"/ˈwɪtmən/",
"witmer":"/ˈwɪtmɝ/",
"witness":"/ˈwɪtnəs/",
"witness'":"/ˈwɪtnəs/",
"witness's":"/ˈwɪtnəsɪz/",
"witnessed":"/ˈwɪtnəst/",
"witnesses":"/ˈwɪtnəsəz/, /ˈwɪtnəsɪz/",
"witnesses'":"/ˈwɪtnəsɪz/",
"witnessing":"/ˈwɪtnəsɪŋ/",
"witowski":"/vɪˈtɔfski/",
"wits":"/ˈwɪts/",
"witt":"/ˈwɪt/",
"witte":"/ˈwɪt/",
"witted":"/ˈwɪtɪd/",
"wittekind":"/ˈwɪtɪkɪnd/",
"witteman":"/ˈwɪtmən/",
"witten":"/ˈwɪtən/",
"wittenauer":"/ˈwɪtɪnaʊɝ/",
"wittenberg":"/ˈwɪtənbɝɡ/",
"wittenborn":"/ˈwɪtɪnbɝn/",
"wittenburg":"/ˈwɪtənbɝɡ/",
"wittenmyer":"/ˈwɪtɪnmaɪɝ/, /ˈwɪtɪnmiɝ/",
"witter":"/ˈwɪtɝ/",
"witter's":"/ˈwɪtɝz/",
"witters":"/ˈwɪtɝz/",
"witthuhn":"/ˈwɪθən/",
"wittig":"/ˈwɪtɪɡ/",
"wittily":"/ˈwɪtəli/",
"witting":"/ˈwɪtɪŋ/",
"wittingly":"/ˈwɪtɪŋli/",
"wittke":"/ˈwɪtki/",
"wittkopp":"/ˈwɪtkəp/",
"wittler":"/ˈwɪtlɝ/",
"wittman":"/ˈwɪtmən/",
"wittmann":"/ˈwɪtmən/",
"wittmer":"/ˈwɪtmɝ/",
"wittmeyer":"/ˈwɪtmaɪɝ/",
"wittner":"/ˈwɪtnɝ/",
"witton":"/ˈwɪtən/",
"wittrock":"/ˈwɪtɹək/",
"witts":"/ˈwɪts/",
"wittwer":"/ˈwɪtwɝ/",
"witty":"/ˈwɪti/",
"witucki":"/wɪˈtəki/",
"witwatersrand":"/ˈwɪtˌwɔtɝsɹænd/",
"witwer":"/ˈwɪtwɝ/",
"witz":"/ˈwɪts/",
"witzel":"/ˈwɪtzəl/",
"witzig":"/ˈwɪtzɪɡ/",
"witzke":"/ˈwɪtski/",
"wives":"/ˈwaɪvz/",
"wives'":"/ˈwaɪvz/",
"wix":"/ˈwɪks/",
"wixom":"/ˈwɪksəm/",
"wixon":"/ˈwɪksən/",
"wixson":"/ˈwɪksən/",
"wixted":"/ˈwɪkstɪd/",
"wiz":"/ˈhwɪz/, /ˈwɪz/",
"wizard":"/ˈwɪzɝd/",
"wizardry":"/ˈwɪzɝdɹi/",
"wizards":"/ˈwɪzɝdz/",
"wizen":"/ˈwaɪzən/",
"wizened":"/ˈwaɪzənd/",
"wlodarczyk":"/wəˈlɑdɝtʃɪk/",
"wlodarski":"/wələˈdɑɹski/",
"wm":"/ˈdəbəjuˈɛm/, /ˈwɪljəm/",
"wnek":"/ˈwnɛk/",
"wnuk":"/ˈwnək/",
"wo":"/ˈhwoʊ/, /ˈwoʊ/",
"wobbe":"/ˈwɑb/",
"wobble":"/ˈwɑbəl/",
"wobbled":"/ˈwɑbəld/",
"wobbling":"/ˈwɑbəlɪŋ/, /ˈwɑblɪŋ/",
"wobbly":"/ˈwɑbəli/",
"wobegon":"/ˈwoʊbəɡɑn/",
"wobig":"/ˈwoʊbɪɡ/",
"wobst":"/ˈwɑbst/",
"woburn":"/ˈwubɝn/",
"wodel":"/ˈwɔdəl/",
"woe":"/ˈwoʊ/",
"woebegone":"/ˈwoʊbɪˌɡɔn/",
"woeful":"/ˈwoʊfəl/",
"woefully":"/ˈwoʊfəli/",
"woehl":"/ˈwoʊl/",
"woehler":"/ˈwoʊlɝ/",
"woehr":"/ˈwɔɹ/",
"woehrle":"/ˈwɔɹəl/",
"woelfel":"/ˈwoʊlfəl/",
"woelfle":"/ˈwoʊlfəl/",
"woerner":"/ˈwɔɹnɝ/",
"woes":"/ˈwoʊz/",
"woessner":"/ˈwoʊsnɝ/",
"woeste":"/ˈwoʊst/",
"wofford":"/ˈwɑfɝd/",
"wofford's":"/ˈwɑfɝdz/",
"wogan":"/ˈwoʊɡən/",
"woggle":"/ˈwɔɡəl/",
"wogoman":"/ˈwoʊɡoʊmən/",
"wohl":"/ˈwoʊl/",
"wohler":"/ˈwoʊlɝ/",
"wohlers":"/ˈwoʊlɝz/",
"wohlfarth":"/ˈwoʊlˌfɑɹθ/",
"wohlfeil":"/ˈwoʊlˌfaɪl/",
"wohlford":"/ˈwoʊlfɝd/",
"wohlgemuth":"/ˈwoʊlɡəmuθ/",
"wohlstetter":"/ˈwoʊlˌstɛtɝ/",
"wohlwend":"/ˈwoʊlwɛnd/",
"woitschatzke":"/ˌwɔɪˈtʃætˌski/",
"wojahn":"/ˈwoʊhɑn/",
"wojciak":"/ˈwɔɪtʃiæk/",
"wojcicki":"/ˌwɔɪˈtʃɪtski/",
"wojciech":"/ˈvɔɪtʃɛk/, /ˈwɔɪtʃɛk/",
"wojciechowski":"/wɔɪtʃɪˈhɔfski/",
"wojcik":"/ˈwɔɪtʃɪk/",
"wojdyla":"/ˌwɔɪˈdɪlə/",
"wojick":"/ˈwɔɪtʃɪk/",
"wojnar":"/ˈwɔɪnɝ/",
"wojnarowski":"/ˌwɔɪnɝˈaʊski/",
"wojnilower":"/ˈwɔɪnəˌloʊɝ/",
"wojnowski":"/ˌwɔɪˈnaʊski/",
"wojtas":"/ˈwɔɪtəs/",
"wojtaszek":"/ˌwɔɪˈtɑʃɛk/",
"wojtkiewicz":"/ˈwɔɪtkəvɪtʃ/",
"wojtkowski":"/ˌwɔɪtˈkaʊski/",
"wojtowicz":"/ˈwɔɪtəvɪtʃ/",
"wok":"/ˈwɑk/",
"woke":"/ˈwoʊk/",
"woken":"/ˈwoʊkən/",
"woks":"/ˈwɑks/",
"wola":"/ˈwoʊlə/",
"wolak":"/ˈwoʊlək/",
"wolanin":"/ˈwɑlənɪn/",
"wolanski":"/vəˈlænski/",
"wolaver":"/ˈwɑləvɝ/",
"wolber":"/ˈwoʊlbɝ/",
"wolbert":"/ˈwoʊlbɝt/",
"wolcott":"/ˈwoʊlkət/",
"wold":"/ˈwoʊld/",
"wolden":"/ˈwoʊldən/",
"woldt":"/ˈwoʊlt/",
"wolenzac":"/ˈwoʊlənˌzæk/",
"wolenzac's":"/ˈwoʊlənˌzæks/",
"wolf":"/ˈwʊlf/",
"wolf's":"/ˈwʊlfs/",
"wolf-dog":"/ˈwʊlfˌdɔɡ/",
"wolfarth":"/ˈwʊlfɑɹθ/",
"wolfe":"/ˈwʊlf/",
"wolfe's":"/ˈwʊlfs/",
"wolfenbarger":"/ˈwʊlfɪnbɑɹɡɝ/",
"wolfenden":"/ˈwʊlˌfɛndən/",
"wolfenschmidt":"/ˈwʊlfənʃˌmɪt/",
"wolfensohn":"/ˈwʊlfənsən/",
"wolfenstein":"/ˈwʊlfənˌstaɪn/",
"wolfer":"/ˈwʊlfɝ/",
"wolfert":"/ˈwʊlfɝt/",
"wolff":"/ˈwʊlf/",
"wolfgang":"/ˈwʊlfˌɡæŋ/",
"wolfgram":"/ˈwʊlfˌɡɹæm/",
"wolfinbarger":"/ˈwʊlfɪnˌbɑɹɡɝ/",
"wolfing":"/ˈwʊlˌfɪŋ/",
"wolfinger":"/ˈwʊlfɪˌŋɝ/",
"wolfley":"/ˈwʊlfli/",
"wolfman":"/ˈwʊlfmən/",
"wolford":"/ˈwoʊlfɝd/",
"wolfram":"/ˈwʊlˌfɹæm/",
"wolfrey":"/ˈwʊlfɹi/",
"wolfrom":"/ˈwʊlfɹəm/",
"wolfrum":"/ˈwʊlfɹəm/",
"wolfsburg":"/ˈwʊlfsbɝɡ/",
"wolfson":"/ˈwʊlfsən/",
"wolgamott":"/ˈwoʊlɡəmɑt/",
"wolgast":"/ˈwoʊlɡəst/",
"wolgemuth":"/ˈwoʊlɡɪmuθ/",
"wolin":"/ˈwoʊlɪn/",
"wolinski":"/vəˈlɪnski/",
"wolinsky":"/vəˈlɪnski/",
"wolitarsky":"/ˌwoʊlɪˈtɑɹski/",
"wolk":"/ˈwoʊk/",
"wolkanczik":"/wəlˈkæŋkzɪk/",
"wolkanczik's":"/wəlˈkæŋkzɪks/",
"wolke":"/ˈwoʊlk/",
"wolken":"/ˈwɔlkən/",
"wolkoff":"/ˈwoʊlkɔf/",
"woll":"/ˈwɑl/",
"wollack":"/ˈwɑlək/",
"wollaeger":"/wəˈleɪɡɝ/",
"wollam":"/ˈwɑləm/",
"wollard":"/ˈwɑlɝd/",
"wolle":"/ˈwɑl/",
"wollen":"/ˈwɑlən/",
"wollenberg":"/ˈwɑlənbɝɡ/",
"wollenweber":"/ˈwɑlɪnwɪbɝ/",
"woller":"/ˈwɑlɝ/",
"wollin":"/ˈwɑlɪn/",
"wollman":"/ˈwɑlmən/",
"wollner":"/ˈwɑlnɝ/",
"wollschlager":"/ˈwɑlʃleɪɡɝ/",
"wolman":"/ˈwɑlmən/",
"wolohan":"/ˈwɑləhæn/",
"woloszyn":"/vəˈlɑʃɪn/",
"wolpe":"/ˈwoʊlpi/",
"wolper":"/ˈwoʊlpɝ/",
"wolpert":"/ˈwoʊlpɝt/",
"wolrath":"/ˈwoʊlˌɹæθ/",
"wolsey":"/ˈwoʊlsi/",
"wolsfeld":"/ˈwoʊlzˌfɛld/",
"wolske":"/ˈwoʊlsk/",
"wolski":"/ˈvoʊlski/",
"wolsky":"/ˈvoʊlski/",
"wolstenholme":"/ˈwoʊlstɪnhoʊlm/",
"wolter":"/ˈwoʊltɝ/",
"wolters":"/ˈwoʊltɝz/",
"woltman":"/ˈwoʊltmən/",
"woltz":"/ˈwoʊlts/",
"wolven":"/ˈwʊlvən/",
"wolverine":"/ˌwʊlvɝˈin/",
"wolverine's":"/ˌwʊlvɝˈinz/",
"wolverton":"/wʊlˈvɝtən/",
"wolves":"/ˈwʊlvz/",
"wolz":"/ˈwoʊlz/",
"womac":"/ˈwoʊmək/",
"womack":"/ˈwoʊmæk/",
"woman":"/ˈwʊmən/",
"woman's":"/ˈwʊmənz/",
"womanhood":"/ˈwʊmənˌhʊd/",
"womanize":"/ˈwʊməˌnaɪz/",
"womanizer":"/ˈwʊməˌnaɪzɝ/",
"womanizing":"/ˈwʊməˌnaɪzɪŋ/",
"womb":"/ˈwum/",
"wombacher":"/ˈwɑmˌbɑkɝ/",
"wombat":"/ˈwɑmˌbæt/",
"wombats":"/ˈwɑmˌbæts/",
"womble":"/ˈwɑmbəl/",
"wombles":"/ˈwɑmbəlz/",
"women":"/ˈwɪmən/",
"women's":"/ˈwɪmənz/",
"womens'":"/ˈwɪmənz/",
"womer":"/ˈwoʊmɝ/",
"wometco":"/woʊˈmɛtkoʊ/",
"wommack":"/ˈwɑmək/",
"won":"/wʌn/",
"won't":"/ˈwoʊnt/",
"wond":"/ˈwɔnd/",
"wonda":"/ˈwɑndə/",
"wonder":"/ˈwʌn.dɚ/",
"wonder's":"/ˈwəndɝz/",
"wondered":"/ˈwəndɝd/",
"wonderful":"/ˈwəndɝfəl/",
"wonderfully":"/ˈwəndɝfəli/, /ˈwəndɝfli/",
"wonderfulness":"/ˈwəndɝfəlnəs/",
"wondering":"/ˈwəndɝɪŋ/",
"wonderland":"/ˈwəndɝˌlænd/",
"wonderly":"/ˈwəndɝli/",
"wonderment":"/ˈwəndɝmənt/",
"wonders":"/ˈwəndɝz/",
"wondra":"/ˈwɑndɹə/",
"wondrous":"/ˈwəndɹəs/",
"wong":"/ˈwɔŋ/",
"wong's":"/ˈwɔŋz/",
"wonk":"/ˈwɑnk/",
"wonks":"/ˈwɑnks/",
"wonksahachee":"/wɑnksəˈhætʃi/",
"wonnacott":"/ˈwənəkɑt/",
"wont":"/ˈwoʊnt/",
"woo":"/ˈwu/",
"woo's":"/ˈwuz/",
"wood":"/ˈwʊd/",
"wood's":"/ˈwʊdz/",
"woodall":"/ˈwʊˌdɔl/",
"woodard":"/ˈwʊdɝd/",
"woodbeck":"/ˈwʊdˌbɛk/",
"woodberry":"/ˈwʊdˌbɛɹi/",
"woodbridge":"/ˈwʊdˌbɹɪdʒ/",
"woodburn":"/ˈwʊdˌbɝn/",
"woodbury":"/ˈwʊdˌbɛɹi/",
"woodby":"/ˈwʊdbi/",
"woodcarver":"/ˈwʊdˌkɑɹvɝ/",
"woodcarvers":"/ˈwʊdˌkɑɹvɝz/",
"woodchip":"/ˈwʊdˌtʃɪp/",
"woodchips":"/ˈwʊdˌtʃɪps/",
"woodchuck":"/ˈwʊdˌtʃək/",
"woodchucks":"/ˈwʊdˌtʃəks/",
"woodcliff":"/ˈwʊdˌklɪf/",
"woodcock":"/ˈwʊdˌkɑk/",
"woodcox":"/ˈwʊdˌkɑks/",
"wooddell":"/ˈwʊdəl/",
"wooded":"/ˈwʊdɪd/",
"woodell":"/ˈwʊdəl/",
"wooden":"/ˈwʊdən/",
"woodfield":"/ˈwʊdˌfild/",
"woodfill":"/ˈwʊdˌfɪl/",
"woodfin":"/ˈwʊdfɪn/",
"woodford":"/ˈwʊdfɝd/",
"woodfork":"/ˈwʊdfɝk/",
"woodhall":"/ˈwʊdˌhɔl/",
"woodham":"/ˈwʊdhəm/",
"woodhams":"/ˈwʊdhəmz/",
"woodhead":"/ˈwʊdˌhɛd/",
"woodhouse":"/ˈwʊdˌhaʊs/",
"woodhull":"/ˈwʊdˌhəl/",
"woodie":"/ˈwʊdi/",
"woodin":"/ˈwʊdɪn/",
"wooding":"/ˈwʊdɪŋ/",
"woodington":"/ˈwʊdɪŋtən/",
"woodis":"/ˈwʊdɪs/",
"woodke":"/ˈwʊdki/",
"woodland":"/ˈwʊdˌlænd/, /ˈwʊdlənd/",
"woodland's":"/ˈwʊdˌlændz/",
"woodlands":"/ˈwʊdˌlændz/, /ˈwʊdləndz/",
"woodle":"/ˈwʊdəl/",
"woodlee":"/ˈwʊdˌli/",
"woodley":"/ˈwʊdli/",
"woodlief":"/ˈwʊdˌlif/",
"woodliff":"/ˈwʊdlɪf/",
"woodling":"/ˈwʊdlɪŋ/",
"woodlock":"/ˈwʊdˌlɑk/",
"woodlot":"/ˈwʊdˌlɑt/",
"woodmac":"/ˈwʊdmæk/",
"woodman":"/ˈwʊdmən/",
"woodmansee":"/wʊdmənˈsi/",
"woodpecker":"/ˈwʊdˌpɛkɝ/",
"woodpeckers":"/ˈwʊdˌpɛkɝz/",
"woodpile":"/ˈwʊdpaɪl/",
"woodpiles":"/ˈwʊdpaɪlz/",
"woodrich":"/ˈwʊˌdɹɪtʃ/",
"woodrick":"/ˈwʊdɹɪk/",
"woodring":"/ˈwʊˌdɹɪŋ/",
"woodrome":"/ˈwʊdɹəm/",
"woodroof":"/ˈwʊˌdɹuf/",
"woodrow":"/ˈwʊˌdɹoʊ/",
"woodruff":"/ˈwʊdɹəf/",
"woodrum":"/ˈwʊdɹəm/",
"woods":"/ˈwʊdz/",
"woods's":"/ˈwʊdzɪz/",
"woodshed":"/ˈwʊdˌʃɛd/",
"woodsheds":"/ˈwʊdˌʃɛdz/",
"woodside":"/ˈwʊdˌsaɪd/",
"woodsmall":"/ˈwʊdsˌmɔl/",
"woodsman":"/ˈwʊdzmæn/",
"woodsmen":"/ˈwʊdzmən/",
"woodsmen's":"/ˈwʊdzmənz/",
"woodson":"/ˈwʊdsən/",
"woodson's":"/ˈwʊdsənz/",
"woodstock":"/ˈwʊdˌstɑk/",
"woodstream":"/ˈwʊdˌstɹim/",
"woodward":"/ˈwʊdˌwɔɹd/, /ˈwʊdwɝd/",
"woodward's":"/ˈwʊdwɝdz/",
"woodwind":"/ˈwʊdˌwɪnd/",
"woodwind's":"/ˈwʊdˌwɪndz/",
"woodwinds":"/ˈwʊdˌwɪndz/",
"woodwork":"/ˈwʊdˌwɝk/",
"woodworker":"/ˈwʊdˌwɝkɝ/",
"woodworkers":"/ˈwʊdˌwɝkɝz/",
"woodworking":"/ˈwʊdˌwɝkɪŋ/",
"woodworth":"/ˈwʊdˌwɝθ/",
"woody":"/ˈwʊdi/",
"woody's":"/ˈwʊdiz/",
"woodyard":"/ˈwʊdˌjɑɹd/",
"wooed":"/ˈwud/",
"woof":"/ˈwuf/",
"woofer":"/ˈwʊfɝ/",
"woofers":"/ˈwʊfɝz/",
"woofter":"/ˈwuftɝ/",
"woogie":"/ˈwuɡi/, /ˈwʊɡi/",
"wooing":"/ˈwuɪŋ/",
"wool":"/ˈwʊl/",
"woolard":"/ˈwʊlɝd/",
"woolbright":"/ˈwʊlˌbɹaɪt/",
"woolco":"/ˈwʊlˌkoʊ/",
"woolcock":"/ˈwʊlˌkɑk/",
"wooldridge":"/ˈwʊldɹɪdʒ/",
"woolen":"/ˈwʊlən/",
"woolens":"/ˈwʊlənz/",
"woolery":"/ˈwʊlɝi/",
"woolever":"/ˈwʊˌlɛvɝ/",
"wooley":"/ˈwʊli/",
"woolf":"/ˈwʊlf/",
"woolfolk":"/ˈwʊlˌfoʊk/",
"woolford":"/ˈwʊlfɝd/",
"woolfork":"/ˈwʊlˌfɔɹk/",
"woollard":"/ˈwʊlɝd/",
"woollcott":"/ˈwʊlkɑt/",
"woollen":"/ˈwʊlən/",
"woolley":"/ˈwʊli/",
"woolly":"/ˈwʊli/",
"woolman":"/ˈwʊlmən/",
"woolridge":"/ˈwʊlˌɹɪdʒ/",
"wools":"/ˈwʊlz/",
"woolsey":"/ˈwʊlzi/",
"woolsey's":"/ˈwʊlziz/",
"woolson":"/ˈwʊlsən/",
"woolston":"/ˈwʊlstən/",
"woolum":"/ˈwʊləm/",
"woolums":"/ˈwʊləmz/",
"woolverton":"/ˈwʊlvɝtən/",
"woolwine":"/ˈwʊlˌwaɪn/",
"woolworth":"/ˈwʊlˌwɝθ/",
"woolworth's":"/ˈwʊlˌwɝθs/",
"wooly":"/ˈwʊli/",
"woomer":"/ˈwumɝ/",
"woong":"/ˈwuŋ/",
"woos":"/ˈwuz/",
"woosley":"/ˈwuzli/",
"wooster":"/ˈwustɝ/",
"wootan":"/ˈwutən/",
"wooten":"/ˈwutən/",
"wooters":"/ˈwutɝz/",
"wooton":"/ˈwutən/",
"wootten":"/ˈwutən/",
"wootton":"/ˈwutən/",
"woozy":"/ˈwuzi/",
"wop":"/ˈwɑp/",
"wops":"/ˈwɑps/",
"wor":"/ˈdəbəˈjuˈoʊˈɑɹ/, /ˈdəbɛlˈjuˈoʊˈɑɹ/, /ˈwɔɹ/",
"worcester":"/ˈwʊstɝ/",
"worcestershire":"/ˈwʊstəʃɝ/",
"word":"/ˈwɝd/",
"word's":"/ˈwɝdz/",
"worded":"/ˈwɝdɪd/",
"wordell":"/ˈwɝdəl/",
"worden":"/ˈwɝdən/",
"wording":"/ˈwɝdɪŋ/",
"wordless":"/ˈwɝdləs/",
"wordperfect":"/ˈwɝdˈpɝfɛkt/",
"wordpress":"/ˈwɝdpɹɪs/",
"words":"/ˈwɝdz/",
"words'":"/ˈwɝdz/",
"wordsmith":"/ˈwɝdsˌmɪθ/",
"wordstar":"/ˈwɝdˌstɑɹ/",
"wordsworth":"/ˈwɝdzwɝθ/",
"wordy":"/ˈwɝdi/",
"wore":"/ˈwɔɹ/",
"work":"/ˈwɝk/",
"work's":"/ˈwɝks/",
"workable":"/ˈwɝkəbəl/",
"workaday":"/ˈwɝkəˌdeɪ/",
"workaholic":"/ˌwɝkəˈhɑlɪk/",
"workaholics":"/ˌwɝkəˈhɑlɪks/",
"workaround":"/ˈwɝkɝˈaʊnd/",
"workbench":"/ˈwɝkˌbɛntʃ/",
"workbook":"/ˈwɝkˌbʊk/",
"workbooks":"/ˈwɝkˌbʊks/",
"workday":"/ˈwɝkˌdeɪ/",
"workdays":"/ˈwɝkˌdeɪz/",
"worked":"/ˈwɝkt/",
"worker":"/ˈwɝkɝ/",
"worker's":"/ˈwɝkɝz/",
"workers":"/ˈwɝkɝz/",
"workers'":"/ˈwɝkɝz/",
"workfare":"/ˈwɝkˌfɛɹ/",
"workflow":"/ˈwɝkˌfloʊ/",
"workflows":"/ˈwɝkˌfloʊz/",
"workforce":"/ˈwɝkˌfɔɹs/",
"workgroup":"/ˈwɝkˌɡɹup/",
"workgroups":"/ˈwɝkˌɡɹups/",
"workhorse":"/ˈwɝkˌhɔɹs/",
"workhorses":"/ˈwɝkˌhɔɹsɪz/",
"workin'":"/ˈwɝkən/",
"working":"/ˈwɝkɪŋ/",
"workinger":"/ˈwɝkɪŋɝ/",
"workings":"/ˈwɝkɪŋz/",
"workload":"/ˈwɝˌkloʊd/",
"workloads":"/ˈwɝˌkloʊdz/",
"workman":"/ˈwɝkmən/",
"workman's":"/ˈwɝkmənz/",
"workmanlike":"/ˈwɝkˌmænˌlaɪk/",
"workmanship":"/ˈwɝkmənˌʃɪp/",
"workmen":"/ˈwɝkmɪn/",
"workmen's":"/ˈwɝkmənz/",
"workout":"/ˈwɝˌkaʊt/",
"workouts":"/ˈwɝˌkaʊts/",
"workplace":"/ˈwɝkˌpleɪs/",
"workplaces":"/ˈwɝkˌpleɪsɪz/",
"workroom":"/ˈwɝˌkɹum/",
"works":"/ˈwɝks/",
"works'":"/ˈwɝks/",
"worksheet":"/ˈwɝkˌʃit/",
"worksheets":"/ˈwɝkˌʃits/",
"workshop":"/ˈwɝkˌʃɑp/",
"workshops":"/ˈwɝkˌʃɑps/",
"workspace":"/ˈwɝkˌspeɪs/",
"workstation":"/ˈwɝkˌsteɪʃən/",
"workstations":"/ˈwɝkˌsteɪʃənz/",
"workweek":"/ˈwɝˌkwik/",
"workweeks":"/ˈwɝˌkwiks/",
"worland":"/ˈwɝlənd/",
"worlco":"/ˈwɝlkoʊ/",
"world":"/ˈwɝld/",
"world's":"/ˈwɝldz/",
"world-class":"/ˈwɝldˌklæs/",
"worldcom":"/ˈwɝldˌkɑm/",
"worldcorp":"/ˈwɝldˌkɔɹp/",
"worlder":"/ˈwɝldɝ/",
"worlders":"/ˈwɝldɝz/",
"worldliness":"/ˈwɝldlinəs/",
"worldly":"/ˈwɝldli/",
"worldnews":"/ˈwɝldˈnuz/",
"worldpass":"/ˈwɝldˌpæs/",
"worlds":"/ˈwɝldz/",
"worldscope":"/ˈwɝldˌskoʊp/",
"worldspan":"/ˈwɝldˌspæn/",
"worldview":"/ˈwɝldˌvju/",
"worldvision":"/ˈwɝldˌvɪʒən/",
"worldwide":"/ˈwɝldˈwaɪd/",
"worldwide's":"/ˈwɝldˌwaɪdz/",
"worley":"/ˈwɝli/",
"worm":"/ˈwɝm/",
"worm's":"/ˈwɝmz/",
"worman":"/ˈwɝmən/",
"wormhole":"/ˈwɝmˌhɔl/",
"wormholes":"/ˈwɝmˌhɔlz/",
"wormington":"/ˈwɝmɪŋtən/",
"wormley":"/ˈwɝmli/",
"wormlike":"/ˈwɝmˌlaɪk/",
"worms":"/ˈwɝmz/",
"wormser":"/ˈwɝmzɝ/",
"wormuth":"/ˈwɝmuθ/",
"wormwood":"/ˈwɝmˌwʊd/",
"worn":"/ˈwɔɹn/",
"worner":"/ˈwɔɹnɝ/",
"woronoff":"/ˈwɔɹənɔf/",
"worrall":"/ˈwɝɹəl/",
"worrel":"/ˈwɝɹəl/",
"worrell":"/ˈwɝɹəl/",
"worried":"/ˈwɝid/",
"worrier":"/ˈwɝiɝ/",
"worriers":"/ˈwɝiɝz/",
"worries":"/ˈwɝiz/",
"worrisome":"/ˈwɝisəm/",
"worry":"/ˈwɝi/",
"worrying":"/ˈwɝiɪŋ/",
"worse":"/ˈwɝs/",
"worseck":"/ˈwɝsɛk/, /ˈwɔɹsɛk/",
"worsen":"/ˈwɝsən/",
"worsened":"/ˈwɝsənd/",
"worsening":"/ˈwɝsənɪŋ/, /ˈwɝsnɪŋ/",
"worsens":"/ˈwɝsənz/",
"worsham":"/ˈwɝʃəm/",
"worship":"/ˈwɝʃəp/, /ˈwɝʃɪp/",
"worshiped":"/ˈwɝʃɪpt/",
"worshiper":"/ˈwɝʃəpɝ/",
"worshipers":"/ˈwɝʃɪpɝz/",
"worshipful":"/ˈwɝʃəpfəl/",
"worshiping":"/ˈwɝʃəˌpɪŋ/",
"worshipped":"/ˈwɝʃəpt/",
"worshippers":"/ˈwɝʃɪpɝz/",
"worshipping":"/ˈwɝʃəpɪŋ/",
"worships":"/ˈwɝʃəps/",
"worsley":"/ˈwɝsli/",
"worst":"/ˈwɝst/",
"worst-case":"/ˈwɝstˈkeɪs/",
"worsted":"/ˈwɝstɪd/",
"worstell":"/ˈwɝstəl/",
"worster":"/ˈwɝstɝ/",
"worth":"/ˈwɝθ/",
"worth's":"/ˈwɝθs/",
"wortham":"/ˈwɝθəm/",
"worthen":"/ˈwɝθən/",
"worthen's":"/ˈwɝθənz/",
"worthey":"/ˈwɝði/",
"worthier":"/ˈwɝðiɝ/",
"worthies":"/ˈwɝðiz/",
"worthiest":"/ˈwɝðiəst/",
"worthiness":"/ˈwɝðinɪs/",
"worthing":"/ˈwɝθɪŋ/",
"worthington":"/ˈwɝðɪŋtən/",
"worthless":"/ˈwɝθləs/",
"worthley":"/ˈwɝθli/",
"worthman":"/ˈwɝθmən/",
"worthog":"/ˈwɔɹthɔɡ/",
"worths":"/ˈwɝθs/",
"worthwhile":"/ˈwɝθˈwaɪl/",
"worthy":"/ˈwɝði/",
"wortley":"/ˈwɝtli/",
"wortman":"/ˈwɝtmən/",
"wortmann":"/ˈwɝtmən/",
"worton":"/ˈwɝtən/",
"worts":"/ˈwɝts/",
"wotan":"/ˈwoʊtən/",
"wotherspoon":"/wəðɝˈspun/",
"wotring":"/ˈwɑtɝɪŋ/",
"wotton":"/ˈwɑtən/",
"wouk":"/ˈwoʊk/, /ˈwuk/",
"would":"/ˈwʊd/",
"would've":"/ˈwʊdəv/",
"wouldn't":"/ˈwʊdənt/",
"woulfe":"/ˈwaʊlf/",
"wound":"/ˈwaʊnd/, /ˈwund/",
"wounded":"/ˈwundɪd/",
"wounding":"/ˈwundɪŋ/",
"wounds":"/ˈwundz/",
"wouters":"/ˈwaʊtɝz/",
"wove":"/ˈwoʊv/",
"woven":"/ˈwoʊvən/",
"wow":"/ˈwaʊ/",
"wow's":"/ˈwaʊz/",
"wowed":"/ˈwaʊd/",
"wowie":"/ˈwaʊi/",
"wowing":"/ˈwaʊɪŋ/",
"wows":"/ˈwaʊz/",
"woy":"/ˈwɔɪ/",
"wozniak":"/ˈwɑzniæk/",
"woznick":"/ˈwɑznɪk/",
"woznicki":"/wəzˈnɪtski/",
"wozny":"/ˈwɑzni/",
"wrack":"/ˈɹæk/",
"wracked":"/ˈɹækt/",
"wracking":"/ˈɹækɪŋ/",
"wrage":"/ˈɹeɪdʒ/",
"wragg":"/ˈɹæɡ/",
"wrandell":"/ˈɹæŋdɛl/",
"wrangell":"/ˈɹæŋɡəl/",
"wrangle":"/ˈɹæŋɡəl/",
"wrangled":"/ˈɹæŋɡəld/",
"wrangler":"/ˈɹæŋɡəlɝ/, /ˈɹæŋɡlɝ/",
"wranglers":"/ˈɹæŋɡəlɝz/, /ˈɹæŋɡlɝz/",
"wrangles":"/ˈɹæŋɡəlz/",
"wrangling":"/ˈɹæŋɡəlɪŋ/, /ˈɹæŋɡlɪŋ/",
"wranglings":"/ˈɹæŋɡəlɪŋz/, /ˈɹæŋɡlɪŋz/",
"wrap":"/ˈɹæp/",
"wrapped":"/ˈɹæpt/",
"wrapper":"/ˈɹæpɝ/",
"wrappers":"/ˈɹæpɝz/",
"wrapping":"/ˈɹæpɪŋ/",
"wraps":"/ˈɹæps/",
"wrapup":"/ˈɹæpəp/",
"wrath":"/ˈɹæθ/",
"wrather":"/ˈɹæðɝ/",
"wray":"/ˈɹeɪ/",
"wreak":"/ˈɹik/",
"wreaked":"/ˈɹikt/",
"wreaking":"/ˈɹikɪŋ/",
"wreaks":"/ˈɹiks/",
"wreath":"/ˈɹiθ/",
"wreaths":"/ˈɹiðz/, /ˈɹiθs/",
"wreck":"/ˈɹɛk/",
"wreckage":"/ˈɹɛkədʒ/, /ˈɹɛkɪdʒ/",
"wrecked":"/ˈɹɛkt/",
"wrecker":"/ˈɹɛkɝ/",
"wrecking":"/ˈɹɛkɪŋ/",
"wrecks":"/ˈɹɛks/",
"wrede":"/ˈɹid/",
"wren":"/ˈɹɛn/",
"wrench":"/ˈɹɛntʃ/",
"wrenched":"/ˈɹɛntʃt/",
"wrenches":"/ˈɹɛntʃɪz/",
"wrenching":"/ˈɹɛntʃɪŋ/",
"wrenn":"/ˈɹɛn/",
"wrest":"/ˈɹɛst/",
"wrested":"/ˈɹɛstɪd/",
"wresting":"/ˈɹɛstɪŋ/",
"wrestle":"/ˈɹɛsəl/",
"wrestled":"/ˈɹɛsəld/",
"wrestler":"/ˈɹɛsəlɝ/, /ˈɹɛslɝ/",
"wrestlers":"/ˈɹɛsəlɝz/, /ˈɹɛslɝz/",
"wrestles":"/ˈɹɛsəlz/",
"wrestling":"/ˈɹɛsəlɪŋ/, /ˈɹɛslɪŋ/",
"wretch":"/ˈɹɛtʃ/",
"wretched":"/ˈɹɛtʃɪd/",
"wretchedly":"/ˈɹɛtʃɪdli/",
"wrice":"/ˈɹaɪs/",
"wriggle":"/ˈɹɪɡəl/",
"wright":"/ˈɹaɪt/",
"wright's":"/ˈɹaɪts/",
"wrights":"/ˈɹaɪts/",
"wrightsman":"/ˈɹaɪtsmən/",
"wrightson":"/ˈɹaɪtsən/",
"wrigley":"/ˈɹɪɡli/",
"wrigley's":"/ˈɹɪɡliz/",
"wring":"/ˈɹɪŋ/",
"wringer":"/ˈɹɪŋɝ/",
"wringing":"/ˈɹɪŋɪŋ/",
"wrinkle":"/ˈɹɪŋkəl/",
"wrinkled":"/ˈɹɪŋkəld/",
"wrinkles":"/ˈɹɪŋkəlz/",
"wrinkling":"/ˈɹɪŋkəlɪŋ/, /ˈɹɪŋklɪŋ/",
"wrisley":"/ˈɹɪzli/",
"wrist":"/ˈɹɪst/",
"wriston":"/ˈɹɪstən/",
"wrists":"/ˈɹɪsts/",
"wristwatch":"/ˈɹɪstˌwɑtʃ/",
"wristwatches":"/ˈɹɪstˌwɑtʃɪz/",
"writ":"/ˈɹɪt/",
"writable":"/ˈraɪdəbəl/",
"write":"/ˈɹaɪt/",
"writedown":"/ˈɹaɪtˌdaʊn/",
"writedowns":"/ˈɹaɪtˌdaʊnz/",
"writeoff":"/ˈɹaɪtɔf/",
"writeoffs":"/ˈɹaɪtɔfs/",
"writer":"/ˈɹaɪtɝ/",
"writer's":"/ˈɹaɪtɝz/",
"writers":"/ˈɹaɪtɝz/",
"writers'":"/ˈɹaɪtɝz/",
"writes":"/ˈɹaɪts/",
"writhe":"/ˈɹɪθ/",
"writhed":"/ˈɹɪθd/",
"writhing":"/ˈɹaɪðɪŋ/, /ˈɹɪθɪŋ/",
"writing":"/ˈɹaɪtɪŋ/",
"writings":"/ˈɹaɪtɪŋz/",
"writs":"/ˈɹɪts/",
"written":"/ˈɹɪtən/",
"wrobel":"/ˈɹoʊbəl/",
"wrobleski":"/ɹəˈblɛski/",
"wroblewski":"/ɹəˈblufski/",
"wroclaw":"/ˈɹɑˌklɔ/",
"wroe":"/ˈɹoʊ/",
"wrona":"/ˈɹoʊnə/",
"wrong":"/ˈɹɔŋ/",
"wrongdoer":"/ˈɹɔŋˈduɝ/",
"wrongdoers":"/ˈɹɔŋˈduɝz/",
"wrongdoing":"/ˈɹɔŋduɪŋ/",
"wrongdoings":"/ɹɔŋˈduɪŋz/",
"wronged":"/ˈɹɔŋd/",
"wrongful":"/ˈɹɔŋfəl/",
"wrongfully":"/ˈɹɔŋfəli/",
"wrongheaded":"/ˈɹɔŋˌhɛdɪd/",
"wrongly":"/ˈɹɔŋli/",
"wrongs":"/ˈɹɔŋz/",
"wronski":"/ˈɹɑnski/",
"wrote":"/ˈɹoʊt/",
"wroten":"/ˈɹoʊtən/",
"wrought":"/ˈɹɔt/",
"wrubel":"/ˈɹubəl/",
"wruck":"/ˈɹək/",
"wrung":"/ˈɹəŋ/",
"wry":"/ˈɹaɪ/",
"wrye":"/ˈɹaɪ/",
"wryly":"/ˈɹaɪli/",
"wryness":"/ˈɹaɪnəs/",
"wrzesinski":"/ɹəzɪˈsɪnski/",
"ws":"/ˈdəbəljuˈɛs/, /ˈdəbjəˈɛs/",
"wu":"/ˈwu/",
"wu's":"/ˈwuz/",
"wubben":"/ˈwəbən/",
"wuellner":"/ˈwʊlnɝ/",
"wuensch":"/ˈwʊnʃ/",
"wuerth":"/ˈwʊɹθ/",
"wuerttemberg":"/ˈwɝtəmbɝɡ/",
"wuertz":"/ˈwʊɹts/",
"wuest":"/ˈwuɪst/",
"wuhan":"/ˈwuən/",
"wujcik":"/ˈwədʒsɪk/",
"wulf":"/ˈwʊlf/",
"wulff":"/ˈwʊlf/",
"wuli":"/ˈwuli/",
"wuliger":"/ˈwulɪɡɝ/",
"wunder":"/ˈwəndɝ/",
"wunderkind":"/ˈwəndɝˌkaɪnd/, /ˈwəndɝˌkɪnd/",
"wunderle":"/ˈwəndɝli/",
"wunderlich":"/ˈwəndɝlɪk/",
"wunderlin":"/ˈwəndɝlɪn/",
"wunsch":"/ˈwənʃ/",
"wunschel":"/ˈwənʃəl/",
"wurdeman":"/ˈwɝdmən/",
"wurl":"/ˈwɝl/",
"wurlitzer":"/ˈwɝlɪtsɝ/",
"wurm":"/ˈwɝm/",
"wurst":"/ˈwɝst/",
"wurster":"/ˈwɝstɝ/",
"wursthaus":"/ˈwɝsthaʊs/",
"wurth":"/ˈwɝθ/",
"wurtman":"/ˈwɝtmən/",
"wurtz":"/ˈwɝts/",
"wurtzel":"/ˈwɝtzəl/",
"wurz":"/ˈwɝz/",
"wurzel":"/ˈwɝzəl/",
"wurzer":"/ˈwɝzɝ/",
"wuss":"/ˈwəs/",
"wussler":"/ˈwəslɝ/",
"wussow":"/ˈwəsoʊ/",
"wuthering":"/ˈwəðɝɪŋ/",
"wuthrich":"/ˈwəθɹɪk/",
"wuttke":"/ˈwətki/",
"wuxi":"/ˈwəksi/",
"wuyda":"/ˈwɔɪdə/",
"wuzzy":"/ˈwʊzi/",
"wy":"/ˈdəbəljuˈwaɪ/, /ˈweɪ/",
"wyan":"/ˈwaɪən/",
"wyand":"/ˈwaɪənd/",
"wyant":"/ˈwaɪənt/",
"wyatt":"/ˈwaɪət/",
"wyatt's":"/ˈwaɪəts/",
"wyble":"/ˈwaɪbəl/",
"wyborn":"/ˈvɪbɝn/",
"wyche":"/ˈwaɪtʃ/",
"wyckoff":"/ˈwɪkɔf/",
"wycliff":"/ˈwɪklɪf/",
"wycoff":"/ˈwɪkɔf/",
"wyden":"/ˈwaɪd/, /ˈwaɪdən/",
"wydra":"/ˈwaɪdɹə/",
"wye":"/ˈwaɪ/",
"wyer":"/ˈwaɪɝ/",
"wyers":"/ˈwaɪɝz/",
"wyeth":"/ˈwaɪɛθ/",
"wyffels":"/ˈwɪfəlz/",
"wygal":"/ˈwaɪɡəl/",
"wygant":"/ˈwaɪɡənt/",
"wygod":"/ˈwaɪˌɡɑd/",
"wyk":"/ˈwɪk/",
"wyka":"/ˈvɪkə/",
"wyke":"/ˈwaɪk/",
"wykes":"/ˈwaɪks/",
"wykle":"/ˈwaɪkəl/",
"wykoff":"/ˈwɪkɔf/",
"wyland":"/ˈwaɪlənd/",
"wylde":"/ˈwaɪld/",
"wyle":"/ˈwaɪl/",
"wyler":"/ˈwaɪlɝ/",
"wyles":"/ˈwaɪlz/",
"wylie":"/ˈwaɪli/",
"wyllie":"/ˈwɪli/",
"wylma":"/ˈwaɪlmə/",
"wyly":"/ˈwaɪli/",
"wyman":"/ˈwaɪmən/",
"wymer":"/ˈwaɪmɝ/",
"wymore":"/ˈwaɪmɔɹ/",
"wyndham":"/ˈwɪndəm/",
"wyne":"/ˈwaɪn/",
"wyner":"/ˈwaɪnɝ/",
"wynes":"/ˈwaɪnz/",
"wynette":"/hwɪˈnɛt/, /wɪˈnɛt/",
"wyngaarden":"/ˈwɪnˌɡɑɹdən/",
"wynia":"/ˈwɪniə/",
"wynkoop":"/ˈwɪŋˌkup/",
"wynn":"/ˈwɪn/",
"wynn's":"/ˈwɪnz/",
"wynne":"/ˈwɪn/",
"wynnona":"/waɪˈnoʊnə/",
"wynns":"/ˈwɪnz/",
"wynona":"/hwaɪˈnoʊnə/, /waɪˈnoʊnə/",
"wynonna":"/waɪˈnoʊnə/",
"wynter":"/ˈwɪntɝ/",
"wynton":"/ˈwɪntən/",
"wynyard":"/ˈwɪnjɝd/",
"wyoming":"/ˌwaɪˈoʊmɪŋ/",
"wyoming's":"/ˌwaɪˈoʊmɪŋz/",
"wyre":"/ˈwaɪɹ/",
"wyrick":"/ˈwɪɹɪk/",
"wyse":"/ˈwaɪz/",
"wyse's":"/ˈwaɪzɪz/",
"wyser":"/ˈwaɪzɝ/",
"wysiwig":"/ˈwɪˌziˌwɪɡ/",
"wysocki":"/vɪˈsɑtski/, /vɪˈsoʊtski/",
"wysong":"/ˈwɪsɔŋ/",
"wyss":"/ˈwɪs/",
"wyszynski":"/vɪˈʃɪnski/",
"wythe":"/ˈwaɪð/",
}, undefined, "w");
}
