/**
 * @type {Options}
 */
const defaultOptions = {
	accessKey: "P",
	allowText: true,
	alertMaxSelectionEnabled: false,
	alertMaxSelectionLength: 1800,
	ipa: {
		enabled: true,
		text: {
			enabled: true,
		},
		showSourceLastError: true,
		style: {
			font: {
				family: "'Lucida Sans Unicode', 'Segoe UI', serif",
				size: 18, // px
				color: "#282828",
			},
			backgroundColor: "#FFFFFF",
			useContextColors: false,
		},
		close: {
			timeout: 3000,
			shortcut: "\\",
			onScroll: false,
			buttonColor: "#737373",
			buttonHoverColor: "#010101",
		},
		position: {
			menuTriggered: "above",
			actionTriggered: "below",
		},
		sources: {
			cambridge: {
				enabled: true,
				order: 1,
				enabledToText: false,
				orderToText: 0,
				save: true,
				textMaxLength: 0,
				waitRateLimitTimeout: 10,
				okStatus: [200, 404],
			},
			oxford: {
				enabled: true,
				order: 2,
				enabledToText: false,
				orderToText: 0,
				save: true,
				textMaxLength: 0,
				waitRateLimitTimeout: 10,
				okStatus: [200, 404],
			},
			antvaset: {
				enabled: true,
				order: 3,
				enabledToText: false,
				orderToText: 0,
				save: true,
				textMaxLength: 0,
				waitRateLimitTimeout: 10,
				okStatus: [200, 404],
			},
			unalengua: {
				enabled: true,
				order: 4,
				enabledToText: true,
				orderToText: 1,
				save: true,
				textMaxLength: 1500,
				waitRateLimitTimeout: 10,
				okStatus: [200, 404],
			},
		},
	},
	audio: {
		enabled: true,
		text: {
			enabled: true,
			save: false,
			playerEnabled: true,
			shortcutsEnabled: false,
			skipSeconds: 3,
			shortcuts: {
				togglePlayer: "T",
				togglePlay: "K",
				toggleMute: "M",
				rewind: "HOME",
				previous: "P",
				next: "N",
				backward: "ARROWLEFT",
				forward: "ARROWRIGHT",
				decreaseVolume: "I",
				increaseVolume: "O",
				decreaseSpeed: "<",
				increaseSpeed: ">",
				resetSpeed: ";",
			},
		},
		showSourceLastError: true,
		volume: 1.0,
		playbackRate: 1.0,
		limitLoudness: false,
		sources: {
			cambridge: {
				enabled: true,
				order: 1,
				enabledToText: false,
				orderToText: 0,
				save: true,
				textMaxLength: 0,
				waitRateLimitTimeout: 10,
				okStatus: [200, 404],
			},
			linguee: {
				enabled: true,
				order: 2,
				enabledToText: false,
				orderToText: 0,
				save: true,
				textMaxLength: 0,
				waitRateLimitTimeout: 30,
				okStatus: [200, 404],
			},
			oxford: {
				enabled: true,
				order: 3,
				enabledToText: false,
				orderToText: 0,
				save: true,
				textMaxLength: 0,
				waitRateLimitTimeout: 10,
				okStatus: [200, 404],
			},
			gstatic: {
				enabled: true,
				order: 4,
				enabledToText: false,
				orderToText: 0,
				save: true,
				textMaxLength: 0,
				waitRateLimitTimeout: 0,
				okStatus: [200, 404],
			},
			googleSpeech: {
				enabled: true,
				order: 6,
				enabledToText: true,
				orderToText: 1,
				save: false,
				textMaxLength: 50000,
				waitRateLimitTimeout: 5,
				okStatus: [200, 404],
			},
			responsiveVoice: {
				enabled: true,
				order: 5,
				enabledToText: true,
				orderToText: 2,
				save: true,
				textMaxLength: 2000,
				waitRateLimitTimeout: 40,
				okStatus: [200, 404],
				api: {
					name: "rjs",
					key: "O8Ic880z",
					gender: "male",
				},
			},
			unrealSpeech: {
				enabled: true,
				order: 7,
				enabledToText: true,
				orderToText: 3,
				save: true,
				textMaxLength: 3000, // stream=1000, speech=3000
				waitRateLimitTimeout: 70,
				okStatus: [200, 404],
				api: {
					token: null,
					voiceId: "Scarlett",
					bitRate: "192k",
					pitch: 1,
					codec: "libmp3lame",
					temperature: 0.25,
				},
			},
			speechify: {
				enabled: true,
				order: 8,
				enabledToText: true,
				orderToText: 4,
				save: true,
				textMaxLength: 2000, // speech=2000
				waitRateLimitTimeout: 70,
				okStatus: [200, 404],
				api: {
					token: null,
					voiceId: "henry",
				},
			},
			playHt: {
				enabled: true,
				order: 9,
				enabledToText: true,
				orderToText: 5,
				save: true,
				textMaxLength: 2000,
				waitRateLimitTimeout: 70,
				okStatus: [200, 404],
				api: {
					userId: null,
					key: null,
					voiceId: "s3://voice-cloning-zero-shot/f2863f63-5334-4f65-9d30-438feb79c2ec/arianasaad2/manifest.json",
					quality: "medium",
					outputFormat: "mp3",
					sampleRate: 24000,
					temperature: null,
					voiceEngine: "PlayDialog",
				},
			},
			elevenLabs: {
				enabled: true,
				order: 10,
				enabledToText: true,
				orderToText: 6,
				save: true,
				textMaxLength: 2000,
				waitRateLimitTimeout: 70,
				okStatus: [200, 404],
				api: {
					key: null,
					voiceId: "FGY2WhTYpPnrIDTdsKH5",
					outputFormat: "mp3_44100_128",
					modelId: "eleven_turbo_v2",
					applyTextNormalization: "auto",
				},
			},
			amazonPolly: {
				enabled: true,
				order: 11,
				enabledToText: true,
				orderToText: 7,
				save: true,
				textMaxLength: 3000,
				waitRateLimitTimeout: 70,
				okStatus: [200, 404],
				api: {
					accessKeyId: null,
					secretAccessKey: null,
					endpoint: "polly.us-east-1.api.aws",
					engine: "standard",
					outputFormat: "mp3",
					sampleRate: "22050",
					voiceId: "Joanna",
				},
			},
			openAi: {
				enabled: true,
				order: 12,
				enabledToText: true,
				orderToText: 8,
				save: true,
				textMaxLength: 4000,
				waitRateLimitTimeout: 70,
				okStatus: [200, 404],
				api: {
					key: null,
					model: "tts-1",
					voice: "ash",
					responseFormat: "mp3",
				},
			},
			deepSeek: {
				enabled: true,
				order: 13,
				enabledToText: true,
				orderToText: 9,
				save: true,
				textMaxLength: 4000,
				waitRateLimitTimeout: 70,
				okStatus: [200, 404],
				api: {
					key: null,
					model: "hexgrad/Kokoro-82M",
					voice: "af_alloy",
					responseFormat: "mp3",
				},
			},
		},
	},
	setPronuncationByShortcut: {
		enabled: false,
		audioShortcut: "A",
		ipaShortcut: "Z",
		restoreDefaultIpaShortcut: "X",
	},
};

export default defaultOptions;
