export default function populateIpai(table) {
return table.set({
"i":"/ˈaɪ/",
"i'd":"/ˈaɪd/",
"i'ers":"/ˈaɪɝz/",
"i'll":"/ˈaɪl/",
"i'm":"/ˈaɪm/, /əm/",
"i's":"/ˈaɪz/",
"i've":"/ˈaɪv/",
"i.":"/ˈaɪ/",
"i.'s":"/ˈaɪz/",
"i.s":"/ˈaɪz/",
"ia":"/ˈiə/",
"iacobelli":"/iˌɑkoʊˈbɛli/",
"iacobellis":"/iˌɑkoʊˈbɛlɪs/",
"iacobucci":"/iɑkoʊˈbutʃi/",
"iacocca":"/ˌaɪəˈkoʊkə/",
"iacocca's":"/ˌaɪəˈkoʊkəz/",
"iacona":"/ˌaɪəˈkoʊnə/",
"iacono":"/ˌaɪəˈkoʊnoʊ/",
"iacovelli":"/iˌɑkoʊˈvɛli/",
"iafrate":"/ˌaɪəˈfɹeɪti/",
"iago":"/iˈɑɡoʊ/",
"iain":"/iˈeɪn/",
"iakovos":"/iˈɑkoʊvoʊs/",
"ialla":"/ˈaɪɑlə/, /ˈiɑlə/",
"iams":"/ˈaɪɑmz/, /ˈiɑmz/",
"ian":"/ˈiən/",
"iannaccone":"/iˌɑnəˈkoʊni/",
"iannacone":"/iˌɑnəˈkoʊni/",
"iannamico":"/iˌɑnəˈmikoʊ/",
"iannelli":"/iəˈnɛli/",
"iannello":"/iəˈnɛloʊ/",
"ianni":"/iˈɑni/",
"ianniello":"/iˌɑniˈɛloʊ/",
"iannone":"/iəˈnoʊni/",
"iannotti":"/iəˈnoʊti/",
"iannucci":"/iəˈnutʃi/",
"iannuzzi":"/iəˈnutsi/, /iəˈnuzi/",
"ianovski":"/jəˈnɑfski/, /jəˈnɑvski/",
"iantha":"/iˈɑnθə/",
"ianthe":"/iˈɑnθeɪ/",
"ianthina":"/iənˈθinə/",
"iason":"/ˈiəsən/",
"iavarone":"/iˌɑvɝˈoʊni/",
"ib":"/ˈaɪˈbi/, /ˈɪb/",
"iba":"/ˈibə/",
"ibach":"/ˈɪbɑk/",
"ibanez":"/ˌɪˈbɑnɛz/",
"ibaraki":"/ˌaɪbɝˈɑki/",
"ibarra":"/ˌɪˈbɑɹə/",
"ibbotson":"/ˈɪbətsən/",
"iberia":"/aɪˈbɪɹiə/",
"iberia's":"/aɪˈbɪɹiəz/",
"iberian":"/aɪˈbɪɹiən/",
"ibero":"/ˌɪˈbɛɹoʊ/",
"ibex":"/ˈaɪbɛks/",
"ibid":"/ˈɪbɪd/",
"ibis":"/ˈaɪbəs/",
"ibiza":"/ˌiˈbizə/",
"ibm":"/ˈaɪˌbiˌɛm/",
"ibmer":"/ˈɪbmɝ/",
"ibmers":"/ˈɪbmɝz/",
"ibn":"/ˈɪbən/",
"ibogaine":"/ˈaɪbəɡeɪn/, /ˈaɪboʊɡeɪn/",
"ibrahim":"/ˌɪbɹɑˈhim/",
"ibsen":"/ˈɪbsən/",
"ibuprofen":"/ˌaɪbjuˈpɹoʊfən/",
"icahn":"/ˈaɪkɑn/",
"icahn's":"/ˈaɪkɑnz/",
"icard":"/ˌɪˈkɑɹd/",
"icarus":"/ˈɪˌkɝəs/",
"ice":"/ˈaɪs/",
"ice-cream":"/ˈaɪsˌkɹim/",
"ice-nine":"/ˈaɪsˈnaɪn/",
"iceberg":"/ˈaɪsbɝɡ/",
"icebergs":"/ˈaɪsbɝɡz/",
"icebox":"/ˈaɪsˌbɑks/",
"icebreaker":"/ˈaɪsˌbɹeɪkɝ/",
"icebreakers":"/ˈaɪsˌbɹeɪkɝz/",
"iced":"/ˈaɪst/",
"icefish":"/ˈaɪsˌfɪʃ/",
"iceland":"/ˈaɪslənd/",
"icelandair":"/ˌaɪslænˈdɛɹ/",
"icelandic":"/aɪˈslændɪk/",
"iceman":"/ˈaɪsmæn/",
"icenhour":"/ˈaɪsənaʊɹ/, /ˈɪsənaʊɹ/",
"icenhower":"/ˈaɪsənˌhaʊɝ/, /ˈɪsənˌhaʊɝ/",
"icenogle":"/ˈaɪsəˌnoʊɡəl/, /ˈɪsəˌnoʊɡəl/",
"ices":"/ˈaɪsəz/, /ˈaɪsɪz/",
"iceskate":"/ˈaɪˌskeɪt/, /ˈaɪsˌskeɪt/",
"iceskating":"/ˈaɪˌskeɪtɪŋ/, /ˈaɪsˌskeɪtɪŋ/",
"ich":"/ˈɪtʃ/",
"ichi":"/ˈiˌtʃi/",
"ichikawa":"/ˌɪˌtʃiˈkɑwɑ/",
"ichiro":"/ˈitʃɪɹoʊ/",
"icicle":"/ˈaɪsɪkəl/",
"icicles":"/ˈaɪsɪkəlz/",
"icily":"/ˈaɪsɪli/",
"icing":"/ˈaɪsɪŋ/",
"ickes":"/ˈaɪkiz/, /ˈaɪks/, /ˈɪkiz/",
"ickes'":"/ˈɪkəs/, /ˈɪkiz/",
"icloud":"/ˈaɪˈklaʊd/",
"icon":"/ˈaɪkɑn/",
"iconic":"/ˌaɪˈkɑnɪk/",
"iconoclasm":"/ˌaɪˈkɑnəˌklæzəm/",
"iconoclast":"/ˌaɪˈkɑnəˌklæst/",
"iconoclastic":"/ˌaɪkənəˈklæstɪk/",
"iconography":"/ˌaɪkəˈnɑɡɹəfi/",
"icons":"/ˈaɪˌkɑnz/",
"icy":"/ˈaɪsi/",
"id":"/ˈaɪˈdi/, /ˈɪd/",
"ida":"/ˈaɪdə/",
"idaho":"/ˈaɪdəˌhoʊ/",
"idaho's":"/ˈaɪdəˌhoʊz/",
"idaho-falls":"/ˈaɪdəˌhoʊˈfɑlz/",
"idalia":"/ˌɪˈdɑljə/",
"idalina":"/ˌɪdɑˈlinə/",
"idaline":"/ˈɪdəlaɪn/",
"iddings":"/ˈɪdɪŋz/",
"ide":"/ˈaɪd/",
"idea":"/aɪˈdiə/",
"idea's":"/aɪˈdiəz/",
"ideal":"/aɪˈdil/",
"ideal's":"/aɪˈdilz/",
"idealism":"/aɪˈdilɪzəm/",
"idealist":"/aɪˈdilɪst/",
"idealistic":"/aɪˌdiəˈlɪstɪk/",
"idealistically":"/aɪˌdiəˈlɪstɪkli/",
"idealists":"/aɪˈdilɪsts/",
"idealize":"/aɪˈdiˌlaɪz/",
"idealized":"/aɪˈdiəˌlaɪzd/",
"idealizes":"/aɪˈdiˌlaɪzɪz/",
"idealizing":"/aɪˈdiˌlaɪzɪŋ/",
"ideally":"/aɪˈdili/",
"ideals":"/aɪˈdilz/",
"ideas":"/aɪˈdiəz/",
"ideation":"/ˌaɪdiˈeɪʃən/",
"idec":"/ˈaɪdək/",
"iden":"/ˈaɪdən/",
"ident":"/aɪˈdɛnt/",
"identa":"/aɪˈdɛntə/",
"identical":"/aɪˈdɛntɪkəl/",
"identics":"/aɪˈdɛntɪks/",
"identifiable":"/aɪˈdɛntəˌfaɪəbəl/",
"identification":"/aɪˌdɛntəfəˈkeɪʃən/",
"identifications":"/aɪˌdɛntəfəˈkeɪʃənz/",
"identified":"/aɪˈdɛntəˌfaɪd/",
"identifier":"/aɪˈdɛntəˌfaɪɝ/",
"identifiers":"/aɪˈdɛnəˌfaɪɝz/",
"identifies":"/aɪˈdɛntəˌfaɪz/",
"identify":"/aɪˈdɛntəˌfaɪ/",
"identifying":"/aɪˈdɛntəˌfaɪɪŋ/",
"identikit":"/aɪˈdɛntɪˌkɪt/",
"identities":"/aɪˈdɛntɪˌtiz/",
"identity":"/aɪˈdɛntɪˌti/",
"ideological":"/ˌaɪdiəˈlɑdʒɪkəl/",
"ideologically":"/ˌaɪdiəˈlɑdʒɪkli/",
"ideologies":"/ˌaɪdiˈɑlədʒiz/",
"ideologist":"/ˌaɪdiˈɑlədʒəst/",
"ideologists":"/ˌaɪdiˈɑlədʒɪsts/",
"ideologue":"/ˈaɪdiəloʊɡ/",
"ideologues":"/ˈaɪdiəlɔɡz/",
"ideology":"/ˌaɪdiˈɑlədʒi/",
"ideonomy":"/ˌaɪdiˈɑnəmi/",
"idette":"/ˌaɪˈdɛt/",
"ididerod":"/aɪˈdɪdɝɑd/",
"idiocy":"/ˈɪdiəsi/",
"idiom":"/ˈɪdiəm/",
"idiomatic":"/ˌɪdiəˈmætɪk/",
"idioms":"/ˈɪdiəmz/",
"idiopath":"/ˌɪdioʊˈpæθ/",
"idiopathic":"/ˌɪdioʊˈpæθək/",
"idiosyncrasies":"/ˌɪdioʊˈsɪnkɹəˌsiz/",
"idiosyncrasy":"/ˌɪdioʊˈsɪnkɹəˌsi/",
"idiosyncratic":"/ˌɪdioʊˌsɪnˈkɹætɪk/",
"idiot":"/ˈɪˌdiət/",
"idiotic":"/ˌɪdiˈɑtɪk/",
"idiotically":"/ˌɪdiˈɑtɪkli/",
"idiots":"/ˈɪˌdiəts/",
"iditarod":"/ˌɪˈdɪtəˌɹɔd/",
"idle":"/ˈaɪdəl/",
"idled":"/ˈaɪdəld/",
"idleman":"/ˈaɪdəlmən/",
"idleness":"/ˈaɪdəlnəs/",
"idler":"/ˈaɪdəlɝ/, /ˈaɪdlɝ/",
"idles":"/ˈaɪdəlz/",
"idlewild":"/ˈaɪdəlˌwaɪl/, /ˈaɪdəlˌwaɪld/",
"idling":"/ˈaɪdəlɪŋ/, /ˈaɪdlɪŋ/",
"idly":"/ˈaɪdli/",
"ido":"/ˈiˌdoʊ/",
"idol":"/ˈaɪdəl/",
"idola":"/ˌɪˈdoʊlə/",
"idolatrous":"/aɪˈdɑlətɹəs/",
"idolatry":"/aɪˈdɑlətɹi/",
"idolize":"/ˈaɪdəˌlaɪz/",
"idolized":"/ˈaɪdəˌlaɪzd/",
"idolizes":"/ˈaɪdəˌlaɪzɪz/",
"idolizing":"/ˈaɪdəˌlaɪzɪŋ/",
"idols":"/ˈaɪdəlz/",
"idona":"/ˌɪˈdoʊnə/",
"idoney":"/ˌɪˈdoʊni/",
"idonia":"/ˌɪˈdoʊniə/",
"idrocarburi":"/ˌɪˌdɹɑˌkɑɹˈbʊɹi/",
"ids":"/ˈaɪˈdiz/",
"iduna":"/ˌɪˈdunə/",
"idyll":"/ˈaɪdəl/",
"idyllic":"/aɪˈdɪlɪk/",
"ieee":"/ˌaɪˌtɹɪpləˈi/",
"ierardi":"/iɝˈɑɹdi/",
"ierne":"/ˈɪɹn/",
"iezzi":"/iˈɛtsi/",
"if":"/ˈɪf/, /ɪf/",
"if's":"/ˈɪfs/",
"ifas":"/ˈaɪfəs/",
"iffy":"/ˈɪfi/",
"ifil":"/ˌaɪˈfil/",
"ifill":"/ɪˈfil/",
"ifint":"/ˈaɪfɪnt/",
"ifor":"/ˈaɪˌfɔɹ/",
"ifs":"/ˈɪfs/",
"igarashi":"/ˌiɡɑˈɹɑʃi/",
"ige":"/ˈaɪdʒ/",
"igel":"/ˈɪɡəl/",
"igene":"/aɪˈdʒin/",
"iger":"/ˈaɪɡɝ/",
"iglehart":"/ˈaɪɡəlhɑɹt/",
"iglesia":"/ˌiˈɡleɪsiə/",
"iglesias":"/ˌɪˈɡleɪsiɪs/",
"igloo":"/ˈɪɡlu/",
"igman":"/ˈɪɡmən/",
"ignace":"/ˈɪɡnəs/",
"ignacio":"/ˌɪɡˈnɑsioʊ/",
"ignacio's":"/ˌɪɡˈnɑsioʊz/",
"ignasiak":"/ˌɪɡˈnɑsiæk/",
"ignatia":"/ˌɪɡˈnɑʃə/",
"ignatius":"/ˌɪɡˈneɪʃəs/",
"ignatowski":"/ˌɪɡnəˈtɔfski/",
"ignatz":"/ˈɪɡnəts/",
"igneous":"/ˈɪɡniəs/",
"ignite":"/ˌɪɡˈnaɪt/",
"ignited":"/ˌɪɡˈnaɪtɪd/",
"ignites":"/ˌɪɡˈnaɪts/",
"igniting":"/ˌɪɡˈnaɪtɪŋ/",
"ignition":"/ˌɪɡˈnɪʃən/",
"ignoble":"/ˌɪɡˈnoʊbəl/",
"ignominious":"/ˌɪɡnəˈmɪniəs/",
"ignominiously":"/ˌɪɡ.nəˈmɪn.i.əs.li/",
"ignominy":"/ˈɪɡnoʊˌmɪni/",
"ignoramus":"/ˌɪɡnɝˈeɪməs/",
"ignorance":"/ˈɪɡnɝəns/",
"ignorant":"/ˈɪɡnɝənt/",
"ignore":"/ˌɪɡˈnɔɹ/",
"ignored":"/ˌɪɡˈnɔɹd/",
"ignores":"/ˌɪɡˈnɔɹz/",
"ignoring":"/ˌɪɡˈnɔɹɪŋ/",
"igo":"/ˈiɡoʊ/",
"igoe":"/ˈiɡoʊ/",
"igon":"/ˈaɪɡən/",
"igor":"/ˈiˌɡɔɹ/, /ˌɪˈɡɔɹ/",
"igou":"/ˌɪˈɡu/",
"iguana":"/aɪˈɡwɑnə/",
"iguanas":"/ˌɪˈɡwɑnəz/",
"iguchi":"/əˈɡutʃi/",
"igushi":"/ɪˈɡuˌʃi/",
"ihasz":"/ˈaɪhæs/",
"ihde":"/ˈɪd/",
"ihle":"/ˈaɪhəl/",
"ihlenfeldt":"/ˈɪlɪnfɪlt/",
"ihnen":"/ˈɪnən/",
"ihrig":"/ˈɪɹɪɡ/",
"ihrke":"/ˈɪɹk/",
"iiams":"/ˈiəmz/",
"iida":"/ˈidə/",
"iie":"/ˈii/",
"ijames":"/ˈaɪˈdʒeɪmz/, /ɪˈjɑmɛs/",
"ijaz":"/ˈɪdʒəz/, /iˈdʒɑz/",
"ikaes":"/ˈaɪkæs/",
"ikard":"/ˈɪkɝd/",
"ike":"/ˈaɪk/",
"ike's":"/ˈaɪks/",
"ikea":"/ˌaɪˈkiə/",
"ikeda":"/ɪˈkeɪdə/",
"ikenberry":"/ˈaɪkənˌbɛɹi/",
"ikerd":"/ˈɪkɝd/",
"ikeuchi":"/iˈkutʃi/",
"ikey":"/ˈɪki/",
"ikie":"/ˈɪki/",
"ikle":"/ˈɪkəl/",
"ikner":"/ˈɪknɝ/",
"ikon":"/ˈaɪkɑn/",
"il":"/ˈɪl/",
"ila":"/ˈilə/",
"ilalis":"/ˌɪˈlæləs/",
"ilalis'":"/ˌɪˈlæləs/",
"ilalis's":"/ˌɪˈlæləsɪs/",
"ilan":"/ˌiˈlɑn/",
"ilana":"/ˌɪˈlɑnə/",
"ilana's":"/ˌɪˈlɑnəz/",
"ilardi":"/ˌɪˈlɑɹdi/",
"ilbo":"/ˈɪlboʊ/",
"ileana":"/ˌɪliˈænə/",
"ilene":"/ˈɪlin/",
"iler":"/ˈaɪlɝ/",
"iles":"/ˈaɪlz/",
"ileto":"/aɪˈleɪdoʊ/",
"ilg":"/ˈɪlɡ/",
"ilgenfritz":"/ˈɪlɡɪnfɹɪts/",
"ilhae":"/ˌɪlˈheɪ/",
"iliad":"/ˈɪliəd/",
"iliano":"/ˌɪliˈɑnoʊ/",
"ilidza":"/ˌɪˈlɪdzə/",
"iliescu":"/ˌɪliˈɛsˌkju/",
"iliff":"/ˈɪlɪf/",
"iljin":"/ˈɪldʒɪn/",
"ilk":"/ˈɪlk/",
"ilka":"/ˈɪlkə/",
"ill":"/ˈɪl/",
"illegal":"/ˌɪˈliɡəl/",
"illegalities":"/ˌɪliˈɡælɪtiz/",
"illegality":"/ˌɪliˈɡælɪti/",
"illegally":"/ˌɪˈliɡəli/",
"illegals":"/ˌɪˈliɡəlz/",
"illegible":"/ˌɪˈlɛdʒəbəl/",
"illegitimacy":"/ˌɪlɪˈdʒɪtəməsi/",
"illegitimate":"/ˌɪlɪˈdʒɪtəmɪt/",
"illes":"/ˈaɪlz/",
"illg":"/ˈɪlɡ/",
"illicit":"/ˌɪˈlɪsət/",
"illicitly":"/ˈɪlɪsɪtli/",
"illig":"/ˈɪlɪɡ/",
"illina":"/ˌɪˈlinə/",
"illingworth":"/ˈɪlɪŋˌwɝθ/",
"illinois":"/ˌɪləˈnɔɪ/, /ˌɪləˈnɔɪz/",
"illinois'":"/ˈɪlɪnɔɪz/",
"illinois's":"/ˌɪlɪˈnɔɪz/",
"illiquid":"/ˌɪˈlɪkwɪd/",
"illiquidity":"/ˌɪlɪˈkwɪdɪti/",
"illiteracy":"/ˌɪˈlɪtɝəsi/",
"illiterate":"/ˌɪˈlɪtɝət/",
"illiterates":"/ˌɪˈlɪtɝəts/",
"illness":"/ˈɪlnəs/",
"illnesses":"/ˈɪlnəsɪz/",
"illogic":"/ˌɪˈlɑdʒɪk/",
"illogical":"/ˌɪˈlɑdʒɪkəl/",
"ills":"/ˈɪlz/",
"illuminate":"/ˌɪˈlumɪnɪt/",
"illuminated":"/ˌɪˈluməˌneɪtəd/",
"illuminates":"/ˌɪˈluməˌneɪts/",
"illuminating":"/ˌɪˈluməˌneɪtɪŋ/",
"illumination":"/ˌɪˌluməˈneɪʃən/",
"illuminator":"/ˌɪˈluməˌneɪtɝ/",
"illumined":"/ˌɪˈlumənd/",
"illusion":"/ˌɪˈluʒən/",
"illusionary":"/ˌɪˈluʒəˌnɛɹi/",
"illusionism":"/ˌɪˈluʒəˌnɪzəm/",
"illusionist":"/ˌɪˈluʒənəst/",
"illusionist's":"/ˌɪˈluʒənəsts/",
"illusionists":"/ˌɪˈluʒənəsts/",
"illusions":"/ˌɪˈluʒənz/",
"illusive":"/ˌɪˈlusɪv/",
"illusory":"/ˌɪˈlusɝi/",
"illustrate":"/ˈɪləˌstɹeɪt/",
"illustrated":"/ˈɪləˌstɹeɪtəd/, /ˈɪləˌstɹeɪtɪd/",
"illustrates":"/ˈɪləˌstɹeɪts/",
"illustrating":"/ˈɪləˌstɹeɪtɪŋ/",
"illustration":"/ˌɪləˈstɹeɪʃən/",
"illustrations":"/ˌɪləˈstɹeɪʃənz/",
"illustrative":"/ˌɪˈləstɹətɪv/",
"illustrator":"/ˈɪləˌstɹeɪtɝ/",
"illustrators":"/ˈɪləˌstɹeɪtɝz/",
"illustrious":"/ˌɪˈləstɹiəs/",
"illyrian":"/ˌɪˈlɪɹiən/",
"ilo":"/ˈaɪloʊ/",
"ilona":"/ˌɪˈloʊnə/",
"ilopango":"/ˌiloʊˈpæŋɡoʊ/",
"ilsa":"/ˈɪlsə/",
"ilse":"/ˈɪls/",
"ilsley":"/ˈɪlzli/",
"ilva":"/ˈɪlvə/",
"ilya":"/ˈɪljə/",
"ilyaronoff":"/ˈɪljɑˈɹɔnɔf/",
"im":"/ˈɪm/",
"image":"/ˈɪmədʒ/, /ˈɪmɪdʒ/",
"imageries":"/ˈɪmɪdʒɹiz/",
"imagery":"/ˈɪmədʒɹi/, /ˈɪmɪdʒɹi/",
"images":"/ˈɪmədʒəz/, /ˈɪmɪdʒɪz/",
"imaginable":"/ˌɪˈmædʒənəbəl/",
"imaginary":"/ˌɪˈmædʒəˌnɛɹi/",
"imagination":"/ˌɪˌmædʒəˈneɪʃən/",
"imaginations":"/ˌɪˌmædʒəˈneɪʃənz/",
"imaginative":"/ˌɪˈmædʒənətɪv/",
"imaginatively":"/ˌɪˈmædʒənəˌtɪvˌli/",
"imagine":"/ˌɪˈmædʒən/",
"imagined":"/ˌɪˈmædʒənd/",
"imagineer":"/ˌɪˌmædʒəˈnɪɹ/",
"imagineering":"/ˌɪˌmædʒəˈnɪɹɪŋ/",
"imagines":"/ˌɪˈmædʒənz/",
"imaging":"/ˈɪmɪdʒɪŋ/",
"imagining":"/ˌɪˈmædʒənɪŋ/",
"imai":"/ˌɪˈmaɪ/",
"imam":"/ˈaɪmæm/",
"imamura":"/ˌɪˌmɑˈmʊˌɹɑ/",
"iman":"/ˈaɪmən/",
"imari":"/iˈmɑɹi/",
"imasco":"/ɪˈmæsoʊ/",
"imax":"/ˈaɪˌmæks/",
"imax'":"/ˈaɪˌmæks/",
"imax's":"/ˈaɪˌmæksɪz/",
"imbalance":"/ɪmˈbæləns/",
"imbalances":"/ɪmˈbælənsɪz/",
"imbecile":"/ˈɪmbəsaɪl/, /ˈɪmbəsəl/",
"imbeciles":"/ˈɪmbəsaɪlz/, /ˈɪmbəsəlz/",
"imbed":"/ɪmˈbɛd/",
"imbedded":"/ɪmˈbɛdɪd/",
"imbeds":"/ɪmˈbɛdz/",
"imber":"/ˈɪmbɝ/",
"imbera":"/ˈɪmbɝə/",
"imbibe":"/ɪmˈbaɪb/",
"imbibed":"/ɪmˈbaɪbd/",
"imboden":"/ˈɪmboʊdən/",
"imbroglio":"/ˌɪmˈbɹoʊlˌjoʊ/",
"imbrogno":"/ˌɪmˈbɹoʊɡˌnoʊ/",
"imbue":"/ˌɪmˈbju/",
"imbued":"/ˌɪmˈbjud/",
"imburgia":"/ˈɪmbɝɡiə/",
"imcera":"/ˌɪmˈsɛɹə/",
"imel":"/ˈɪməl/",
"imelda":"/ˌɪˈmɛldə/",
"imes":"/ˈaɪmz/",
"imhof":"/ˈɪmhəf/",
"imhoff":"/ˈɪmˌhɔf/",
"imig":"/ˈɪmɪɡ/",
"imitable":"/ˈɪmətəbəl/",
"imitate":"/ˈɪməˌteɪt/",
"imitated":"/ˈɪməˌteɪtɪd/",
"imitates":"/ˈɪməˌteɪts/",
"imitating":"/ˈɪməˌteɪtɪŋ/",
"imitation":"/ˌɪməˈteɪʃən/",
"imitations":"/ˌɪmɪˈteɪʃənz/",
"imitative":"/ˈɪməˌteɪtɪv/",
"imitator":"/ˈɪməˌteɪtɝ/",
"imitators":"/ˈɪmɪˌteɪtɝz/",
"imlay":"/ˌɪmˈleɪ/",
"imler":"/ˈɪmlɝ/",
"imm":"/ˈɪm/",
"immaculate":"/ˌɪˈmækjulɪt/",
"immaculately":"/ˌɪˈmækjələtli/",
"immanence":"/ˈɪmənəns/",
"immanent":"/ˈɪmənənt/",
"immanuel":"/ˈɪmənʊl/",
"immaterial":"/ˌɪməˈtɪɹiəl/",
"immature":"/ˌɪmətˈjʊɹ/",
"immaturity":"/ˌɪməˈtʃʊɹɪti/",
"immeasurable":"/ˌɪˈmɛʒɝˌæbəl/",
"immeasurably":"/ˌɪˈmɛʒɝˌæbli/",
"immediacy":"/ˌɪˈmiˌdiəsi/",
"immediate":"/ˌɪˈmiˌdiət/",
"immediately":"/ˌɪˈmiˌdiətli/",
"immel":"/ˈɪməl/",
"immemorial":"/ˌɪməˈmɔɹiəl/",
"immense":"/ˌɪˈmɛns/",
"immensely":"/ˌɪˈmɛnsli/",
"immerman":"/ˈɪmɝmən/",
"immerse":"/ˌɪˈmɝs/",
"immersed":"/ˌɪˈmɝst/",
"immersion":"/ˌɪˈmɝʒən/",
"immigrant":"/ˈɪməɡɹənt/",
"immigrant's":"/ˈɪməɡɹənts/",
"immigrants":"/ˈɪməɡɹənts/",
"immigrants'":"/ˈɪmɪɡɹənts/",
"immigrate":"/ˈɪməˌɡɹeɪt/",
"immigrated":"/ˈɪməˌɡɹeɪtɪd/",
"immigration":"/ˌɪməˈɡɹeɪʃən/",
"imminence":"/ˈɪmənəns/",
"imminent":"/ˈɪmənənt/",
"imminently":"/ˈɪmənəntli/",
"immiscible":"/ˌɪˈmɪsəbəl/",
"immobile":"/ˌɪˈmoʊˌbaɪl/, /ˌɪˈmoʊˌbil/, /ˌɪˈmoʊbəl/",
"immobility":"/ˌɪmoʊˈbɪlɪti/",
"immobilize":"/ˌɪˈmoʊbəˌlaɪz/",
"immobilized":"/ˌɪˈmoʊbəˌlaɪzd/",
"immobilizing":"/ˌɪˈmoʊbəˌlaɪzɪŋ/",
"immolate":"/ˈɪməˌleɪt/",
"immolated":"/ˈɪməˌleɪtəd/",
"immolates":"/ˈɪməˌleɪts/",
"immolating":"/ˈɪməˌleɪtɪŋ/",
"immolation":"/ˈɪməˌleɪʃən/",
"immoral":"/ˌɪˈmɔɹəl/",
"immorality":"/ˌɪmɝˈælɪti/",
"immortal":"/ˌɪˈmɔɹtəl/",
"immortality":"/ˌɪmɔɹˈtælɪti/",
"immortalize":"/ˌɪˈmɔɹtəlaɪz/",
"immortalized":"/ˌɪˈmɔɹtəlaɪzd/",
"immortalizes":"/ˌɪˈmɔɹtəlaɪzɪz/",
"immortalizing":"/ˌɪˈmɔɹtəlaɪzɪŋ/",
"immortals":"/ˌɪˈmɔɹtəlz/",
"immotile":"/ˌɪˈmoʊtəl/",
"immovable":"/ˌɪˈmuvəbəl/",
"immu":"/ˈɪmju/",
"immulogic":"/ˈɪmjuˌlɑdʒɪk/",
"immune":"/ˌɪmˈjun/",
"immunetech":"/ˈɪmjunˌtɛk/",
"immunex":"/ˈɪmjunɛks/",
"immunities":"/ˌɪmˈjunɪtiz/",
"immunity":"/ˌɪmˈjunəti/, /ˌɪmˈjunɪti/",
"immunization":"/ˌɪmjunəˈzeɪʃən/",
"immunizations":"/ˌɪmjunəˈzeɪʃənz/",
"immunize":"/ˈɪmjuˌnaɪz/",
"immunized":"/ˈɪmjəˌnaɪzd/",
"immunizes":"/ˈɪmjəˌnaɪzɪz/",
"immunizing":"/ˈɪmjəˌnaɪzɪŋ/",
"immuno":"/ˌɪmˈjunoʊ/",
"immunodeficiency":"/ˌɪmjunoʊˌdɪˈfɪʃənsi/",
"immunological":"/ˌɪmjunəˈlɑdʒɪkəl/",
"immunologist":"/ˌɪmjuˈnɑlədʒɪst/",
"immunology":"/ˌɪmjuˈnɑlədʒi/",
"immunomedic":"/ˈɪmjunoʊˌmɛdɪk/",
"immunomedics":"/ˈɪmjunoʊˌmɛdɪks/",
"immunoperoxidase":"/ˈɪmjunoʊpɛˈɹɔksɪˌdeɪz/",
"immunotherapy":"/ˌɪmjunoʊˈθɛɹəpi/",
"immutability":"/ɪˌmjuː.t̬əˈbɪl.ə.t̬i/",
"immutable":"/ˌɪmˈjutəbəl/",
"imnet":"/ˈɪmˌnɛt/",
"imo":"/ˈaɪˈɛˈmoʊ/, /ˈaɪmoʊ/",
"imogen":"/ˈɪməɡən/",
"imogene":"/ˈɪməˌdʒin/",
"imondi":"/ˌɪˈmɑnˌdi/, /ˌɪˈmoʊnˌdi/",
"imp":"/ˈɪmp/",
"impact":"/ˈɪmpækt/, /ˌɪmˈpækt/",
"impacted":"/ˈɪmˌpæktɪd/, /ˌɪmˈpæktɪd/",
"impacting":"/ˌɪmˈpæktɪŋ/",
"impacts":"/ˈɪmpæks/, /ˈɪmpækts/, /ˌɪmˈpækts/, /ɪmˈpæks/",
"impair":"/ˌɪmˈpɛɹ/",
"impaired":"/ˌɪmˈpɛɹd/",
"impairing":"/ˌɪmˈpɛɹɪŋ/",
"impairment":"/ˌɪmˈpɛɹmənt/",
"impairments":"/ˌɪmˈpɛɹmənts/",
"impairs":"/ˌɪmˈpɛɹz/",
"impala":"/ˌɪmˈpɑlə/",
"impale":"/ˌɪmˈpeɪl/",
"impaled":"/ˌɪmˈpeɪld/",
"impales":"/ˌɪmˈpeɪlz/",
"impaling":"/ˌɪmˈpeɪlɪŋ/",
"impanel":"/ˌɪmˈpænəl/",
"impaneled":"/ˌɪmˈpænəld/",
"impart":"/ˌɪmˈpɑɹt/",
"imparted":"/ˌɪmˈpɑɹtɪd/",
"impartial":"/ˌɪmˈpɑɹʃəl/",
"impartiality":"/ˌɪmˌpɑɹʃiˈælɪti/",
"impartially":"/ˌɪmˈpɑɹʃəli/",
"imparting":"/ˌɪmˈpɑɹtɪŋ/",
"imparts":"/ˌɪmˈpɑɹts/",
"impassable":"/ˌɪmˈpæsəbəl/",
"impasse":"/ˈɪmˌpæs/, /ˌɪmˈpæs/",
"impassion":"/ˌɪmˈpæʃən/",
"impassioned":"/ˌɪmˈpæʃənd/",
"impassive":"/ˌɪmˈpæsɪv/",
"impassively":"/ˌɪmˈpæsɪvli/",
"impastato":"/ˌɪmpɑˈstɑtoʊ/",
"impatience":"/ˌɪmˈpeɪʃəns/",
"impatiens":"/ˌɪmˈpeɪʃənz/",
"impatient":"/ˌɪmˈpeɪʃənt/",
"impatiently":"/ˌɪmˈpeɪʃəntli/",
"impeach":"/ˌɪmˈpitʃ/",
"impeachable":"/ˌɪmˈpitʃəbəl/",
"impeached":"/ˌɪmˈpitʃt/",
"impeaches":"/ˌɪmˈpitʃəz/",
"impeaching":"/ˌɪmˈpitʃɪŋ/",
"impeachment":"/ˌɪmˈpitʃmənt/",
"impeachments":"/ˌɪmˈpitʃmənts/",
"impeccable":"/ˌɪmˈpɛkəbəl/",
"impeccably":"/ˌɪmˈpɛkəbli/",
"impedance":"/ˌɪmˈpidəns/",
"impede":"/ˌɪmˈpid/",
"impeded":"/ˌɪmˈpidɪd/",
"impedes":"/ˌɪmˈpidz/",
"impediment":"/ˌɪmˈpɛdəmənt/",
"impediments":"/ˌɪmˈpɛdəmənts/",
"impeding":"/ˌɪmˈpidɪŋ/",
"impel":"/ˌɪmˈpɛl/",
"impelled":"/ˌɪmˈpɛld/",
"impend":"/ˌɪmˈpɛnd/",
"impending":"/ˌɪmˈpɛndɪŋ/",
"impenetrable":"/ˌɪmˈpɛnətɹəbəl/",
"imperative":"/ˌɪmˈpɛɹətɪv/",
"imperatives":"/ˌɪmˈpɛɹətɪvz/",
"imperato":"/ˌɪmpɝˈɑtoʊ/",
"imperceptible":"/ˌɪmpɝˈsɛptɪbəl/",
"imperceptibly":"/ˌɪmpɝˈsɛptɪbli/",
"imperfect":"/ˌɪmˈpɝfɪkt/",
"imperfection":"/ˌɪmpɝˈfɛkʃən/",
"imperfections":"/ˌɪmpɝˈfɛkʃənz/",
"imperfectly":"/ˌɪmˈpɝfɪktli/",
"imperia":"/ˌɪmˈpiɹiə/",
"imperial":"/ˌɪmˈpɪɹiəl/",
"imperial's":"/ˌɪmˈpɪɹiəlz/",
"imperiale":"/ˌɪmpɝiˈɑli/",
"imperialism":"/ˌɪmˈpɪɹiəˌlɪzəm/",
"imperialist":"/ˌɪmˈpɪɹiəlɪst/",
"imperialistic":"/ˌɪmˌpiɹiəˈlɪstɪk/",
"imperialists":"/ˌɪmˈpɪɹiəlɪsts/",
"imperil":"/ˌɪmˈpɛɹəl/",
"imperiled":"/ˌɪmˈpɛɹəld/",
"imperiling":"/ˌɪmˈpɛɹəlɪŋ/",
"imperils":"/ˌɪmˈpɛɹəlz/",
"imperious":"/ˌɪmˈpɪɹiəs/",
"impermissible":"/ˌɪmpɝˈmɪsɪbəl/",
"impersonal":"/ˌɪmˈpɝsənəl/",
"impersonality":"/ˌɪmˌpɝsəˈnæləti/",
"impersonate":"/ˌɪmˈpɝsəˌneɪt/",
"impersonated":"/ˌɪmˈpɝsəˌneɪtɪd/",
"impersonates":"/ˌɪmˈpɝsəˌneɪts/",
"impersonating":"/ˌɪmˈpɝsəˌneɪtɪŋ/",
"impersonation":"/ˌɪmpɝsəˈneɪʃən/",
"impersonator":"/ˌɪmˈpɝsəneɪtɝ/",
"impersonators":"/ˌɪmˈpɝsəˌneɪtɝz/",
"impertinent":"/ˌɪmˈpɝtənənt/",
"impervious":"/ˌɪmˈpɝviəs/",
"impetuous":"/ˌɪmˈpɛtʃwəs/",
"impetus":"/ˈɪmpətəs/",
"impinge":"/ˌɪmˈpɪndʒ/",
"impinged":"/ˌɪmˈpɪndʒd/",
"impinges":"/ˌɪmˈpɪndʒɪz/",
"impinging":"/ˌɪmˈpɪndʒɪŋ/",
"impious":"/ˌɪmˈpaɪəs/",
"impish":"/ˈɪmpɪʃ/",
"implacable":"/ˌɪmˈplækəbəl/",
"implant":"/ˈɪmˌplænt/, /ˌɪmˈplænt/",
"implantable":"/ˈɪmˌplæntəbəl/",
"implantation":"/ˌɪmplænˈteɪʃən/",
"implanted":"/ˌɪmˈplæntɪd/",
"implanting":"/ˌɪmˈplæntɪŋ/",
"implants":"/ˈɪmˌplænts/, /ˌɪmˈplænts/",
"implausible":"/ˌɪmˈplɔzəbəl/",
"implausibly":"/ˌɪmˈplɔzəbli/",
"implement":"/ˈɪmpləmənt/",
"implementation":"/ˌɪmpləmɛnˈteɪʃən/",
"implementations":"/ˌɪmpləmɛnˈteɪʃənz/",
"implemented":"/ˈɪmpləˌmɛnəd/, /ˈɪmpləˌmɛntəd/",
"implementing":"/ˈɪmpləˌmɛnɪŋ/, /ˈɪmpləˌmɛntɪŋ/",
"implements":"/ˈɪmpləmənts/",
"implicate":"/ˈɪmplɪˌkeɪt/",
"implicated":"/ˈɪmplɪˌkeɪtɪd/",
"implicates":"/ˈɪmplɪˌkeɪts/",
"implicating":"/ˈɪmplɪˌkeɪtɪŋ/",
"implication":"/ˌɪmpləˈkeɪʃən/",
"implications":"/ˌɪmpləˈkeɪʃənz/",
"implicit":"/ˌɪmˈplɪsət/",
"implicitly":"/ˌɪmˈplɪsətli/",
"implied":"/ˌɪmˈplaɪd/",
"implies":"/ˌɪmˈplaɪz/",
"implode":"/ˌɪmˈploʊd/",
"imploded":"/ˌɪmˈploʊdɪd/",
"implodes":"/ˌɪmˈploʊdz/",
"imploding":"/ˌɪmˈploʊdɪŋ/",
"implore":"/ˌɪmˈplɔɹ/",
"implored":"/ˌɪmˈplɔɹd/",
"implores":"/ˌɪmˈplɔɹz/",
"imploring":"/ˌɪmˈplɔɹɪŋ/",
"implosion":"/ˌɪmˈploʊʒən/",
"imply":"/ˌɪmˈplaɪ/",
"implying":"/ˌɪmˈplaɪɪŋ/",
"impolite":"/ˌɪmpəˈlaɪt/",
"impolitic":"/ˌɪmpɔˈlɪˌtɪk/",
"imponderable":"/ˌɪmˈpɑndɝəbəl/",
"imponderables":"/ˌɪmˈpɑndɝəbəlz/",
"import":"/ˈɪmˌpɔɹt/, /ˌɪmˈpɔɹt/",
"importance":"/ˌɪmˈpɔɹtəns/",
"important":"/ˌɪmˈpɔɹtənt/",
"importantly":"/ˌɪmˈpɔɹtəntli/",
"importation":"/ˌɪmpɔɹˈteɪʃən/",
"imported":"/ˌɪmˈpɔɹtɪd/",
"importer":"/ˌɪmˈpɔɹtɝ/",
"importers":"/ˌɪmˈpɔɹtɝz/",
"importers'":"/ˌɪmˈpɔɹtɝz/",
"importing":"/ˌɪmˈpɔɹtɪŋ/",
"imports":"/ˈɪmˌpɔɹts/, /ˌɪmˈpɔɹts/",
"imports'":"/ˈɪmpɔɹts/",
"impose":"/ˌɪmˈpoʊz/",
"imposed":"/ˌɪmˈpoʊzd/",
"imposes":"/ɪmˈpoʊzəz/, /ɪmˈpoʊzɪz/",
"imposing":"/ˌɪmˈpoʊzɪŋ/",
"imposition":"/ˌɪmpəˈzɪʃən/",
"impossibilities":"/ɪmˌpɔsɪˈbɪlɪtiz/",
"impossibility":"/ˌɪmˌpɔsɪˈbɪlɪti/",
"impossible":"/ˌɪmˈpɑsəbəl/",
"impossible's":"/ˌɪmˈpɑsəbəlz/",
"impossibly":"/ˌɪmˈpɑsəbli/",
"imposter":"/ˌɪmˈpɔstɝ/",
"impostor":"/ˌɪmˈpɔstɝ/",
"impostors":"/ˌɪmˈpɔstɝz/",
"impotence":"/ˈɪmpətəns/",
"impotent":"/ˈɪmpətənt/",
"impound":"/ˌɪmˈpaʊnd/",
"impounded":"/ˌɪmˈpaʊndɪd/",
"impounding":"/ˌɪmˈpaʊndɪŋ/",
"impoundment":"/ˌɪmˈpaʊndmənt/",
"impoundments":"/ˌɪmˈpaʊndmənts/",
"impounds":"/ˌɪmˈpaʊndz/",
"impoverish":"/ˌɪmˈpɑvɹɪʃ/",
"impoverished":"/ˌɪmˈpɑvɹɪʃt/",
"impoverishes":"/ˌɪmˈpɑvɹɪʃəz/",
"impoverishing":"/ˌɪmˈpɑvɹɪʃɪŋ/",
"impoverishment":"/ˌɪmˈpɑvɹɪʃmənt/",
"impracticable":"/ˌɪmˈpɹæktɪkəbəl/",
"impractical":"/ˌɪmˈpɹæktəkəl/, /ˌɪmˈpɹæktɪkəl/",
"imprecise":"/ˈɪmpɹəˌsaɪs/",
"impregnable":"/ˌɪmˈpɹɛɡnəbəl/",
"impregnate":"/ˌɪmˈpɹɛɡˌneɪt/",
"impregnated":"/ˌɪmˈpɹɛɡˌneɪtəd/",
"impregnates":"/ˌɪmˈpɹɛɡˌneɪts/",
"impregnating":"/ˌɪmˈpɹɛɡˌneɪtɪŋ/",
"impregnation":"/ˌɪmˈpɹɛɡˈneɪʃən/",
"impresario":"/ˌɪmpɹɪˈsɑɹiˌoʊ/",
"impress":"/ˈɪmˌpɹɛs/, /ˌɪmˈpɹɛs/",
"impressed":"/ˌɪmˈpɹɛst/",
"impresses":"/ˌɪmˈpɹɛsɪz/",
"impressing":"/ˌɪmˈpɹɛsɪŋ/",
"impression":"/ˌɪmˈpɹɛʃən/",
"impressionable":"/ˌɪmˈpɹɛʃənəbəl/",
"impressionism":"/ˌɪmˈpɹɛʃəˌnɪzəm/",
"impressionist":"/ˌɪmˈpɹɛʃənəst/, /ˌɪmˈpɹɛʃənɪst/",
"impressionistic":"/ˌɪmˌpɹɛʃəˈnɪstɪk/",
"impressionists":"/ˌɪmˈpɹɛʃənɪsts/",
"impressions":"/ˌɪmˈpɹɛʃənz/",
"impressive":"/ˌɪmˈpɹɛsɪv/",
"impressively":"/ˌɪmˈpɹɛsɪvli/",
"impressment":"/ˌɪmˈpɹɛsmənt/",
"imprimatur":"/ˌɪmpɹɪˈmɑtɝ/",
"imprimis":"/ˌɪmˈpɹimɪs/",
"imprint":"/ˈɪmpɹɪnt/, /ˌɪmˈpɹɪnt/",
"imprinted":"/ˌɪmˈpɹɪnɪd/, /ˌɪmˈpɹɪntɪd/",
"imprinting":"/ˌɪmˈpɹɪnɪŋ/, /ˌɪmˈpɹɪntɪŋ/",
"imprints":"/ˌɪmˈpɹɪnts/",
"imprison":"/ˌɪmˈpɹɪzən/",
"imprisoned":"/ˌɪmˈpɹɪzənd/",
"imprisoning":"/ˌɪmˈpɹɪzənɪŋ/",
"imprisonment":"/ˌɪmˈpɹɪzənmənt/",
"imprisons":"/ˌɪmˈpɹɪzənz/",
"improbable":"/ˌɪmˈpɹɑbəbəl/",
"improbably":"/ˌɪmˈpɹɑbəbli/",
"impromptu":"/ˌɪmˈpɹɑmptu/",
"improper":"/ˌɪmˈpɹɑpɝ/",
"improperly":"/ˌɪmˈpɹɑpɝli/",
"improprieties":"/ˌɪmpɹəˈpɹaɪətiz/",
"impropriety":"/ˌɪmpɹəˈpɹaɪəti/",
"improv":"/ˈɪmˌpɹɑv/",
"improve":"/ˌɪmˈpɹuv/",
"improved":"/ˌɪmˈpɹuvd/",
"improvement":"/ˌɪmˈpɹuvmənt/",
"improvements":"/ˌɪmˈpɹuvmənts/",
"improves":"/ˌɪmˈpɹuvz/",
"improving":"/ˌɪmˈpɹuvɪŋ/",
"improvisation":"/ˌɪmpɹɑvɪˈzeɪʃən/",
"improvisational":"/ˌɪmpɹɑvɪˈzeɪʃənəl/",
"improvisations":"/ˌɪmpɹɑvɪˈzeɪʃənz/",
"improvise":"/ˈɪmpɹəˌvaɪz/, /ˌɪmpɹəˈvaɪz/",
"improvised":"/ˈɪmpɹəˌvaɪzd/",
"improvises":"/ˈɪmpɹəˌvaɪzəz/, /ˌɪmpɹəˈvaɪzəz/",
"improvising":"/ˈɪmpɹəˌvaɪzɪŋ/",
"imprudence":"/ˌɪmˈpɹudəns/",
"imprudent":"/ˌɪmˈpɹudənt/",
"imprudently":"/ˌɪmˈpɹudəntli/",
"impson":"/ˈɪmpsən/",
"impugn":"/ˌɪmˈpjun/",
"impugned":"/ˌɪmˈpjund/",
"impugning":"/ˌɪmˈpjunɪŋ/",
"impugns":"/ˌɪmˈpjunz/",
"impulse":"/ˈɪmpəls/, /ˌɪmˈpəls/",
"impulses":"/ˈɪmpəlsɪz/, /ˌɪmˈpəlsɪz/",
"impulsive":"/ˌɪmˈpəlsɪv/",
"impulsively":"/ˌɪmˈpəlsɪvli/",
"impunity":"/ˌɪmˈpjunɪti/",
"impure":"/ˌɪmˈpjʊɹ/",
"impurities":"/ˌɪmˈpjʊɹətiz/",
"impurity":"/ˌɪmˈpjʊɹəti/",
"imputation":"/ˌɪmpjəˈteɪʃən/",
"impute":"/ˌɪmˈpjut/",
"imputed":"/ˌɪmˈpjutɪd/",
"imre":"/ˈɪmɹə/",
"imreg":"/ˌɪmˈɹɛɡ/",
"imreg's":"/ˌɪmˈɹɛɡz/",
"imrie":"/ˈɪmɝi/",
"imus":"/ˈaɪməs/",
"in":"/ˈɪn/, /ɪn/",
"in's":"/ˈɪnz/, /ɪnz/",
"in-app":"/ɪˈnæp/",
"in-depth":"/ɪnˈdɛpθ/",
"in-house":"/ɪnˈhaʊs/",
"in-law":"/ɪnˈlɔ/",
"in-laws":"/ɪnˈlɔz/",
"in-memory":"/ɪnˈmɛmɝi/",
"in-person":"/ɪnˈpɝsən/",
"in.":"/ˈɪn/, /ˈɪntʃ/",
"ina":"/ˈinə/",
"inability":"/ˌɪnəˈbɪlɪti/",
"inabinet":"/ˌɪnəˈbɪnɪt/",
"inaccessibility":"/ˌɪnəkˌsɛsəˈbɪləti/",
"inaccessible":"/ˌɪnəkˈsɛsəbəl/",
"inaccuracies":"/ˌɪˈnækjɝˌæsiz/",
"inaccuracy":"/ˌɪˈnækjɝəsi/",
"inaccurate":"/ˌɪˈnækjɝət/",
"inaccurately":"/ˌɪˈnækjɝətli/",
"inacom":"/ˈaɪnəˌkɑm/, /ˈɪnəˌkɑm/",
"inacomp":"/ˈaɪnəˌkɑmp/, /ˈɪnəˌkɑmp/",
"inaction":"/ˌɪˈnækʃən/",
"inactivate":"/ˌɪˈnæktɪˌveɪt/",
"inactivated":"/ˌɪˈnæktɪˌveɪtɪd/",
"inactivates":"/ˌɪˈnæktɪˌveɪts/",
"inactivation":"/ˌɪˌnæktɪˈveɪʃən/",
"inactive":"/ˌɪˈnæktɪv/",
"inactivity":"/ˌɪnækˈtɪvɪti/",
"inadequacies":"/ˌɪˈnædəkwəsiz/",
"inadequacy":"/ˌɪˈnædɪkwəsi/",
"inadequate":"/ˌɪˈnædəˌkweɪt/, /ˌɪˈnædəkwət/",
"inadequately":"/ˌɪˈnædəkwətli/",
"inadmissible":"/ˌɪnædˈmɪsəbəl/, /ˌɪnədˈmɪsəbəl/",
"inadmissibly":"/ˌɪnædˈmɪsəbli/, /ˌɪnədˈmɪsəbli/",
"inadvertence":"/ˌɪnædˈvɝtəns/, /ˌɪnədˈvɝtəns/",
"inadvertent":"/ˌɪnædˈvɝtənt/, /ˌɪnədˈvɝtənt/",
"inadvertently":"/ˌɪnædˈvɝtəntli/, /ˌɪnədˈvɝtəntli/",
"inadvisable":"/ˌɪnædˈvaɪzəbəl/, /ˌɪnədˈvaɪzəbəl/",
"inaez":"/ˌɪˈnæz/, /ˌɪˈneɪz/",
"inaki":"/ˌɪˈnɑki/",
"inalienable":"/ˌɪˈneɪljənəbəl/",
"inamura":"/ˌɪnəˈmʊɹə/",
"inane":"/ˌɪˈneɪn/",
"inanimate":"/ˌɪˈnænəmət/",
"inapplicable":"/ˌɪˈnæplɪkəbəl/",
"inappropriate":"/ˌɪnəˈpɹoʊpɹiɪt/",
"inappropriately":"/ˌɪnəˈpɹɑpɹiətli/",
"inarticulate":"/ˌɪnɑɹˈtɪkjələt/",
"inasmuch":"/ˌɪˈnæsmək/",
"inattention":"/ˌɪnəˈtɛntʃən/",
"inattentive":"/ˌɪnəˈtɛntɪv/",
"inaudible":"/ˌɪˈnɔdəbəl/",
"inaudibly":"/ˌɪˈnɔdəbli/",
"inaugural":"/ˌɪˈnɔɡɝəl/, /ˌɪˈnɔɡjɝəl/",
"inaugurate":"/ɪˈnɔɡjɝeɪt/, /ɪˈnɔɡjɝɪt/",
"inaugurated":"/ɪˈnɔɡɝˌeɪtɪd/, /ɪˈnɔɡjɝˌeɪtɪd/",
"inaugurates":"/ɪˈnɔɡjɝɪts/",
"inaugurating":"/ɪˈnɔɡjɝˌeɪtɪŋ/",
"inauguration":"/ɪˌnɔɡjɝˈeɪʃən/",
"inaugurations":"/ɪˌnɔɡjɝˈeɪʃənz/",
"inauspicious":"/ˌɪˌnaʊˈspɪʃɪs/",
"inbio":"/ˌɪnˈbaɪoʊ/",
"inboard":"/ˈɪnˌbɔɹd/",
"inboden":"/ˈɪnboʊdən/",
"inbody":"/ˈɪnbɑdi/",
"inborn":"/ˈɪnˌbɔɹn/",
"inbound":"/ˈɪnbaʊnd/, /ˌɪnˈbaʊnd/",
"inbox":"/ˈɪnˌbɑks/",
"inbred":"/ˈɪnˌbɹɛd/",
"inbreed":"/ˈɪnˌbɹid/",
"inbreeding":"/ˌɪnˈbɹidɪŋ/",
"inc":"/ˈɪŋk/",
"inc.":"/ˈɪŋk/, /ɪŋˈkɔɹpɔɹeɪtəd/",
"inc.'s":"/ˈɪŋks/",
"inca":"/ˈɪŋkə/",
"incalculable":"/ˌɪnˈkælkjələbəl/",
"incandescent":"/ˌɪnkənˈdɛsənt/",
"incant":"/ˌɪnˈkænt/",
"incantation":"/ˌɪnˈkænˈteɪʃən/",
"incantatory":"/ˌɪnˈkæntəˌtɔɹi/",
"incapable":"/ˌɪnˈkeɪpəbəl/",
"incapacitate":"/ˌɪnkəˈpæsɪˌteɪt/",
"incapacitated":"/ˌɪnkəˈpæsɪˌteɪtɪd/",
"incapacitating":"/ˌɪnkəˈpæsɪˌteɪtɪŋ/",
"incapacitation":"/ˌɪnkəˌpæsɪˈteɪʃən/",
"incapacity":"/ˌɪnkəˈpæsəti/",
"incarcerate":"/ˌɪnˈkɑɹsɝˌeɪt/",
"incarcerated":"/ˌɪnˈkɑɹsɝˌeɪtɪd/",
"incarcerates":"/ˌɪnˈkɑɹsɝˌeɪts/",
"incarcerating":"/ˌɪnˈkɑɹsɝˌeɪtɪŋ/",
"incarceration":"/ˌɪnˌkɑɹsɝˈeɪʃən/",
"incarnate":"/ˌɪnˈkɑɹˌneɪt/, /ˌɪnˈkɑɹnət/",
"incarnation":"/ˌɪnˈkɑɹˈneɪʃən/",
"incarnations":"/ˌɪnkɑɹˈneɪʃənz/",
"incas":"/ˈɪŋkəz/",
"incase":"/ˌɪnˈkeɪs/",
"incata":"/ˌɪŋˈkɑtə/",
"incata's":"/ˌɪŋˈkɑtəz/",
"ince":"/ˈɪns/",
"incendiary":"/ˌɪnˈsɛndiɛɹi/",
"incense":"/ˈɪnˌsɛns/, /ˌɪnˈsɛns/",
"incensed":"/ˈɪnˌsɛnst/",
"incentive":"/ˌɪnˈsɛnɪv/, /ˌɪnˈsɛntɪv/",
"incentives":"/ˌɪnˈsɛntɪvz/, /ˌɪnˈsɪnɪvz/",
"inception":"/ˌɪnˈsɛpʃən/",
"incessant":"/ˌɪnˈsɛsənt/",
"incessantly":"/ˌɪnˈsɛsəntli/",
"incest":"/ˈɪnˌsɛst/",
"incestuous":"/ˌɪnˈsɛstʃwəs/",
"inch":"/ˈɪntʃ/",
"inchcape":"/ˈɪntʃˌkeɪp/",
"inched":"/ˈɪntʃt/",
"incheon":"/ˈɪntʃɔn/",
"inches":"/ˈɪntʃəz/, /ˈɪntʃɪz/",
"inches'":"/ˈɪntʃəz/, /ˈɪntʃɪz/",
"inching":"/ˈɪntʃɪŋ/",
"inchoate":"/ˌɪnˈkoʊət/",
"inchon":"/ˈɪntʃɔn/",
"incidence":"/ˈɪnsədəns/, /ˈɪnsɪdəns/",
"incidences":"/ˈɪnsədənsɪz/",
"incident":"/ˈɪnsədənt/",
"incidental":"/ˌɪnsɪˈdɛntəl/",
"incidentally":"/ˌɪnsɪˈdɛntəli/, /ˌɪnsɪˈdɛntli/",
"incidentals":"/ˌɪnsɪˈdɛntəlz/",
"incidents":"/ˈɪnsədənts/",
"incinerate":"/ˌɪnˈsɪnɝˌeɪt/",
"incinerated":"/ˌɪnˈsɪnɝˌeɪtɪd/",
"incinerating":"/ˌɪnˈsɪnɝˌeɪtɪŋ/",
"incineration":"/ˌɪnˈsɪnɝˌeɪʃən/",
"incinerator":"/ˌɪnˈsɪnɝˌeɪtɝ/",
"incinerators":"/ˌɪnˈsɪnɝˌeɪtɝz/",
"incipient":"/ˌɪnˈsɪpiənt/",
"incirlik":"/ˌɪnˈsɝlɪk/",
"incise":"/ˌɪnˈsaɪz/",
"incised":"/ˌɪnˈsaɪzd/",
"incision":"/ˌɪnˈsɪʒən/",
"incisions":"/ˌɪnˈsɪʒənz/",
"incisive":"/ˌɪnˈsaɪsɪv/",
"incisor":"/ˌɪnˈsaɪzɝ/",
"incisors":"/ˌɪnˈsaɪzɝz/",
"incite":"/ˌɪnˈsaɪt/",
"incited":"/ˌɪnˈsaɪtɪd/",
"incitement":"/ˌɪnˈsaɪtmənt/",
"incitements":"/ˌɪnˈsaɪtmənts/",
"incites":"/ˌɪnˈsaɪts/",
"inciting":"/ˌɪnˈsaɪtɪŋ/",
"incivility":"/ˌɪnsɪˈvɪlɪti/",
"inclement":"/ˈɪnklɪmənt/, /ˌɪnˈklɛmənt/",
"inclination":"/ˌɪnkləˈneɪʃən/",
"inclinations":"/ˌɪnkləˈneɪʃənz/",
"incline":"/ˈɪnklaɪn/, /ˌɪnˈklaɪn/",
"inclined":"/ˌɪnˈklaɪnd/",
"inclines":"/ˈɪnklaɪnz/, /ˌɪnˈklaɪnz/",
"inclosure":"/ˌɪnˈkloʊʒɝ/",
"include":"/ˌɪnˈklud/",
"included":"/ˌɪnˈkludəd/, /ˌɪnˈkludɪd/",
"includes":"/ˌɪnˈkludz/",
"including":"/ˌɪnˈkludɪŋ/",
"inclusion":"/ˌɪnˈkluʒən/",
"inclusions":"/ˌɪnˈkluʒənz/",
"inclusive":"/ˌɪnˈklusɪv/",
"inclusiveness":"/ˌɪnˈklusɪvnɛs/, /ˌɪnˈklusɪvnɪs/",
"inco":"/ˌɪnˈkoʊ/",
"inco's":"/ˈɪŋkoʊz/",
"incognito":"/ˌɪnkɔɡˈnitoʊ/",
"incoherence":"/ˌɪnkoʊˈhɪɹəns/",
"incoherent":"/ˌɪnkoʊˈhɪɹənt/",
"incoherently":"/ˌɪnkoʊˈhɪɹəntli/",
"incom":"/ˈɪŋkɑm/",
"income":"/ˈɪnˌkəm/",
"incomes":"/ˈɪnˌkəmz/",
"incoming":"/ˈɪnˌkəmɪŋ/",
"incommunicado":"/ˌɪnkəmˌjunəˈkɑdoʊ/",
"incomparable":"/ˌɪnˈkɑmpɝəbəl/",
"incomparably":"/ˌɪnˈkɑmpɝəbli/",
"incompatibility":"/ˌɪnˌkɑmpətɪˈbɪlɪti/",
"incompatible":"/ˌɪnkəmˈpætəbəl/",
"incompetence":"/ˌɪnˈkɑmpətəns/",
"incompetency":"/ˌɪnˈkɑmpətənsi/",
"incompetent":"/ˌɪnˈkɑmpətənt/",
"incompetently":"/ˌɪnˈkɑmpətəntli/",
"incompetents":"/ˌɪŋˈkɑmpətənts/",
"incomplete":"/ˌɪnkəmˈplit/",
"incomprehensible":"/ˌɪŋˌkɑmpɹəˈhɛnsɪbəl/",
"incomprehensibly":"/ˌɪŋˌkɑmpɹəˈhɛnsɪbli/",
"incompressible":"/ˌɪnkəmˈpɹɛsəbəl/",
"inconceivable":"/ˌɪnkənˈsivəbəl/",
"inconclusive":"/ˌɪnkənˈklusɪv/",
"inconclusively":"/ˌɪŋˈkɑnklusɪvli/",
"incongruity":"/ˌɪŋkɔŋˈɹuɪti/",
"incongruous":"/ˌɪŋˈkɔŋɹuəs/",
"incongruously":"/ˌɪŋˈkɔŋɹuəsli/",
"inconsequential":"/ˌɪŋˌkɑnsəˈkwɛntʃəl/",
"inconsistencies":"/ˌɪŋˈkɑnsɪˌstɛnsiz/",
"inconsistency":"/ˌɪnkənˈsɪstənsi/",
"inconsistent":"/ˌɪnkənˈsɪstənt/",
"inconspicuous":"/ˌɪŋˈkɑnspɪkwəs/",
"inconstancy":"/ˌɪnˈkɑnstənsi/",
"incontinence":"/ˌɪnˈkɑntənəns/",
"incontinent":"/ˌɪnˈkɑntənənt/",
"incontrovertible":"/ˌɪŋˌkɑntɹoʊˈvɝtɪbəl/",
"inconvenience":"/ˌɪnkənˈvinjəns/",
"inconvenienced":"/ˌɪnkənˈvinjənst/",
"inconveniences":"/ˌɪnkənˈvinjənsɪz/",
"inconvenient":"/ˌɪnkənˈvinjənt/",
"incoordination":"/ˌɪnˌkoʊˈɔɹdəˌneɪʃən/",
"incorporate":"/ˌɪnˈkɔɹpɝˌeɪt/",
"incorporated":"/ˌɪnˈkɔɹpɝˌeɪtɪd/, /ɪnˈkɔɹpɝˌeɪtɪd/",
"incorporated's":"/ˌɪnˈkɔɹpɝˌeɪtɪdz/",
"incorporates":"/ˌɪnˈkɔɹpɝˌeɪts/",
"incorporating":"/ˌɪnˈkɔɹpɝˌeɪtɪŋ/",
"incorporation":"/ˌɪnˌkɔɹpɝˈeɪʃən/",
"incorporation's":"/ˌɪnˌkɔɹpɝˈeɪʃənz/",
"incorporations":"/ˌɪnˌkɔɹpɝˈeɪʃənz/",
"incorrect":"/ˌɪnkɝˈɛkt/",
"incorrectly":"/ˌɪnkɝˈɛktli/",
"incorrigible":"/ˌɪnˈkɑɹədʒəbəl/",
"incorvaia":"/ˌɪnkɔɹˈvɑjə/",
"increase":"/ˈɪnˌkɹis/, /ˌɪnˈkɹis/",
"increased":"/ˈɪnˌkɹist/, /ˌɪnˈkɹist/",
"increases":"/ˈɪnˌkɹisɪz/, /ˈɪnkɹisəz/, /ɪnˈkɹisəz/",
"increasing":"/ˌɪnˈkɹisɪŋ/",
"increasingly":"/ɪnˈkɹisɪŋɡli/, /ɪnˈkɹisɪŋli/",
"incredible":"/ˌɪnˈkɹɛdəbəl/",
"incredibly":"/ˌɪnˈkɹɛdəbli/",
"incredulity":"/ˌɪnkɹəˈdulɪti/",
"incredulous":"/ˌɪnˈkɹɛdʒələs/",
"increment":"/ˈɪnkɹəmənt/",
"incremental":"/ˌɪnkɹəˈmɛntəl/",
"incrementalism":"/ˌɪnkɹəˈmɛntəˌlɪzm/",
"incrementally":"/ˌɪnkɹəˈmɛntəˌli/",
"incremented":"/ˈɪnkɹəˌmɛntɪd/",
"increments":"/ˈɪŋkɹəmənts/",
"incriminate":"/ˌɪnˈkɹɪməˌneɪt/",
"incriminating":"/ˌɪnˈkɹɪməˌneɪtɪŋ/",
"incrimination":"/ˌɪnˌkɹɪməˈneɪʃən/",
"incrust":"/ˌɪnˈkɹəst/",
"incrustation":"/ˌɪnkɹəˈsteɪʃən/",
"incstar":"/ˈɪŋkˌstɑɹ/",
"incubate":"/ˈɪnkjəˌbeɪt/",
"incubates":"/ˈɪnkjəˌbeɪts/",
"incubating":"/ˈɪnkjəˌbeɪtɪŋ/",
"incubation":"/ˌɪŋkjuˈbeɪʃən/",
"incubator":"/ˈɪŋkjəˌbeɪtɝ/",
"incubators":"/ˈɪŋkjuˌbeɪtɝz/",
"inculcate":"/ˈɪŋkəlˌkeɪt/",
"inculcated":"/ˈɪŋkəlˌkeɪtəd/",
"inculcates":"/ˈɪŋkəlˌkeɪts/",
"incumbency":"/ˌɪnˈkəmbənsi/",
"incumbent":"/ˌɪnˈkəmbənt/",
"incumbent's":"/ˌɪnˈkəmbənts/",
"incumbents":"/ˌɪnˈkəmbənts/",
"incur":"/ˌɪnˈkɝ/",
"incurable":"/ˌɪnˈkjʊɹəbəl/",
"incurred":"/ˌɪnˈkɝd/",
"incurring":"/ˌɪnˈkɝɪŋ/",
"incurs":"/ˌɪnˈkɝz/",
"incursion":"/ˌɪnˈkɝʒən/",
"incursions":"/ˌɪnˈkɝʒənz/",
"inda":"/ˈində/",
"indaba":"/ˌɪnˈdɑbə/",
"indal":"/ˈɪndəl/",
"indata":"/ˌɪnˈdɑtə/",
"indebted":"/ˌɪnˈdɛtɪd/, /ɪnˈdɛtɪd/",
"indebtedness":"/ˌɪnˈdɛtɪdnɪs/",
"indecency":"/ˌɪnˈdisənsi/",
"indecent":"/ˌɪnˈdisənt/",
"indecision":"/ˌɪndɪˈsɪʒən/",
"indecisive":"/ˌɪndɪˈsaɪsɪv/",
"indecisiveness":"/ˌɪnˈdɛsɪsɪvnəs/",
"indeed":"/ˌɪnˈdid/",
"indefatigable":"/ˌɪndɪˈfætɪɡəbəl/",
"indefeasible":"/ˌɪdəˈfizəbəl/",
"indefensible":"/ˌɪndɪˈfɛnsəbəl/",
"indefinable":"/ˌɪndɪˈfaɪnəbəl/",
"indefinite":"/ˌɪnˈdɛfənət/",
"indefinitely":"/ˌɪnˈdɛfənətli/",
"indelible":"/ˌɪnˈdɛlɪbəl/",
"indelibly":"/ˌɪnˈdɛləbli/",
"indelicate":"/ˌɪnˈdɛlɪkət/",
"indelicato":"/ˌɪndɛliˈkɑtoʊ/",
"indemnification":"/ˌɪnˌdɛmnəfɪˈkeɪʃən/",
"indemnified":"/ˌɪnˈdɛmnəˌfaɪd/",
"indemnify":"/ˌɪnˈdɛmnəˌfaɪ/",
"indemnifying":"/ˌɪnˌdɛmnɪˈfaɪɪŋ/",
"indemnities":"/ˌɪnˈdɛmnɪtiz/",
"indemnity":"/ˌɪnˈdɛmnəti/, /ˌɪnˈdɛmnɪti/",
"indent":"/ˌɪnˈdɛnt/",
"indentation":"/ˌɪnˌdɛnˈteɪʃən/",
"indenture":"/ˌɪnˈdɛntʃɝ/",
"indentured":"/ˌɪnˈdɛntʃɝd/",
"indentures":"/ˌɪnˈdɛntʃɝz/",
"independence":"/ˌɪndɪˈpɛndəns/",
"independence's":"/ˌɪndɪˈpɛndənsɪz/",
"independent":"/ˌɪndɪˈpɛndənt/",
"independently":"/ˌɪndɪˈpɛndəntli/",
"independents":"/ˌɪndɪˈpɛndənts/",
"inderal":"/ˈɪndɝəl/",
"indescribable":"/ˌɪndɪsˈkɹaɪbəbəl/",
"indestructibility":"/ˌɪndəˌstɹəktɪˈbɪlɪti/",
"indestructible":"/ˌɪndəˈstɹəktɪbəl/",
"indeterminate":"/ˌɪndɪˈtɝmɪnɪt/",
"index":"/ˈɪndɛks/",
"index's":"/ˈɪndɛksɪz/",
"indexation":"/ˈɪnˌdɛkˈseɪʃən/",
"indexed":"/ˈɪndɛkst/",
"indexer":"/ˈɪnˌdɛksɝ/",
"indexers":"/ˈɪnˌdɛksɝz/",
"indexes":"/ˈɪndɛksɪz/",
"indexing":"/ˈɪndɛksɪŋ/",
"india":"/ˈɪndiə/",
"india's":"/ˈɪndiəz/",
"indiaia":"/ˌɪndiˈaɪə/",
"indian":"/ˈɪndiən/",
"indian's":"/ˈɪndiənz/",
"indiana":"/ˌɪndiˈænə/",
"indiana's":"/ˌɪndiˈænəz/",
"indianapolis":"/ˌɪndiəˈnæpəlɪs/",
"indianapolis's":"/ˌɪndiəˈnæpəlɪsɪz/",
"indianian":"/ˌɪndiˈæniən/",
"indianians":"/ˌɪndiˈæniənz/",
"indianola":"/ˈɪndiəˈnoʊlə/",
"indians":"/ˈɪndiənz/",
"indians'":"/ˈɪndiənz/",
"indic":"/ˈɪndɪk/",
"indica":"/ˈɪdəkə/",
"indicate":"/ˈɪndəˌkeɪt/",
"indicated":"/ˈɪndəˌkeɪtəd/, /ˈɪndəˌkeɪtɪd/",
"indicates":"/ˈɪndɪˌkeɪts/",
"indicating":"/ˈɪndəˌkeɪtɪŋ/",
"indication":"/ˌɪndəˈkeɪʃən/",
"indications":"/ˌɪndəˈkeɪʃənz/",
"indicative":"/ˌɪnˈdɪkətɪv/",
"indicator":"/ˈɪndəˌkeɪtɝ/",
"indicators":"/ˈɪndəˌkeɪtɝz/",
"indices":"/ˈɪndəsɪz/, /ˈɪndɪˌsiz/",
"indicia":"/ˌɪnˈdɪsjə/",
"indict":"/ˌɪnˈdaɪt/",
"indicted":"/ˌɪnˈdaɪtɪd/",
"indicting":"/ˌɪnˈdaɪtɪŋ/",
"indictment":"/ˌɪnˈdaɪtmənt/",
"indictments":"/ˌɪnˈdaɪtmənts/",
"indie":"/ˈɪndi/",
"indies":"/ˈɪndiz/",
"indifference":"/ˌɪnˈdɪfɝəns/, /ˌɪnˈdɪfɹəns/",
"indifferent":"/ˌɪnˈdɪfɝənt/, /ˌɪnˈdɪfɹənt/",
"indigenous":"/ˌɪnˈdɪdʒənəs/",
"indigenously":"/ˌɪnˈdɪdʒənəˌsli/",
"indigent":"/ˈɪndɪdʒənt/",
"indigents":"/ˈɪndɪdʒənts/",
"indigest":"/ˌɪndaɪˈdʒɛst/, /ˌɪndəˈdʒɛst/",
"indigestion":"/ˌɪndaɪˈdʒɛstʃən/",
"indignant":"/ˌɪnˈdɪɡnənt/",
"indignantly":"/ˌɪnˈdɪɡnəntˌli/",
"indignation":"/ˌɪndɪɡˈneɪʃən/",
"indignities":"/ˌɪnˈdɪɡnətiz/",
"indignity":"/ˌɪnˈdɪɡnəˌti/",
"indigo":"/ˈɪndəˌɡoʊ/, /ˈɪndɪˌɡoʊ/",
"indira":"/ˌɪnˈdɪɹə/",
"indirect":"/ˌɪndɝˈɛkt/",
"indirectly":"/ˌɪndɝˈɛktˌli/",
"indiscreet":"/ˌɪndɪsˈkɹit/",
"indiscretion":"/ˌɪndɪsˈkɹɛʃən/",
"indiscretions":"/ˌɪndɪsˈkɹɛʃənz/",
"indiscriminate":"/ˌɪndɪsˈkɹɪmənət/",
"indiscriminately":"/ˌɪndɪsˈkɹɪmənətˌli/",
"indispensable":"/ˌɪndɪˈspɛnsəbəl/",
"indispensible":"/ˌɪndɪˈspɛnsɪbəl/",
"indisputable":"/ˌɪndɪˈspjutəbəl/",
"indisputably":"/ˌɪnˈdɪspjuˌtæˌbli/",
"indistinct":"/ˌɪndɪˈstɪŋkt/",
"indistinguishable":"/ˌɪndɪˈstɪŋɡwɪʃəbəl/",
"indite":"/ˌɪnˈdaɪt/",
"indited":"/ˌɪnˈdaɪtɪd/",
"indium":"/ˈɪndiəm/",
"individual":"/ˌɪndəˈvɪdʒəwəl/",
"individual's":"/ˌɪndəˈvɪdʒəwəlz/",
"individualism":"/ˌɪndɪvɪˈduəˌlɪzəm/",
"individualist":"/ˌɪndɪvɪˈduəlɪst/",
"individualistic":"/ˌɪndɪˌvɪdʒuəˈlɪstɪk/",
"individualists":"/ˌɪndəˈvɪdʒuəlɪsts/",
"individuality":"/ˌɪnˌdɪvɪdʒuˈælɪti/",
"individualize":"/ˌɪndɪˈvɪdʒəlaɪz/, /ˌɪndɪˈvɪdʒuəlaɪz/",
"individualized":"/ˌɪndɪˈvɪdʒəlaɪzd/, /ˌɪndɪˈvɪdʒuəlaɪzd/",
"individually":"/ˌɪndɪˈvɪdʒəli/, /ˌɪndɪˈvɪdʒuəli/",
"individuals":"/ˌɪndəˈvɪdʒəwəlz/",
"individuals'":"/ˌɪndɪˈvɪdʒəwəlz/",
"indivisible":"/ˌɪndɪˈvɪsɪbəl/",
"indo":"/ˈɪndoʊ/",
"indo-european":"/ˌɪndoʊˌjʊɹəˈpiən/",
"indochina":"/ˌɪndoʊˈtʃaɪnə/",
"indochinese":"/ˌɪndoʊˌtʃaɪˈniz/",
"indoctrinate":"/ɪnˈdɑktɹəˌneɪt/",
"indoctrinated":"/ˌɪnˈdɑktɹəˌneɪtɪd/",
"indoctrination":"/ˌɪnˌdɑktɹəˈneɪʃən/",
"indolent":"/ˈɪndələnt/",
"indomitable":"/ˌɪnˈdɑmətəbəl/",
"indonesia":"/ˌɪn.dəˈniː.ʒə/",
"indonesia's":"/ˌɪndoʊˈniʒəz/",
"indonesian":"/ˌɪndoʊˈniʒən/",
"indonesians":"/ˌɪndoʊˈnisiənz/, /ˌɪndoʊˈniʒənz/",
"indoor":"/ˈɪnˌdɔɹ/",
"indoors":"/ˈɪnˌdɔɹz/",
"indosuez":"/ˈɪndoʊsuˈeɪz/, /ˈɪndoʊsuɛz/",
"indovina":"/ˌɪndoʊˈvinə/",
"indri":"/ˌɪnˈdɹi/",
"indubious":"/ˌɪˈdubiəs/",
"indubiously":"/ˌɪˈdubiəsli/",
"induce":"/ˌɪnˈdus/",
"induced":"/ˌɪnˈdust/",
"inducement":"/ˌɪnˈdusmənt/",
"inducements":"/ˌɪnˈdusmənts/",
"induces":"/ˌɪnˈdusɪz/",
"inducing":"/ˌɪnˈdusɪŋ/",
"induct":"/ˌɪnˈdəkt/",
"inductance":"/ˌɪnˈdəktəns/",
"inducted":"/ˌɪnˈdəktɪd/",
"inductee":"/ˌɪnˈdəkˈti/",
"inductees":"/ˌɪnˈdəkˈtiz/",
"induction":"/ˌɪnˈdəkʃən/",
"inductive":"/ˌɪnˈdəktɪv/",
"inductor":"/ˌɪnˈdəktɝ/",
"indulge":"/ˌɪnˈdəldʒ/",
"indulged":"/ˌɪnˈdəldʒd/",
"indulgence":"/ˌɪnˈdəldʒəns/",
"indulgences":"/ɪnˈdəldʒənsəz/, /ɪnˈdəldʒənsɪz/",
"indulgent":"/ˌɪnˈdəldʒənt/",
"indulges":"/ˌɪnˈdəldʒɪz/",
"indulging":"/ˌɪnˈdəldʒɪŋ/",
"indus":"/ˈɪndəs/",
"industri":"/ˌɪnˈdəstɹi/",
"industria":"/ˌɪnˈdəstɹiə/",
"industrial":"/ˌɪnˈdəstɹiəl/",
"industrial's":"/ˌɪnˈdəstɹiəlz/",
"industriale":"/ˌɪndəstɹiˈɑli/",
"industriali":"/ˌɪnˌdəstɹiˈɑli/",
"industrialist":"/ˌɪnˈdəstɹiəlɪst/",
"industrialists":"/ˌɪnˈdəstɹiəlɪsts/",
"industrialization":"/ˌɪnˌdəstɹiəlɪˈzeɪʃən/",
"industrialize":"/ˌɪnˈdəstɹiəˌlaɪz/",
"industrialized":"/ˌɪnˈdəstɹiəˌlaɪzd/",
"industrializing":"/ˌɪnˈdəstɹiəˌlaɪzɪŋ/",
"industrially":"/ˌɪnˈdəstɹiəli/",
"industrials":"/ˌɪnˈdəstɹiəlz/",
"industrials'":"/ˌɪnˈdəstɹiəlz/",
"industrie":"/ˈɪndəstɹi/",
"industrielle":"/ˌɪnˈdəstɹiəˌlɛ/, /ˌɪnˌdəstɹiˈɛl/",
"industrier":"/ˈɪndəˌstɹiɝ/",
"industries":"/ˈɪndəstɹiz/",
"industries'":"/ˈɪndəstɹiz/",
"industrious":"/ˌɪnˈdəstɹiəs/",
"industrivaerden":"/ˈɪndəstɹiˌvɛɹdən/",
"industry":"/ˈɪndəstɹi/",
"industry's":"/ˈɪndəstɹiz/",
"industrywide":"/ˈɪndəstɹiˌwaɪd/",
"indy":"/ˈɪndi/",
"indyk":"/ˈɪndɪk/",
"inebriate":"/ˌɪˈnɛbɹiˌeɪt/",
"inebriated":"/ˌɪˈnɛbɹiˌeɪtəd/",
"inebriates":"/ˌɪˈnɛbɹiˌeɪts/",
"inebriating":"/ˌɪˈnɛbɹiˌeɪtɪŋ/",
"inedible":"/ˌɪˈnɛdəbəl/",
"ineffable":"/ˌɪˈnɛfəbəl/",
"ineffective":"/ˌɪnɪˈfɛktɪv/",
"ineffectiveness":"/ˌɪnəˈfɛktɪvnəs/",
"ineffectual":"/ˌɪnəˈfɛktʃuəl/",
"inefficiencies":"/ˌɪnɪˈfɪʃənsiz/",
"inefficiency":"/ˌɪnɪˈfɪʃənsi/",
"inefficient":"/ˌɪnɪˈfɪʃənt/",
"inefficiently":"/ˌɪnɪˈfɪʃəntli/",
"inelastic":"/ˌɪnəˈlæstɪk/",
"ineligible":"/ˌɪˈnɛlɪdʒəbəl/",
"ineluctible":"/ˌɪnəˈləktəbəl/",
"inept":"/ˌɪˈnɛpt/",
"ineptitude":"/ˌɪˈnɛptɪˌtud/",
"ineptly":"/ˌɪˈnɛptli/",
"ineptness":"/ˌɪˈnɛptnɪs/",
"inequalities":"/ˈɪniˈkwɑlɪtiz/, /ˌɪnəˈkwɑlɪtiz/, /ˌɪnɪˈkwɑlɪtiz/",
"inequality":"/ˈɪniˈkwɑləti/, /ˌɪnəˈkwɑləti/, /ˌɪnɪˈkwɑləti/",
"inequitable":"/ˌɪˈnɛkwətəbəl/",
"inequities":"/ˌɪˈnɛkwətiz/",
"inequity":"/ˌɪˈnɛkwəti/",
"ineradicable":"/ˌɪnɝˈædəˌkəbəl/",
"inerco":"/ˌɪˈnɝkoʊ/",
"inert":"/ˌɪˈnɝt/",
"inertia":"/ˌɪˈnɝʃə/",
"inertial":"/ˌɪˈnɝʃəl/",
"inertness":"/ˌɪˈnɝtnəs/",
"ines":"/ˈɪnɪs/, /ˌɪˈnɛs/",
"inescapable":"/ˌɪnɪˈskeɪpəbəl/",
"inescapably":"/ˌɪnɪˈskeɪpəbli/",
"inevitability":"/ˌɪˌnɛvɪtəˈbɪlɪti/",
"inevitable":"/ˌɪˈnɛvətəbəl/",
"inevitably":"/ˌɪˈnɛvətəbli/",
"inexact":"/ˌɪnɪɡˈzækt/",
"inexcusable":"/ˌɪnɪkˈskjuzəbəl/",
"inexcusably":"/ˌɪnɪkˈskjuzəbli/",
"inexhaustible":"/ˌɪnɪɡˈzɔstəbəl/",
"inexorable":"/ˌɪˈnɛksɝəbəl/",
"inexorably":"/ˌɪˈnɛksɝəbli/",
"inexpensive":"/ˌɪnɪkˈspɛnsɪv/",
"inexpensively":"/ˌɪnəkˈspɛnsɪvli/",
"inexperience":"/ˌɪnɪkˈspɪɹiəns/",
"inexperienced":"/ɪnɪkˈspɪɹiənst/",
"inexplicable":"/ˌɪnəksˈplɪsəbəl/",
"inexplicably":"/ˌɪnɪksˈplɪkəbli/",
"inextricable":"/ˌɪˈnɛkstɹɪˌkəbəl/",
"inextricably":"/ˌɪˈnɛkstɹɪˌkəbli/",
"inez":"/ˌɪˈnɛz/",
"infallibility":"/ˌɪnˌfælɪˈbɪlɪti/",
"infallible":"/ˌɪnˈfæləbəl/",
"infamous":"/ˈɪnfəməs/",
"infamy":"/ˈɪnfəmi/",
"infancy":"/ˈɪnfənsi/",
"infant":"/ˈɪnfənt/",
"infant's":"/ˈɪnfənts/",
"infante":"/ˌɪnˈfɑnˌteɪ/",
"infanticide":"/ˌɪnˈfæntəˌsaɪd/",
"infanticides":"/ˌɪnˈfæntəˌsaɪdz/",
"infantile":"/ˈɪnfəntɪl/",
"infantino":"/ˌɪnfɑnˈtiˌnoʊ/",
"infantry":"/ˈɪnfəntɹi/",
"infantryman":"/ˈɪnfæntɹimən/",
"infantrymen":"/ˈɪnfæntɹimən/",
"infants":"/ˈɪnfənts/",
"infants'":"/ˈɪnfənts/",
"infarction":"/ˌɪnˈfɑɹkʃən/",
"infatuate":"/ˌɪnˈfætʃuˌeɪt/",
"infatuated":"/ˌɪnˈfætʃuˌeɪtɪd/",
"infatuates":"/ˌɪnˈfætʃuˌeɪts/",
"infatuating":"/ˌɪnˈfætʃuˌeɪtɪŋ/",
"infatuation":"/ˌɪnˌfætʃuˈeɪʃən/",
"infeasible":"/ˌɪnˈfizəbəl/",
"infect":"/ˌɪnˈfɛkt/",
"infected":"/ˌɪnˈfɛktɪd/",
"infecting":"/ˌɪnˈfɛktɪŋ/",
"infection":"/ˌɪnˈfɛkʃən/",
"infections":"/ˌɪnˈfɛkʃənz/",
"infectious":"/ˌɪnˈfɛkʃəs/",
"infective":"/ˌɪnˈfɛktɪv/",
"infects":"/ˌɪnˈfɛkts/",
"infer":"/ˌɪnˈfɝ/",
"inference":"/ˈɪnfɝəns/",
"inferences":"/ˈɪnfɝˌɛnsɪz/",
"inferential":"/ˌɪnfɝˈɛnʃəl/",
"inferior":"/ˌɪnˈfɪɹiɝ/",
"inferiority":"/ˌɪnfɪɹiˈɔɹɪˌti/",
"infernal":"/ˌɪnˈfɝnəl/",
"inferno":"/ˌɪnˈfɝˌnoʊ/",
"inferred":"/ˌɪnˈfɝd/",
"inferring":"/ˌɪnˈfɝɪŋ/",
"infers":"/ˌɪnˈfɝz/",
"infertile":"/ˌɪnˈfɝtəl/",
"infertility":"/ˌɪnfɝˈtɪlɪˌti/",
"infest":"/ˌɪnˈfɛst/",
"infestation":"/ˌɪnˈfɛsˈteɪʃən/",
"infestations":"/ˌɪnˌfɛsˈteɪʃənz/",
"infested":"/ˌɪnˈfɛstɪd/",
"infests":"/ˌɪnˈfɛsts/",
"infidel":"/ˈɪnfɪˌdɛl/",
"infidelities":"/ˌɪnfɪˈdɛlɪtiz/",
"infidelity":"/ˌɪnfɪˈdɛlɪti/",
"infidels":"/ˈɪnfɪdɛlz/",
"infield":"/ˈɪnˌfild/",
"infielder":"/ˈɪnˌfildɝ/",
"infielders":"/ˈɪnˌfildɝz/",
"infighting":"/ˈɪnˌfaɪtɪŋ/",
"infiltrate":"/ˈɪnfɪlˌtɹeɪt/",
"infiltrated":"/ˈɪnfɪlˌtɹeɪtɪd/",
"infiltrating":"/ˌɪnˈfɪlˌtɹeɪtɪŋ/",
"infiltration":"/ˌɪnfɪlˈtɹeɪʃən/",
"infiltrator":"/ˈɪnfɪlˌtɹeɪtɝ/",
"infiltrators":"/ˈɪnfɪlˌtɹeɪtɝz/",
"infinger":"/ˈɪnfɪŋɝ/",
"infinite":"/ˈɪnfənət/",
"infinitely":"/ˈɪnfənətli/",
"infinitesimal":"/ˌɪnfɪnɪˈtɛsɪməl/",
"infiniti":"/ˌɪnˈfɪnɪti/",
"infinitive":"/ˌɪnˈfɪnɪtɪv/",
"infinitum":"/ˌɪnˈfɪnɪtəm/",
"infinity":"/ˌɪnˈfɪnɪti/",
"infirm":"/ɪnˈfɝm/",
"infirmary":"/ɪnˈfɝmɝi/",
"infirmed":"/ɪnˈfɝmd/",
"infirmities":"/ɪnˈfɝmɪtiz/",
"infirmity":"/ɪnˈfɝmɪti/",
"inflame":"/ɪnˈfleɪm/",
"inflamed":"/ɪnˈfleɪmd/",
"inflames":"/ɪnˈfleɪmz/",
"inflaming":"/ɪnˈfleɪmɪŋ/",
"inflammable":"/ɪnˈflæməbəl/",
"inflammation":"/ˌɪnfləˈmeɪʃən/",
"inflammatory":"/ɪnˈflæməˌtɔɹi/",
"inflatable":"/ɪnˈfleɪtəbəl/",
"inflate":"/ɪnˈfleɪt/",
"inflated":"/ˌɪnˈfleɪtɪd/",
"inflates":"/ˌɪnˈfleɪts/",
"inflating":"/ˌɪnˈfleɪtɪŋ/",
"inflation":"/ˌɪnˈfleɪʃən/",
"inflation's":"/ˌɪnˈfleɪʃənz/",
"inflationary":"/ˌɪnˈfleɪʃəˌnɛɹi/",
"inflator":"/ˌɪnˈfleɪtɝ/",
"inflected":"/ˌɪnˈflɛktəd/",
"inflection":"/ˌɪnˈflɛkʃən/",
"inflections":"/ˌɪnˈflɛkʃənz/",
"inflexibility":"/ˌɪnˌflɛksɪˈbɪlɪti/",
"inflexible":"/ˌɪnˈflɛksəbəl/",
"inflexibly":"/ˌɪnˈflɛksəbli/",
"inflict":"/ˌɪnˈflɪkt/",
"inflicted":"/ˌɪnˈflɪktɪd/",
"inflicting":"/ˌɪnˈflɪktɪŋ/",
"infliction":"/ˌɪnˈflɪkʃən/",
"inflicts":"/ˌɪnˈflɪkts/, /ɪnˈflɪks/",
"inflight":"/ˈɪnˌflaɪt/",
"inflow":"/ˈɪnˌfloʊ/",
"inflows":"/ˈɪnˌfloʊz/",
"influence":"/ˈɪnfluəns/",
"influenced":"/ˈɪnfluənst/",
"influences":"/ˈɪnˌfluənsɪz/",
"influencing":"/ˈɪnˌfluənsɪŋ/",
"influential":"/ˌɪnfluˈɛnʃəl/",
"influenza":"/ˌɪnfluˈɛnzə/",
"influx":"/ˈɪnˌfləks/",
"info":"/ˈɪnfoʊ/",
"infocorp":"/ˈɪnfoʊˌkɔɹp/",
"infographic":"/ˈɪnfoʊˈɡɹæfɪk/",
"infomercial":"/ˈɪnfoʊˌmɝʃəl/",
"infomercial's":"/ˈɪnfoʊˌmɝʃəlz/",
"infomercials":"/ˈɪnfoʊˌmɝʃəlz/",
"inform":"/ˌɪnˈfɔɹm/",
"informal":"/ˌɪnˈfɔɹməl/",
"informality":"/ˌɪnfɝˈmælɪti/",
"informally":"/ˌɪnˈfɔɹməli/",
"informals":"/ˌɪnˈfɔɹməlz/",
"informant":"/ˌɪnˈfɔɹmənt/",
"informants":"/ˌɪnˈfɔɹmənts/",
"informatic":"/ɪnˈfɔɹˈmætɪk/, /ɪnfɝˈmætɪk/",
"informatics":"/ˌɪnfɝˈmætɪks/, /ɪnˈfɔɹˈmætɪks/",
"information":"/ˌɪnfɝˈmeɪʃən/, /ɪnˈfɔɹˈmeɪʃən/",
"information's":"/ˌɪnfɝˈmeɪʃənz/, /ɪnˈfɔɹˈmeɪʃənz/",
"informational":"/ˌɪnfɝˈmeɪʃənəl/, /ɪnˈfɔɹˈmeɪʃənəl/",
"informations":"/ˌɪnfɝˈmeɪʃənz/, /ɪnˈfɔɹˈmeɪʃənz/",
"informative":"/ˌɪnˈfɔɹmətɪv/",
"informed":"/ˌɪnˈfɔɹmd/",
"informer":"/ˌɪnˈfɔɹmɝ/",
"informers":"/ˌɪnˈfɔɹmɝz/",
"informing":"/ˌɪnˈfɔɹmɪŋ/",
"informix":"/ˌɪnˈfɔɹmɪks/",
"informs":"/ˌɪnˈfɔɹmz/",
"infoscan":"/ˈɪnfoʊˌskæn/",
"infotainment":"/ˌɪnfoʊˈteɪnmənt/",
"infotech":"/ˈɪnfoʊˌtɛk/",
"infotechnology":"/ˌɪnfoʊtɛkˈnɑlədʒi/",
"infotron":"/ˈɪnfoʊˌtɹɑn/",
"infotron's":"/ˈɪnfoʊˌtɹɑnz/",
"infoworld":"/ˈɪnfoʊˌwɝld/",
"infra":"/ˈɪnfɹə/",
"infraction":"/ˌɪnˈfɹækʃən/",
"infractions":"/ˌɪnˈfɹækʃənz/",
"infrared":"/ˌɪnfɹɝˈɛd/",
"infrastructural":"/ˌɪnfɹəˈstɹəktʃɝəl/",
"infrastructure":"/ˌɪnfɹəˈstɹəktʃɝ/",
"infrastructures":"/ˌɪnfɹəˈstɹəktʃɝz/",
"infrequency":"/ˌɪnˈfɹikwənsi/",
"infrequent":"/ˌɪnˈfɹikwənt/",
"infrequently":"/ˌɪnˈfɹikwəntli/",
"infringe":"/ˌɪnˈfɹɪndʒ/",
"infringed":"/ˌɪnˈfɹɪndʒd/",
"infringement":"/ˌɪnˈfɹɪndʒmənt/",
"infringements":"/ˌɪnˈfɹɪndʒmənts/",
"infringes":"/ˌɪnˈfɹɪndʒɪz/",
"infringing":"/ˌɪnˈfɹɪndʒɪŋ/",
"infuriate":"/ˌɪnˈfjʊɹiˌeɪt/",
"infuriated":"/ˌɪnˈfjʊɹiˌeɪtɪd/, /ɪnˈfjʊɹiˌeɪtɪd/",
"infuriates":"/ˌɪnˈfjʊɹiˌeɪts/",
"infuriating":"/ˌɪnˈfjʊɹiˌeɪtɪŋ/",
"infuse":"/ˌɪnˈfjuz/",
"infused":"/ˌɪnˈfjuzd/",
"infuses":"/ˌɪnˈfjuzɪz/",
"infusing":"/ˌɪnˈfjuzɪŋ/",
"infusion":"/ˌɪnˈfjuʒən/",
"infusions":"/ˌɪnˈfjuʒənz/",
"ing":"/ˈɪŋ/",
"inga":"/ˈiŋɡə/",
"ingalls":"/ˌɪŋˈɡɔlz/",
"ingalsbe":"/ˈɪŋɡəlsbi/",
"ingar":"/ˈɪŋɡɝ/",
"ingber":"/ˈɪŋbɝ/",
"inge":"/ˈɪndʒ/",
"ingelheim":"/ˈɪŋɡəlˌhaɪm/",
"ingels":"/ˈɪŋɡəlz/",
"ingemar":"/ˈɪŋɡɪmɑɹ/, /ˈɪŋɡɪmɝ/",
"ingenious":"/ˌɪnˈdʒinjəs/",
"ingeniously":"/ˌɪnˈdʒinjəsli/",
"ingenito":"/ˌɪŋdʒɛˈnitoʊ/, /ˌɪŋɡɛˈnitoʊ/",
"ingenue":"/ˈɑndʒəˌnu/, /ˈɪnˌdʒɛnˌju/, /ˈɪndʒənu/, /ɪnˈdʒɛnu/",
"ingenuity":"/ˌɪndʒəˈnuəˌti/",
"ingenuous":"/ˌɪnˈdʒɛnjuəs/",
"inger":"/ˈɪŋɝ/",
"ingersoll":"/ˈɪŋɡɝsɔl/",
"ingerson":"/ˈɪŋɡɝsən/",
"ingest":"/ˌɪnˈdʒɛst/",
"ingested":"/ˌɪnˈdʒɛstəd/",
"ingesting":"/ˌɪnˈdʒɛstɪŋ/",
"ingestion":"/ˌɪnˈdʒɛstʃən/",
"ingham":"/ˈɪŋəm/",
"inghram":"/ˈɪŋˌɡɹæm/",
"ingimarson":"/ˈɪŋəˌmɑɹsən/",
"ingle":"/ˈɪŋɡəl/",
"inglebert":"/ˈɪŋɡəlbɝt/",
"inglenook":"/ˈɪŋɡəlˌnʊk/",
"ingles":"/ˈɪŋɡəlz/",
"inglese":"/ˈɪŋɡliz/",
"inglett":"/ˌɪŋˈɡlɛt/",
"inglewood":"/ˈɪŋɡəlˌwʊd/",
"inglis":"/ˈɪŋɡlɪs/",
"inglish":"/ˈɪŋɡəlɪʃ/",
"inglorious":"/ˌɪnˈɡlɔɹiəs/",
"ingman":"/ˈɪŋmən/",
"ingmar":"/ˈɪŋmɑɹ/",
"ingmire":"/ˈɪŋmaɪɹ/",
"ingo":"/ˈɪŋɡoʊ/",
"ingoglia":"/ˌɪŋˈɡoʊɡliˌɑ/",
"ingold":"/ˈɪŋɡoʊld/",
"ingot":"/ˈɪŋɡət/",
"ingots":"/ˈɪŋɡəts/",
"ingraham":"/ˈɪŋɡɹəˌhæm/",
"ingrained":"/ˌɪnˈɡɹeɪnd/",
"ingram":"/ˈɪŋɡɹəm/",
"ingrao":"/ˈiŋɡɹaʊ/",
"ingrassia":"/ˌɪŋˈɡɹɑʃə/",
"ingratiate":"/ˌɪŋˈɡɹeɪʃiˌeɪt/",
"ingratiating":"/ˌɪŋˈɡɹeɪʃiˌeɪtɪŋ/",
"ingredient":"/ˌɪnˈɡɹidiənt/",
"ingredients":"/ˌɪnˈɡɹidiənts/",
"ingria":"/ˈɪŋɡɹiə/",
"ingrid":"/ˈɪŋɡɹɪd/",
"ingrum":"/ˈɪŋɡɹəm/",
"ingvar":"/ˈɪŋvɑɹ/",
"ingwersen":"/ˈɪŋɡwɝsən/",
"inhabit":"/ˌɪnˈhæbət/",
"inhabitant":"/ɪnˈhæbətənt/, /ɪnˈhæbɪtənt/",
"inhabitants":"/ɪnˈhæbətənts/, /ɪnˈhæbɪtənts/",
"inhabitation":"/ɪnˌhæbəˈteɪʃən/",
"inhabited":"/ˌɪnˈhæbətəd/",
"inhabiting":"/ɪnˈhæbətɪŋ/",
"inhabits":"/ɪnˈhæbəts/",
"inhalable":"/ˌɪnˈheɪləbəl/",
"inhalant":"/ˌɪnˈheɪlənt/",
"inhalants":"/ˌɪnˈheɪlənts/",
"inhalation":"/ˌɪnhəˈleɪʃən/, /ɪnəˈleɪʃən/",
"inhale":"/ˌɪnˈheɪl/",
"inhaled":"/ˌɪnˈheɪld/",
"inhaler":"/ˌɪnˈheɪlɝ/",
"inhalers":"/ˌɪnˈheɪlɝz/",
"inhaling":"/ˌɪnˈheɪlɪŋ/",
"inherent":"/ɪnˈhɛɹənt/, /ɪnˈhɪɹənt/",
"inherently":"/ɪnˈhɛɹəntli/, /ɪnˈhɪɹəntli/",
"inherit":"/ˌɪnˈhɛɹət/",
"inheritable":"/ˌɪnˈhɛɹətəbəl/",
"inheritance":"/ˌɪnˈhɛɹətəns/",
"inherited":"/ˌɪnˈhɛɹətɪd/",
"inheriting":"/ˌɪnˈhɛɹətɪŋ/",
"inheritor":"/ˌɪnˈhɛɹətɝ/",
"inherits":"/ˌɪnˈhɛɹəts/",
"inhibit":"/ˌɪnˈhɪbət/",
"inhibited":"/ˌɪnˈhɪbətɪd/",
"inhibiting":"/ˌɪnˈhɪbətɪŋ/",
"inhibition":"/ˌɪnəˈbɪʃən/, /ˌɪnhəˈbɪʃən/",
"inhibitions":"/ˌɪnəˈbɪʃənz/, /ˌɪnhəˈbɪʃənz/",
"inhibitor":"/ˌɪnˈhɪbətɝ/",
"inhibitors":"/ˌɪnˈhɪbətɝz/",
"inhibitory":"/ˌɪnˈhɪbəˌtɔɹi/",
"inhibits":"/ˌɪnˈhɪbəts/",
"inhofe":"/ˈɪnˌhɑf/, /ˈɪnˌhoʊf/",
"inhofe's":"/ˈɪnˌhɑfs/, /ˈɪnˌhoʊfs/",
"inhospitable":"/ˌɪnhɑˈspɪtəbəl/, /ɪnˈhɑspətəbəl/",
"inhouse":"/ˈɪnˌhaʊs/",
"inhuman":"/ˌɪnˈhjumən/",
"inhumane":"/ˌɪnhjuˈmeɪn/",
"inhumanity":"/ˌɪnhjuˈmænəti/",
"iniga":"/ˌɪˈniɡə/",
"iniguez":"/ˌɪˈniɡɛz/",
"iniki":"/ˌiˈniˌki/",
"inikpratt":"/ˌɪˈnikpɹæt/",
"inimical":"/ˌɪˈnɪmɪkəl/",
"inimitable":"/ˌɪˈnɪmətəbəl/",
"iniquity":"/ˌɪˈnɪkwɪti/",
"iniss":"/ˈɪnɪs/",
"initable":"/ˌɪˈnɪtəbəl/",
"initial":"/ˌɪˈnɪʃəl/",
"initialed":"/ˌɪˈnɪʃəld/",
"initialing":"/ˌɪˈnɪʃəlɪŋ/",
"initialize":"/ˌɪˈnɪʃəˌlaɪz/",
"initialized":"/ˌɪˈnɪʃəˌlaɪzd/",
"initialling":"/ˌɪˈnɪʃəlɪŋ/",
"initially":"/ˌɪˈnɪʃəli/",
"initials":"/ˌɪˈnɪʃəlz/",
"initiate":"/ˌɪˈnɪʃiˌeɪt/",
"initiated":"/ˌɪˈnɪʃiˌeɪtəd/, /ˌɪˈnɪʃiˌeɪtɪd/",
"initiates":"/ˌɪˈnɪʃiəts/",
"initiating":"/ˌɪˈnɪʃiˌeɪtɪŋ/",
"initiation":"/ˌɪˌnɪʃiˈeɪʃən/",
"initiative":"/ˌɪˈnɪʃətɪv/, /ˌɪˈnɪʃjətɪv/",
"initiatives":"/ˌɪˈnɪʃətɪvz/, /ˌɪˈnɪʃjətɪvz/",
"initiator":"/ˌɪnɪˈʃieɪtɝ/",
"initiators":"/ˌɪˈnɪʃieɪtɝz/",
"initio":"/ˌɪˈnɪʃioʊ/, /ˌɪˈnɪtioʊ/",
"iniziativa":"/ˌɪnɪˌziəˈtivə/",
"inject":"/ˌɪnˈdʒɛkt/",
"injectable":"/ˌɪnˈdʒɛktəbəl/",
"injected":"/ˌɪnˈdʒɛktəd/, /ˌɪnˈdʒɛktɪd/",
"injecting":"/ˌɪnˈdʒɛktɪŋ/",
"injection":"/ˌɪnˈdʒɛkʃən/",
"injections":"/ˌɪnˈdʒɛkʃənz/",
"injector":"/ˌɪnˈdʒɛktɝ/",
"injectors":"/ˌɪnˈdʒɛktɝz/",
"injects":"/ˌɪnˈdʒɛkts/",
"injudicious":"/ˌɪnˌdʒəˈdɪʃəs/",
"injunction":"/ˌɪnˈdʒəŋkʃən/, /ˌɪnˈdʒəŋʃən/",
"injunctions":"/ˌɪnˈdʒəŋkʃənz/, /ˌɪnˈdʒəŋʃənz/",
"injunctive":"/ˌɪnˈdʒəŋktɪv/, /ˌɪnˈdʒəŋtɪv/",
"injure":"/ˈɪndʒɝ/",
"injured":"/ˈɪndʒɝd/",
"injures":"/ˈɪndʒɝz/",
"injuries":"/ˈɪndʒɝiz/",
"injuring":"/ˈɪndʒɝɪŋ/",
"injurious":"/ˌɪnˈdʒʊɹiəs/",
"injury":"/ˈɪndʒɝi/",
"injustice":"/ˌɪnˈdʒəstɪs/",
"injustices":"/ˌɪnˈdʒəstəsɪz/",
"ink":"/ˈɪŋk/",
"inkatha":"/ˌɪŋˈkæθə/, /ˌɪŋˈkɑˌtə/, /ˌɪŋˈkɑtə/",
"inkatha's":"/ˌɪŋˈkæθəz/, /ˌɪŋˈkɑˌtəz/, /ˌɪŋˈkɑtəz/",
"inkblot":"/ˈɪŋkˌblɑt/",
"inkjet":"/ˈɪŋkˌdʒɛt/",
"inkling":"/ˈɪŋklɪŋ/",
"inks":"/ˈɪŋks/",
"inky":"/ˈɪŋki/",
"inlaid":"/ˈɪnˌleɪd/",
"inland":"/ˈɪnˌlænd/",
"inland's":"/ˈɪnləndz/",
"inlaw":"/ˈɪnˌlɔ/, /ˌɪnˈlɔ/",
"inlaws":"/ˈɪnlɔz/, /ˌɪnˈlɔz/",
"inlay":"/ˈɪnˌleɪ/",
"inlet":"/ˈɪnˌlɛt/",
"inlets":"/ˈɪnˌlɛts/",
"inlex":"/ˈɪnlɛks/",
"inline":"/ˌɪnˈlaɪn/",
"inlow":"/ˌɪnˈloʊ/",
"inmac":"/ˈɪnmæk/",
"inman":"/ˈɪnmən/",
"inman's":"/ˈɪnmənz/",
"inmarsat":"/ˌɪnˌmɑɹˈsæt/",
"inmate":"/ˈɪnˌmeɪt/",
"inmate's":"/ˈɪnˌmeɪts/",
"inmates":"/ˈɪnˌmeɪts/",
"inmex":"/ˈɪnˌmɛks/",
"inmobiliaria":"/ˌɪnˌmoʊbəliˈɛɹiə/",
"inmon":"/ˈɪnmən/",
"inmont":"/ˈɪnˌmɑnt/",
"inn":"/ˈɪn/",
"inn's":"/ˈɪnz/",
"innard":"/ˈɪnɝd/",
"innards":"/ˈɪnɝdz/",
"innate":"/ˌɪˈneɪt/",
"innately":"/ˌɪˈneɪtli/",
"inner":"/ˈɪnɝ/",
"innermost":"/ˈɪnɝˌmoʊst/",
"innerspace":"/ˈɪnɝˌspeɪs/",
"innes":"/ˈɪnəs/",
"inness":"/ˈɪnɪs/",
"inning":"/ˈɪnɪŋ/",
"innings":"/ˈɪnɪŋz/",
"innis":"/ˈɪnɪs/",
"inniss":"/ˈɪnɪs/",
"innkeeper":"/ˈɪnˌkipɝ/",
"innkeepers":"/ˈɪnˌkipɝz/",
"inno":"/ˈɪnoʊ/",
"innocence":"/ˈɪnəsəns/",
"innocent":"/ˈɪnəsənt/",
"innocenti":"/ˌɪnoʊˈtʃɛnti/",
"innocently":"/ˈɪnəsəntli/",
"innocents":"/ˈɪnəsənts/",
"innoculate":"/ˌɪˈnɔkjəˌleɪt/",
"innoculated":"/ˌɪˈnɔkjəˌleɪtəd/",
"innoculates":"/ˌɪˈnɔkjəˌleɪts/",
"innoculating":"/ˌɪˈnɔkjəˌleɪtɪŋ/",
"innoculation":"/ˌɪˌnɔkjəˈleɪʃən/",
"innocuous":"/ˌɪˈnɑkjuəs/",
"innominate":"/ˌɪˈnɑmənət/",
"innopac":"/ˈɪnəˌpæk/",
"innovate":"/ˈɪnəˌveɪt/, /ˈɪnoʊˌveɪt/",
"innovated":"/ˈɪnəˌveɪtɪd/, /ˈɪnoʊˌveɪtɪd/",
"innovates":"/ˈɪnəˌveɪts/, /ˈɪnoʊˌveɪts/",
"innovating":"/ˌɪnəˈveɪtɪŋ/, /ˌɪnoʊˈveɪtɪŋ/",
"innovation":"/ˌɪnəˈveɪʃən/, /ˌɪnoʊˈveɪʃən/",
"innovations":"/ˌɪnəˈveɪʃənz/, /ˌɪnoʊˈveɪʃənz/",
"innovative":"/ˈɪnəˌveɪtɪv/, /ˈɪnoʊˌveɪtɪv/",
"innovator":"/ˈɪnəˌveɪtɝ/, /ˈɪnoʊˌveɪtɝ/",
"innovators":"/ˈɪnəˌveɪtɝz/, /ˈɪnoʊˌveɪtɝz/",
"inns":"/ˈɪnz/",
"inns'":"/ˈɪnz/",
"innuendo":"/ˌɪnjuˈɛndoʊ/",
"innuendoes":"/ˌɪnjuˈɛndoʊz/",
"innuendos":"/ˌɪnjuˈɛndoʊz/",
"innumerable":"/ˌɪˈnumɝəbəl/",
"inocencio":"/ˌɪnoʊˈtʃɛntʃioʊ/",
"inoculate":"/ˌɪˈnɑkjəˌleɪt/",
"inoculated":"/ˌɪˈnɑkjəˌleɪtɪd/",
"inoculates":"/ˌɪˈnɑkjəˌleɪts/",
"inoculation":"/ˌɪˌnɑkjəˈleɪʃən/",
"inoculations":"/ˌɪˌnɑkjəˈleɪʃənz/",
"inoffensive":"/ˌɪnəˈfɛnsɪv/",
"inoperable":"/ˌɪˈnɑpɝəbəl/",
"inoperative":"/ˌɪˈnɑpɝətɪv/",
"inopportune":"/ˌɪˌnɑpɝˈtun/",
"inordinate":"/ˌɪˈnɔɹdənɪt/",
"inordinately":"/ˌɪˈnɔɹdənətli/",
"inorganic":"/ˌɪnɔɹˈɡænɪk/",
"inoue":"/ˌɪˈnoʊˌeɪ/",
"inouye":"/ˌɪˈnuˌeɪ/",
"inpatient":"/ˈɪnˌpeɪʃənt/",
"inpatients":"/ˈɪnˌpeɪʃənts/",
"input":"/ˈɪnˌpʊt/",
"inputs":"/ˈɪnˌpʊts/",
"inquest":"/ˈɪnˌkwɛst/",
"inquire":"/ˌɪnˈkwaɪɹ/",
"inquired":"/ˌɪnˈkwaɪɝd/",
"inquirer":"/ˌɪnˈkwaɪɹɝ/",
"inquires":"/ˌɪnˈkwaɪɝz/",
"inquiries":"/ˈɪnkwɝiz/, /ˌɪnˈkwaɪɝiz/",
"inquiring":"/ˌɪnˈkwaɪɝɪŋ/",
"inquiry":"/ˌɪnˈkwaɪˌɹi/, /ɪnkwɝɹi/",
"inquisition":"/ˌɪnkwəˈzɪʃən/",
"inquisitive":"/ˌɪnˈkwɪzɪtɪv/",
"inquisitor":"/ˌɪnˈkwɪzətɝ/",
"inquisitors":"/ˌɪnˈkwɪzətɝz/",
"inroad":"/ˈɪnˌɹoʊd/",
"inroads":"/ˈɪnˌɹoʊdz/",
"ins":"/ˈaɪˈɛˈnɛs/, /ˈɪnz/",
"insalaco":"/ˌɪnsɑˈlɑkoʊ/",
"insane":"/ˌɪnˈseɪn/",
"insanity":"/ˌɪnˈsænəti/, /ˌɪnˈsænɪti/",
"insatiable":"/ˌɪnˈseɪʃəbəl/",
"inscho":"/ˈɪnʃoʊ/",
"insco":"/ˈinskoʊ/",
"inscoe":"/ˌɪnˈskoʊ/",
"inscore":"/ˌɪnˈskɔɹi/",
"inscribe":"/ˌɪnsˈkɹaɪb/",
"inscribed":"/ˌɪnsˈkɹaɪbd/",
"inscribes":"/ˌɪnsˈkɹaɪbz/",
"inscribing":"/ˌɪnsˈkɹaɪbɪŋ/",
"inscription":"/ˌɪnsˈkɹɪpʃən/",
"inscriptions":"/ˌɪnsˈkɹɪpʃənz/",
"inscrutable":"/ˌɪnsˈkɹutəbəl/",
"insect":"/ˈɪnˌsɛkt/",
"insect's":"/ˈɪnˌsɛkts/",
"insecticide":"/ˌɪnˈsɛktəˌsaɪd/",
"insecticides":"/ˌɪnˈsɛktəˌsaɪdz/",
"insectivorous":"/ˌɪnsɛkˈtɪvɝəs/",
"insects":"/ˈɪnˌsɛkts/",
"insecure":"/ˈɪnsəkjɝ/",
"insecurities":"/ˌɪnsəkˈjʊɹɪtiz/",
"insecurity":"/ˌɪnsɪkˈjʊɹɪti/",
"insel":"/ˈɪnsəl/",
"inseminate":"/ˌɪnˈsɛməˌneɪt/",
"insemination":"/ˌɪnˌsɛməˈneɪʃən/",
"insensible":"/ˌɪnˈsɛnsəbəl/",
"insensitive":"/ˌɪnˈsɛnsətɪv/, /ˌɪnˈsɛnsɪtɪv/",
"insensitivity":"/ˌɪnˌsɛnsəˈtɪvəti/",
"inseparable":"/ˌɪnˈsɛpɝəbəl/",
"inseparably":"/ˌɪnˈsɛpɝəbli/",
"inserra":"/ˌɪnˈsɛɹə/",
"insert":"/ˈɪnˌsɝt/, /ˌɪnˈsɝt/",
"inserted":"/ˌɪnˈsɝtəd/, /ˌɪnˈsɝtɪd/",
"inserting":"/ˌɪnˈsɝtɪŋ/",
"insertion":"/ˌɪnˈsɝʃən/",
"inserts":"/ˈɪnˌsɝts/, /ˌɪnˈsɝts/",
"inset":"/ˈɪnˌsɛt/",
"inshore":"/ˈɪnˈʃɔɹ/",
"inside":"/ˈɪnˌsaɪd/, /ˌɪnˈsaɪd/",
"insider":"/ˌɪnˈsaɪdɝ/",
"insider's":"/ˌɪnˈsaɪdɝz/",
"insiders":"/ˌɪnˈsaɪdɝz/",
"insiders'":"/ˌɪnˈsaɪdɝz/",
"insides":"/ˈɪnsaɪdz/, /ˌɪnˈsaɪdz/",
"insidious":"/ˌɪnˈsɪˌdiəs/",
"insight":"/ˈɪnˌsaɪt/",
"insightful":"/ˈɪnˌsaɪtfəl/",
"insights":"/ˈɪnˌsaɪts/",
"insignia":"/ˌɪnˈsɪɡˌniə/",
"insignificance":"/ˌɪnsɪɡˈnjɪfɪkəns/",
"insignificant":"/ˌɪnsɪɡˈnjɪfɪkənt/",
"insilco":"/ˌɪnˈsɪlkoʊ/",
"insincere":"/ˌɪnsɪnˈsɪɹ/",
"insinuate":"/ˌɪnˈsɪnjueɪt/",
"insinuated":"/ˌɪnˈsɪnjueɪtɪd/",
"insinuates":"/ˌɪnˈsɪnjueɪts/",
"insinuating":"/ˌɪnˈsɪnjueɪtɪŋ/",
"insinuation":"/ˌɪnˌsɪnjuˈeɪʃən/",
"insinuations":"/ˌɪnˌsɪnjuˈeɪʃənz/",
"insipid":"/ˌɪnˈsɪpəd/",
"insist":"/ˌɪnˈsɪst/",
"insisted":"/ˌɪnˈsɪstəd/, /ˌɪnˈsɪstɪd/",
"insistence":"/ˌɪnˈsɪstəns/",
"insistent":"/ˌɪnˈsɪstənt/",
"insistently":"/ˌɪnˈsɪstəntli/",
"insisting":"/ˌɪnˈsɪstɪŋ/",
"insists":"/ˌɪnˈsɪsts/",
"insituform":"/ˌɪnˈsɪˌtufɔɹm/",
"inskeep":"/ˈɪnzˌkip/",
"inskip":"/ˈɪnskɪp/",
"insko":"/ˈɪnskoʊ/",
"inslaw":"/ˈɪnslɑ/",
"insley":"/ˈɪnsli/",
"insofar":"/ˈɪnsəfɑɹ/",
"insolence":"/ˈɪnsələns/",
"insolent":"/ˈɪnsələnt/",
"insoluble":"/ˌɪnˈsɑljəbəl/",
"insolvencies":"/ˌɪnˈsɑlvənsiz/",
"insolvency":"/ˌɪnˈsɑlvənsi/",
"insolvent":"/ˌɪnˈsɑlvənt/",
"insomnia":"/ˌɪnˈsɑmniə/",
"insomniac":"/ˌɪnˈsɑmniˌæk/",
"insouciance":"/ˌɪnˈsusiəns/, /ˌɪnˈsusjəns/",
"insouciant":"/ˌɪnˈsusjənt/",
"inspect":"/ˌɪnˈspɛkt/",
"inspected":"/ˌɪnˈspɛktɪd/",
"inspecting":"/ˌɪnˈspɛktɪŋ/",
"inspection":"/ˌɪnˈspɛkʃən/",
"inspections":"/ˌɪnˈspɛkʃənz/",
"inspector":"/ˌɪnˈspɛktɝ/",
"inspector's":"/ˌɪnˈspɛktɝz/",
"inspectorate":"/ˌɪnˈspɛktɝət/",
"inspectors":"/ˌɪnˈspɛktɝz/",
"inspectors'":"/ˌɪnˈspɛktɝz/",
"inspects":"/ˌɪnˈspɛkts/",
"inspeech":"/ˌɪnˈspitʃ/",
"inspiration":"/ˌɪnspɝˈeɪʃən/",
"inspirational":"/ˌɪnspɝˈeɪʃənəl/",
"inspirations":"/ˌɪnspɝˈeɪʃənz/",
"inspire":"/ˌɪnˈspaɪɹ/",
"inspired":"/ˌɪnˈspaɪɝd/",
"inspires":"/ˌɪnˈspaɪɹz/",
"inspiring":"/ˌɪnˈspaɪɝɪŋ/, /ˌɪnˈspaɪɹɪŋ/",
"instabilities":"/ˌɪnstəˈbɪlɪtiz/",
"instability":"/ˌɪnstəˈbɪlɪti/",
"instagram":"/ˌɪnstəˌɡɹæm/",
"install":"/ˌɪnˈstɔl/",
"installation":"/ˌɪnstəˈleɪʃən/",
"installations":"/ˌɪnstəˈleɪʃənz/",
"installed":"/ˌɪnˈstɔld/",
"installer":"/ˌɪnˈstɔlɝ/",
"installers":"/ˌɪnˈstɔlɝz/",
"installing":"/ˌɪnˈstɔlɪŋ/",
"installment":"/ˌɪnˈstɔlmənt/",
"installments":"/ˌɪnˈstɔlmənts/",
"installs":"/ˌɪnˈstɔlz/",
"instance":"/ˈɪnstəns/",
"instances":"/ˈɪnstənsəz/, /ˈɪnstənsɪz/",
"instant":"/ˈɪnstənt/",
"instantaneous":"/ˌɪnstənˈtæniəs/",
"instantaneously":"/ˌɪnstənˈtæniəsli/",
"instantiate":"/ˌɪnˈstænʃiˌeɪt/",
"instantiated":"/ˌɪnˈstænʃiˌeɪtəd/",
"instantiates":"/ˌɪnˈstænʃiˌeɪts/",
"instantiating":"/ˌɪnˈstænʃiˌeɪtɪŋ/",
"instantiation":"/ˌɪnˌstænʃiˈeɪʃən/",
"instantly":"/ˈɪnstəntli/",
"instead":"/ˌɪnˈstɛd/",
"instigate":"/ˈɪnstəˌɡeɪt/",
"instigated":"/ˈɪnstəˌɡeɪtɪd/",
"instigates":"/ˈɪnstəˌɡeɪts/",
"instigating":"/ˈɪnstəˌɡeɪtɪŋ/",
"instigation":"/ˌɪnstɪˈɡeɪʃən/",
"instigator":"/ˈɪnstəˌɡeɪtɝ/",
"instigators":"/ˈɪnstəˌɡeɪtɝz/",
"instill":"/ˌɪnˈstɪl/",
"instilled":"/ˌɪnˈstɪld/",
"instilling":"/ˌɪnˈstɪlɪŋ/",
"instills":"/ˌɪnˈstɪlz/",
"instinct":"/ˈɪnstɪŋkt/",
"instinctive":"/ˌɪnˈstɪŋktɪv/",
"instinctively":"/ˌɪnˈstɪŋktɪvˌli/",
"instincts":"/ˈɪnstɪŋkts/",
"instinet":"/ˈɪnstɪˌnɛt/",
"institucional":"/ˌɪnstɪˌtusiəˈnæl/",
"institut":"/ˈɪnstɪtut/",
"institute":"/ˈɪnstəˌtut/",
"institute's":"/ˈɪnstɪtuts/",
"instituted":"/ˈɪnstəˌtutɪd/",
"institutes":"/ˈɪnstəˌtuts/",
"institutes'":"/ˈɪnstɪˌtuts/",
"instituting":"/ˈɪnstɪˌtutɪŋ/",
"institution":"/ˌɪnstɪˈtuʃən/",
"institution's":"/ˌɪnstɪˈtuʃənz/",
"institutional":"/ˌɪnstɪˈtuʃənəl/",
"institutionalist":"/ˌɪnstɪˈtuʃənəlɪst/",
"institutionalists":"/ˌɪnstɪˈtuʃənəlɪsts/",
"institutionalization":"/ˌɪnstɪˌtuʃənəlɪˈzeɪʃən/",
"institutionalize":"/ˌɪnstɪˈtuʃənəˌlaɪz/",
"institutionalized":"/ˌɪnstɪˈtuʃənəˌlaɪzd/",
"institutionalizes":"/ˌɪnstɪˈtuʃənəˌlaɪzɪz/",
"institutionalizing":"/ˌɪnstɪˈtuʃənəˌlaɪzɪŋ/",
"institutionally":"/ˌɪnstɪˈtuʃənəˌli/, /ˌɪnstɪˈtuʃnəli/",
"institutions":"/ˌɪnstɪˈtuʃənz/",
"institutions'":"/ˌɪnstɪˈtuʃənz/",
"instituto":"/ˌɪnstɪˈtuˌtoʊ/",
"instone":"/ˈɪnˌstoʊn/",
"instruct":"/ˌɪnˈstɹəkt/",
"instructed":"/ˌɪnˈstɹəktəd/, /ˌɪnˈstɹəktɪd/",
"instructing":"/ˌɪnˈstɹəktɪŋ/",
"instruction":"/ˌɪnˈstɹəkʃən/",
"instructional":"/ˌɪnˈstɹəkʃənəl/",
"instructions":"/ˌɪnˈstɹəkʃənz/",
"instructive":"/ˌɪnˈstɹəktɪv/",
"instructor":"/ˌɪnˈstɹəktɝ/",
"instructors":"/ˌɪnˈstɹəktɝz/",
"instructs":"/ˌɪnˈstɹəkts/",
"instrument":"/ˈɪnstɹəmənt/",
"instrument's":"/ˈɪnstɹəmənts/",
"instrumental":"/ˌɪnstɹəˈmɛnəl/, /ˌɪnstɹəˈmɛntəl/",
"instrumentalist":"/ˌɪnstɹəˈmɛnəlɪst/, /ˌɪnstɹəˈmɛntəlɪst/",
"instrumentalists":"/ˌɪnstɹəˈmɛnəlɪs/, /ˌɪnstɹəˈmɛnəlɪsts/, /ˌɪnstɹəˈmɛntəlɪs/, /ˌɪnstɹəˈmɛntəlɪsts/",
"instrumentality":"/ˌɪnstɹəmɛnˈtælɪti/",
"instrumentals":"/ˌɪnstɹəˈmɛnəlz/, /ˌɪnstɹəˈmɛntəlz/",
"instrumentation":"/ˌɪnstɹəˌmɛnˈteɪʃən/",
"instruments":"/ˈɪnstɹəmənts/",
"instruments'":"/ˈɪnstɹəmənts/",
"insubordinate":"/ˌɪnsəˈbɔɹdəˌneɪt/, /ˌɪnsəˈbɔɹdənət/",
"insubordination":"/ˌɪnsəˌbɔɹdəˈneɪʃən/",
"insubstantial":"/ˌɪnsəbˈstænʃəl/",
"insubstantiate":"/ˌɪnsəbˈstænˌʃieɪt/, /ˌɪnsəbˈstænˌtʃieɪt/",
"insubstantiated":"/ˌɪnsəbˈstænˌʃieɪtəd/, /ˌɪnsəbˈstænˌtʃieɪtəd/",
"insufferable":"/ˌɪnˈsəfɝəbəl/",
"insufficiency":"/ˌɪnsəˈfɪʃənˌsi/",
"insufficient":"/ˌɪnsəˈfɪʃənt/",
"insufficiently":"/ˌɪnsəˈfɪʃəntli/",
"insular":"/ˈɪnsəlɝ/",
"insularity":"/ˌɪnsəˈlɛɹɪti/",
"insulate":"/ˈɪnsəˌleɪt/",
"insulated":"/ˈɪnsəˌleɪtəd/, /ˈɪnsəˌleɪtɪd/",
"insulating":"/ˈɪnsəˌleɪtɪŋ/",
"insulation":"/ˌɪnsəˈleɪʃən/",
"insulator":"/ˈɪnsəˌleɪtɝ/",
"insulators":"/ˈɪnsəˌleɪtɝz/",
"insulin":"/ˈɪnsələn/",
"insult":"/ˈɪnˌsəlt/, /ˌɪnˈsəlt/",
"insulted":"/ˌɪnˈsəltɪd/",
"insulting":"/ˌɪnˈsəltɪŋ/",
"insultingly":"/ɪnˈsʌl.tɪŋ.li/",
"insults":"/ˈɪnˌsəlts/, /ˌɪnˈsəlts/",
"insupportable":"/ˌɪnsəˈpɔɹtəbəl/",
"insurance":"/ˌɪnˈʃʊɹəns/",
"insurance's":"/ˌɪnˈʃʊɹənsɪz/",
"insurances":"/ˌɪnˈʃʊɹənsɪz/",
"insure":"/ˌɪnˈʃʊɹ/",
"insured":"/ˌɪnˈʃʊɹd/",
"insurer":"/ˌɪnˈʃʊɹɝ/",
"insurer's":"/ˌɪnˈʃʊɹɝz/",
"insurers":"/ˌɪnˈʃʊɹɝz/",
"insurers'":"/ˌɪnˈʃʊɹɝz/",
"insures":"/ˌɪnˈʃʊɹz/",
"insurgencies":"/ˌɪnˈsɝdʒənsiz/",
"insurgency":"/ˌɪnˈsɝdʒənsi/",
"insurgent":"/ˌɪnˈsɝdʒənt/",
"insurgents":"/ˌɪnˈsɝdʒənts/",
"insurgents'":"/ˌɪnˈsɝdʒənts/",
"insuring":"/ˌɪnˈʃʊɹɪŋ/",
"insurmountable":"/ˌɪnsɝˈmaʊntəbəl/",
"insurrection":"/ˌɪnsɝˈɛkʃən/",
"intact":"/ˌɪnˈtækt/",
"intaglio":"/ˌɪnˈtæɡljoʊ/, /ˌɪnˈtæljoʊ/",
"intake":"/ˈɪnˌteɪk/",
"intan":"/ˈɪntən/",
"intangible":"/ˌɪnˈtændʒəbəl/",
"intangibles":"/ˌɪnˈtændʒəbəlz/",
"intangibly":"/ˌɪnˈtændʒəbli/",
"intefadeh":"/ˌɪntəˈfɑdə/, /ˌɪntɪˈfɑdə/",
"integer":"/ˈɪntədʒɝ/",
"integers":"/ˈɪntədʒɝz/",
"integon":"/ˈɪntəɡɑn/",
"integra":"/ˌɪnˈtɛɡɹə/",
"integral":"/ˈɪnəɡɹəl/, /ˈɪntəɡɹəl/",
"integrals":"/ˈɪntəɡɹəlz/",
"integrate":"/ˈɪnəˌɡɹeɪt/, /ˈɪntəˌɡɹeɪt/",
"integrated":"/ˈɪnəˌɡɹeɪtəd/, /ˈɪnəˌɡɹeɪtɪd/, /ˈɪntəˌɡɹeɪtəd/, /ˈɪntəˌɡɹeɪtɪd/",
"integrated's":"/ˈɪnəˌɡɹeɪtɪdz/, /ˈɪntəˌɡɹeɪtɪdz/",
"integrates":"/ˈɪnəˌɡɹeɪts/, /ˈɪntəˌɡɹeɪts/",
"integrating":"/ˈɪnəˌɡɹeɪtɪŋ/, /ˈɪntəˌɡɹeɪtɪŋ/",
"integration":"/ˌɪnəˈɡɹeɪʃən/, /ˌɪntəˈɡɹeɪʃən/",
"integrations":"/ˌɪnəˈɡɹeɪʃənz/, /ˌɪntəˈɡɹeɪʃənz/",
"integrator":"/ˈɪnəˌɡɹeɪtɝ/, /ˈɪntəˌɡɹeɪtɝ/",
"integrators":"/ˈɪnəˌɡɹeɪtɝz/, /ˈɪntəˌɡɹeɪtɝz/",
"integrelin":"/ˌɪnˈtɛɡɹəlɪn/, /ˌɪntəˈɡɹɛlən/",
"integrity":"/ˌɪnˈtɛɡɹəti/, /ɪnˈtɛɡɹɪti/",
"integument":"/ˌɪnˈtɛɡjəmənt/",
"intel":"/ˌɪnˈtɛl/",
"intel's":"/ˌɪnˈtɛlz/",
"intelco":"/ˌɪnˈtɛlkoʊ/",
"intelcom":"/ˌɪnˈtɛlkɑm/",
"intellect":"/ˈɪnəˌlɛkt/, /ˈɪntəˌlɛkt/",
"intellects":"/ˈɪnəˌlɛks/, /ˈɪnəˌlɛkts/, /ˈɪntəˌlɛks/, /ˈɪntəˌlɛkts/",
"intellectual":"/ˌɪnəˈlɛktʃuəl/, /ˌɪntəˈlɛktʃuəl/",
"intellectualism":"/ˌɪˌnɛləkˈtʃuəˌlɪzəm/, /ˌɪnˌtɛləkˈtʃuəˌlɪzəm/",
"intellectually":"/ˌɪnəˈlɛktʃuəli/, /ˌɪnəˈlɛktʃuli/, /ˌɪntəˈlɛktʃuəli/, /ˌɪntəˈlɛktʃuli/",
"intellectuals":"/ˌɪntəˈlɛktʃuəlz/",
"intellicall":"/ˌɪnˈtɛlɪˌkɔl/",
"intellicorp":"/ˌɪnˈtɛlɪˌkɔɹp/",
"intelligence":"/ˌɪnˈtɛlədʒəns/",
"intelligent":"/ˌɪnˈtɛlədʒənt/",
"intelligently":"/ˌɪnˈtɛlɪdʒəntli/",
"intelligentsia":"/ˌɪnˌtɛləˈdʒɛntsiə/",
"intelligible":"/ˌɪnˈtɛlədʒəbəl/",
"intelligibly":"/ˌɪnˈtɛlədʒəbli/",
"intelogic":"/ˌɪntəˈlɑdʒɪk/",
"intelsat":"/ˌɪnˈtɛlsæt/",
"intemperate":"/ˌɪnˈtɛmpɝət/",
"intend":"/ˌɪnˈtɛnd/",
"intended":"/ˌɪnˈtɛndɪd/, /ɪnˈtɛndɪd/",
"intending":"/ˌɪnˈtɛndɪŋ/",
"intends":"/ˌɪnˈtɛndz/",
"intense":"/ˌɪnˈtɛns/",
"intensely":"/ˌɪnˈtɛnsli/",
"intensification":"/ɪnˌtɛnsəfəˈkeɪʃən/",
"intensified":"/ɪnˈtɛnsəˌfaɪd/",
"intensifies":"/ɪnˈtɛnsəˌfaɪz/",
"intensify":"/ɪnˈtɛnsəˌfaɪ/",
"intensifying":"/ɪnˈtɛnsəˌfaɪɪŋ/",
"intensities":"/ɪnˈtɛnsətiz/",
"intensity":"/ɪnˈtɛnsəti/, /ɪnˈtɛnsɪti/",
"intensive":"/ˌɪnˈtɛnsɪv/",
"intensively":"/ˌɪnˈtɛnsɪvli/",
"intent":"/ˌɪnˈtɛnt/",
"intention":"/ˌɪnˈtɛntʃən/",
"intentional":"/ˌɪnˈtɛnʃənəl/",
"intentionally":"/ˌɪnˈtɛnʃənəli/",
"intentioned":"/ˌɪnˈtɛntʃənd/",
"intentions":"/ˌɪnˈtɛntʃənz/",
"intently":"/ˌɪnˈtɛntli/",
"intents":"/ˌɪnˈtɛnts/",
"inter":"/ˌɪnˈtɝ/",
"interacciones":"/ˌɪntɝˌæksiˈoʊnz/",
"interact":"/ˌɪnɝˈækt/, /ˌɪntɝˈækt/",
"interacted":"/ˌɪnɝˈæktəd/, /ˌɪntɝˈæktəd/",
"interacting":"/ˌɪnɝˈæktɪŋ/, /ˌɪntɝˈæktɪŋ/",
"interaction":"/ˌɪnɝˈækʃən/, /ˌɪntɝˈækʃən/",
"interactions":"/ˌɪnɝˈækʃənz/, /ˌɪntɝˈækʃənz/",
"interactive":"/ˌɪnɝˈæktɪv/, /ˌɪntɝˈæktɪv/",
"interactivity":"/ˌɪnɝˌækˈtɪvɪti/, /ˌɪntɝˌækˈtɪvɪti/",
"interacts":"/ˌɪnɝˈækts/, /ˌɪntɝˈækts/",
"interagency":"/ˌɪntɝˈeɪdʒənsi/",
"interamerican":"/ˌɪntɝəˈmɛɹəkən/",
"interand":"/ˈɪntɝənd/",
"interbank":"/ˌɪntɝˈbæŋk/",
"interbred":"/ˌɪntɝˈbɹɛd/",
"interbrew":"/ˈɪnˌtɝˌbɹu/, /ˈɪntɝˌbɹu/",
"interbrew's":"/ˈɪnˌtɝˌbɹuz/, /ˈɪntɝˌbɹuz/",
"intercable":"/ˌɪntɝˈkeɪbəl/",
"intercapital":"/ˌɪntɝˈkæpətəl/",
"intercare":"/ˈɪntɝˌkɛɹ/",
"intercede":"/ˌɪntɝˈsid/",
"interceded":"/ˌɪntɝˈsidɪd/",
"interceding":"/ˌɪntɝˈsidɪŋ/",
"intercellular":"/ˌɪntɝˈsɛljəlɝ/",
"intercept":"/ˌɪnɝˈsɛpt/, /ˌɪntɝˈsɛpt/",
"intercepted":"/ˌɪnɝˈsɛptəd/, /ˌɪnɝˈsɛptɪd/, /ˌɪntɝˈsɛptəd/, /ˌɪntɝˈsɛptɪd/",
"intercepting":"/ˌɪnɝˈsɛptɪŋ/, /ˌɪntɝˈsɛptɪŋ/",
"interception":"/ˌɪnɝˈsɛpʃən/, /ˌɪntɝˈsɛpʃən/",
"interceptions":"/ˌɪnɝˈsɛpʃənz/, /ˌɪntɝˈsɛpʃənz/",
"interceptor":"/ˌɪnɝˈsɛptɝ/, /ˌɪntɝˈsɛptɝ/",
"interceptors":"/ˌɪnɝˈsɛptɝz/, /ˌɪntɝˈsɛptɝz/",
"intercepts":"/ˌɪnɝˈsɛpts/, /ˌɪntɝˈsɛpts/",
"intercession":"/ˌɪnɝˈsɛʃən/, /ˌɪntɝˈsɛʃən/",
"interchange":"/ˌɪnɝˈtʃeɪndʒ/, /ˌɪntɝˈtʃeɪndʒ/",
"interchangeable":"/ˌɪnɝˈtʃeɪndʒəbəl/, /ˌɪntɝˈtʃeɪndʒəbəl/",
"interchangeably":"/ˌɪnɝˈtʃeɪndʒəbli/, /ˌɪntɝˈtʃeɪndʒəbli/",
"interchanges":"/ˈɪnɝˌtʃeɪndʒɪz/, /ˈɪntɝˌtʃeɪndʒɪz/",
"intercity":"/ˈɪnɝˌsɪti/, /ˈɪntɝˌsɪti/",
"interco":"/ˈɪntɝˌkoʊ/",
"interco's":"/ˈɪntɝˌkoʊz/",
"intercollegiate":"/ˌɪntɝkəˈlidʒət/",
"intercom":"/ˈɪntɝˌkɑm/",
"intercompany":"/ˌɪntɝˈkəmpəni/",
"interconnect":"/ˌɪntɝkəˈnɛkt/",
"interconnected":"/ˌɪntɝkəˈnɛktɪd/",
"interconnection":"/ˌɪntɝkəˈnɛkʃən/",
"interconnections":"/ˌɪntɝkəˈnɛkʃənz/",
"intercontinental":"/ˌɪntɝˌkɑntəˈnɛntəl/",
"intercontinentale":"/ˌɪntɝkɑnˈtɪnənˌtɑl/",
"intercorp":"/ˈɪntɝˌkɔɹp/",
"intercorporation":"/ˌɪntɝˌkɔɹpɝˈeɪʃən/",
"intercourse":"/ˈɪnɝˌkɔɹs/, /ˈɪntɝˌkɔɹs/",
"intercultural":"/ˌɪntɝˈkəltʃɝəl/",
"intercurrent":"/ˌɪntɝˈkɝənt/",
"interdealer":"/ˈɪntɝˌdilɝ/",
"interdependence":"/ˌɪntɝdəˈpɛndəns/",
"interdependent":"/ˌɪntɝdɪˈpɛndənt/",
"interdict":"/ˈɪntɝˌdɪkt/",
"interdicted":"/ˈɪntɝˌdɪktɪd/",
"interdictes":"/ˈɪntɝˌdɪkts/",
"interdicting":"/ˌɪntɝˈdɪktɪŋ/",
"interdiction":"/ˌɪntɝˈdɪkʃən/",
"interdigital":"/ˌɪntɝˈdɪdʒətəl/",
"interdisciplinary":"/ˌɪntɝˈdɪsəpləˌnɛɹi/",
"interdyne":"/ˈɪntɝˌdaɪn/",
"interest":"/ˈɪntɝəst/, /ˈɪntɝɪst/, /ˈɪntɹəst/, /ˈɪntɹɪst/",
"interested":"/ˈɪn.trɪ.stɪd/",
"interesting":"/ˈɪntɝəstɪŋ/, /ˈɪntɝɪstɪŋ/, /ˈɪntɹəstɪŋ/, /ˈɪntɹɪstɪŋ/",
"interestingly":"/ˈɪntɝˌɛstɪŋli/",
"interestrate":"/ˈɪntɝəˌstɹeɪt/",
"interests":"/ˈɪntɝəsts/, /ˈɪntɝɪsts/, /ˈɪntɹəsts/, /ˈɪntɹɪsts/",
"interface":"/ˈɪnɝˌfeɪs/, /ˈɪntɝˌfeɪs/",
"interfaces":"/ˈɪnɝˌfeɪsɪz/, /ˈɪntɝˌfeɪsɪz/",
"interfaith":"/ˌɪntɝˈfeɪθ/",
"interfax":"/ˈɪntɝˌfæks/",
"interfere":"/ˌɪnɝˈfɪɹ/, /ˌɪntɝˈfɪɹ/",
"interfered":"/ˌɪnɝˈfɪɹd/, /ˌɪntɝˈfɪɹd/",
"interference":"/ˌɪnɝˈfɪɹəns/, /ˌɪntɝˈfɪɹəns/",
"interferes":"/ˌɪnɝˈfɪɹz/, /ˌɪntɝˈfɪɹz/",
"interfering":"/ˌɪnɝˈfɪɹɪŋ/, /ˌɪntɝˈfɪɹɪŋ/",
"interferometer":"/ˌɪntɝfɝˈɑmətɝ/",
"interferon":"/ˌɪntɝˈfɛɹɑn/, /ˌɪntɝˈfɪɹɑn/",
"interferons":"/ˌɪntɝˈfɪɹɑnz/",
"interfirst":"/ˌɪntɝˈfɝst/",
"interflug":"/ˈɪntɝfləɡ/",
"interfunding":"/ˈɪntɝˌfəndɪŋ/",
"intergenerational":"/ˌɪntɝˈdʒɛnɝˈeɪʃənəl/",
"intergovernmental":"/ˌɪntɝˌɡəvɝnˈmɛntəl/",
"intergraph":"/ˈɪntɝˌɡɹæf/",
"intergraph's":"/ˈɪntɝˌɡɹæfs/",
"intergroup":"/ˌɪntɝˈɡɹup/",
"intergroup's":"/ˌɪntɝˈɡɹups/",
"interim":"/ˈɪnɝəm/, /ˈɪntɝəm/, /ˈɪntɹəm/",
"interior":"/ˌɪnˈtɪɹiɝ/",
"interiors":"/ˌɪnˈtɪɹiɝz/",
"interject":"/ˌɪntɝˈdʒɛkt/",
"interjected":"/ˌɪntɝˈdʒɛktɪd/",
"interjection":"/ˌɪntɝˈdʒɛkʃən/",
"interjections":"/ˌɪntɝˈdʒɛkʃənz/",
"interjects":"/ˌɪntɝˈdʒɛkts/",
"interlace":"/ˌɪntɝˈleɪs/",
"interlaced":"/ˌɪntɝˈleɪst/",
"interlake":"/ˈɪntɝˌleɪk/",
"interlake's":"/ˈɪntɝˌleɪks/",
"interleaf":"/ˈɪntɝˌlif/",
"interleave":"/ˌɪntɝˈliv/",
"interleaved":"/ˌɪntɝˈlivd/",
"interleaves":"/ˌɪntɝˈlivz/",
"interleaving":"/ˌɪntɝˈlivɪŋ/",
"interleukin":"/ˌɪntɝˈlukɪn/",
"interlink":"/ˌɪntɝˈlɪŋk/",
"interlinked":"/ˌɪntɝˈlɪŋkt/",
"interlock":"/ˌɪntɝˈlɑk/",
"interlocked":"/ˌɪntɝˈlɑkd/",
"interlocking":"/ˈɪntɝˌlɑkɪŋ/",
"interlocutor":"/ˌɪntɝˈlɑkjətɝ/",
"interlocutors":"/ˌɪntɝˈlɑkjətɝz/",
"interloper":"/ˈɪntɝˌloʊpɝ/",
"interlopers":"/ˈɪntɝˌloʊpɝz/",
"interlude":"/ˈɪntɝˌlud/",
"interludes":"/ˈɪntɝˌludz/",
"intermagnetic":"/ˌɪntɝmæɡˈnɛtɪk/",
"intermagnetics":"/ˌɪntɝmæɡˈnɛtɪks/",
"intermark":"/ˌɪntɝˈmɑɹk/",
"intermarket":"/ˌɪntɝˈmɑɹkɪt/",
"intermarriage":"/ˌɪntɝˈmɛɹɪdʒ/",
"intermarried":"/ˌɪntɝˈmæɹid/",
"intermarry":"/ˌɪntɝˈmæɹi/",
"intermec":"/ˈɪntɝmək/",
"intermedia":"/ˌɪntɝˈmidiə/",
"intermediaries":"/ˌɪnɝˈmidiˌɛɹiz/, /ˌɪntɝˈmidiˌɛɹiz/",
"intermediary":"/ˌɪnɝˈmidiɛɹi/, /ˌɪntɝˈmidiɛɹi/",
"intermediate":"/ˌɪnɝˈmidiɪt/, /ˌɪntɝˈmidiɪt/",
"intermediates":"/ˌɪnɝˈmidieɪts/, /ˌɪnɝˈmidiəts/, /ˌɪntɝˈmidieɪts/, /ˌɪntɝˈmidiəts/",
"intermedic":"/ˈɪntɝˌmɛdɪk/",
"intermedics":"/ˈɪntɝˌmɛdɪks/",
"intermet":"/ˌɪntɝˈmɛt/",
"interminable":"/ˌɪnˈtɝmənəbəl/",
"interminably":"/ˈɪntɝmɪˌnæbli/, /ˌɪnˈtɝmɪnəbli/",
"intermingle":"/ˌɪntɝˈmɪŋɡəl/",
"intermingled":"/ˌɪntɝˈmɪŋɡəld/",
"intermingling":"/ˌɪntɝˈmɪŋɡəlɪŋ/, /ˌɪntɝˈmɪŋɡlɪŋ/",
"intermission":"/ˌɪntɝˈmɪʃən/",
"intermissions":"/ˌɪntɝˈmɪʃənz/",
"intermittent":"/ˌɪntɝˈmɪtənt/",
"intermittently":"/ˌɪntɝˈmɪtəntli/",
"intermix":"/ˌɪntɝˈmɪks/",
"intermixed":"/ˌɪntɝˈmɪkst/",
"intermixing":"/ˈɪntɝˈmɪksɪŋ/",
"intermodal":"/ˌɪntɝˈmoʊdəl/",
"intermolecular":"/ˌɪntɝməˈlɛkjəlɝ/",
"intermountain":"/ˌɪntɝˈmaʊntɪn/",
"intern":"/ˈɪntɝn/",
"internacional":"/ˌɪntɝˈnæʃənəl/, /ˌɪntɝˌnɑsioʊˈnæl/",
"internal":"/ˌɪnˈtɝnəl/",
"internalize":"/ˌɪnˈtɝnəˌlaɪz/",
"internalized":"/ˌɪnˈtɝnəˌlaɪzd/",
"internally":"/ˌɪnˈtɝnəli/",
"international":"/ˌɪnɝˈnæʃənəl/, /ˌɪntɝˈnæʃənəl/",
"international's":"/ˌɪnɝˈnæʃənəlz/, /ˌɪntɝˈnæʃənəlz/",
"internationale":"/ˌɪnɝˌnæʃəˈnɑli/, /ɪntɝˌnæʃəˈnɑli/",
"internationalism":"/ɪnɝˈnæʃənəˌlɪzəm/, /ɪntɝˈnæʃənəˌlɪzəm/",
"internationalist":"/ˌɪnɝˈnæʃənəlɪst/, /ˌɪntɝˈnæʃənəlɪst/",
"internationalists":"/ˌɪnɝˈnæʃənəlɪs/, /ˌɪnɝˈnæʃənəlɪsts/, /ˌɪntɝˈnæʃənəlɪs/, /ˌɪntɝˈnæʃənəlɪsts/",
"internationalization":"/ˌɪnɝˌnæʃənəlɪˈzeɪʃən/, /ˌɪntɝˌnæʃənəlɪˈzeɪʃən/",
"internationalize":"/ˌɪnɝˈnæʃənəˌlaɪz/, /ˌɪnɝˈnæʃnəˌlaɪz/, /ˌɪntɝˈnæʃənəˌlaɪz/",
"internationalized":"/ɪnɝˈnæʃənəlaɪzd/, /ɪnɝˈnæʃnəlaɪzd/, /ɪntɝˈnæʃənəlaɪzd/",
"internationally":"/ˌɪnɝˈnæʃənəli/, /ˌɪnɝˈnæʃnəli/, /ˌɪntɝˈnæʃənəli/, /ˌɪntɝˈnæʃnəli/",
"internationals":"/ˌɪntɝˈnæʃənəlz/",
"internatonal":"/ˌɪnɝˈnæʃənəl/, /ˌɪntɝˈnæʃənəl/",
"internecine":"/ˌɪnˈtɝnəˌsin/",
"interned":"/ˈɪnˌtɝnd/",
"internee":"/ˌɪntɝˈni/",
"internees":"/ˌɪntɝˈniz/",
"internet":"/ˈɪntɝˌnɛt/",
"internet's":"/ˈɪntɝˌnɛts/",
"internist":"/ˌɪnˈtɝnɪst/",
"internists":"/ˌɪnˈtɝnɪsts/",
"internment":"/ˌɪnˈtɝnmənt/",
"internorth":"/ˈɪntɝnɔɹθ/",
"interns":"/ˈɪntɝnz/",
"internship":"/ˈɪntɝnˌʃɪp/",
"internships":"/ˈɪntɝnˌʃɪps/",
"interoffice":"/ˌɪntɝˈɔfəs/",
"interoperate":"/ˌɪntɝˈɔpɝət/",
"interoperates":"/ˌɪntɝˈɔpɝəts/",
"interpart":"/ˈɪntɝˌpɑɹt/",
"interpersonal":"/ˌɪntɝˈpɝsənəl/",
"interplanetary":"/ˌɪntɝˈplænəˌtɛɹi/",
"interplay":"/ˈɪntɝˌpleɪ/",
"interpol":"/ˈɪntɝˌpoʊl/",
"interpolate":"/ˌɪˈtɝpəˌleɪt/",
"interpolated":"/ˌɪˈtɝpəˌleɪtɪd/",
"interpolation":"/ˌɪˈtɝpəˌleɪʃən/",
"interpolations":"/ˌɪˈtɝpəˌleɪʃənz/",
"interpose":"/ˌɪntɝˈpoʊz/",
"interpret":"/ˌɪnˈtɝpɹət/",
"interpretation":"/ˌɪnˌtɝpɹɪˈteɪʃən/",
"interpretations":"/ˌɪnˌtɝpɹɪˈteɪʃənz/",
"interpreted":"/ˌɪnˈtɝpɹətəd/",
"interpreter":"/ˌɪnˈtɝpɹətɝ/",
"interpreters":"/ˌɪnˈtɝpɹətɝz/",
"interpreting":"/ˈɪntɝˌpɹɛtɪŋ/",
"interpretive":"/ˌɪnˈtɝpɹətɪv/",
"interprets":"/ˌɪnˈtɝpɹəts/",
"interprovincial":"/ˌɪntɝpɹoʊˈvɪnʃəl/",
"interpublic":"/ˌɪntɝˈpəblɪk/",
"interpublic's":"/ˌɪntɝˈpəblɪks/",
"interracial":"/ˌɪntɝˈɹeɪʃəl/",
"interrante":"/ˌɪntɝˈɹɑnti/",
"interred":"/ˌɪnˈtɝd/",
"interregnum":"/ˌɪntɝˈɹɛɡnəm/",
"interrelate":"/ˌɪntɝɹɪˈleɪt/",
"interrelated":"/ˌɪntɝɹiˈleɪtɪd/, /ˌɪntɝɹɪˈleɪtɪd/",
"interrelationship":"/ˈɪntɝɹiˈleɪʃənʃɪp/",
"interrent":"/ˈɪnɝˌɛnt/, /ˈɪntɝˌɛnt/",
"interrogate":"/ˌɪnˈtɛɹəˌɡeɪt/",
"interrogated":"/ˌɪnˈtɛɹəˌɡeɪtɪd/",
"interrogating":"/ˌɪnˈtɛɹəˌɡeɪtɪŋ/",
"interrogation":"/ˌɪnˌtɛɹəˈɡeɪʃən/",
"interrogations":"/ˌɪnˌtɛɹəˈɡeɪʃənz/",
"interrogator":"/ˌɪnˈtɛɹəˌɡeɪtɝ/",
"interrogatories":"/ˌɪntɛˈɹɑɡəˌtɔɹiz/",
"interrogators":"/ˌɪnˈtɛɹəˌɡeɪtɝz/",
"interrogatory":"/ˌɪntɛˈɹɑɡəˌtɔɹi/",
"interrupt":"/ˌɪntɝˈəpt/",
"interrupted":"/ˌɪntɝˈəptɪd/",
"interruptible":"/ˌɪntɝˈɹəptɪbəl/",
"interrupting":"/ˌɪntɝˈəptɪŋ/",
"interruption":"/ˌɪntɝˈəpʃən/",
"interruptions":"/ˌɪntɝˈəpʃənz/",
"interrupts":"/ˌɪntɝˈəpts/",
"interscholastic":"/ˌɪntɝskəˈlæstɪk/",
"interscope":"/ˈɪntɝˌskoʊp/",
"intersec":"/ˈɪntɝsɛk/",
"intersect":"/ˌɪntɝˈsɛkt/",
"intersected":"/ˌɪntɝˈsɛktɪd/",
"intersecting":"/ˌɪntɝˈsɛktɪŋ/",
"intersection":"/ˌɪntɝˈsɛkʃən/",
"intersections":"/ˌɪntɝˈsɛkʃənz/",
"intersects":"/ˌɪntɝˈsɛkts/",
"intersegment":"/ˌɪntɝˈsɛɡmənt/",
"interspec":"/ˈɪntɝspɛk/",
"intersperse":"/ˌɪntɝˈspɝs/",
"interspersed":"/ˌɪntɝˈspɝst/",
"intersperses":"/ˌɪntɝˈspɝsəz/",
"interstate":"/ˌɪntɝˈsteɪt/",
"interstate's":"/ˌɪntɝˈsteɪts/",
"interstates":"/ˈɪntɝˌsteɪts/",
"interstellar":"/ˌɪntɝˈstɛlɝ/",
"interstitial":"/ˌɪntɝˈstɪʃəl/",
"intertan":"/ˌɪntɝˈtæn/",
"intertech":"/ˈɪntɝˌtɛk/",
"intertechnology":"/ˌɪntɝtəkˈnɑlədʒi/",
"intertect":"/ˈɪntɝˌtɛkt/",
"intertidal":"/ˌɪntɝˈtaɪdəl/",
"intertrans":"/ˈɪntɝˌtɹænz/",
"intertribal":"/ˌɪntɝˈtɹaɪbəl/",
"intertwine":"/ˌɪntɝtˈwaɪn/",
"intertwined":"/ˌɪntɝtˈwaɪnd/",
"intertwining":"/ˈɪntɝtˌwaɪnɪŋ/",
"interurban":"/ˌɪntɝˈɝbən/",
"interval":"/ˈɪntɝvəl/",
"intervals":"/ˈɪntɝvəlz/",
"intervene":"/ˌɪntɝˈvin/",
"intervened":"/ˌɪntɝˈvind/",
"intervenes":"/ˌɪntɝˈvinz/",
"intervening":"/ˌɪntɝˈvinɪŋ/",
"intervenor":"/ˌɪntɝˈvinɝ/",
"intervenors":"/ˌɪntɝˈvinɝz/",
"intervention":"/ˌɪntɝˈvɛnʃən/",
"interventionism":"/ˌɪntɝˈvɛnʃəˌnɪzəm/",
"interventionist":"/ˌɪntɝˈvɛnʃənɪst/",
"interventionists":"/ˌɪntɝˈvɛnʃənɪsts/",
"interventions":"/ˌɪntɝˈvɛnʃənz/",
"interview":"/ˈɪntɝvˌju/",
"interviewed":"/ˈɪntɝvˌjud/",
"interviewee":"/ˌɪntɝvjuˈi/",
"interviewees":"/ˌɪntɝvjuˈiz/",
"interviewer":"/ˈɪntɝvˌjuɝ/",
"interviewers":"/ˈɪntɝvˌjuɝz/",
"interviewing":"/ˈɪntɝvˌjuɪŋ/",
"interviews":"/ˈɪntɝvˌjuz/",
"intervoice":"/ˌɪntɝˈvɔɪs/",
"interweave":"/ˌɪntɝˈwiv/",
"interweaving":"/ˌɪntɝˈwivɪŋ/",
"interwoven":"/ˌɪntɝˈwoʊvən/",
"intestinal":"/ɪnˈtɛstənəl/",
"intestine":"/ˌɪnˈtɛstən/",
"intestines":"/ˌɪnˈtɛstənz/",
"intex":"/ˈɪnˌtɛks/",
"inti":"/ˈɪnti/",
"intifada":"/ˌɪntɪˈfɑdə/",
"intimacy":"/ˈɪntəməsi/",
"intimate":"/ˈɪnəmət/, /ˈɪntəˌmeɪt/, /ˈɪntəmət/",
"intimated":"/ˈɪntəˌmeɪtɪd/",
"intimately":"/ˈɪntəmətli/",
"intimates":"/ˈɪntəməts/",
"intimation":"/ˌɪntəˈmeɪʃən/",
"intimations":"/ˌɪntəˈmeɪʃənz/",
"intimidate":"/ˌɪnˈtɪmɪˌdeɪt/",
"intimidated":"/ˌɪnˈtɪmɪˌdeɪtɪd/",
"intimidates":"/ˌɪnˈtɪmɪˌdeɪts/",
"intimidating":"/ˌɪnˈtɪmɪˌdeɪtɪŋ/",
"intimidation":"/ˌɪnˌtɪmɪˈdeɪʃən/",
"intis":"/ˈɪntɪs/",
"into":"/ˈɪntu/, /ɪnˈtu/, /ɪntə/",
"intolerable":"/ˌɪnˈtɑlɝəbəl/",
"intolerably":"/ˌɪnˈtɑlɝəbli/",
"intolerance":"/ˌɪnˈtɑlɝəns/",
"intolerant":"/ˌɪnˈtɑlɝənt/",
"intonation":"/ˌɪntəˈneɪʃən/",
"intonations":"/ˌɪntəˈneɪʃənz/",
"intone":"/ˌɪnˈtoʊn/",
"intoned":"/ˌɪnˈtoʊnd/",
"intones":"/ˌɪnˈtoʊnz/",
"intoning":"/ˌɪnˈtoʊnɪŋ/",
"intourist":"/ˌɪnˈtʊɹɪst/",
"intoxicate":"/ˌɪnˈtɑksəˌkeɪt/",
"intoxicated":"/ɪnˈtɑksəˌkeɪtɪd/, /ɪnˈtɑksɪˌkeɪtɪd/",
"intoxicates":"/ˌɪnˈtɑksəˌkeɪts/",
"intoxicating":"/ˌɪnˈtɑksɪˌkeɪtɪŋ/",
"intoxication":"/ˌɪnˌtɑksəˈkeɪʃən/",
"intra":"/ˈɪntɹɑ/",
"intracellular":"/ˌɪntɹɑˈsɛljəlɝ/",
"intracompany":"/ˌɪntɹəˈkɑmpəni/",
"intracranial":"/ˌɪntɹəˈkɹeɪniəl/",
"intractable":"/ˌɪnˈtɹæktəbəl/",
"intraday":"/ˌɪntɹəˈdeɪ/",
"intramarginal":"/ˌɪntɹəˈmɑɹdʒɪnəl/",
"intramural":"/ˌɪntɹəmˈjʊɹəl/",
"intransigence":"/ˌɪnˈtɹænsədʒəns/, /ˌɪnˈtɹænsɪdʒəns/",
"intransigent":"/ˌɪnˈtɹænsədʒənt/, /ˌɪnˈtɹænzədʒənt/",
"intraocular":"/ˌɪntɹəˈoʊkjulɝ/",
"intraparty":"/ˈɪntɹəˌpɑɹti/",
"intraspecific":"/ˌɪntɹəspəˈsɪfək/",
"intrastate":"/ˌɪntɹəˈsteɪt/",
"intrauterine":"/ˌɪntɹəˈjutɝɪn/",
"intravenous":"/ˌɪntɹəˈvinəs/",
"intravenously":"/ɪnˈtɹævənəsli/, /ɪntɹəˈvinəsli/",
"intrawest":"/ˈɪntɹəwəst/, /ˌɪntɹəˈwɛst/",
"intrepid":"/ɪnˈtɹɛpəd/",
"intrepidity":"/ˌɪnˈtɹɛpɪdəˌti/",
"intrepidly":"/ɪnˈtɹɛpədli/",
"intrex":"/ˈɪntɹəks/",
"intricacies":"/ˈɪntɹəkəsiz/",
"intricacy":"/ˈɪntɹəkəsi/",
"intricate":"/ˈɪntɹəkət/",
"intricately":"/ˈɪntɹəkətli/",
"intrie":"/ˈɪntɹi/",
"intrieri":"/ˌɪnˈtɹɪɹi/",
"intrigue":"/ˈɪntɹiɡ/, /ˌɪnˈtɹiɡ/",
"intrigued":"/ˈɪntɹiɡd/, /ˌɪnˈtɹiɡd/",
"intrigues":"/ˈɪntɹiɡz/, /ˌɪnˈtɹiɡz/",
"intriguing":"/ˌɪnˈtɹiɡɪŋ/",
"intriguingly":"/ˌɪnˈtɹiɡɪŋli/",
"intrinsic":"/ˌɪnˈtɹɪnsɪk/",
"intrinsically":"/ˌɪnˈtɹɪnsɪkəli/, /ˌɪnˈtɹɪnsɪkli/",
"intro":"/ˈɪntɹoʊ/",
"introduce":"/ˌɪntɹəˈdus/, /ˌɪntɹoʊˈdus/",
"introduced":"/ˌɪntɹəˈdust/, /ˌɪntɹoʊˈdust/",
"introduces":"/ˌɪntɹəˈdusɪz/, /ˌɪntɹoʊˈdusɪz/",
"introducing":"/ˌɪntɹəˈdusɪŋ/, /ˌɪntɹoʊˈdusɪŋ/",
"introduction":"/ˌɪntɹəˈdəkʃən/, /ˌɪntɹoʊˈdəkʃən/",
"introductions":"/ˌɪntɹəˈdəkʃənz/, /ˌɪntɹoʊˈdəkʃənz/",
"introductory":"/ˌɪn.trəˈdʌk.tər.i/",
"intron":"/ˈɪntɹən/",
"intros":"/ˈɪntɹoʊz/",
"introspect":"/ˈɪntɹəˌspɛkt/",
"introspection":"/ˌɪntɹəˈspɛkʃən/, /ˌɪntɹoʊˈspɛkʃən/",
"introspective":"/ˌɪntɹəˈspɛktɪv/, /ˌɪntɹoʊˈspɛktɪv/",
"introvert":"/ˈɪntɹoʊˌvɝt/",
"introverted":"/ˈɪntɹoʊˌvɝtɪd/",
"intrude":"/ˌɪnˈtɹud/",
"intruded":"/ˌɪnˈtɹudəd/",
"intruder":"/ˌɪnˈtɹudɝ/",
"intruders":"/ˌɪnˈtɹudɝz/",
"intrudes":"/ˌɪnˈtɹudz/",
"intruding":"/ˌɪnˈtɹudɪŋ/",
"intrusion":"/ˌɪnˈtɹuʒən/",
"intrusions":"/ˌɪnˈtɹuʒənz/",
"intrusive":"/ˌɪnˈtɹusɪv/",
"intrusiveness":"/ˌɪnˈtɹusɪvnɛs/",
"intuit":"/ˌɪnˈtuət/",
"intuit's":"/ˌɪnˈtuəts/",
"intuition":"/ˌɪntuˈɪʃən/",
"intuitive":"/ˌɪnˈtuətɪv/",
"intuitively":"/ˌɪnˈtuɪtɪvli/",
"inuit":"/ˈɪnut/",
"inundate":"/ˈɪnənˌdeɪt/",
"inundated":"/ˈɪnənˌdeɪtɪd/",
"inundating":"/ˈɪnənˌdeɪtɪŋ/, /ˌɪˈnənˌdeɪtɪŋ/",
"inundation":"/ˌɪnənˈdeɪʃən/",
"inundations":"/ˌɪnənˈdeɪʃənz/",
"inure":"/ˌɪnˈjʊɹ/",
"inured":"/ˌɪnˈjʊɹd/",
"invacare":"/ˈɪnvəˌkɛɹ/",
"invade":"/ˌɪnˈveɪd/",
"invaded":"/ˌɪnˈveɪdəd/, /ˌɪnˈveɪdɪd/",
"invader":"/ˌɪnˈveɪdɝ/",
"invaders":"/ˌɪnˈveɪdɝz/",
"invades":"/ˌɪnˈveɪdz/",
"invading":"/ˌɪnˈveɪdɪŋ/",
"invalid":"/ˈɪnvələd/, /ˈɪnvəlɪd/, /ˌɪnˈvæləd/",
"invalidate":"/ˌɪnˈvælɪˌdeɪt/",
"invalidated":"/ˌɪnˈvæləˌdeɪtəd/, /ˌɪnˈvælɪˌdeɪtɪd/",
"invalidating":"/ˌɪnˈvæləˌdeɪtɪŋ/",
"invalidation":"/ˌɪnˌvæləˈdeɪʃən/",
"invalids":"/ˈɪnvələdz/",
"invaluable":"/ˌɪnˈvæljəbəl/",
"invariable":"/ˌɪnˈvɛɹiəbəl/",
"invariably":"/ˌɪnˈvɛɹiəbli/",
"invariance":"/ˌɪnˈvɛɹiəns/",
"invariant":"/ˌɪnˈvɛɹiənt/",
"invasion":"/ˌɪnˈveɪʒən/",
"invasions":"/ˌɪnˈveɪʒənz/",
"invasive":"/ˌɪnˈveɪsɪv/",
"invective":"/ˌɪnˈvɛktɪv/",
"invent":"/ˌɪnˈvɛnt/",
"invented":"/ˌɪnˈvɛntəd/, /ˌɪnˈvɛntɪd/",
"inventing":"/ˌɪnˈvɛntɪŋ/",
"invention":"/ˌɪnˈvɛnʃən/",
"inventions":"/ˌɪnˈvɛnʃənz/",
"inventive":"/ˌɪnˈvɛntɪv/",
"inventiveness":"/ˌɪnˈvɛntɪvnəs/",
"inventor":"/ˌɪnˈvɛntɝ/",
"inventoried":"/ˈɪnvənˌtɔɹid/",
"inventories":"/ˌɪnvənˈtɔɹiz/",
"inventors":"/ˌɪnˈvɛntɝz/",
"inventory":"/ˌɪnvənˈtɔɹi/",
"inventory's":"/ˌɪnvənˈtɔɹiz/",
"invents":"/ˌɪnˈvɛnts/",
"inverlat":"/ˈɪnvɝˌlæt/",
"inverness":"/ˈɪnvɝˌnɛs/",
"inverse":"/ˌɪnˈvɝs/",
"inversely":"/ˌɪnˈvɝsli/",
"inversion":"/ˌɪnˈvɝʒən/",
"invert":"/ˌɪnˈvɝt/",
"invertebrate":"/ˌɪnˈvɝtəˌbɹeɪt/, /ˌɪnˈvɝtəbɹət/",
"invertebrates":"/ˌɪnˈvɝtəˌbɹeɪts/, /ˌɪnˈvɝtəbɹəts/",
"inverted":"/ˌɪnˈvɝtɪd/",
"invesco":"/ˌɪnˈvɛskoʊ/",
"invesco's":"/ˌɪnˈvɛsoʊz/",
"invest":"/ˌɪnˈvɛst/",
"investable":"/ˌɪnˈvɛstəbəl/",
"investcorp":"/ˌɪnˈvɛstkɔɹp/",
"invested":"/ˌɪnˈvɛstəd/, /ˌɪnˈvɛstɪd/",
"investigate":"/ˌɪnˈvɛstəˌɡeɪt/",
"investigated":"/ˌɪnˈvɛstəˌɡeɪtəd/, /ˌɪnˈvɛstəˌɡeɪtɪd/",
"investigates":"/ˌɪnˈvɛstəˌɡeɪts/",
"investigating":"/ˌɪnˈvɛstəˌɡeɪtɪŋ/",
"investigation":"/ˌɪnˌvɛstəˈɡeɪʃən/",
"investigational":"/ˌɪnvɛstɪˈɡeɪʃənəl/",
"investigations":"/ˌɪnˌvɛstəˈɡeɪʃənz/",
"investigative":"/ˌɪnˈvɛstəˌɡeɪtɪv/",
"investigator":"/ˌɪnˈvɛstəˌɡeɪtɝ/",
"investigator's":"/ˌɪnˈvɛstəˌɡeɪtɝz/",
"investigators":"/ˌɪnˈvɛstəˌɡeɪtɝz/",
"investigators'":"/ˌɪnˈvɛstəˌɡeɪtɝz/",
"investigatory":"/ˌɪnˈvɛstəɡəˌtɔɹi/",
"investimento":"/ˌɪnˌvɛstɪˈmɛnˌtoʊ/",
"investing":"/ˌɪnˈvɛstɪŋ/",
"investissements":"/ˌɪnˌvɛsˈtizɪmɑnts/",
"investiture":"/ˌɪnˈvɛstətʃɝ/",
"investment":"/ˌɪnˈvɛsmənt/, /ˌɪnˈvɛstmənt/",
"investment's":"/ˌɪnˈvɛsmənts/, /ˌɪnˈvɛstmənts/",
"investments":"/ˌɪnˈvɛsmənts/, /ˌɪnˈvɛstmənts/",
"investments'":"/ˌɪnˈvɛsmənts/, /ˌɪnˈvɛstmənts/",
"investnet":"/ˌɪnˈvɛstˌnɛt/",
"investor":"/ˌɪnˈvɛstɝ/",
"investor's":"/ˌɪnˈvɛstɝz/",
"investors":"/ˌɪnˈvɛstɝz/",
"investors'":"/ˌɪnˈvɛstɝz/",
"invests":"/ˌɪnˈvɛsts/",
"inveterate":"/ˌɪnˈvɛtɝət/",
"invidious":"/ˌɪnˈvɪdiəs/",
"invigorate":"/ˌɪnˈvɪɡɝɪt/",
"invigorated":"/ˌɪnˈvɪɡɝˌeɪtɪd/",
"invigorating":"/ˌɪnˈvɪɡɝˌeɪtɪŋ/",
"invincibility":"/ˌɪnˌvɪnsəˈbɪlɪti/",
"invincible":"/ˌɪnˈvɪnsəbəl/",
"inviolable":"/ˌɪnˈvaɪələbəl/",
"inviolate":"/ˌɪnˈvaɪəlɪt/",
"invirase":"/ˌɪnˈvaɪˌɹeɪz/",
"invisibility":"/ˌɪnˌvɪzəˈbɪləti/",
"invisible":"/ˌɪnˈvɪzəbəl/",
"invisibles":"/ˌɪnˈvɪzəbəlz/",
"invitation":"/ˌɪnvɪˈteɪʃən/",
"invitational":"/ˌɪnvəˈteɪʃənəl/",
"invitations":"/ˌɪnvɪˈteɪʃənz/",
"invite":"/ˌɪnˈvaɪt/",
"invited":"/ˌɪnˈvaɪtəd/, /ˌɪnˈvaɪtɪd/",
"invitee":"/ˌɪnvaɪˈti/",
"invitees":"/ˌɪnvaɪˈtiz/",
"invites":"/ˌɪnˈvaɪts/",
"inviting":"/ˌɪnˈvaɪtɪŋ/",
"invitron":"/ˈɪnvɪtɹɑn/",
"invitron's":"/ˈɪnvɪtɹɑnz/",
"invocation":"/ˌɪnvəˈkeɪʃən/",
"invoice":"/ˈɪnvɔɪs/",
"invoiced":"/ɪnˈvɔɪst/",
"invoices":"/ˈɪnvɔɪsɪz/",
"invoicing":"/ˈɪnˌvɔɪsɪŋ/",
"invoke":"/ˌɪnˈvoʊk/",
"invoked":"/ˌɪnˈvoʊkt/",
"invokes":"/ˌɪnˈvoʊks/",
"invoking":"/ˌɪnˈvoʊkɪŋ/",
"involuntarily":"/ˌɪnˌvɑlənˈtɝəli/, /ˌɪnvoʊˈləntɝˌɪli/",
"involuntary":"/ˌɪnˈvɑlənˌtɛɹi/",
"involve":"/ˌɪnˈvɑlv/",
"involved":"/ˌɪnˈvɑlvd/",
"involvement":"/ˌɪnˈvɑlvmənt/",
"involvements":"/ˌɪnˈvɑlvmənts/",
"involves":"/ˌɪnˈvɑlvz/",
"involving":"/ˌɪnˈvɑlvɪŋ/",
"invulnerability":"/ˌɪnˌvəlnɝəˈbɪlɪti/",
"invulnerable":"/ˌɪnˈvəlnɝəbəl/",
"inward":"/ˈɪnwɝd/",
"inwardly":"/ˈɪnwɝdli/",
"inwood":"/ˈɪnˌwʊd/",
"iny":"/ˈɪni/",
"inyokern":"/ˌɪnˈjoʊkɝn/",
"inzer":"/ˈɪnzɝ/",
"io":"/ˈaɪoʊ/",
"iodice":"/ˈaɪəˌdaɪs/, /ˌaɪəˈdiseɪ/",
"iodide":"/ˈaɪəˌdaɪd/",
"iodide's":"/ˈaɪəˌdaɪdz/",
"iodides":"/ˈaɪəˌdaɪdz/",
"iodine":"/ˈaɪəˌdaɪn/",
"iola":"/aɪˈoʊlə/",
"iolande":"/ioʊˈlɑndi/",
"iolanthe":"/iəˈlɑnθeɪ/",
"iole":"/iˈoʊli/",
"iomega":"/ˌaɪoʊˈmeɪɡə/",
"ion":"/ˈaɪˌɑn/, /ˈaɪən/",
"iona":"/aɪˈoʊnə/",
"ionarde":"/iəˈnɑɹdeɪ/",
"ione":"/aɪˈoʊni/",
"ionic":"/ˌaɪˈɑnɪk/",
"ionics":"/ˌaɪˈɑnɪks/",
"ionics's":"/ˌaɪˈɑnɪksɪz/",
"ionization":"/ˌaɪənəˈzeɪʃən/",
"ionize":"/ˈaɪəˌnaɪz/",
"ionizer":"/ˈaɪəˌnaɪzɝ/",
"ionizers":"/ˈaɪəˌnaɪzɝz/",
"ionizing":"/ˈaɪəˌnaɪzɪŋ/",
"ionosphere":"/ˌaɪˈɑnɔsˌfiɹ/",
"ionospheric":"/ˌaɪˌɑnɔsˈfɛɹɪk/",
"ions":"/ˈaɪˌɑnz/, /ˈaɪənz/",
"iorio":"/iˈɔɹiˌoʊ/",
"ios":"/ˈaɪoʊs/, /ˈioʊs/",
"iosif":"/ˈaɪəsɪf/, /ˈjɛsəf/",
"iosue":"/aɪˈoʊsu/",
"iota":"/ˌaɪˈoʊtə/",
"iott":"/ˈaɪət/",
"iou":"/ˌaɪˌoʊˈju/",
"iovine":"/ioʊˈvini/",
"iovino":"/ioʊˈvinoʊ/",
"iowa":"/ˈaɪəwə/, /ˈaɪoʊə/",
"iowa's":"/ˈaɪəwəz/, /ˈaɪoʊəz/",
"iowan":"/ˈaɪəwən/, /ˈaɪoʊən/",
"iowans":"/ˈaɪəwənz/, /ˈaɪoʊənz/",
"ip":"/ˈaɪˈpi/, /ˈɪp/",
"ipaDictionary":"/ˈɛntɹiz/",
"ipaTimeout":"/ˈtaɪˌmaʊt/",
"ipad":"/ˈaɪˌpæd/",
"ipad's":"/ˈaɪˌpædz/",
"ipads":"/ˈaɪˌpædz/",
"ipalco":"/iˈpælkoʊ/",
"ipalco's":"/iˈpælkoʊz/",
"ipco":"/ˈɪpkoʊ/",
"iphegenia":"/ˌɪfədʒəˈnaɪə/",
"iphiginia":"/ˌɪfədʒiˈnaɪə/, /ˌɪfədʒiˈniə/",
"iphone":"/ˈaɪˌfoʊn/",
"iphones":"/ˈaɪˌfoʊnz/",
"ipock":"/ˈɪpək/",
"ipod":"/ˈaɪˌpɑd/",
"ipods":"/ˈaɪˌpɑdz/",
"ippolito":"/ˌɪpoʊˈlitoʊ/",
"ipsco":"/ˈɪpskoʊ/",
"ipsen":"/ˈɪpsən/",
"iptay":"/ˈɪpteɪ/",
"iq":"/ˈaɪkˈju/",
"iq's":"/ˈaɪkˈjuz/",
"iqbal":"/ˈɪkbəl/",
"ira":"/ˈaɪɹə/, /ˌaɪˌɑˈɹeɪ/",
"ira's":"/ˈaɪɹəz/",
"iran":"/ˌaɪˈɹæn/, /ˌɪˈɹɑn/",
"iran's":"/ˌaɪˈɹænz/, /ˌɪˈɹænz/",
"iranamok":"/ˌaɪɹəˈnɑmɑk/",
"irangate":"/ˌɪˈɹɑnˌɡeɪt/",
"irani":"/ˌɪˈɹɑni/",
"iranian":"/ˌɪˈɹɑniən/, /aɪˈɹeɪniən/",
"iranians":"/ˌɪˈɹɑniənz/, /aɪˈɹeɪniənz/",
"iranians'":"/aɪˈɹeɪniənz/",
"iranscam":"/aɪˈɹænskæm/",
"iraq":"/ˌaɪˈɹɑk/, /ˌiˈɹɑk/, /ˌɪˈɹɑk/",
"iraq's":"/ˌaɪˈɹɑks/, /ˌiˈɹɑks/, /ˌɪˈɹɑks/",
"iraqgate":"/ˌaɪˈɹɑkˌɡeɪt/, /ˌiˈɹɑkˌɡeɪt/, /ˌɪˈɹɑkˌɡeɪt/",
"iraqi":"/ˌaɪˈɹæki/, /ˌiˈɹæki/, /ˌɪˈɹæki/",
"iraqi's":"/ˌaɪˈɹækiz/, /ˌiˈɹækiz/, /ˌɪˈɹækiz/",
"iraqis":"/ˌaɪˈɹækiz/, /ˌiˈɹækiz/, /ˌɪˈɹækiz/",
"iras":"/ˈaɪˈɑˈɹeɪz/, /ˈaɪɹəz/",
"irascible":"/ˌɪˈɹæsɪbəl/",
"irascibly":"/ˌɪˈɹæsɪbli/",
"irate":"/aɪˈɹeɪt/",
"irbinna":"/ɝˈbɪnə/",
"irby":"/ˈɝbi/",
"ire":"/ˈaɪɹ/",
"ireene":"/aɪˈɹin/",
"irelan":"/ˌɪɹeɪˈlɑn/",
"ireland":"/ˈaɪɝlənd/, /ˈaɪɹlənd/",
"ireland's":"/ˈaɪɹləndz/",
"irelands":"/ˈaɪɹləndz/",
"irell":"/aɪˈɹɛl/",
"irena":"/ˌɪˈɹeɪnə/",
"irene":"/aɪˈɹin/",
"irene's":"/ˌaɪˈɹinz/",
"ireson":"/ˈaɪɝsən/, /ˈɪɹɪsən/",
"ireta":"/ˌɪˈɹeɪtə/",
"ireton":"/ˈaɪɝtən/, /ˈɪɹɪtɑn/",
"iretta":"/ˌɪˈɹɛtə/",
"irette":"/ˌɪˈɹɛt/",
"irey":"/ˈaɪɹi/",
"irian":"/ˈaɪɹiən/",
"irianese":"/aɪˈɹiəˌnis/",
"irick":"/ˈɪɹɪk/",
"iridescent":"/ˌɪɹəˈdɛsənt/",
"iridium":"/ˌɪˈɹɪdiəm/",
"irimajiri":"/aɪˌɹiməˈdʒɪɹi/",
"irina":"/ˌɪˈɹinə/",
"iris":"/ˈaɪɹəs/, /ˈaɪɹɪs/",
"irises":"/ˈaɪɹəsɪz/",
"irish":"/ˈaɪɹɪʃ/",
"irishman":"/ˈaɪɹɪʃmən/",
"irishness":"/ˈaɪɹɪʃnɪs/",
"irit":"/ˈaɪˈɑˈɹaɪˈti/, /ˈɪɹɪt/",
"irizarry":"/ˈɪɹɪzæɹi/",
"irk":"/ˈɝk/",
"irked":"/ˈɝkt/",
"irks":"/ˈɝks/",
"irksome":"/ˈɝksəm/",
"irkutsk":"/ˌɪɹˈkʊtsk/, /ɝˈkʊtsk/",
"irlbeck":"/ˈɝlbɛk/",
"irma":"/ˈɝmə/",
"irma's":"/ˈɝməz/",
"iron":"/ˈaɪɝn/",
"ironclad":"/ˈaɪɝnˌklæd/",
"ironed":"/ˈaɪɝnd/",
"ironic":"/aɪˈɹɑnɪk/",
"ironical":"/aɪˈɹɑnɪkəl/",
"ironically":"/aɪˈɹɑnɪkli/",
"ironies":"/ˈaɪɹəniz/",
"ironing":"/ˈaɪɝnɪŋ/, /ˈaɪɹnɪŋ/",
"ironize":"/ˈaɪɝˌnaɪz/",
"ironized":"/ˈaɪɝˌnaɪzd/",
"ironizer":"/ˈaɪɝˌnaɪzɝ/",
"ironizes":"/ˈaɪɝˌnaɪzɪz/",
"ironizing":"/ˈaɪɝˌnaɪzɪŋ/",
"irons":"/ˈaɪɝnz/",
"ironside":"/ˈaɪɝnˌsaɪd/",
"ironsides":"/ˈaɪɝnˌsaɪdz/",
"ironton":"/ˈaɪɹntən/",
"ironwood":"/ˈaɪɝnˌwʊd/",
"ironwood's":"/ˈaɪɝnˌwʊdz/",
"irony":"/ˈaɪɹəni/",
"iroquois":"/ˈɪɹəˌkwɔɪ/",
"irradiate":"/ˌɪˈɹeɪdiˌeɪt/",
"irradiated":"/ˌɪˈɹeɪdiˌeɪtɪd/",
"irradiation":"/ˌɪˌɹeɪdiˈeɪʃən/",
"irrational":"/ˌɪˈɹæʃənəl/",
"irrationality":"/ˌɪˌɹæʃəˈnæləti/",
"irrationally":"/ˌɪˈɹæʃənəli/, /ˌɪˈɹæʃnəli/",
"irrawaddy":"/ˈɪɹəˌwɑdi/",
"irreconcilable":"/ˌɪˈɹɛkənˌsaɪləbəl/",
"irredentism":"/ˌɪɹəˈdɛntɪzəm/",
"irrefutable":"/ˌɪɹəfˈjutəbəl/",
"irregardless":"/ˌɪɹəˈɡɑdləs/",
"irregular":"/ˌɪˈɹɛɡjəlɝ/",
"irregularities":"/ˌɪɹɛɡjəˈlɛɹətiz/",
"irregularity":"/ˌɪˌɹɛɡjəˈlɛɹəti/",
"irregularly":"/ˌɪˈɹɛɡjəlɝli/",
"irregulars":"/ˌɪˈɹɛɡjəlɝz/",
"irrelevance":"/ˌɪˈɹɛləvəns/",
"irrelevancy":"/ˌɪˈɹɛləvənsi/",
"irrelevant":"/ˌɪˈɹɛləvənt/",
"irremediable":"/ˌɪɹɪˈmidiəbəl/",
"irreparable":"/ˌɪˈɹɛpɝəbəl/",
"irreparably":"/ˌɪˈɹɛpɝəbli/",
"irreplaceable":"/ˌɪɹəˈpleɪsəbəl/",
"irrepressible":"/ˌɪɹəˈpɹɛsəbəl/",
"irresistible":"/ˌɪɹɪˈzɪstəbəl/",
"irresistibly":"/ˌɪɹɪˈzɪstəbli/",
"irrespective":"/ˌɪɹəˈspɛktɪv/",
"irresponsibility":"/ˌɪɹəˌspɑnsəˈbɪləti/",
"irresponsible":"/ˌɪɹəˈspɑnsəbəl/",
"irresponsibly":"/ˌɪɹəˈspɑnsəbli/",
"irretrievably":"/ˌɪɹəˈtɹivəbli/",
"irreverence":"/ˌɪˈɹɛvɝəns/",
"irreverent":"/ˌɪˈɹɛvɝənt/",
"irreversible":"/ˌɪɹɪˈvɝsəbəl/",
"irreversibly":"/ˌɪɹɪˈvɝsəbli/",
"irrevocable":"/ˌɪˈɹɛvəkəbəl/",
"irrevocably":"/ˌɪˈɹɛvəkəbli/, /ˌɪˌɹɛˈvoʊkəbli/",
"irrigate":"/ˈɪɹəˌɡeɪt/",
"irrigated":"/ˈɪɹəˌɡeɪtɪd/",
"irrigation":"/ˌɪɹəˈɡeɪʃən/",
"irrigator":"/ˈɪɹəˌɡeɪtɝ/",
"irrigators":"/ˈɪɹəˌɡeɪtɝz/",
"irritability":"/ˌɪɹɪtəˈbɪləti/",
"irritable":"/ˈɪɹətəbəl/",
"irritant":"/ˈɪɹətənt/",
"irritants":"/ˈɪɹətənts/",
"irritate":"/ˈɪɹɪˌteɪt/",
"irritated":"/ˈɪɹəˌteɪtəd/",
"irritates":"/ˈɪɹɪˌteɪts/",
"irritating":"/ˈɪɹəˌteɪtɪŋ/",
"irritation":"/ˌɪɹɪˈteɪʃən/",
"irritations":"/ˌɪɹɪˈteɪʃənz/",
"irs":"/ˈaɪˌɑˈɹɛs/",
"irv":"/ˈɝv/",
"irve":"/ˈaɪˈɑɹˈviˈi/, /ˈɝv/",
"irvette":"/ɝˈvɛt/",
"irvin":"/ˈɝvɪn/",
"irvine":"/ˈɝvaɪn/",
"irving":"/ˈɝvɪŋ/",
"irving's":"/ˈɝvɪŋz/",
"irwin":"/ˈɝwən/, /ˈɝwɪn/",
"irwindale":"/ˈɝwɪnˌdeɪl/",
"is":"/ˈɪz/, /ɪz/",
"isa":"/ˈisə/",
"isaac":"/ˈaɪzək/, /ˈaɪzɪk/",
"isaacks":"/ˈɪsɑks/",
"isaacs":"/ˈaɪzɪks/",
"isaacson":"/ˈaɪzɪksən/",
"isaak":"/ˈaɪzæk/, /ˌɪˈsɑk/",
"isabel":"/ˈɪzəˌbɛl/",
"isabell":"/ˌɪsɑˈbɛl/",
"isabella":"/ˌɪzəˈbɛlə/",
"isabelle":"/ˈɪzəˌbɛl/",
"isackson":"/ˈɪsəksən/",
"isadore":"/ˈɪsɑdɔɹ/, /ˌɪsɑˈdɔɹeɪ/",
"isaiah":"/ˌaɪˈzeɪə/",
"isaksen":"/ˈɪsəksən/",
"isakson":"/ˈɪsəksən/",
"isaly":"/ˈaɪsli/, /ˈaɪzli/",
"isautier":"/aɪˈsɔtjɝ/",
"isay":"/ˈaɪˌseɪ/",
"isbell":"/ˈɪsbɛl/",
"isbill":"/ˌɪsˈbɪl/",
"isbn":"/ˌaɪˌɛsˌbiˈɛn/",
"iscariot":"/ˌɪsˈkɛɹiət/",
"isch":"/ˈɪʃ/",
"ischemia":"/ˌɪsˈkɛˌmiə/",
"ischemic":"/ˌɪsˈkɛmɪk/",
"ischo":"/ˈiʃoʊ/",
"ise":"/ˈaɪz/",
"iselin":"/ˈɪsɪlɪn/",
"iseman":"/ˈaɪsmən/",
"iseminger":"/ˈɪsimɪŋɝ/",
"isenberg":"/ˈaɪzənbɝɡ/",
"isenhart":"/ˈaɪzənˌhɑɹt/",
"isenhour":"/ˈɪsɪnaʊɹ/",
"isenhower":"/ˈɪsɪnhoʊɝ/",
"isensee":"/ˈaɪzənˌsi/",
"isentrope":"/ˈaɪzənˌtɹoʊp/",
"isentropic":"/ˌaɪzənˈtɹɑpək/",
"iser":"/ˈaɪzɝ/",
"isetan":"/ˈɪsɪtən/",
"isgrigg":"/ˌɪsˈɡɹɪɡ/",
"isgro":"/ˈisɡɹoʊ/",
"isgur":"/ˈɪsɡɝ/",
"ish":"/ˈɪʃ/",
"isham":"/ˈɪʃəm/",
"ishaq":"/ˈɪʃæk/",
"ishee":"/ˈɪʃi/",
"isherwood":"/ˈɪʃɝˌwʊd/",
"ishi":"/ˈɪʃi/",
"ishi's":"/ˈɪʃiz/",
"ishibashi":"/ˌɪˌʃiˈbɑˌʃi/",
"ishida":"/ˌɪˈʃiˌdɑ/",
"ishihara":"/ˌɪˌʃiˈhɑˌɹɑ/",
"ishii":"/ˌɪˈʃiˌi/",
"ishikawa":"/ˌɪˌʃiˈkɑˌwɑ/",
"ishikawajima":"/ˌiˌʃɪˌkɑwəˈdʒiˌmɑ/",
"ishikura":"/ˌɪʃɪˈkʊˌɹɑ/",
"ishimura":"/ˌiʃɪˈmuˌɹɑ/",
"ishler":"/ˈɪʃlɝ/",
"ishmael":"/ˈɪʃmeɪl/, /ˈɪʃmil/",
"ishmail":"/ˈɪʃmeɪl/",
"ishman":"/ˈɪʃmən/",
"ishtar":"/ˈɪʃtɑɹ/",
"isidore":"/ˈɪzɪˌdɔɹ/",
"isikoff":"/ˈɪzəkɔf/",
"isis":"/ˈaɪsəs/",
"iskra":"/ˈɪskɹə/",
"isla":"/ˈilə/",
"islam":"/ˈɪsˌlɑm/, /ˈɪzləm/, /ˌɪsˈlɑm/",
"islam's":"/ˈɪsˌlɑmz/, /ˌɪsˈlɑmz/",
"islamabad":"/ˌɪsˈlæməbæd/",
"islamabad's":"/ˌɪsˈlæməbædz/",
"islami":"/ˌɪzˈlɑmi/",
"islamic":"/ˌɪzˈlɑmɪk/",
"islamically":"/ˌɪzˈlɑmɪkli/",
"islamist":"/ˈɪsləmɪst/",
"islamists":"/ˈɪsləmɪsts/",
"islamiya":"/ˌɪsˈlɑmiə/",
"islamization":"/ˌɪzlɑməˈzeɪʃən/",
"island":"/ˈaɪlənd/",
"island's":"/ˈaɪləndz/",
"islander":"/ˈaɪləndɝ/",
"islanders":"/ˈaɪləndɝz/",
"islandia":"/ˌaɪˈlændiə/",
"islands":"/ˈaɪləndz/",
"islands'":"/ˈaɪsləndz/",
"islas":"/ˈaɪləz/",
"isle":"/ˈaɪl/",
"isleen":"/ˈaɪlin/",
"isler":"/ˈaɪlɝ/",
"isles":"/ˈaɪlz/",
"islet":"/ˈaɪlɪt/",
"islets":"/ˈaɪlɪts/",
"isley":"/ˈaɪzli/",
"islip":"/ˈaɪslɪp/",
"ism":"/ˈɪzəm/",
"ismael":"/ˈɪsmeɪl/",
"ismail":"/ˈɪsmeɪl/",
"isms":"/ˈɪzəmz/",
"isn't":"/ˈɪzən/, /ˈɪzənt/, /ɪzənt/",
"isner":"/ˈɪsnɝ/",
"isobel":"/ˈaɪsɔˌbɛl/",
"isocyanate":"/ˌaɪsəˈsaɪəˌneɪt/",
"isoda":"/ˌiˈsoʊdə/",
"isoelectronic":"/ˌaɪsoʊilɛkˈtɹɑnɪk/, /ˌaɪsoʊɪlɛkˈtɹɑnɪk/",
"isoetec":"/ˈaɪsoʊˌtɛk/",
"isogenic":"/ˌaɪsoʊˈdʒɛnək/",
"isola":"/aɪˈsɑlə/",
"isolate":"/ˈaɪsəˌleɪt/",
"isolated":"/ˈaɪsəˌleɪtəd/, /ˈaɪsəˌleɪtɪd/",
"isolates":"/ˈaɪsəˌleɪts/",
"isolating":"/ˈaɪsəˌleɪtɪŋ/",
"isolation":"/ˌaɪsəˈleɪʃən/",
"isolationism":"/ˌaɪsəˈleɪʃəˌnɪzəm/",
"isolationist":"/ˌaɪsəˈleɪʃənəst/",
"isolationists":"/ˌaɪsəˈleɪʃənɪs/, /ˌaɪsəˈleɪʃənɪsts/",
"isolde":"/ˈɪsoʊld/, /ɪˈsoʊldə/",
"isom":"/ˈaɪsəm/",
"isomedix":"/ˌaɪsoʊˈmɛdɪks/",
"isomedix's":"/ˌaɪsoʊˈmɛdɪks/, /ˌaɪsoʊˈmɛdɪksɪz/",
"isomer":"/ˈaɪsəmɝ/",
"isomers":"/ˈaɪsəmɝz/",
"isomorphic":"/ˌaɪsəˈmɔrfɪk/",
"isomorphism":"/ˌaɪsəˈmɔɹfɪzəm/",
"ison":"/ˈɪsən/",
"isoprinosine":"/ˌɪsəˈpɹɪnəˌsin/",
"isosceles":"/aɪˈsɔsəˌliz/",
"isothermal":"/ˌaɪsəˈθɝməl/",
"isotoner":"/ˈaɪsoʊˌtoʊnɝ/, /ˈɪzoʊˌtənɝ/",
"isotonic":"/ˌaɪsəˈtɑnɪk/",
"isotope":"/ˈaɪsəˌtoʊp/",
"isotopes":"/ˈaɪsəˌtoʊps/",
"isotopic":"/ˌaɪsəˈtɑpɪk/",
"isoxicam":"/ˌɪˈsɑksɪkəm/",
"ispra":"/ˈɪspɹə/",
"israel":"/ˈɪzɹeɪl/, /ˈɪzɹiəl/",
"israel's":"/ˈɪzɹeɪlz/, /ˈɪzɹiəlz/",
"israeli":"/ˌɪzˈɹeɪli/",
"israeli's":"/ˌɪzˈɹeɪliz/",
"israelis":"/ˌɪzˈɹeɪliz/",
"israelis'":"/ˌɪzˈɹeɪliz/",
"israelite":"/ˈɪzɹəˌlaɪt/",
"israelites":"/ˈɪzɹəˌlaɪts/",
"israeloff":"/ˌɪsˈɹeɪlɔf/",
"israelson":"/ˈɪsɹɛlsən/",
"israhi":"/ˌɪzˈɹɑhi/",
"isringhouser":"/ˈɪsɹɪŋˌhaʊzɝ/",
"issa":"/ˈɪsə/",
"issac":"/ˈaɪzɪk/, /ˈɪsək/",
"issah":"/ˈɪsə/",
"issam":"/ˈɪsəm/",
"issar":"/ˈiˌsɑɹ/",
"issie":"/ˈɪsi/",
"issing":"/ˈɪsɪŋ/",
"issuable":"/ˈɪʃuəbəl/",
"issuance":"/ˈɪʃuəns/",
"issuances":"/ˈɪʃuənsɪz/",
"issue":"/ˈɪʃu/",
"issue's":"/ˈɪʃuz/",
"issued":"/ˈɪʃud/",
"issueless":"/ˈɪʃuləs/",
"issuer":"/ˈɪʃuɝ/",
"issuer's":"/ˈɪʃuɝz/",
"issuers":"/ˈɪʃuɝz/",
"issuers'":"/ˈɪsuɹz/",
"issues":"/ˈɪʃuz/",
"issues'":"/ˈɪsuz/",
"issuing":"/ˈɪʃuɪŋ/",
"issy":"/ˈɪsi/",
"istanbul":"/ˌɪstɑnˈbul/",
"istat":"/ˈɪstæt/",
"istel":"/ˈɪstɛl/",
"istel's":"/ˈɪstɛlz/",
"isthmus":"/ˈɪsməs/",
"istituto":"/ˌɪstɪˈtutoʊ/",
"istook":"/ˈɪsˌtʊk/",
"istre":"/ˈɪstɝ/",
"isty":"/ˈaɪˈɛsˈtiˈwaɪ/, /ˈɪsti/",
"isu":"/ˈaɪˈɛsˈju/, /ˈɪˌsu/",
"isuzu":"/ˌɪˈsuˌzu/",
"it":"/ˈɪt/, /ɪt/",
"it'd":"/ˈɪtəd/",
"it'll":"/ˈɪtəl/, /ˈɪtl/",
"it's":"/ˈɪts/, /ɪts/",
"it-wit":"/ˈɪtˈwɪt/",
"ita":"/ˈaɪˈtiˈeɪ/, /ˈaɪtə/",
"italia":"/ˌɪˈtæljə/, /iˈtæliə/",
"italian":"/ˌɪˈtæljən/",
"italiana":"/ˌɪˌtæliˈænə/",
"italianate":"/ˌɪˈtæljəˌneɪt/",
"italiano":"/ˌɪtɑliˈɑnoʊ/",
"italians":"/ˌɪˈtæljənz/",
"italic":"/aɪˈtælɪk/",
"italics":"/aɪˈtælɪks/",
"italish":"/ˌɪˈtælɪʃ/",
"italtel":"/ˌɪˈtælˌtɛl/",
"italy":"/ˈɪtəli/",
"italy's":"/ˈɪtəliz/",
"itamar":"/ˈitəˌmɑɹ/",
"itami":"/ˌɪˈtɑˌmi/",
"itar":"/ˈiˌtɑɹ/",
"itasca":"/aɪˈtæskɑ/",
"itch":"/ˈɪtʃ/",
"itches":"/ˈɪtʃəz/, /ˈɪtʃɪz/",
"itching":"/ˈɪtʃɪŋ/",
"itchy":"/ˈɪtʃi/",
"itek":"/ˈaɪˌtɛk/",
"itel":"/ˈaɪˌtɛl/",
"item":"/ˈaɪtəm/",
"itemize":"/ˈaɪtəˌmaɪz/",
"itemized":"/ˈaɪtəˌmaɪzd/",
"itemizer":"/ˈaɪtəˌmaɪzɝ/",
"itemizers":"/ˈaɪtəˌmaɪzɝz/",
"itemizes":"/ˈaɪtəˌmaɪzɪz/",
"itemizing":"/ˈaɪtəˌmaɪzɪŋ/",
"items":"/ˈaɪtəmz/",
"iten":"/ˈaɪtən/",
"iterate":"/ˈɪdəˌreɪt/",
"iteration":"/ˌɪtɝˈeɪʃən/",
"iterations":"/ˌɪtəˈɹeɪʃənz/",
"iterative":"/ˈɪtɝˌeɪtɪv/",
"ithaca":"/ˈɪθəkə/",
"ithaca's":"/ˈɪθəkəz/",
"itinerant":"/aɪˈtɪnɝənt/",
"itineraries":"/aɪˈtɪnɝˌɛɹiz/",
"itinerary":"/aɪˈtɪnɝˌɛɹi/",
"itkin":"/ˌɪtˈkɪn/",
"ito":"/ˈiˌtoʊ/, /ˈitoʊ/",
"ito's":"/ˈiˌtoʊz/, /ˈitoʊz/",
"itochu":"/ˌiˈtoʊˌtʃu/",
"itoh":"/ˈitoʊ/",
"its":"/ˈɪts/, /ɪts/",
"itself":"/ˌɪtˈsɛlf/",
"itstee":"/ˈɪtsti/",
"itsy":"/ˈɪtsi/",
"itsy-bitsy":"/ˌɪtsiˈbɪtsi/",
"ittner":"/ˈɪtnɝ/",
"itty":"/ˈɪti/",
"itty-bitty":"/ˌɪtiˈbɪti/",
"itunes":"/ˈaɪˌtunz/",
"itzhak":"/ˈɪtsæk/, /ˈɪtsɑk/, /ˈɪtshæk/",
"itzkowitz":"/ˈɪtskəwɪts/",
"iuliano":"/iuliˈɑnoʊ/, /juliˈɑnoʊ/",
"iva":"/ˈivə/",
"ivaco":"/ˈaɪvəˌkoʊ/",
"ivan":"/ˈaɪvən/",
"ivana":"/ˌɪˈvɑnə/",
"ivancic":"/ˌɪˈvæŋkɪk/",
"ivane":"/ˈɪvən/",
"ivanhoe":"/ˈaɪvənˌhoʊ/",
"ivanko":"/iˈvɑnkoʊ/",
"ivanna":"/ˌɪˈvɑnə/",
"ivanoff":"/ˈɪvənɔf/",
"ivanov":"/ˈɪvənɑv/",
"ivanyenko":"/ˌaɪvənˈjɛnkoʊ/",
"ivar":"/ˈɪvɝ/",
"ivatans":"/ˈaɪvətənz/",
"ivax":"/ˈaɪvæks/",
"iven":"/ˈaɪvən/",
"ivens":"/ˈaɪvənz/",
"iver":"/ˈaɪvɝ/",
"ivern":"/ˈaɪvɝn/",
"ivers":"/ˈaɪvɝz/",
"iversen":"/ˌɪˈvɝsən/",
"iverson":"/ˈaɪvɝsən/",
"ivery":"/ˈaɪvɝi/",
"ives":"/ˈaɪvz/",
"ivester":"/ˌaɪˈvɛstɝ/",
"ivey":"/ˈaɪvi/",
"ivie":"/ˈaɪvi/",
"ivins":"/ˈɪvɪnz/",
"ivo":"/ˈaɪˌvoʊ/",
"ivor":"/ˈaɪvɝ/",
"ivorian":"/aɪˈvɔɹiən/",
"ivorians":"/aɪˈvɔɹiənz/",
"ivory":"/ˈaɪvɝi/, /ˈaɪvɹi/",
"ivory-coast":"/ˈaɪvɝiˈkoʊst/, /ˈaɪvɹiˈkoʊst/",
"ivy":"/ˈaɪvi/",
"iwai":"/aɪˈwaɪ/",
"iwaki":"/aɪˈwɑki/",
"iwamoto":"/ˌɪˌwɑˈmoʊˌtoʊ/",
"iwan":"/ˈiwɑn/",
"iwanicki":"/ˌɪvəˈnɪtˌski/",
"iwanski":"/ˌɪˈvænˌski/",
"iwasaki":"/ˌiˌwɑˈsɑˌki/",
"iwata":"/ɪˈwɑˌtɑ/",
"iwate":"/aɪˈweɪt/",
"iwen":"/ˈɪwən/",
"iwerks":"/ˈaɪˌwɝks/",
"iwinski":"/ˌɪˈvɪnˌski/",
"iwo":"/ˈaɪwoʊ/",
"iwosaki":"/ˌaɪwəˈsɑki/",
"ixion":"/ɪkˈsaɪən/",
"iyer":"/ˈaɪɝ/",
"izaguirre":"/ˈɪzəˌɡwaɪɹ/, /ɪzəˈɡwɪɹeɪ/",
"izansky":"/ɪˈzænski/",
"izansky's":"/ɪˈzænskiz/",
"izard":"/ˈɪzɝd/",
"izatt":"/ˈizɑt/",
"izetbegovic":"/ˌɪzɛtˈbɛɡoʊˌvɪtʃ/",
"izetbegovic's":"/ˌɪzɛtˈbɛɡoʊˌvɪtʃɪz/",
"izod":"/ˈaɪzɑd/",
"izquierdo":"/ɪzˈkwɪɹdoʊ/",
"izumi":"/ɪˈzumi/",
"izvestia":"/ɪzˈvɛstiə/",
"izzard":"/ˈɪzɝd/",
"izzi":"/ˈɪzi/",
"izzo":"/ˈɪzoʊ/",
"izzy":"/ˈɪzi/",
"izzy's":"/ˈɪziz/",
}, undefined, "i");
}
