export default {
	accessKey: "A",
	ipaEnabled: true,
	ipaTimeout: 3000,
	ipaFontFamily: "Lucida Sans Unicode",
	ipaFontSizePx: 18,
	ipaCloseShortcut: "\\\\",
	ipaCloseOnScroll: true,
	ipaUseContextColors: false,
	audioEnabled: true,
	audioVolume: 1.0,
	audioPlaybackRate: 1.0,
	audioFetchFileTimeout: 1100,
	audioFetchScrapTimeout: 1300,
	audioGoogleSpeechSpeed: 0.48,
	setAudioShortcut: "A",
	setIpaShortcut: "Z",
	defaultIpaShortcut: "X",
};
