export default {
	accessKey: "A",
	ipaEnabled: true,
	ipaTimeout: 3000,
	useWordColors: false,
	audioVolume: 1.0,
	audioPlaybackRate: 1.0,
	fetchFileAudioTimeout: 1100,
	fetchScrapAudioTimeout: 1300,
	audioEnabled: true,
	googleSpeechSpeed: 0.48,
	setAudioShortcut: "A",
	setIpaShortcut: "Z",
	defaultIpaShortcut: "X",
	popupFontFamily: "Lucida Sans Unicode",
	popupFontSizepx: 18,
	popupCloseShortcut: "\\\\",
	popupCloseOnScroll: true,
};
